### ISSUE TITLE
Question on usage of HighLevelProducer and ConsumerGroup

### ISSUE THREAD

**Issue by MUI-Pop** [SOHU-Co/kafka-node#1003]
Hi Guys,

I am trying to write client code of Producers and Consumers on a specific requirement for which I require clarifications on usage of the library.

1. Using a HighLevelProducer I want to enforce some guarantees that the message is actually sent to brokers and I understood that we could pass the config 'requireAcks' - is this sufficient or do you recommend anything specifically to be handled from client code, because in other client libraries I see 'beginTransactions' and other stuff to enforce guarantees.

2. My understanding on 'ConsumerGroup' is it would have several Consumer instances and each instance would map to available partitions per Topic.
Is there anyway that I could control the number of Consumers for a ConsumerGroup  or anyway to achieve similar ?

Thanks

**Comment by MUI-Pop** [comment]
@jnotnull 

Thanks for the reply.

How this would differs from the ordinary 'Consumer' instance, I am trying to understand how 'ConsumerGroup' makes difference

**Comment by hyperlink** [comment]
The ConsumerGroup will automatically load balance your partitions to your ConsumerGroup instances. They need to share the same groupid for this to happen. It will also keep track of offsets so if an instance dies a new one is able to pick up where it left off.

With the Consumer you need to specify which partitions you are consuming from much of it is manual.

**Comment by MUI-Pop** [comment]
@hyperlink , @jnotnull 
Thank you, I am clear now.
