### ISSUE TITLE
Is Possible Producer.send() with different KafkaClinet Host and Kafka cluster Broker Host

### ISSUE THREAD

**Issue by barogo-jwyoon** [SOHU-Co/kafka-node#1007]
## Questions?

KafkaClient host : xxx.xxx.xxx.xxx:9092, xxx.xxx.xxx.xxx:9092 (aws network loadbalancer elasticip)
Kafka Broker host : kafka1, kafka2, kafk3

Is Possible produce.send() with above kafka host?

We application occured error

```
TimeoutError: Request timed out after 30000ms
    at new TimeoutError (/Users/jongwonyoon/barogo/traffic-hell/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout [as _onTimeout] (/Users/jongwonyoon/barogo/traffic-hell/node_modules/kafka-node/lib/kafkaClient.js:760:14)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

## Bug Report

```
return brokers[addr] || this.setupBroker(broker.host, broker.port, longpolling, brokers);
```
https://github.com/SOHU-Co/kafka-node/blob/a3653ba2d75a180be1e35f25be66cae0c9dcaa1c/lib/kafkaClient.js#L447

addr: 'kafka1:9092'

brokers :
```
{
'xxx.xxx.xxx.xxx9092':  {...},
'xxx.xxx.xxx.xxx:9092': {...}
}
```

->

brokers[addr] is 'undefined'

->

```
if (!broker. isReady()) {  ---> isReady() false
```
https://github.com/SOHU-Co/kafka-node/blob/a3653ba2d75a180be1e35f25be66cae0c9dcaa1c/lib/kafkaClient.js#L944

### Environment

* Node version: 8.10.0
* Kafka-node version: 2.6.1
* Kafka version: 1.1.0

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 8

Thank you..

**Comment by hyperlink** [comment]
I don't understand the question / issue. Request timeout can happen on occasion when either the broker or client is busy. You can increase the timeout by adjusting the `requestTimeout`.

**Comment by barogo-jwyoon** [comment]
Sorry,,,

I setting kafkaClient option host set `xxx.xxx.xxx.xxx:9092`.

But

``` js
addr = broker.host + ':' + broker.port; 
-> kafka1:9092 (kafka broker host name)
```
at KafkaClient.prototype.brokerForLeader()

@hyperlink

**Comment by barogo-jwyoon** [comment]
I sovled this issue.

I modify `/etc/hosts`

```
{kafka ip}    kafka1
{kafka ip}    kafka2
{kafka ip}    kafka3
```
