### ISSUE TITLE
producer.ready event doesn't fire on windows

### ISSUE THREAD

**Issue by keswanikaran** [SOHU-Co/kafka-node#102]
var client = new kafka.Client(),
    producer = new Producer(client),
    payloads = [
        { topic: 'topic1', messages: 'hi', partition: 0 },
        { topic: 'topic2', messages: ['hello', 'world'] }
    ];
producer.on('ready', function () {
    producer.send(payloads, function (err, data) {
        console.log(data);
    });
}); 

producer.on('ready',callback) never get's called on windows machine. Same code is running fine on mac. Are you aware of this ?

**Comment by rachel13** [comment]
I am having this issue too. The same codeset above doesn't get fired even when I run it on uBuntu. Any ideas on how to get it to run payload.send()?
