### ISSUE TITLE
How to detect consumer group disconnect?

### ISSUE THREAD

**Issue by t9rres** [SOHU-Co/kafka-node#1028]
* Node version: latest
* Kafka-node version: latest
* Kafka version: latest

There is no disconnect event on consumer group, so how can i detect disconnection? with timeout?

**Comment by jnotnull** [comment]
CG will invoke `startHeartbeats` method after connected to kafka, then recovery the connection one the callback has error.

**Comment by aikar** [comment]
@t9rres a rebalance event occurs.

The client will recover broker changes.
