### ISSUE TITLE
how to set max.poll.records in consumer 

### ISSUE THREAD

**Issue by deepak6446** [SOHU-Co/kafka-node#1034]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

### Environment

* Node version:
* Kafka-node version:
* Kafka version:

### For specific cases also provide
* Number of Brokers:
* Number partitions for topic:

### Include Sample Code to reproduce behavior

```js
// include code here
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by hyperlink** [comment]
While we don't support this setting directly we do have a similar undocumented setting called `maxTickMessages`. It's main purpose is to prevent holding up the eventloop since messages are processed synchronously.
