### ISSUE TITLE
Is 'idleConnection' (a documented KafkaClientOption) supposed to be missing here? Why?

### ISSUE THREAD

**Issue by quinsulon** [SOHU-Co/kafka-node#1035]
https://github.com/SOHU-Co/kafka-node/blob/a9478a85e1cf79e59c4582b0b34ffa367034f009/types/index.d.ts#L160

**Comment by hyperlink** [comment]
PRs welcome!

**Comment by bensooraj** [comment]
@hyperlink I have added `maxAsyncRequests` and `sasl` as well, along with `idleConnection` (#1099).

**Comment by bensooraj** [comment]
@hyperlink A gentle reminder :)

**Comment by hyperlink** [comment]
PR merged. Thanks @bensooraj
