### ISSUE TITLE
Read messages synchronously

### ISSUE THREAD

**Issue by ammarNoon** [SOHU-Co/kafka-node#1044]
Kafka consumer gets bombarded with lots of messages at a time, 
I need to read them one after another only after committing the first one.
I tried autoCommit false, and tried to pause and resume too.
But still, it doesn't work.
Is there a way to achieve this in this library?

**Comment by zoltan-nz** [comment]
Is that not the basic feature of the Kafka, the sort of arrived messages is guarantied, so you always get the next message, one after another? Have you tried to modify the bulk size?

**Comment by arpitjain099** [comment]
I am using the same functionality for my project, I am also following the same steps -> autoCommit: false and manually pausing and resuming. It seems to work for us. 
1. Can you share the code snippet you are using?
2. Are you sure that you have handled all the corner cases in case of pause and resume. In our case, we realized that we had missed a case when we didn't resume the consumer (after pausing it), and as a result were not receiving any new messages. This took us quite a while to identify the actual problem.

**Comment by ammarNoon** [comment]
Well resume and pause work, but after receiving a certain size of message, so i had to create an internal queue to handle it
There i a high chance of losing data now

**Comment by zoftdev** [comment]
Use ConsumerGroupStream. 
when you use consumer.on('data') , 
it will pause client until you finish process data.
