### ISSUE TITLE
Empty messages

### ISSUE THREAD

**Issue by comrat** [SOHU-Co/kafka-node#1069]
## Bug Report
Hello!
I've tried to interact with kafka in docker from [cp-docker-images](https://github.com/confluentinc/cp-docker-images) (branch 5.0.0-post). I've implement simple message listening code:
```js
const client = new kafka.Client("zookeeper:2181");
const consumer = new kafka.Consumer(client, [{ topic: "test30", partition: 0 }], { autoCommit: false });

consumer.on("message", (message) => {
      console.log("Got message", message)
});
```
Then I've run docker and create topic
```bash
$ docker-compose up -d
$ docker-compose exec broker kafka-topics --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic test30
```
Then I've send one message:
```bash
$ docker-compose exec broker kafka-console-producer --broker-list localhost:9092 --topic test30
>hello!
```
And this is what I've got:
```js
$ node .
Got message { topic: 'test30',
  value: 'hello!',
  offset: 0,
  partition: 0,
  highWaterOffset: 1,
  key: null }
Got message { topic: 'test30',
  value: '',
  offset: 0,
  partition: 0,
  highWaterOffset: 1,
  key: '' }
```
Two messages one of them has zero message and offset.
If I try consumer manually I've got just one message:
```bash
$ docker-compose exec broker kafka-console-consumer --bootstrap-server localhost:9092 --topic test30 --from-beginning
hello!
^CProcessed a total of 1 messages
```
But it's getting worse when I try to send one more message it start to emitting 'message' signal infinitely:
```bash
...
Got message { topic: 'test30',
  value: 'world',
  offset: 1,
  partition: 0,
  highWaterOffset: 2,
  key: null }
Got message { topic: 'test30',
  value: '',
  offset: 0,
  partition: 0,
  highWaterOffset: 2,
  key: '' }
Got message { topic: 'test30',
  value: 'world',
  offset: 1,
  partition: 0,
  highWaterOffset: 2,
  key: null }
Got message { topic: 'test30',
  value: '',
  offset: 0,
  partition: 0,
  highWaterOffset: 2,
  key: ''
... 
```
How can I handle that?
Best regards!

### Environment

* Node version: v8.10.0
* Kafka-node version: ^2.6.1
* Kafka version: 2.0.0

**Comment by hyperlink** [comment]
Can you try with version 3.0?

**Comment by hyperlink** [comment]
I'm glad that worked for you. 

> Does it mean that 2.6.1 version is deprecated?

We don't have bandwidth to support older releases.

I thought yarn just used npm's repository? Not familiar with it.

**Comment by comrat** [comment]
Anyway problem is solved
Thank you once again
