### ISSUE TITLE
TopicsNotExistError: The topic(s) xxx do not exist in kafka-node?

### ISSUE THREAD

**Issue by helxsz** [SOHU-Co/kafka-node#1074]
### Environment

* Node version: v8.11.3
* Kafka-node version: latest
* Kafka version: 2.0.0

i am using kafka to build two consumer client as the code shown below, but it gave me a error, saying

> TopicsNotExistError: The topic(s) DEVICE_BINDED do not exist
>     at new TopicsNotExistError (/Users/xisizhe/Documents/projects/mean-master/node_modules/_kafka-node@3.0.0@kafka-node/lib/errors/TopicsNotExistError.js:11:9)
>     at /Users/xisizhe/Documents/projects/mean-master/node_modules/_kafka-node@3.0.0@

How can I solve this?

### Include Sample Code to reproduce behavior

```js
var kafka = require('kafka-node');

function ConnectionProvider() {
    this.getConsumer = function (topic_name) {
          console.log('consumer consumer',topic_name);
          this.client = new kafka.Client("localhost:2181");
          this.kafkaConsumerConnection = new kafka.Consumer(this.client,[ { topic: topic_name, partition: 0 }]);
          this.kafkaConsumerConnection.on('ready', function () {
            console.log('consumer ready!')
          })
      return this.kafkaConsumerConnection;
    };

    //Code will be executed when we start Producer
    this.getProducer = function () {

        if (!this.kafkaProducerConnection) {
            this.client = new kafka.Client("localhost:2181");
            var HighLevelProducer = kafka.HighLevelProducer;
            //this.kafkaProducerConnection = new HighLevelProducer(this.client);
            this.kafkaProducerConnection = new kafka.Producer(this.client);
            var self = this;
            this.kafkaProducerConnection.on('ready', function () {
                logger.debug('producer ready');

                self.kafkaProducerConnection.on('error', function (err) {
                    console.error("Error " + err)
                })
            });

        }
        return this.kafkaProducerConnection;
    };
}


const device_add_consumer  = connection.getConsumer(config.kafka.topic.DEVICE_ADDED);
```

**Comment by cricket007** [comment]
I don't think this is an issue with the repo.

Your question on Stackoverflow is sufficient. 
https://stackoverflow.com/questions/52245766/topicsnotexisterror-the-topics-xxx-do-not-exist-in-kafka-node

At the very least, you need to show your topic actually does exist, and you shouldn't be using the deprecated Client

**Comment by hyperlink** [comment]
@helxsz if you switched to using the `KafkaClient` you can create the topic using the [createTopic method](https://github.com/SOHU-Co/kafka-node#createtopicstopics-cb) before producing to it.
