### ISSUE TITLE
Multiple Consumer Per Client not working.

### ISSUE THREAD

**Issue by mmatthews06** [SOHU-Co/kafka-node#108]
I am trying to create two consumers that use the same client, but only the first that is created ever receives any, "message," events.  Is this supposed to be something that's supported?

I can provide example code if multiple consumers are expected to work, or if this is something that will be supported in the future.

To accomplish what we need, either creating multiple clients, or using one consumer to read multiple topics works fine.  Maybe a note in the documentation is all we need.

**Comment by haio** [comment]
Will update this in document

**Comment by imsnif** [comment]
The problem with the consumer with a new client approach is that each new client creates a new network connection to Kafka. Is there some way around this?
