### ISSUE TITLE
Hanging timeouts after KafkaClient closure

### ISSUE THREAD

**Issue by twawszczak** [SOHU-Co/kafka-node#1085]
## Bug Report
I think all ```setTimeout``` instructions in KafkaClient (i did not checked ZK Client) should be immediately cleared after ```close``` method. For example (and especially, because requestTimeout could be quite long, default 30s) it concerns request timeouts (wrapper only used in KafkaClient)

### Environment

* Node version: 8.9
* Kafka-node version: 3.0.1

**Comment by chrisandrews7** [comment]
👍

**Comment by hyperlink** [comment]
This should be fixed in 4.0.0.
