### ISSUE TITLE
npm "latest" version is 102.5.1, not 3.0.1, causing confusion

### ISSUE THREAD

**Issue by dylang** [SOHU-Co/kafka-node#1088]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

## Bug Report

Wrong version tagged as `latest` in npm registry:

```json
{ "latest": "102.5.1" },
```

According to https://github.com/SOHU-Co/kafka-node/releases, the latest release as of when this ticket was created is `3.0.1`, so that should be tagged as `latest`. 

This is breaking automatic upgrade tools like [renovate](https://renovatebot.com/) because they are suggesting upgrading to `102.5.1`.

### Include Sample Code to reproduce behavior

```
$ npm info kafka-node

kafka-node@102.5.1 | MIT | deps: 13 | versions: 105
Client for Apache Kafka v0.8.1+, v0.9.x, and v0.10.x

keywords: kafka, zookeeper, consumer, producer, broker

dist
.tarball: https://martifactory.io/api/npm/virtual-npm/kafka-node/-/kafka-node-102.5.1.tgz
.shasum: bd14573b2dc8c6bcc0ba24f0714ccbd258584f20

dependencies:
async: ^2.5.0                 buffer-crc32: ~0.2.5          lodash: ^4.17.4               node-zookeeper-client: ~0.2.2 uuid: ^3.0.0
binary: ~0.3.0                buffermaker: ~1.2.0           minimatch: ^3.0.2             optional: ^0.1.3
bl: ^1.2.0                    debug: ^2.1.3                 nested-error-stacks: ^2.0.0   retry: ^0.10.1

dist-tags:
latest: 102.5.1
```

**Comment by hyperlink** [comment]
There's something wrong with your registry. npm's registry is `3.0.1`

**Comment by dylang** [comment]
Why yes, you are correct, let me talk to my team, thanks @hyperlink!
