### ISSUE TITLE
Consume all old messages after server restart

### ISSUE THREAD

**Issue by dinhthibc** [SOHU-Co/kafka-node#1090]
I'm using kafka-node for my nodejs application connect to Apache Kafka on Heroku, but when I start the server, the consumer get all old messages again
How can I consume from the last offset? 

```js
const client = new KafkaClient(kafkaOptions);

var options = { 
    autoCommit: true,
    encoding: 'utf8',
};
const consumer = new Consumer(client, [{ topic: 'create_address'}], options);
consumer.on('message', function (message) {
    console.log(message);
});
```

My code above works fine in localhost (consume from the last offset) but does not in Apache Kafka on Heroku
Thanks

**Comment by edgarjrg** [comment]
I understand you need to add a groupId in order to let zookeeper track the offset.

**Comment by hyperlink** [comment]
Should have a consistent groupId and should also use a `ConsumerGroup` so it can consume automatically from all partitions.
