### ISSUE TITLE
How to start reading messages from offset 0 with ConsumerGroupStream

### ISSUE THREAD

**Issue by Alequin** [SOHU-Co/kafka-node#1122]
- kafka-node version 3.0.1

We are successfully making use of the ConsumerGroupStream to read in messages from Kafka but were hoping there would be an option to read all messages from offset 0 of a partition. After reading through the docs and the code I cannot see a solution.

**Comment by hyperlink** [comment]
ConsumerGroup can start read from the earliest or latest. But earliest may not be offset 0 due to your broker's retention settings.
