### ISSUE TITLE
Why my consumer is not working?

### ISSUE THREAD

**Issue by B1anker** [SOHU-Co/kafka-node#1123]
## Questions?
I tested it in two ways, one was using the command line and the other was writing the nodejs.

As you can see the result in my terminal at the bottom image.

The left window is consumer and it could receive the middle window's messages which is producer, but the right window was not worked.

![kafka](https://user-images.githubusercontent.com/17514962/48396666-31974100-e756-11e8-9b50-671fd6e3cda5.png)

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

### Environment

* Node version: v9.11.2
* Kafka-node version: v3.0.1
* Kafka version:v0.11.0.2

### For specific cases also provide
* Number of Brokers:5
* Number partitions for topic:0

### Include Sample Code to reproduce behavior

This's my nodejs's code:
```js
// include code here
var kafka = require('kafka-node')
var Consumer = kafka.Consumer,
  client = new kafka.KafkaClient({
    kafkaHost: 'x1.aaa.com:9092,x2.aaa.com:9092,x3.aaa.com:9092,x34.aaa.com:9092,x5.aaa.com:9092'
  }),
  consumer = new Consumer(client, [{
    topic: 'xxx',
    partition: 0
  }], {
    autoCommit: true,
    groupId: 'xxxx'
  })

consumer.on('message', function(message) {
  console.log(message.value)
})
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by hyperlink** [comment]
Sounds like you answered your own question?

**Comment by B1anker** [comment]
@hyperlink online is not working but local is working, I want online count work as local!

**Comment by ilkertuna** [comment]
+1
