### ISSUE TITLE
How to get always last message with ConsumerGroup 

### ISSUE THREAD

**Issue by evgenydk** [SOHU-Co/kafka-node#1126]
I want my app to be able to get the latest one message from a topic, even if the offset had been comitted. Now, when application is restarted and there were no new messages, I don't get anything.

The closest to desired behaviour I could achieve while using `autoCommit: true`. I can manually get the latest one, but there could be a lot of old messages that are definitely not needed. Is that possible to get only last message? Thank you.

**Comment by hyperlink** [comment]
I suppose you could fetch the latest offset for all partitions and then set the initial fetch offset in the consumergroup to -1 whatever that was. Good luck!
