### ISSUE TITLE
What if my broker was shutdown by hardware problem, will producer will retry sending the message?

### ISSUE THREAD

**Issue by Celthi** [SOHU-Co/kafka-node#1130]
If I have 1 broker and the broker the producer tries to send to shut down, will the producer retry to send the message until the broker start again?

What if I have 3 brokers, will the producer will know how to send the messages to the new leader broker?

I see there are message reliability provided by the library Librdkafka https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#message-reliability .
In librdkafka, there will be retry in the library code so the application code don't have to handle the cases. Does kafka-node does the similar handle in the library?

Does the kafka-node has the same machanism. 

I'm newly to kafka and kafka-node. Any help is very appreciated.

**Comment by hyperlink** [comment]
You will need to add retry if there's a failure in the callback. The module doesn't make this decision for you since message order might be important for some users. The client should automatically fetch metadata again and determine the new leader if it encounters an error related to that.
