### ISSUE TITLE
When I specify 3 kafka host in the Client, how do I know which host the producer is connecting with?

### ISSUE THREAD

**Issue by Celthi** [SOHU-Co/kafka-node#1134]
```
let kafkahost = '127.0.0.1';
var client = new kafka.KafkaClient({kafkaHost:`${kafkahost}:32773,${kafkahost}:32774,${kafkahost}:32775`}),
    Producer = kafka.Producer,
    producer = new Producer(client);
```

How do I know which host the producer is connecting to?

I want to kill the host that the producer is connecting to see how the producer will behavior. Does the producer pop out an error? Or it will select the next leader host to send the messages?

**Comment by ncalibey** [comment]
When a producer connects to a broker it has access to the entire cluster. By connecting it to all three of the brokers there, you're guaranteeing that if one goes down it can still write to the other two. If you only connect it to one broker (i.e., only `${kafkahost}:32773`) and then kill that broker, the producer won't be able to access the cluster

**Comment by Celthi** [comment]
@ncalibey 
Thank you very much. I tested it before and I mistook the error messages so I think it can not send to other brokers. 
Now I have another question given that the error messages I saw, can I use zoo keeper's ip and port when creating the KafkaCilent?
Why I want to use zoo keeper's ip and port? It is because:

If I use Kafkas' ip and port, when I kill the broker, it will periodically try to reconnect the broker I kill. But due the Kafka docker image I use, it will generate a new port when I start the Kafka container I kill.  [Kafka Docer I use](https://hub.docker.com/r/wurstmeister/kafka/)

I see the document saying that it has deprecated the zookeeper way. Is it not recommended? And then why it is not recommended?

**Comment by ncalibey** [comment]
@Celthi 
Sorry for taking a little to get back to you. Just so you know I don't actually contribute to the project, just another user, so I may not always respond right away.

If you read the `README` of wurstmeister's docker image for Kafka, you'll see that it specifies that you can set a port for your broker so that when it restarts it'll maintain the same port. He has a `docker-compose.yml` file example for [single broker setup](https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose-single-broker.yml). That might fix your problem.

**Comment by hyperlink** [comment]
> I see the document saying that it has deprecated the zookeeper way. Is it not recommended? And then why it is not recommended?

Kafka has deprecated the use of zookeeper for tracking offsets and broker discovery. Everything should go directly through kafka brokers. Once a client successfully connects to a broker it will do a metadata call to retrieve the rest of the cluster.

**Comment by Celthi** [comment]
@ncalibey 
Thank you very much. The way specify individual brokers should work.

**Comment by Celthi** [comment]
@hyperlink 

Thank for the clarification.
