### ISSUE TITLE
kafka.ConsumerGroup creates topic automatically

### ISSUE THREAD

**Issue by Khelleos** [SOHU-Co/kafka-node#1135]
### Bug Report
Why kafka.ConsumerGroup creates topic in kafka (topic is not exist in kafka) automatically when it is initiated? But when I tried to add new topic to consumerGroup dynamically, it throws error that topic is not exist in kafka.

### Environment
* Node version:
v8.11.3
* Kafka-node version:
v3.0.1
* Kafka version:
2.1.0

### Include Sample Code to reproduce behavior
```js
const consumerGroupOptions= {
   id: "consumer",
   host: kafkaUrl,
   sessionTimeout: 10000,
   groupId: "kafka-node-group",
   fromOffset: FromOffsetValues.Earliest
};
const consumer = new kafka.ConsumerGroup(consumerGroupOptions, "test_topic");
```

**Comment by hyperlink** [comment]
Automatic topic creation is an setting on the kafka broker. It's probably not safe to rely on it. I would use the topic APIs to [create the topic](https://github.com/SOHU-Co/kafka-node#createtopicstopics-cb) before adding it to the ConsumerGroup.

**Comment by Khelleos** [comment]
@hyperlink, thanks for reponse. I know about property 'auto.create.topics.enable' in kafka, but why there is two different behaviour? When kafkaConsumer is initiated and connects to zookeeper/kafka, it creates automatically topic in kafka. But when I try to add new topic kafkaConsumerGroup, it throws error. Is it related to configuration of kafka?
