### ISSUE TITLE
Question: How to configure consumers to ignore old data?

### ISSUE THREAD

**Issue by accnops** [SOHU-Co/kafka-node#1141]
I'm only interested in the latest data. Data loss is acceptable when a client goes down for a short period. So basically, I don't want offsets. Can I then just configure my consumers like this:

```
{
    "autoCommit": false,
    "fromOffset": "latest"
}
```

Will this work?

If I update my existing consumers with `"autoCommit": false`, will the existing offset be used? Will they get old data at every request, or will the offset expire?

**Comment by hyperlink** [comment]
Seems reasonable to me and you may also want to set `commitOffsetsOnFirstJoin` to false as well.
