### ISSUE TITLE
Node-Kafka fails to pass messages from producer to consumer in Amazon MSK

### ISSUE THREAD

**Issue by domderen** [SOHU-Co/kafka-node#1143]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

## Bug Report

Hey, I'm new to kafka, and wanted to try out Amazon's new MSK service, that is Managed Streams for Kafka. I tried integrating it into my application, and everything worked fine when I ran it using a localhost Docker version of Kafka using `landoop/fast-data-dev` image. It seems that this image has Kafka v1.1.1.

The problem started when I tried switching to the MSK deployment of Kafka (that also runs Kafka v1.1.1). When I ran my application there, the Producer was able to publish the message, but consumer was getting an error `UnknownTopicOrPartition` when it was trying to pick up the message from my topic. 

The full stack trace looked like this:

```
Tue, 11 Dec 2018 05:01:00 GMT kafka-node:KafkaClient compressing messages if needed
Tue, 11 Dec 2018 05:01:00 GMT kafka-node:KafkaClient payloads has no leaders! Our metadata could be out of date try refreshingMetadata [ { topic: 'chromium-outgoing-messages-8',
    partition: 0,
    messages: [ [Object] ],
    attributes: 0 } ]
Tue, 11 Dec 2018 05:01:00 GMT kafka-node:Client refresh metadata currentAttempt 1
Tue, 11 Dec 2018 05:01:01 GMT kafka-node:Client refresh metadata currentAttempt 2
Tue, 11 Dec 2018 05:01:01 GMT kafka-node:Client refresh metadata currentAttempt 3
Tue, 11 Dec 2018 05:01:02 GMT kafka-node:Client refresh metadata currentAttempt 4
Tue, 11 Dec 2018 05:01:03 GMT kafka-node:Client refresh metadata currentAttempt 5
Tue, 11 Dec 2018 05:01:04 GMT kafka-node:Client refresh metadata currentAttempt 6
Tue, 11 Dec 2018 05:01:05 GMT kafka-node:Client refresh metadata currentAttempt 7
Tue, 11 Dec 2018 05:01:05 GMT kafka-node:ConsumerGroup checking for new topics and partitions
Tue, 11 Dec 2018 05:01:05 GMT kafka-node:ConsumerGroup no new Topic/Partitions
Tue, 11 Dec 2018 05:01:05 GMT kafka-node:ConsumerGroup consumer2 is leader scheduled new topic/partition check
Tue, 11 Dec 2018 05:01:06 GMT kafka-node:Client refresh metadata currentAttempt 8
Tue, 11 Dec 2018 05:01:07 GMT kafka-node:Client refresh metadata currentAttempt 9
Tue, 11 Dec 2018 05:01:08 GMT kafka-node:Client refresh metadata currentAttempt 10
Tue, 11 Dec 2018 05:01:09 GMT kafka-node:Client refresh metadata currentAttempt 11
Tue, 11 Dec 2018 05:01:09 GMT kafka-node:Client refresh metadata error UnknownTopicOrPartition
Tue, 11 Dec 2018 05:01:09 GMT kafka-node:Client refresh metadata currentAttempt 1

Error: UnknownTopicOrPartition
    at /usr/src/app/node_modules/kafka-node/lib/client.js:533:17
    at async.series (/usr/src/app/node_modules/kafka-node/lib/kafkaClient.js:885:5)
    at /usr/src/app/node_modules/async/dist/async.js:3888:9
    at /usr/src/app/node_modules/async/dist/async.js:473:16
    at replenish (/usr/src/app/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/usr/src/app/node_modules/async/dist/async.js:995:17)
    at /usr/src/app/node_modules/async/dist/async.js:969:16
    at /usr/src/app/node_modules/async/dist/async.js:3885:13
    at KafkaClient.wrappedFn (/usr/src/app/node_modules/kafka-node/lib/kafkaClient.js:471:14)
    at KafkaClient.Client.invokeResponseCallback (/usr/src/app/node_modules/kafka-node/lib/client.js:827:10)
    at KafkaClient.Client.handleReceivedData (/usr/src/app/node_modules/kafka-node/lib/client.js:803:10)
    at KafkaClient.handleReceivedData (/usr/src/app/node_modules/kafka-node/lib/kafkaClient.js:1226:48)
    at Socket.<anonymous> (/usr/src/app/node_modules/kafka-node/lib/kafkaClient.js:782:10)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
```

I then tried to create a small example that reproduces this issue, using examples found in this repository. The result is in this gist: https://gist.github.com/domderen/99b727c6cef6811e213b4969539a2bce

Again, running those apps locally on Dockerized Kafka worked just fine. Switching to AWS MSK, again caused the same issue, but this time, it was the producer that was returning the same error, while consumer never got the message. Here is a screenshot of the logs when running this small example on MSK: https://cl.ly/ec4b48116cf3

I tried using MSK with the example that they have in their docs: https://docs.aws.amazon.com/msk/latest/developerguide/produce-consume.html

I was able to create topic, produce and consume messages using the standard Kafka utils. So the instance seems to be fine, but I'm not sure why the problem happens when I switch to using Kafka-Node library.

Did anyone saw similar issues, or knows what `UnknownTopicOrPartition` might be related to in this case?

Thanks in advance for your help!

### Environment

* Node version: v10.13.0
* Kafka-node version: v3.0.1
* Kafka version: v1.1.1

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 1

### Include Sample Code to reproduce behavior

https://gist.github.com/domderen/99b727c6cef6811e213b4969539a2bce

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by domderen** [comment]
Actually it turns out that on MSK Kafka-Node library is not creating the topics automatically when publishing messages. That's why my producer fails. After creating the topic manually, everything worked. If the feature of creating topics automatically, something that has be enabled on the server side?

**Comment by ahmedlafta** [comment]
@domderen `auto.create.topics.enable` is a broker config and defaults to `true`
https://kafka.apache.org/documentation/
I'm not sure how to configure this with amazon's MSK service though.

**Comment by domderen** [comment]
Cool thanks for letting me know, I’ll follow up with AWS support to see if that is configurable in MSK.

**Comment by domderen** [comment]
It seems they don't at the moment.

**Comment by orcr** [comment]
I it using aws cli on following link you will find the way to configure
[AWS Kafka configuration](https://docs.aws.amazon.com/msk/latest/developerguide/msk-configuration-operations.html)
