### ISSUE TITLE
Removal of Zookeeper dependency

### ISSUE THREAD

**Issue by sideeque786** [SOHU-Co/kafka-node#1145]
I see latest documentation (https://www.npmjs.com/package/kafka-node) that zookeeper based client  is deprecated. Can you remove the dependancy. I get error using with webpack but the fix is not available with zookeeper yet(https://github.com/alexguan/node-zookeeper-client/pull/73). When will be the next release with removal of zookeeper?

**Comment by hyperlink** [comment]
Yes, we can remove zookeeper in the next major release.

**Comment by adityataday** [comment]
@hyperlink When is the next release scheduled to be? Seems like there will be a lot of updates and bug fixes to consumerGroupStream. Thanks
