### ISSUE TITLE
Doc Fix: Should kafka.Client still be used?

### ISSUE THREAD

**Issue by gishu** [SOHU-Co/kafka-node#1146]
New to the library here..

The readme mentions that kafka.Client is deprecated in favor of kafka.KafkaClient.
However the Producer/Consumer examples still continue to use the older Client.

Tried using KafkaClient in lieu of Client in the example - doesn't seem like a straight replacement.

Can you please clarify this in the readme?

kafka-node 3.0.1 on MacOS High Sierra 10.13.6 + node v8.11

**Comment by hyperlink** [comment]
I'm planning on removing zookeeper dependency from the project in the next major release so hopefully it will be clearer then. Thanks for the feedback!
