### ISSUE TITLE
Unable to create array of topic: InvalidConfigError: topic name [object Object] is illegal, contains a character other than ASCII alphanumerics

### ISSUE THREAD

**Issue by SubhashPavuskar** [SOHU-Co/kafka-node#1147]
```
var kafka = require('kafka-node');
var client = new kafka.KafkaClient();
 
var topicsToCreate = [{
  topic: 'topic1',
  partitions: 1,
  replicationFactor: 2
},
{
  topic: 'topic2',
  partitions: 5,
  replicationFactor: 3
}];
 
client.createTopics(topics, (error, result) => {
  // result is an array of any errors if a given topic could not be created 
});
```

In the above snippet contain array of topics _topicsToCreate_  but while creating createTopics passing  **_topics_**. So i changed in my code and passing the **_topicsToCreate_** variable in the createTopics function. now facing the below exception 

> _ InvalidConfigError: topic name [object Object] is illegal, contains a character other than ASCII alphanumerics .,_ and -_

**Comment by hyperlink** [comment]
Your example does not show the value of `topics` but it should be similar to the structure of `topicsToCreate` .

**Comment by SubhashPavuskar** [comment]
Exactly i am referring from npm kafka-node documentation and this is the link [https://www.npmjs.com/package/kafka-node](url)
i have changed from _**topics**_  to **_topicsToCreate _** where sending array of object.
But once you pass **_topicsToCreate _**  in createTopics below exception it will throw

`Unable to create array of topic: InvalidConfigError: topic name [object Object] is illegal, contains a character other than ASCII alphanumerics`
