### ISSUE TITLE
Broker id of undefined when it equals 0

### ISSUE THREAD

**Issue by StorkZ** [SOHU-Co/kafka-node#1175]
Hello guys!
I just started using this lib. After installing Kafka on my minikube using this chart:
https://github.com/helm/charts/tree/master/incubator/kafka
I have problem with creating new topics using client/admin. 
```
"Error: No broker with id undefined
at KafkaClient.sendRequestToBroker (/usr/src/app/node_modules/kafka-node/lib/kafkaClient.js:1089:21)
...
```
After looking through the code and some debugging I found error in this line:
https://github.com/SOHU-Co/kafka-node/blob/26531fc6f3c5575e0e2aa3466d2dbdddeba18019/lib/kafkaClient.js#L258

It checks if `controllerId` is defined but in my config it equals `0`. 
I kind of fixed it for now by changing `0` to `'0'` and everything works fine, but it would be nice to fix it by checking if its undefined or null.

**Comment by mvataleu** [comment]
Hello. Could you please push this fix to the npm? The latest published version (4.0.0) doesn't contain this fix. Thanks in advance.

**Comment by deju** [comment]
i have the problem too when using version 4.0.2

**Comment by hyperlink** [comment]
> i have the problem too when using version 4.0.2

Looks like the controllerId/brokerId was undefined. What version is your kafka broker?

**Comment by deju** [comment]
the version of kafka is v2.1.1
@hyperlink

**Comment by hyperlink** [comment]
@deju I have not been able to reproduce this issue.
