### ISSUE TITLE
Batching producer requests when using keyed partitioner

### ISSUE THREAD

**Issue by ajwootto** [SOHU-Co/kafka-node#1178]
Hi,

It seems that HighLevelProducer supports two ways to produce multiple messages in a single call. You can either pass an array of "payloads" to the method which each contain message(s), or you can put all your outbound messages into the messages array of a single payload. 

There is also a warning:

⚠️WARNING: Batch multiple messages of the same topic/partition together as an array on the messages attribute otherwise you may lose messages!

In my use case, I'm using a keyed partitioner, with the key being a particular piece of information from the messages themselves. The key has to be defined at the payload level, and the key is different for each message, but I only have 20 partitions so multiple different keys will hash to the same partition. According to that warning I'm not supposed to put more than one payload in the request if it's going to the same partition (which I have no way to determine because my keys may or may not resolve to the same partition).

Given all this, is there any way for me to use a keyed partitioner and still publish batches of messages?

Thanks

**Comment by hyperlink** [comment]
I think this was fixed awhile ago and not sure if this is an issue anymore.

**Comment by ajwootto** [comment]
Is there any way to verify that for sure?

**Comment by hyperlink** [comment]
I believe this is the same issue the message was referring to #515
