### ISSUE TITLE
ConsumerGroup fails to resume message consumption on brief connection loss

### ISSUE THREAD

**Issue by badeball** [SOHU-Co/kafka-node#1179]
### Environment

* Node version: v11.6.0
* Kafka-node version: v4.0.0
* Kafka version: v2.1.0

I am experiencing that a ConsumerGroup fails to resume consumption of messages after a brief connection loss. _If however_, the loss of connection is long enugh that a heartbeat is invoked during the outage, then `refreshBrokerMetadata failed` will be emitted, _and a JoinGroup request is sent after reconnecting_. It seems that this doesn't otherwise happen when the outage is brief.

Is this a sufficient explanation to go on? If not, then I will attempt to put together some code to reproduce the issue.

**Comment by hyperlink** [comment]
Yes more details would be helpful thanks!

**Comment by badeball** [comment]
I've put together an [example](https://gist.github.com/badeball/a8f7015e76d831da8228f07aa1565865) that illustrates the issue (this is unfortunately a big one).

The example reproduces connection loss in a producer and a consumer, by using Nginx as a proxy and restarting it midway. The producer successfully reconnects and is able to send another message. The consumer however seems to reconnect, but no message is ever emitted.

If one increase the outage by 10s, using the command shown below, then the consumer succeeds in reconnecting and consuming messages.

```
$ sed -i "s/# sleep/sleep/" restartable.sh
```

Are you able to run it and reproduce the issue?

**Comment by hyperlink** [comment]
I was able to reproduce this. I will put up a fix ASAP. Thank you!
