### ISSUE TITLE
support kafka 0.8.2

### ISSUE THREAD

**Issue by fadaytak** [SOHU-Co/kafka-node#118]
hi,

 any support for the kafka 0.8.2 ?

crodially

**Comment by eudaimos** [comment]
I would like this as well - for anyone coming across this, I can state from experience that this library does *not* work with kafka 0.8.2.beta.  When executing, you will get a lot of sockets terminating on kafka's side, topics losing leaders and offsets not being committed.

**Comment by DeanHere** [comment]
Just would like to know do you guys have a plan or schedule to have this supporting for the last kafka release of 0.8.2.0(The current stable version is 0.8.2.0). Thanks

**Comment by haio** [comment]
Yes we will support 0.8.2
I have done some rough tests with kafka 0.8.2.0(build from source code) with the exists api in kafka-node and it works fine, maybe I missed something.
The next plan is implement new api and features come with 0.8.2. If you got any problem related with Kafka 0.8.2.x, please write it down here, all discussions and PR are welcome.

**Comment by MayhemYDG** [comment]
I'm having an issue where kafka-node's consumer will try to fetch from a topic that was deleted, then re-created, with an offset that's not 0.

**Comment by kadishmal** [comment]
0.8.2.1 with critical patches have been released https://archive.apache.org/dist/kafka/0.8.2.1/RELEASE_NOTES.html.
