### ISSUE TITLE
Same message is being consumed by the multiple pods. (Consumer)

### ISSUE THREAD

**Issue by Sumukha1496** [SOHU-Co/kafka-node#1183]
## Questions?

*I am running my kafka-node application in 8 pods. It consumes from a topic(6 partitions) and does some processing. But I found out that each pod is consuming the same message. So the same message is being processed 8 times. I am using 'Consumer' of kafka-node. How to make the messages getting sent to only one pod?

### Environment

* Node version:
* Kafka-node version: 2.6.1
* Kafka version:

### For specific cases also provide
* Number of Brokers:
* Number partitions for topic: 6

### Include Sample Code to reproduce behavior

```js
let consumer = new kafka.Consumer(client, topics, consumerOptions);

  consumer.on("message", (message)=> {
    const processedData = processMessage(message);
    if (processedData) {
      sendAndCommit(processedData, offset, message);
    }
  });
```

This is the consumer options : 

consumerOptions:
    groupId: testGroup
    autoCommit: false
    fetchMaxWaitMs: 30000
    fetchMaxBytes: 1048576
    encoding: utf8
    fetchMinBytes: 500
    requireAcks: 0
    fromOffset: false

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by hyperlink** [comment]
Try using a `ConsumerGroup`. Make sure you are using the same `groupId`. Hope that helps!
