### ISSUE TITLE
How to pass the SSL config like truststore location and password?

### ISSUE THREAD

**Issue by THPubs** [SOHU-Co/kafka-node#1185]
Right now I have configured my Kafka server with a self-signed certificate.

    version: '2'
    services:
      zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
          - 2181:2181
        hostname: zookeeper
      kafka:
        image: wurstmeister/kafka:2.11-2.0.0
        command: [start-kafka.sh]
        ports:
          - 9093:9093
        hostname: kafka
        environment:
          KAFKA_LISTENERS: SSL://0.0.0.0:9093
          KAFKA_ADVERTISED_LISTENERS: SSL://alfrescokafka.leafycode.com:9093
          KAFKA_SSL_KEYSTORE_LOCATION: /home/amur42s/ssl/kafka.server.keystore.jks
          KAFKA_SSL_KEYSTORE_PASSWORD: oE4KJ9FVMjMXGpgpp0qwLzUDy0uz
          KAFKA_SSL_KEY_PASSWORD: oE4KJ9FVMjMXGpgpp0qwLzUDy0uz
          KAFKA_SSL_TRUSTSTORE_LOCATION: /home/amur42s/ssl/kafka.server.truststore.jks
          KAFKA_SSL_TRUSTSTORE_PASSWORD: 123
          KAFKA_ADVERTISED_HOST_NAME: 116.203.65.132 # docker-machine ip
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_CREATE_TOPICS: ""
          KAFKA_SSL_CLIENT_AUTH: 'required'
          KAFKA_SECURITY_INTER_BROKER_PROTOCOL: 'SSL'
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/ssl:/home/ssl
        depends_on:
          - "zookeeper"

Unfortunetely, I'm unable to connect to it using kafka node. Looks like I need to set the `ssl.truststore.location` and `ssl.trsutstore.password`. How can I do this?

**Comment by hyperlink** [comment]
You should not need to pass those options in the client.  If it's self-signed you will need to include this option in the KafkaClient option:

```
        sslOptions: {
          rejectUnauthorized: false
        }
```

**Comment by THPubs** [comment]
@hyperlink Thanks it worked!

**Comment by meetumaltiar** [comment]
Hi, what to do if its properly signed certificate? I need these values to set in my code.
security.protocol=SSL
ssl.truststore.location=kafka.client.truststore.jks
ssl.truststore.password=clientpass

**Comment by hyperlink** [comment]
Nothing. Just pass an empty sslOptions object and provide the correct kafka port.

**Comment by CooooSo** [comment]
> Nothing. Just pass an empty sslOptions object and provide the correct kafka port.

Hi, I hava the same question. 

> Hi, what to do if its properly signed certificate? I need these values to set in my code.
> security.protocol=SSL
> ssl.truststore.location=kafka.client.truststore.jks
> ssl.truststore.password=clientpass

Hi, I get the same question. How do you fix it? Just pass an empty sslOptions?

**Comment by clion94** [comment]
I am facing the same issue. Has anyone bee able to figure this out? 

> You should not need to pass those options in the client. If it's self-signed you will need to include this option in the KafkaClient option:
> 
> ```
>         sslOptions: {
>           rejectUnauthorized: false
>         }
> ```

The above did not work me.

**Comment by hyperlink** [comment]
add `ca` option with the contents of your .pem file.

**Comment by marugechen** [comment]
you should make an example for ssl

**Comment by belabartha** [comment]
An example for TLS/SSL connection would help a lot. Eventually a tutorial.

**Comment by Ferdy2003** [comment]
Here is my solution:

```
var kafkaClientOption = {
  clientId: 'kafkaadmin',
  kafkaHost : 'broker1:9092,broker2:9092,broker3:9092',
  ssl: true,
  sslOptions: {
    rejectUnauthorized: false,
    ca: [fs.readFileSync('./bin/chain.pem', 'utf-8')],
    cert: [fs.readFileSync('./bin/kafkaadmin.pem', 'utf-8')],
    key: [fs.readFileSync('./bin/kafkaadmin.key', 'utf-8')],
    passphrase: "mypass",
  },
  autoConnect: true,
  connectTimeout: 1000,
  requestTimeout: 1000
}

var client = new kafka.KafkaClient( kafkaClientOption );
```

**Comment by marugechen** [comment]
Thank u very much, and I  solved this problem by the method  u provide

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Ferdy2003 <notifications@github.com>
发送时间: Wednesday, August 14, 2019 4:44:58 PM
收件人: SOHU-Co/kafka-node <kafka-node@noreply.github.com>
抄送: marugechen <marugezte@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [SOHU-Co/kafka-node] How to pass the SSL config like truststore location and password? (#1185)


Here is my solution:

var kafkaClientOption = {
  clientId: 'kafkaadmin',
  kafkaHost : 'broker1:9092,broker2:9092,broker3:9092',
  ssl: true,
  sslOptions: {
    rejectUnauthorized: false,
    ca: [fs.readFileSync('./bin/chain.pem', 'utf-8')],
    cert: [fs.readFileSync('./bin/kafkaadmin.pem', 'utf-8')],
    key: [fs.readFileSync('./bin/kafkaadmin.key', 'utf-8')],
    passphrase: "mypass",
  },
  autoConnect: true,
  connectTimeout: 1000,
  requestTimeout: 1000
}

var client = new kafka.KafkaClient( kafkaClientOption );


―

**Comment by prabhatmishra-metro** [comment]
Hello, Don't we have support for the `JKS` file?

**Comment by prabhatmishra33** [comment]
Hello, Don't we have support for the `JKS` file ?

**Comment by drstil** [comment]
Is there still a solution for this issue? I'm using the following configuration, but always got the following error:

```
options.ssl = {
    rejectUnauthrorized: false,
    cert: cert.pem,
    key: key.pem,
    ca: 'For this I tried all combinations of certificates (cert.pem, cert and key.pem, cert-signed, docker.kafka.server.keystore.pem,
    passphrase: 'x'
}
```

> Error: Client network socket disconnected before secure TLS connection was established

Created certificates like written here: [https://github.com/trastle/docker-kafka-ssl](https://github.com/trastle/docker-kafka-ssl).

I have the truststore configured for kafka. But those files are only available as .jks-files. Do I have to convert them and add to `ca` configuration? 


**EDIT:**
The error was in Kafka configuration: I used `KAFKA_LISTENERS: SSL://localhost:9092`. It is working with `KAFKA_LISTENERS: SSL://:9092` or `KAFKA_LISTENERS: SSL://0.0.0.0:9092`.
