### ISSUE TITLE
Consumer receiving duplicate messages

### ISSUE THREAD

**Issue by snatesan** [SOHU-Co/kafka-node#1192]
## Bug Report
Consumer receiving duplicate messages.

### Environment

* Node version: 10.15.0
* Kafka-node version: 3.0.1
* Kafka version: 1.1

### For specific cases also provide
* Number of Brokers: 7
* Number partitions for topic: 20

### Include Sample Code to reproduce behavior

I have a consumer created with ConsumerGroupStream with following options
```js
{
  "groupId":"<group id>",
  "autoCommit":true,
  "autoCommitIntervalMs":1000,
  "fetchMaxWaitMs":100,
  "fetchMinBytes":1,
  "fetchMaxBytes":1048576,
  "fromOffset":"latest",
  "encoding":"utf8",
  "id":"<id>",
  "migrateHLC":true,
  "migrateRolling":false,
  "host":"<hostname>:2181/kafka"
}
```
But whenever the consumer is restarted some of already consumed messages got re-delivered.

What I see from the logs is that fetchOffset Response returns -1.
kafka-node:ConsumerGroup ... fetchOffset Response: {"<topic_name>":{"0":-1,"1":-1,"2":-1,"3":-1,"4":-1,"5":271,"6":-1,"7":-1,"8":347,"9":-1,"10":-1,"11":-1,"12":-1,"13":-1,"14":-1,"15":-1,"16":-1,"17":-1,"18":-1,"19":-1}}

Then defaultOffSet Response for latest returns the results.
kafka-node:ConsumerGroup ... defaultOffset Response for latest: {"<topic_name>":{"0":247,"1":370,"2":233,"3":312,"4":229,"5":271,"6":205,"7":298,"8":347,"9":324,"10":274,"11":281,"12":301,"13":289,"14":296,"15":341,"16":347,"17":303,"18":389,"19":245}}

But I get message for partition 3 starting from offset 307
{ topic: '<topic_name>',
  value:'...',
  offset: 307,
  partition: 3,
  highWaterOffset: 312,
  key: '...' }

Shouldn't it start consuming messages from offset 312?

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Mon, 18 Feb 2019 23:56:43 GMT kafka-node:ConsumerGroupStream _read called
Mon, 18 Feb 2019 23:56:43 GMT kafka-node:ConsumerGroupStream consumerGroup is not ready, calling consumerGroup.connect
Mon, 18 Feb 2019 23:56:43 GMT kafka-node:ConsumerGroup Connecting ...
Mon, 18 Feb 2019 23:56:43 GMT kafka-node:ConsumerGroupStream commit ignored. no commits to make.
Mon, 18 Feb 2019 23:56:43 GMT kafka-node:ConsumerGroup Connecting ...
Mon, 18 Feb 2019 23:56:43 GMT kafka-node:ConsumerGroupStream commit ignored. no commits to make.
Mon, 18 Feb 2019 23:56:43 GMT kafka-node:ConsumerGroup GroupCoordinator Response: { coordinatorHost: '...',
  coordinatorPort: 9000,
  coordinatorId: 4 }
Mon, 18 Feb 2019 23:56:44 GMT kafka-node:ConsumerGroup Connect ignored. Currently connecting.
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup joinGroupResponse {"members":[{"subscription":[...],"version":0,"id":"..."}],"generationId":5,"groupProtocol":"roundrobin","leaderId":"...","memberId":"..."} from ...
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup Assigning Partitions to members [ { subscription:
     [ ... ],
    version: 0,
    userData: undefined,
    id: '...' } ]
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup Using group protocol roundrobin
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup loadingMetadata for topics: [ ... ]
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup mapTopicToPartitions {
  '<topic_name>':
   [ '0',
     '1',
     '2',
     '3',
     '4',
     '5',
     '6',
     '7',
     '8',
     '9',
     '10',
     '11',
     '12',
     '13',
     '14',
     '15',
     '16',
     '17',
     '18',
     '19' ] }
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup SyncGroup Request from ...
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup SyncGroup Response
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup ... owns topics:  { 
  '<topic_name>':
   [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19 ] }
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup ... fetchOffset Response: {"<topic_name>":{"0":-1,"1":-1,"2":-1,"3":-1,"4":-1,"5":271,"6":-1,"7":-1,"8":347,"9":-1,"10":-1,"11":-1,"12":-1,"13":-1,"14":-1,"15":-1,"16":-1,"17":-1,"18":-1,"19":-1}}
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup No saved offsets
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup ... defaultOffset Response for latest: {"<topic_name>":{"0":247,"1":370,"2":233,"3":312,"4":229,"5":271,"6":205,"7":298,"8":347,"9":324,"10":274,"11":281,"12":301,"13":289,"14":296,"15":341,"16":347,"17":303,"18":389,"19":245}}
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup generationId 5
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup startFetch is true
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup ... is leader scheduled new topic/partition check
Mon, 18 Feb 2019 23:56:46 GMT kafka-node:ConsumerGroup ... started heartbeats at every 10000 ms

Any help is really appreciated!
Thank you!

**Comment by hyperlink** [comment]
4.x has fixes for duplicate messages. Can you upgrade to the latest and check?

**Comment by mayank13** [comment]
@hyperlink  Using 4.x but still getting duplicate messages.

**Comment by Ridarso** [comment]
@hyperlink any update for this issue?

**Comment by Ridarso** [comment]
@mayank13 do you have any solution for this problem?

**Comment by mayank13** [comment]
@Ridarso : I switched to KafkaJS, looks more stable than this node module. Has good documentation as well.

**Comment by Ridarso** [comment]
@mayank13 thank you. You save me 👍
