### ISSUE TITLE
kafka consumer -group gets failed even one server down from a cluster of kafka

### ISSUE THREAD

**Issue by ngoyal16** [SOHU-Co/kafka-node#1222]
## Questions?
kafka consumer -group gets failed even one server down from a cluster of kafka

### Environment

* Node version: 8.x.x
* Kafka-node version: ^4.0.3
* Kafka version: kafka_2.12-2.1.1

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 1

### Include Sample Code to reproduce behavior

```js
// include code here
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by hyperlink** [comment]
Can you provide some more details?

**Comment by ngoyal16** [comment]
we have in-premise Kafka cluster we are running single consumer in a consumer group.. when due to some issue internal network fails to same Kafka instance fails it retry with the heartbeat time to the same server and drops the connection if it cross the time. it will not try to connect to other Kafka nodes even they are alive in the network

**Comment by hyperlink** [comment]
Can you attach some logs so we could see what the consumer and client are doing?

**Comment by ngoyal16** [comment]
here is the step which is causing consumer-group fail when attach to cluster mode.

we are connecting to our consumer using below function by passing topic name

function KafkaConsumer(topicName, options = {}) {
  this.kafkaConsumer = new kafka.ConsumerGroup(options, topicName);
  return this.kafkaConsumer;
}

this will connect our consumer to the given topic with give option. we provide following options to connect to kafa consumer

{
    kafkaHost: "192.168.1.1:9092,192.168.1.2:9092,192.168.1.3:9092",
    groupId: "123"
    autoCommit: true, 
    autoCommitIntervalMs: 5000,
    sessionTimeout: 15000,
    fetchMaxBytes: 10 * 1024 * 1024, // 10 MB
    protocol: ['roundrobin'],
    fromOffset: 'earliest',
    outOfRangeOffset: 'earliest',
    encoding: "buffer"
}

using these options it connects to cluster. and read data from given topic. but if due to any reason any on the Kafka gets restart/fail our consumer also gets terminated.

seems like it is not behaving auto change of a server when server get fail/restarted.

**Comment by hyperlink** [comment]
Do you have an error listener on your `kafkaConsumer` ?  Node's default behavior is to exit the process when there's no listener attached to the EventEmitter when an error is emitted.
