### ISSUE TITLE
Producer do not retry to send failed messages ?

### ISSUE THREAD

**Issue by fungiboletus** [SOHU-Co/kafka-node#1230]
Does the producer try to resend failed messages ? If I simulate network issues between kafka-node and my kafka nodes, I get errors from kafka-nodes and it looks like the messages are never sent.

Should I keep a buffer to manage the errors outside kafka-node ?

**Comment by hyperlink** [comment]
Yes, you should handle failures and retry in your code.

**Comment by fungiboletus** [comment]
Alright, thanks for your answer.
