### ISSUE TITLE
[Question] What is groupId of Consumer?

### ISSUE THREAD

**Issue by Clan-Utility** [SOHU-Co/kafka-node#1238]
A Consumer with a specified groupId can receive messages. But another Consumer with a different groupId can not, even if the first Consumer is not running. And `bin/kafka-consumer-groups.sh --bootstrap-server localhost:9092 --list` gives nothing. Using ConsumerGroup is OK.

So what is meaning of groupId for Consumer? For case of 1 consumer per 1 group, should I always use ConsumerGroup instead of Consumer?

kafka_2.12-2.1.0
kafka-node 4.1.1

**Comment by hyperlink** [comment]
The groupid is used to keep track of offsets.

Should use probably use a ConsumerGroup unless you need to control the specific partition your consumer consumes from.

**Comment by Clan-Utility** [comment]
I just don't understand why a second Consumer with a different groupId can not receive any message. Anyway, using ConsumerGroup has no problem.
