### ISSUE TITLE
can not connect kafka

### ISSUE THREAD

**Issue by zf329398320** [SOHU-Co/kafka-node#1240]
import * as kafka from "kafka-node"
export const getKfkMsg = async (req, res) =>{
    try{
        const client = new kafka.KafkaClient({ kafkaHost: 'localhost:2181' })
        // topic: 'uplink', 
        const Consumer = kafka.Consumer
        const consumer = new Consumer(
            client,
            [
                { topic: 'uplink', partition: 0 }
            ],
            {
                autoCommit: true,
                fetchMaxWaitMs: 1000,
                fetchMaxBytes: 1024 * 1024,
                encoding: "buffer"
            }
        )
       consumer.on('message', function (message) {
            //can not recived any message, kafka-node version is 4.1.1,  use before kafka.HighLevelConsumer  can get message, why?
            console.log(message);
        });
    }catch(err){
        console.log(err)
        return res.json({
            code: -1,
            msg: err
        })
    }
    
}

**Comment by hyperlink** [comment]
You need to pass a list of kafka broker hosts to KafkaClient. We no longer allow connections to zookeeper since v4.
