### ISSUE TITLE
Kafka client is not connected to AWS MSK 

### ISSUE THREAD

**Issue by msenthu** [SOHU-Co/kafka-node#1242]
Hi,

I have AWS MSK up and running. The kafka client is not connecting and producing the message to the AWS MSK topics. 

Here is the sample code 

  var kafka = require('kafka-node'),
  Producer = kafka.Producer,
  KeyedMessage = kafka.KeyedMessage,
  client = new kafka.KafkaClient({kafkaHost: "x.x.x.x:9092,x.x.x.x:9092,x.x.x.x:9092"}),
  producer = new Producer(client ),
  km = new KeyedMessage('key', 'message'),
  payloads =  { topic: 'testTopic', messages: 'hi' };
  
  client.on("ready", function() {
    console.log("Client Connected.");
  });

  producer.on('ready', function () {
    console.log("preparing to send ");
    producer.send(payloads, function (err, data) {
        console.log("after produce: "+data);
    });
  });

  producer.on('error', function (err) {
    console.log("Error - "+err);
  });

**Comment by hyperlink** [comment]
Can you turn on debugging and also attach the error stack?
