### ISSUE TITLE
Unable to consume data

### ISSUE THREAD

**Issue by 1karthik** [SOHU-Co/kafka-node#125]
I have my kafka installed on cloud.
Trying to connect to it from local machine.

code:
var kafka = require('kafka-node');
var Consumer = kafka.Consumer;
var Producer = kafka.Producer;
var Offset = kafka.Offset;
var Client = kafka.Client;
var argv = require('optimist').argv;
var topic = argv.topic || 'mytopicname';
var client = new Client('remotehostip:2181');
var topics = [
{topic: topic, partition: 1},
{topic: topic, partition: 0}
],
options = { autoCommit: false, fromBeginning: true, fetchMaxWaitMs: 1000, fetchMaxBytes: 1024*1024, autoCommitIntervalMs: 100000};
function createConsumer(topics) {
var consumer = new Consumer(client, topics, options);
var offset = new Offset(client);
consumer.on('message', function (message) {
console.log(this.id, message);
});
consumer.on('error', function (err) {
console.log('error', err);
});
}

createConsumer(topics);

I get the following error:
error { [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND'  errno: 'ENOTFOUND', syscall: 'getaddrinfo' }
close
error { [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND'  errno: 'ENOTFOUND', syscall: 'getaddrinfo' }
close

**Comment by haio** [comment]
#close

**Comment by mllanes** [comment]
I'm having the same issue; I'm running out of docker container and I can run create/list/describe topics without issues using the bin/*.sh scripts but can't create a new client with the node pkg
```
    kafka = require('kafka-node'),
    client = new kafka.Client('192.168.99.100:2181');
```

Any suggestions?

**Comment by hyperlink** [comment]
Looks like node can't connect to your zookeeper host?

**Comment by mllanes** [comment]
So after further testing I discovered the issue was the lack of ADVERTISED_HOST. Once I set that env variable in the container for Kafka it works. I thinks it was a matter of communication between kafka and zookeeper when both were in a docker container.

**Comment by sugir93** [comment]
Got Error
{ Error: connect ECONNREFUSED 104.211.246.27:9092
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '104.211.246.27',
  port: 9092 }
