### ISSUE TITLE
BrokerNotAvailableError

### ISSUE THREAD

**Issue by prasad4491** [SOHU-Co/kafka-node#1259]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

## Bug Report
NestedError {nested: BrokerNotAvailableError, message: "topic/partition change check failed", stack: "NestedError: topic/partition change check failed
### Environment

* Node version:10.15.3
* Kafka-node version: 4.1.3
* Kafka version:kafka_2.12-2.1.1

### For specific cases also provide
* Number of Brokers:3
* Number partitions for topic:1

### Include Sample Code to reproduce behavior

```js
// include code here
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by hyperlink** [comment]
See the explanation in #1228

**Comment by prasad4491** [comment]
No, I am intentionally stopping leader Kafka node to test HA(High availability). I am trying to publish data topic with publisher After closing leader Kafka broker. Then I am getting this error.
