### ISSUE TITLE
Why call the retry function when the socket is closed?

### ISSUE THREAD

**Issue by chosh31** [SOHU-Co/kafka-node#1264]
## Questions

* Why call the `retry` function when the socket is closed?

```
  socket.on('close', function (hadError) {
    ...
    retry(this);
  });
  socket.on('end', function () {
    retry(this);
  });
```
- https://github.com/SOHU-Co/kafka-node/blame/707348d9a9881782f3a390fdcc6362d35cfe24c0/lib/kafkaClient.js#L789

**Comment by hyperlink** [comment]
there could be network issues that closed the socket so we need to reconnect.
