### ISSUE TITLE
Kafka Cluster node restart resends all messages

### ISSUE THREAD

**Issue by elabrc** [SOHU-Co/kafka-node#128]
I'm having an issue where I have:

- A zookeeper cluster (3 nodes)
- A kafka cluster (2 nodes)
- A topic set to replication factor 2, # partitions 1

All seems to work fine in normal scenarios. I have two consumer groups for this topic, one in Java and one using kafka-node. I publish messages and both node.js and java apps get the messages.

When I take one of the kafka nodes down, a rebalance occurs and everything continues to occur as expected. However, when I bring the downed kafka node back up, the kafka-node client gets all of the old messages sent to it (whereas the Java client does not). After all of these messages (which are days or weeks old) get resent, things continue to work per normal.

I can see in zookeeper that the kafka-node message group is correctly committing its position (I'm using HighLevelConsumer / autocommit).

```
'use strict';

var kafka = require('kafka-node');
var HighLevelConsumer = kafka.HighLevelConsumer;
var Offset = kafka.Offset;
var Client = kafka.Client;
var argv = require('optimist').argv;
var topic = argv.topic || 'testrs';
var client = new Client('zoo1:2181,zoo2:2181,zoo3:2181', 'MyHLC');
var topics = [
    { topic: topic }
];
var options = {
    groupId: 'MyNodeGroup',
    autoCommit: true,
    autoCommitIntervalMs: 5000
};
var consumer = new HighLevelConsumer(client, topics, options);
var offset = new Offset(client);

var expectedCount = 0;

console.log('using topic: ' + topic);

consumer.on('message', function (message) {
    console.log(this.id, message);
    var msg = JSON.parse(message.value);
    if (msg.count != expectedCount) {
        console.warn("Expected count does not match count!", expectedCount, msg.count);
    }
    expectedCount++;
});
consumer.on('error', function (err) {
    console.log('error', err);
    console.log(err.stack);
});
```

**Comment by haio** [comment]
#close

**Comment by ericdolson** [comment]
I am seeing this exact same issue using kafka-node v0.2.26. Somehow, my offsets are getting set to zero and all nodes in my cluster running kafka-node with the same group begin reprocessing old messages. Any help on this would be greatly appreciated.

**Comment by ersumitchh** [comment]
Having same problem which @ericdolson has mentioned. Please fix this up.
