### ISSUE TITLE
ConsumerGroup - retry functionality and events ?

### ISSUE THREAD

**Issue by appsolutegeek** [SOHU-Co/kafka-node#1286]
## Questions?

Can you document or explain the following properties from ConsumerGroup

```
  retries?: number;
  retryFactor?: number;
  retryMinTimeout?: number;
```

retries is the maximum retries ?

What happens when this reaches the maximum, is there some kind of special event that is raised ?

I am listening to

```
on('error', function (err) {})
```

But i get a message for each error, and when it reaches say retries: 3 - then messages constantly carry on being streamed.

Is there some other even to say maximum retries reached and then i assume I can do a 

```
process.exit(1)
```

I am probably not understanding great the funtionality of these 3 properties (above) and the events.

Tried checking the docs but still not sure.

### Environment

* Node version:11
* Kafka-node version:latest
* Kafka version:1.2.1

Thanks for your contribution!

**Comment by appsolutegeek** [comment]
I am using ConsumerGroup and not Kafka client, as I understand it, kafka client is create behind the scenes.

So I can't pass in a kafka client to a ConsumerGroup

**Comment by appsolutegeek** [comment]
Actually, out of interest, I was using a Consumer before and passing in a kafkaClient but I had to move over to a ConsumerGroup as the Consumer wasn't registering the groupId with kafka.

Although not specific to the problems above, I thought I would mention it.

**Comment by hyperlink** [comment]
> Can you document or explain the following properties from ConsumerGroup

Look at the [retry module](https://www.npmjs.com/package/retry) for documentation for those settings.

> What happens when this reaches the maximum, is there some kind of special event that is raised ?

if the retry fails either an error is yielded to the callback or an error is emitted on the `error` event when a number of retries are exhausted.

> So I can't pass in a kafka client to a ConsumerGroup

The options passed to the ConsumerGroup is also passed to the underlying [kafkaClient](https://github.com/SOHU-Co/kafka-node/blob/51b6292340b12af423c1e331ab5eda0f3beb1852/lib/consumerGroup.js#L83).
