### ISSUE TITLE
Example of replaying a msg when consumer handling fails

### ISSUE THREAD

**Issue by crobinson42** [SOHU-Co/kafka-node#1294]
### Question

I'm looking for an example of how to not commit/ack a msg when the Consumer fails to handle the message, ie: the Consumer handler throws an Error in a long running process like server-side rendering for an email. 

Ideally I'd like to retry a msg a certain number of times before throwing it away - I think I plan on doing this with some Redis cache state for retry count on a message unless there's a better way :-) 

Thanks!

**Comment by AmirAliSobhGol** [comment]
you should turn off auto-commit and commit the messages you have fetched manually for at-least-once-delivery.
also i recommend using dead letter queues instead of a redis cache for handling poison messages.
this is the standard approach that Uber, Confluent any many others have taken.
