### ISSUE TITLE
Consumer stop consuming after several messages consumed

### ISSUE THREAD

**Issue by lanlanlove4ever** [SOHU-Co/kafka-node#1300]
Kafka-node: 4.1.3
```
const client = new kafka.KafkaClient(config.kafka.client);
const consumer = new Consumer(client, [{topic: config.kafka.topic}], {
    groupId: config.kafka.groupId, autoCommit: true,
});
consumer.on('message', async (message) => {
    // do something
});
consumer.on('error', (err) => {
    // do something
});
```
The consumer works ok at initial time, but it stops after several messages consumed. Sometimes it will take a few days to stop, and sometimes only one day. This has been bothering me for a long time. Please help me out for this.

**Comment by sharmaadarsh563** [comment]
Why you are using **async** in the callback upon receiving **message** event -- callback is inherently async? Try after removing **async**.

Also, try using ConsumerGroup like below:

```
            consumerGroups[groupId] = {};
            consumerGroups[groupId] = new kafka.ConsumerGroup(consumerOptions, topic);
            consumerGroups[groupId].on('error', (error) => {
                    // do something
            });
            consumerGroups[groupId].on('message', (message) => {
                    // do something
            });
```

**Comment by lanlanlove4ever** [comment]
@sharmaadarsh563 I am wrong with async in the callback used and have removed it. Using ConsumerGroup is a good idea, thanks a million.
