### ISSUE TITLE
Share client instance with ConsumerGroup?

### ISSUE THREAD

**Issue by clarkttfu** [SOHU-Co/kafka-node#1312]
## Questions?

I found the ConsumerGroup constructor, unlike any other high level class, does not accept `client` as argument. And each consumer group will [create its own client instance here](https://github.com/SOHU-Co/kafka-node/blob/master/lib/consumerGroup.js#L83).

Is there some special concerns here? because I'd expect only one kafka connection from same process..

Otherwise, can I share the client instance of a ConsumerGroup to construct another, i.e. Producer instance?

Clark

**Comment by hyperlink** [comment]
I would not recommend share clients since each client maintains their own state. The `ConsumerGroup` was designed that way to discourage the sharing of Client instances.

Also, a client could maintain several different socket connections based on different tasks or cluster configuration.

**Comment by clarkttfu** [comment]
OK, thanks
