### ISSUE TITLE
How to implement message queuing among consumers?

### ISSUE THREAD

**Issue by ntquyen** [SOHU-Co/kafka-node#137]
I'm implementing 2 consumers in a same consumer group, listening to the same topic to test how the scalability work. However, the message queuing doesn't work: when I send a message to the topic, both consumers fetch that message. Below is my config of the 2 consumers:

```
consumer: {
        payloads: [
          {
            topic: 'topicA',
            partition: 0
          }
        ],
        options: {
          groupId: 'topicA',
          autoCommit: false,
          autoCommitIntervalMs: 60000,
          fetchMaxWaitMs: 100,
          fetchMinBytes: 1,
          fetchMaxBytes: 1024 * 1024,
          fromOffset: false
        }
      }
```
Please help, I'm not sure what I did wrong or is it really an issue.

**Comment by haio** [comment]
Yes, for Consumer(Low Level) it's the expected behavior. You can try HighLevelConsumer, it can rebalance consumers by different partition.

**Comment by ntquyen** [comment]
Unfortunately, HighLevelConsumer doesn't fit our requirement because of the autoCommit. Thanks!

**Comment by haio** [comment]
There is a discuss about it here #78 ,and the solution by @jezzalaycock https://github.com/jezzalaycock/kafka-node-manager, hope it help.

**Comment by haio** [comment]
close this.
