### ISSUE TITLE
Missing timestamp in Message Interface for Typescript

### ISSUE THREAD

**Issue by zesagata** [SOHU-Co/kafka-node#1384]
## Questions?

Why there is no timestamp in Message interface ? 

I always get the "Property 'timestamp' does not exist' " error when i compile my typescript apps, but actually the data is there
console.log(message.timestamp) // output : 2020-02-27T17:07:33.203Z

```ts
export interface Message {
  topic: string;
  value: string | Buffer;
  offset?: number;
  partition?: number;
  highWaterOffset?: number;
  key?: string | Buffer;
}
```

**Comment by sykesey** [comment]
This is a problem in ProduceRequest also - I ended up patching that to have timestamp?: number; :

```typescript
export interface ProduceRequest {
  topic: string;
  messages: any; // string[] | Array<KeyedMessage> | string | KeyedMessage
  key?: string | Buffer;
  partition?: number;
  attributes?: number;
  timestamp?: number;
}
```

For the moment we will use patch-package to fix up both Message and ProduceRequest, but it would be good if this can be fixed in the upstream

**Comment by zesagata** [comment]
Yea, same with me, i ended up patching Message to have timestamp too
```typescript
export type Payload<T = any> = Message & {
  body: T,
  timestamp?: Date
}
```
