### ISSUE TITLE
Add explicitly the "partition" option to Consumer/HighLevelConsumer documentation

### ISSUE THREAD

**Issue by eudaimos** [SOHU-Co/kafka-node#139]
Having worked a little with Kafka in another language, I should've known better that I have to specify which partition I want to consume from when creating the `FetchRequest` object for the `Consumer`, but I didn't.

Currently the README doesn't call this out for a multi-partition environment except for one example case.

For future users (and possibly current), please add `partition` option to `FetchRequest` more explicitly in the documentation for `Consumer` and `HighLevelConsumer`

**Comment by eudaimos** [comment]
When I get a chance, I will fork -> change -> PR but atm I don't know when that will be.

**Comment by haio** [comment]
For Consumer, you actually can specify the partition to consume, but HighLevelConsumer will fetch all partitions.

**Comment by kadishmal** [comment]
I'm going to reorganize the README and add more explanations about this.

**Comment by mickhansen** [comment]
@haio https://github.com/SOHU-Co/kafka-node/blob/master/lib/highLevelConsumer.js#L62 are you sure that HighLevelConsumer fetches all partitions? Looking at that line of code and my own consumer which only specifices a single payload with a single topic (no partitions specified) i'm not seeing all data from all my partitions.

**Comment by haio** [comment]
yes it will fetch all partitions, consumer will make a rebalance after initialize, if there is only one consumer, it will consume message from all partitions.

**Comment by mickhansen** [comment]
@haio Yes i deleted the comment, i think my issue has to do with fetchMaxBytes, at 1024 * 90 happens, at 2014 * 128 it will fetch 80 messages at once, doesn't make a whole lot of sense.

**Comment by haio** [comment]
@mickhansen OK
