### ISSUE TITLE
Support consuming binary messages

### ISSUE THREAD

**Issue by hpihkala** [SOHU-Co/kafka-node#142]
In #29 support was added for producing raw buffer messages. However, as far as I understand, support for *consuming* binary messages is missing. The decoder converts message values to strings by assumption before calling the callback.

There should be a configuration parameter that controls whether to interpret messages as strings or not, or alternatively, the possibility to provide a custom message decoder function.

**Comment by haio** [comment]
We can add a option to determine whether to convert message to string or not.

**Comment by haio** [comment]
The consumer support `encoding` option now, when set it to `buffer`, the message value will be a raw buffer

**Comment by hpihkala** [comment]
Works beautifully. Thanks!
