### ISSUE TITLE
How to connect to a broker which forces client auth?

### ISSUE THREAD

**Issue by jim-king-2000** [SOHU-Co/kafka-node#1422]
## Questions?

We are trying to connect a cloud kafka broker. However, it forces client auth. The sample code of Java is like the following:

```java
 security.protocol=SSL
 ssl.truststore.location=client.truststore.jks
 ssl.truststore.password=<your certificate password>
 ssl.keystore.location=client.keystore.jks
 ssl.keystore.password=<your certificate password>
```

Now we are using node.js. Is there any code sample for connecting to a broker which forces client auth?

Thanks.

**Comment by jim-king-2000** [comment]
Resolved!

**Comment by prashanthrelekar** [comment]
> Resolved!

@jim-king-2000 please share the sample code.
