### ISSUE TITLE
HighLevelConsumer NODE_EXISTS

### ISSUE THREAD

**Issue by justjv** [SOHU-Co/kafka-node#147]
kafka：6个broker，18个partition
消费端，3台机器，每台机器两个消费者，groupid相同。启动时，只有一个消费者启动成功，其它都报：[FailedToRebalanceConsumerError: Exception: NODE_EXISTS[-110]] message: 'Exception: NODE_EXISTS[-110]' 

回退到0.2.10版本测试，后台日志发现：Gained ownership of /consumers/pserver_0/owners/test/6
后面又出现：
Removed partition ownership /consumers/pserver_0/owners/test/6
生成后又删除，咋回事啊？

**Comment by haio** [comment]
这个异常是因为partition 6已经被其他消费者 own了，可以尝试下按先后顺序启动各个consumer

**Comment by justjv** [comment]
非常感谢，这个问题的确是由于消费者同时启动造成的

**Comment by ahkimkoo** [comment]
我有同样的问题, 顺序启动也不行.
