### ISSUE TITLE
How to detect when a broker become available

### ISSUE THREAD

**Issue by florentvaldelievre** [SOHU-Co/kafka-node#149]
Hi,

I am running a Zookeeper and kafka instance. I would like to run offset.fetch(...) only if there is at least one broker available.
Currently, offset.fetch(...) gets stuck forever as this.client.ready = false when kafka is down. How to detect that a broker become available ?

**Scenario:**
<ul>
<li>Zookeeper up</li>
<li>kafka is down</li>
</ul>

According to <a href="https://github.com/SOHU-Co/kafka-node/blob/master/lib/offset.js">offset.js</a> code, get offset is triggered only on this condition:

**offset.js**
````
this.client.once('connect', function () {
   this.ready = true;
}.bind(this));
````

**my_app.js**

````
var kafka = require('kafka-node');
var client = new kafka.Client("localhost:2181", {
      sessionTimeout: 30000,
      spinDelay : 1000,
      retries : 100
  });
var offset = new kafka.Offset(client);

client.on("ready", function() {
 console.log("Zookeeper ready");
 fetch()
})

var fetch = function() {
 offset.fetch([...], function (err, offsets) { }
}
````

**Comment by olalonde59** [comment]
Would be nice to have retry-based failover support here.

**Comment by haio** [comment]
@florentvaldelievre  How about return error when broker is not available?

**Comment by haio** [comment]
@olalonde59 this is not good, it should respond whether success or not

**Comment by florentvaldelievre** [comment]
@haio , yes, it would be good to have an error returned in case no broker is available. Or maybe have 'ready' event received if there is at least one broker available.

According to <a href="https://github.com/SOHU-Co/kafka-node/blob/master/lib/client.js">client.js</a> 'ready' event is triggered no matter the number of broker loaded into brokers object.

How would you deal with the  scenario "retry until there is a broker available" in case you return an error ?

**Comment by haio** [comment]
yes, `ready` event is emit when the client connect zookeeper, that doesn't mean there is any broker. Basically the user should limit the retries in case there isn't any broker available for a long time

**Comment by florentvaldelievre** [comment]
How do you retry until there is a broker available ? this.client.ready = false even when a kafka broker become available.
Do you mean i should retry on offset.fetch X times ?

**Comment by haio** [comment]
Yes, I think this retry should be done in the user end. If the broker is not available for some time , you can  make notification ,logs, etc.
Also I think the Offset should also emit `ready`(when zk ready), `connect`(when broker(s) ready) events.

**Comment by florentvaldelievre** [comment]
Sounds like a good plan. Is it something you are planning to add to offset.js in a near future ?

**Comment by florentvaldelievre** [comment]
Hi,

I had a look at your latest commit though #151 and attempted to update my code accordingly:

````
LOG.info("Waiting for a Zookeeper instance");

offset.on("ready", function() {
	LOG.info("Zookeeper instance found");
	offset.on("connect", function() {
		LOG.info("Broker(s) found");
		fetch();
	});
});
````
It is working fine if a broker is already running. However, if you run the script with a broker down ( and zk up ), it will just get stuck.
Ideally, when a broker become available, the script should trigger an event. It seems that "connect" event is only triggered if there is at least one broker up on start.

Any advice?

**Comment by haio** [comment]
The client doesn't know when the broker become available. The `connect` event should better not to be used, I think your code should be 
```js
offset.on("ready", function() {
    LOG.info("Zookeeper instance found");
    fetch(function (err) {
      // If broker is not available , err should be present
    });
});
```

**Comment by florentvaldelievre** [comment]
I see ! Thanks a lot !

**Comment by haio** [comment]
It's already in npm, see kafka-node@0.2.17.

**Comment by florentvaldelievre** [comment]
Perfect ! Thank you, this issue can be closed. Thanks for your prompt action!

**Comment by haio** [comment]
Ok, let's close it.
