### ISSUE TITLE
kafka-node@0.2.16 or kafka-node@0.2.17 fail to install

### ISSUE THREAD

**Issue by florentvaldelievre** [SOHU-Co/kafka-node#153]
Hi there, 

It seems there is a problem with snappy module on windows (7) as well as linux (debian)
I have created an <a href="https://github.com/kesla/node-snappy/issues/38">issue</a> on snappy side as well, you might probably close yours:

**package.json**
````  
"dependencies": {
    "kafka-node": "0.2.16"
  },

````
C:\dev\apps\rtc>npm install
npm WARN package.json rtc-app@0.0.1 No repository field.
npm WARN package.json rtc-app@0.0.1 No README data
> snappy@3.0.6 install C:\dev\apps\rtc\node_modules\kafka-node\node_modules\snap
py
> node-gyp rebuild
C:\dev\apps\rtc\node_modules\kafka-node\node_modules\snappy>node "C:\dev\tools\n
odejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gy
p.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1001:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:792:
34)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\dev\\tools\\nodejs\\node_modules\\npm\\node_modules
\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\apps\rtc\node_modules\kafka-node\node_modules\snappy
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm ERR! snappy@3.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snappy@3.0.6 install script.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\dev\\tools\\nodejs\\\\node.exe" "C:\\dev\\tools\\nodejs\\n
ode_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\dev\apps\rtc
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
````

**kafka-node@0.2.15 works fine**
````
C:\dev\apps\rtc>npm install
npm WARN package.json rtc-app@0.0.1 No repository field.
npm WARN package.json rtc-app@0.0.1 No README data
kafka-node@0.2.15 node_modules\kafka-node
├── buffer-crc32@0.2.5
├── retry@0.6.1
├── node-uuid@1.4.1
├── async@0.7.0
├── lodash@2.2.1
├── debug@2.1.1 (ms@0.6.2)
├── buffermaker@1.2.0 (long@1.1.2)
├── node-zookeeper-client@0.2.0 (async@0.2.10, underscore@1.4.4)
└── binary@0.3.0 (buffers@0.1.1, chainsaw@0.1.0)
````

**Comment by haio** [comment]
Didn't have problem on linux debain, no windows to test this.

**Comment by florentvaldelievre** [comment]
After some research, snappy depends on <a href="https://github.com/TooTallNate/node-gyp">node-gyp</a> to compile some addon modules which depends on Python and Developement tools ( Visual Studio C++ 2010 Express ).
This is heavy dependencies for windows users, just to let you know :)

Cheers

**Comment by haio** [comment]
:congratulations:

**Comment by haio** [comment]
close.

**Comment by shivako** [comment]
On windows, is this problem installed? I couldn't make it work even after visual studio installed, any help is appreciated.

**Comment by suresh-mits** [comment]
Can you please specify how did you solve this? i am getting similar issue in 0.2.27 version
