### ISSUE TITLE
kafkamonitor问题

### ISSUE THREAD

**Issue by justjv** [SOHU-Co/kafka-node#155]
HighLevelConsumer，通过kafkamonitor监控发现，每个Partition都有一条消息没有消费掉，咋回事？
Partition  Offset   logSize  Lag
    0          68            69      1
    1          51            52      1

**Comment by haio** [comment]
可以重现吗？

**Comment by justjv** [comment]
不用重现，测试过程中重搭了n次环境，一直是这样的

**Comment by shandafu** [comment]
我们也遇到相同的问题，没有解决

**Comment by haio** [comment]
是自动commit还是手动commit的

**Comment by shandafu** [comment]
自动commit

**Comment by haio** [comment]
发现了，应该是客户端管理offset的bug

**Comment by haio** [comment]
kafka-node@0.2.19应该修复了这个问题

**Comment by haio** [comment]
close.
