### ISSUE TITLE
When paused why try to fetch every 1000 ms?

### ISSUE THREAD

**Issue by kadishmal** [SOHU-Co/kafka-node#169]
In `highLevelConsumer.js` there is this code:

    this.on('done', function (topics) {
        self.updateOffsets(topics);
        if (!self.paused) {
            setImmediate(function () {
                self.fetch();
            });
        }
        else {
            setTimeout(function () {
                self.fetch();
            }, 1000);
        }
    });

The `.fetch()` function is as follows:

	HighLevelConsumer.prototype.fetch = function () {
	    if (!this.ready || this.rebalancing || this.paused) {
	        return;
	    }
	
	    this.client.sendFetchRequest(this, this.topicPayloads, this.options.fetchMaxWaitMs, this.options.fetchMinBytes, this.options.maxTickMessages);
	}

This means that even if the consumer is paused, it will try to fetch every 1 second:

           setTimeout(function () {
               self.fetch();
           }, 1000);

Why try if the code in `.fetch()` will just `return`?

            if (!this.ready || this.rebalancing || this.paused) {
	        return;
	    }

**Comment by kadishmal** [comment]
@jezzalaycock seems to have written those lines.

**Comment by haio** [comment]
I think those lines can be removed.
