### ISSUE TITLE
Zookeeper and connected event

### ISSUE THREAD

**Issue by florentvaldelievre** [SOHU-Co/kafka-node#173]
How do you know with kafka-node if the connection to zookeeper has been succesfull ?
Ideally  I would like to have something like this:
````
var client = new kafka.Client('localhost:2081', 'rtc-client');
client.once('connected', function () {
    console.log('Connected to ZK.');
});
````

I have noticed that zookeeper.js expose a 'connected' event which work as expected. However, how do you use it with kafka.Client ?

kafka-node/lib/zookeeper.js
````
var Zookeeper = function (connectionString, options) {
    this.client = zookeeper.createClient(connectionString, options);

    var that = this;
    this.client.on('connected', function () {
        that.listBrokers();
    });
    this.client.connect();
};
````

**Comment by haio** [comment]
That is done by `this.client.on('connected')`

**Comment by florentvaldelievre** [comment]
I tried to do it on kafka.Client but it does not seem to work: It never triggers the event. However, it is triggering properly in zookeeper.js
````    
this.client.on('connected', function () {console.log("connected!"});
````

app.js
````
var client = new kafka.Client('localhost:2081');
client.on('connected', function () {
    console.log('Connected to ZK.'); // it never goes here
});
````

**Comment by haio** [comment]
yes, `kafka.Client` will not emit connected event. If you really need this you should use `client.zk.on('connected', fn)`

**Comment by florentvaldelievre** [comment]
It does not seem to work with(also tried with client.zk.once) : 
````
var client = new kafka.Client('localhost:2081');
client.zk.on('connected', function () {
    console.log('Connected to ZK.'); // it never goes here
});


````
However, a simple test like this works fine:

````
var zookeeper = require('node-zookeeper-client');
var client = zookeeper.createClient('localhost:2181');
client.once('connected', function () {
    console.log('Connected to the server.');
});
client.connect();
````

**Comment by haio** [comment]
sorry, the code should be `client.zk.client.on('connected', cb)`, but doing so also won't work, because before the code which listen the event executed, the connected event already emitted.

**Comment by florentvaldelievre** [comment]
Ok I see, thanks for your reply
