### ISSUE TITLE
FailedToRebalanceConsumerError

### ISSUE THREAD

**Issue by ahkimkoo** [SOHU-Co/kafka-node#183]
events.js:72
        throw er; // Unhandled 'error' event
              ^
FailedToRebalanceConsumerError: Exception: NODE_EXISTS[-110]
    at new FailedToRebalanceConsumerError (/home/project/recommend/node_modules/kafka-node/lib/errors/FailedToRebalanceConsumerError.js:11:11)
    at /home/project/recommend/node_modules/kafka-node/lib/highLevelConsumer.js:170:51
    at /home/project/recommend/node_modules/kafka-node/lib/highLevelConsumer.js:416:17
    at /home/project/recommend/node_modules/kafka-node/node_modules/async/lib/async.js:254:17
    at /home/project/recommend/node_modules/kafka-node/node_modules/async/lib/async.js:151:21
    at /home/project/recommend/node_modules/kafka-node/node_modules/async/lib/async.js:251:21
    at /home/project/recommend/node_modules/kafka-node/node_modules/async/lib/async.js:615:34
    at /home/project/recommend/node_modules/kafka-node/lib/highLevelConsumer.js:396:29
    at /home/project/recommend/node_modules/kafka-node/node_modules/async/lib/async.js:151:21
    at /home/project/recommend/node_modules/kafka-node/lib/highLevelConsumer.js:386:41

**Comment by ahkimkoo** [comment]
两个客户端运行就报错. highlevelconsumer 用java client可以同groupid运行多个, 为何nodejs的就报错.

**Comment by haio** [comment]
这个错误我只在这种情况下见过，通过 `CTRL+C` 关闭当前的进程然后立刻重新启动建议你看下log。建议看下log：DEBUG=kafka-node:* node sth.js，同时consumer应该监听 `error` 事件

**Comment by haio** [comment]
close this
