### ISSUE TITLE
[regression for 0.2.24] got "consumersChanged not ready"

### ISSUE THREAD

**Issue by fwang7** [SOHU-Co/kafka-node#184]
kafka cluster version: 0.8.2
kafka-node version: 0.2.24

After I downgraded to 0.2.17, "consumersChanged not ready" was gone.

**Comment by fwang7** [comment]
consumersChanged not ready
consumersChanged not ready
Node: /consumers/kafka-node-group/ids/kafka-node-group_b1ed505f-b463-496a-a5c4-571a32638b18 was created.
HighLevelConsumer kafka-node-group_b1ed505f-b463-496a-a5c4-571a32638b18 is attempting to rebalance
HighLevelConsumer kafka-node-group_b1ed505f-b463-496a-a5c4-571a32638b18 stopping data read during rebalance
HighLevelConsumer kafka-node-group_b1ed505f-b463-496a-a5c4-571a32638b18 assembling data for rebalance
Children are: ["kafka-node-group_65e330c7-00ce-45f0-abdd-0e7d6e3dd6f9","kafka-node-group_b1ed505f-b463-496a-a5c4-571a32638b18"].
HighLevelConsumer kafka-node-group_b1ed505f-b463-496a-a5c4-571a32638b18 releasing current partitions during rebalance
HighLevelConsumer kafka-node-group_b1ed505f-b463-496a-a5c4-571a32638b18 determining the partitions to own during rebalance
HighLevelConsumer kafka-node-group_b1ed505f-b463-496a-a5c4-571a32638b18 has been assigned no partitions during rebalance
HighLevelConsumer kafka-node-group_b1ed505f-b463-496a-a5c4-571a32638b18 rebalance attempt was successful

**Comment by haio** [comment]
where do you log `consumersChanged not ready`, I can't figure out where does it come from

**Comment by fwang7** [comment]
yes, seems like it gave the correct error message. I will close it.

btw, could you update the options in the example.
some deprecated options would be confusing.

**Comment by haio** [comment]
Yes, thanks for pointing out!
