### ISSUE TITLE
how to set the "partition" can send the message to consumers in balance.

### ISSUE THREAD

**Issue by wltofly** [SOHU-Co/kafka-node#186]
I have three nodes ,each of them has one consumer. All the nodes are managed by zookeeper. My problem is that all the messages of the producers is sent to one node .How to  config so that  every node can receive message in balance?

**Comment by haio** [comment]
Maybe you should use HighLevelProducer. It will send message to different partition based on a simple round robin algorithm

**Comment by wltofly** [comment]
I had change my code like this,but it is not worked:
exports.sendAlarmToMQ = function(params, topic, callback){
    var HighLevelProducer = kafka.HighLevelProducer,
        Client = kafka.Client,
        client = new Client(KAFKA_HOST),
        producer = new HighLevelProducer(client);

    producer.on('ready', function () {
        logger.info('params=' + params);
        send(params);
        callback(null);
    });
    producer.on('error', function (err) {
        logger.error('error', err);
        callback(err);
    });
    function send(messages) {
        producer.send([
            {topic: topic, messages: messages}
        ], function (err, data) {
            producer.close(function (err) {
                if (err) {
                    logger.error('Close kafka internal error', err);
                    callback(err);
                } else {
                    logger.info('Kafka close successful');
                }
            });
            if (err) {
                logger.error('Send kafka internal error', err);
                callback(err);
            } else {
                logger.info('Message sent: ', data);
            }
        });
    }
};

**Comment by haio** [comment]
You should initialize the producer outside  `sendAlarmToMQ` method, for example:
```js
var HighLevelProducer = kafka.HighLevelProducer,
Client = kafka.Client,
client = new Client(KAFKA_HOST),
producer = new HighLevelProducer(client);
producer.on('ready', function () {
  this._ready = true;
});
producer.on('error', function (err) {
  this._error = true;
});

exports.sendAlarmToMQ = function(params, topic, callback){
  if (!producer._ready || producer._error) {
    return callback(new Error('producer not ready or error'));
  }

  producer.send(something, callback);
}
```

**Comment by wltofly** [comment]
It is worked when I do as you say. thank you ! But now, I have another problem.  when I send the first message ,it is OK, and the second message not worked well ,The error happend in lib/client.js:
        if (broker.error || broker.closing) {
            return cb(new errors.BrokerNotAvailableError('Could not find the leader'), payloads[leader]);
        }
and when I delete "producer.close", my program work well.  why?

**Comment by wltofly** [comment]
Oh,I know that "producer.close" is not necessary. thank you very much.
