### ISSUE TITLE
Issue #180 changes not appearing on npm install kafka-node

### ISSUE THREAD

**Issue by lsampathreddy** [SOHU-Co/kafka-node#195]
Hi Team,
 Today i noticed issue #180 changes were not seems to be appeared in kafka-node. after looking in to the myProject/node_module/kafk-node, supprisingly ../lib/client.js missed code related to #180 . it shouldn't happen. could you check ASAP. its very urgent as we are moving to production soon.

Thanks
Sampath

**Comment by haio** [comment]
Did you reinstall it with npm?

**Comment by lsampathreddy** [comment]
@haio 
Yes. I reinstalled multiple times. #180 changes were not there in 0.2.24 version. 
When i install latest version of kafka-node i.e. 0.2.25, intermittently #180 changes are appearing( i did multiple npm install kafka-node)...

i tried with delete require['kafka-node'] to make sure not to fetch module from cache. but issue still exists.

**Comment by haio** [comment]
@lsampathreddy I have seen the same issue! The publish time of version 0.2.24 is `2015-03-20T09:29:19.533Z`, I can't figure out why the changes is not in this version. You should use kafka-node@0.2.25.

**Comment by lsampathreddy** [comment]
Thanks for your response @haio 
Was it a npm repo issue? i'm sure i saw #180 changes in 0.2.24 and i tested it couple of days back. but then later i saw changes these were missing in 0.2.24 version... it sounds weird but i'm clueless

**Comment by haio** [comment]
It's strange for me too, just can't reproduce it.

**Comment by haio** [comment]
Close.
