### ISSUE TITLE
kafka-node fails to install with iojs 2.0

### ISSUE THREAD

**Issue by MCF** [SOHU-Co/kafka-node#204]
kafka-node is failing to install with iojs 2.0.  The snappy dependency is set to ~3.0.8, but that version of snappy has a dependency on an older version of the nan module (which fails to install with iojs 2.0).  The dependency problem in snappy has been fixed recently and released as 3.2.0: https://github.com/kesla/node-snappy/commit/74620e1ea8b7e2521b3dc3cb6a40550caa6dfa39.

If the dependency to snappy is changed to ^3.2.0 in kafka-node then kafka-node will install properly.  It seems unlikely that the newer version of snappy would cause problems with kafka-node as the other changes to snappy between 3.0.8 and 3.2.0 seem to be pretty benign.

For the record, the output from the failed install is shown below.

```
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cc:21:
In file included from ../src/./binding.h:26:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
```

**Comment by haio** [comment]
Thanks @MCF
