### ISSUE TITLE
Getting error wile trying to connect kafka instance in remote server.

### ISSUE THREAD

**Issue by mustafamamun** [SOHU-Co/kafka-node#212]
The following lines creating the error.
var kafka=require('kafka-node');
client=new kafka.Client('address_of_remote_server:2181', 'kafkaProducer'),

The error log is 

Error: getaddrinfo ENOTFOUND 'dns name of the server i am trying to connect'
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
15 Jun 16:12:06 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by haio** [comment]
Please check can you connect `address_of_remote_server:2181` in your local machine?

**Comment by janantala** [comment]
I am getting the same errors when using Zookeeper and Kafka in docker containers. Zookeeper receives kafka hostname, however then errors are occuring.

```
init { '1': 
   { jmx_port: -1,
     timestamp: '1436866928774',
     host: '9cb66bae8e70',
     version: 1,
     port: 9092 } }
Producer ready
client error { [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }
Producer error { [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }
```

**Comment by mustafamamun** [comment]
Actually it was not a problem of this module. I  had to change the the host name to the server address to solve it. I am sorry that I did not close it.
