### ISSUE TITLE
Batch producer with transformed streams

### ISSUE THREAD

**Issue by carlessistare** [SOHU-Co/kafka-node#214]
Hi,
I've done a wrapper for the producer which buffer a configurable amount of messages before sending them to kafka. The messages are sent either when a timeout triggers or a max amount of messages are sent.
Would it be interesting to create a pull request in order to integrate it to this project?
Other kafka client libs such us the Java one have already integrated this functionality, and the performance is really much better.
Cheers

**Comment by haio** [comment]
Hi,
LGTM, please send a PR

**Comment by mr1azl** [comment]
@carlessistare is there any repo where we could find your wrapper  ?

**Comment by mr1azl** [comment]
any news about this issue?

**Comment by carlessistare** [comment]
Not yet, i'll pr it soon

**Comment by carlessistare** [comment]
@mr1azl @haio PR is created for async batch producers
