### ISSUE TITLE
how to write zookeeper connection in cluster mode

### ISSUE THREAD

**Issue by juhanishen** [SOHU-Co/kafka-node#215]
Hi:

I have kafka nodejs talking to zookeeper in cluster mode. In nodejs, how to write multiple zookeeper connection url string. 

for single one it is: ip:port/, for multiple is it a) ip1:port,ip2:port/ or b) ip1:port/,ip2:port/?

**Comment by carlessistare** [comment]
I am using option a, with no slashes.
Cheers

**Comment by haio** [comment]
I think should work, here is the document for [zookeeper options](https://github.com/alexguan/node-zookeeper-client#client-createclientconnectionstring-options)

**Comment by juhanishen** [comment]
Thank you, carlessistare and haio! I will test it and give confirmation.
