### ISSUE TITLE
npm i kafka-node Error:    pangyp: Permission denied

### ISSUE THREAD

**Issue by chenkline** [SOHU-Co/kafka-node#217]
> snappy@3.2.0 install /media/kline/works/src-nodejs/mypassport/node_modules/kafka-node/node_modules/snappy
> pangyp rebuild

sh: 1: pangyp: Permission denied
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/opt/nvm-master/versions/node/v0.12.0/bin/node" "/opt/nvm-master/versions/node/v0.12.0/bin/npm" "i" "kafka-node"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! snappy@3.2.0 install: `pangyp rebuild`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the snappy@3.2.0 install script 'pangyp rebuild'.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pangyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/kline/works/src-nodejs/mypassport/npm-debug.log

**Comment by desktoping** [comment]
do you have python installed?

**Comment by crzidea** [comment]
Sounds like env problem.

**Comment by kadishmal** [comment]
I have a similar case:

```
> snappy@3.2.2 install /tmp/node_modules/kafka-node/node_modules/snappy
> pangyp rebuild

sh: 1: pangyp: not found
npm ERR! Linux 4.0.9-boot2docker
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v0.10.38
npm ERR! npm  v2.11.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! snappy@3.2.2 install: `pangyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the snappy@3.2.2 install script 'pangyp rebuild'.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pangyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log
```

**Comment by hyperlink** [comment]
closing since snappy is optional now.

**Comment by sandy-adi** [comment]
@hyperlink what does it mean by `snappy is optional`? If I'm a package dependent on kafka-node how can I avoid being dependent on Snappy?

**Comment by hyperlink** [comment]
1. npm install continues on even if snappy fails to install. 
https://docs.npmjs.com/files/package.json#optionaldependencies

2. It won't use snappy unless you explicitly choose the compression attributes.
