### ISSUE TITLE
Consumer takes all the previous messages from the kafka queue

### ISSUE THREAD

**Issue by haanns** [SOHU-Co/kafka-node#222]
Hello! I have a quick question regarding this project, when I start a kafka consumer with the kafka-node module, the consumer automatically takes all the previous messages in the kafka queue (basically "from-beginning" for kafka). How do I only take the messages that's coming in after I started the consumer?

Thanks in advance!
Hans

**Comment by MaciekRakowski** [comment]
I don't know the background of what you did, so it's hard for me to say. The first thing I will ask is this: Have you committed your messages after receiving them? Somewhat like this:

consumer.on("message", function (msg) {
// do stuff
consumer.commit();
});

You can also turn "auto-commit" on, but I found that committing every few messages as opposed to every message was more reliable (it seems that if you don't wait for the commit to finish before getting the next message, you may run into issues with actually committing).

**Comment by hyperlink** [comment]
There's now way to read from the latest offset see the FAQ section [here](https://github.com/SOHU-Co/kafka-node/#for-a-new-consumer-how-do-i-start-consuming-from-the-latest-message-in-a-partition).
