### ISSUE TITLE
HighLevelConsumer can fetch messages from 0 offset if resume called before rebalancing complete

### ISSUE THREAD

**Issue by IharKrasnik** [SOHU-Co/kafka-node#235]
Hello, in our project we experienced problem when one of our consumers reconsumed all topic messages from 0 offset. 
After digging in logs I've found that it happened immediately after one of rebalances (before that moment rebalances happened periodically and everything worked fine, offsets were ok).

I found that rebalanced event is emitting before topicPayloads set to real offsets (newTopicPayloads have 0 offset before fetchOffset completed) https://github.com/SOHU-Co/kafka-node/blob/master/lib/highLevelConsumer.js#L109

So, if pause consumer from outside and rebalancing happens and then consumer.resume() called before fetchOffset completed, fetch will be called with current topicPayloads that will have 0 offset for that moment and messages will be reconsumed
https://github.com/SOHU-Co/kafka-node/blob/master/lib/highLevelConsumer.js#L593
https://github.com/SOHU-Co/kafka-node/blob/master/lib/highLevelConsumer.js#L485

Am I missing something or is it a real issue?

**Comment by jezzalaycock** [comment]
I have written a job manager which help manage offsets and commit only when the client has completed processing of a message - see https://www.npmjs.com/package/kafka-node-manager. 

Managing committing of offsets is a real pain and quite thorny.  Hopefully that job manager package will help you.

**Comment by ersumitchh** [comment]
Having the same problem and it generally happens when lag size is zero.

**Comment by ersumitchh** [comment]
Please fix this.

**Comment by darthjoel** [comment]
Have exact same problem.  Trying jezzalaycock's job manager.

**Comment by bencebalogh** [comment]
@hyperlink I think this can be closed as it should be fixed with #402
