### ISSUE TITLE
Write kafka cluster seems too slow

### ISSUE THREAD

**Issue by zwb-ict** [SOHU-Co/kafka-node#236]
My kafka cluster has four brokers with 8 partitions, one topic, managed by zookeeper. 

I use pm2 setup a cluster with four processes, then scale cluster to eight , sixteen,  twenty-four, use glances found the eth0's Tx almost unchanged. I don't know why. This is my code:

```
var kclient = new kafka.Client(cfg.dc.kafka, 'kafka-node-client', {retries: 3}),
    kproducer = new KProducer(kclient);

var message = '';
for (var i =0; i < 200; i++) {
    message += 'hello, world';
}

var messages = [];

for (var i = 0; i < 2048; i++) {
    messages.push(message)
}

var payloads = [];
var payload = {
 topic: cfg.dc.kafkaTopic,
 messages: messages,
 attributes: 1
};
payloads.push(payload);


var send = function() {
    kproducer.send(payloads, function(err, data) {
         if (err) console.log(err);
        console.log(data);
        send();
    });
};

kproducer.on('ready', function() {
    send();
});

kproducer.on('error', function(err) {
    console.log(err);
});

```

My colleague uses java client with ten more processes, can easily raise eth0's Tx. Is there anything I need to notice?

**Comment by ahmedissa** [comment]
i think your client is connected to kafka. Listen on error event so we can help further. 

```javascript
kproducer.on('error', function (err) {
  console.log(err);
})
```

**Comment by zwb-ict** [comment]
Sorry, I have this code in my file, I forgot to paste this section to you.
I check PM2 log,  up till now, no error message.

**Comment by zwb-ict** [comment]
@ahmedissa , Sorry I have listen 'error' event code in my file, I forgot to paste this section to here. I checked PM2 log, up till now no error info.

**Comment by jezzalaycock** [comment]
Are you using highlevel producer or just the producer? I wonder if you're only writing to a single partition - normal Producer if you don't specify defaults to partitioon 0. If so try the HighLevelProducer. HTH

**Comment by zwb-ict** [comment]
@jezzalaycock I used HighLevelProducer, but everytime I send the same payload, and found everytime it use partition 0, then I do another test,  the payload's messages is random，and found the partition is 0~7, and the speed move upward, is this the reason? What's the rule of partition chosen?

**Comment by hyperlink** [comment]
High level producer by default will round robin the partitions.
