### ISSUE TITLE
Delete a topic (feature request)

### ISSUE THREAD

**Issue by ericbroda** [SOHU-Co/kafka-node#237]
While there is a capability to create a topic (Producer.createTopics) there does not appear to be the ability to delete a topic.  This is a feature request to add the capability to delete a topic.  Recognizing this is an administrator capability, perhaps this can be grouped into an "Admin" subset of calls rather than grouped under Producer.

**Comment by chetangautam** [comment]
Does kafka-node supports deleting a topic?
Can we use function removeTopics for deleting a topic?

**Comment by hyperlink** [comment]
Creating topics relies on a broker setting for auto creating topics when you request the metadata for those topics.

I am not aware of any way to delete topics. We can only add functionality to this module based on what's exposed by the Kafka [protocol](http://kafka.apache.org/protocol.html).

**Comment by chetangautam** [comment]
So what is removeTopics functions use?

**Comment by hyperlink** [comment]
In the context of the consumer it's to remove topics to listen to.

**Comment by alexilyaev** [comment]
@hyperlink I was wondering if there's anything new in this regard?

We're currently using `kafka-topics.sh` to delete topics:
```
bin/kafka-topics.sh --zookeeper 192.168.33.10:2181 --delete --topic test
```

But would very much like to it programmatically using kafka-node.

**Comment by hyperlink** [comment]
We have capability to add new protocol support for new APIs in the module so anybody now can submit a PR to add new features. See #770 as an example to add support for `ListGroups` and `DescribeGroups`.

Currently I have no plans to implement this but I am willing to review and merge any PRs submitted.

**Comment by respinha-ribeiro** [comment]
Questions:
1. Was a PR for this already submitted?
2. Also: the question is "how to delete a topic", but is it already possible to simply delete the topic's _data_, not the topic itself?

**Comment by hyperlink** [comment]
> 1. Was a PR for this already submitted?

No.

> 2\. Also: the question is "how to delete a topic", but is it already possible to simply delete the topic's _data_, not the topic itself?

It's possible to stop listening to the topic if your consumer was previously subscribed to it.

There are admin APIs to delete topic as well as create it.  Create is already implemented in #958 so PRs welcome!

**Comment by alexk-etsy** [comment]
Heya folks! I'm working on this issue and I hope to have a PR ready soon. Is this still a feature that you'd be willing to accept into master?

**Comment by ellik95** [comment]
Hey @alexk-etsy! Will this PR be ready soon? We are interested about this feature.
