### ISSUE TITLE
List a kafka topic

### ISSUE THREAD

**Issue by ericbroda** [SOHU-Co/kafka-node#238]
Introduce a new capability to list kafka topics.  This will enable additional capabilities that mirror current kafka java capabilities.  This is a new feature request.

**Comment by mingfang** [comment]
+1
This feature is critical for the application that I'm building.

**Comment by mingfang** [comment]
Until we have official support, here is a hack that works for me.
```
  client.zk.client.getChildren('/brokers/topics', function (error, children, stats) {
    if (error) {
        console.log(error.stack);
        return;
    }

    console.log('Children are: %j.', children);
  });
```

**Comment by samypr100** [comment]
+1

**Comment by hyperlink** [comment]
It's not documented but you can call `client.loadMetadataForTopics` with a blank topic array to get the entire list of available topics (and available brokers).

This maybe more future proof than querying zookeeper since this is a request using the kafka protocol.

```javascript
client.loadMetadataForTopics([], function (error, results) {
    console.log('%j', results);
});
```
