### ISSUE TITLE
This socket has been ended by the other party

### ISSUE THREAD

**Issue by obazoud** [SOHU-Co/kafka-node#243]
We have this stack trace sometimes in production (maybe it's because of the high-traffic).

```
This socket has been ended by the other party
  at Socket.writeAfterFIN [as write] (net.js:276:12) 
  at [object Object].Client.sendToBroker (node_modules/kafka-node/lib/client.js:422:20)
  at [object Object].Client.send (node_modules/kafka-node/lib/client.js:375:14) 
  at node_modules/kafka-node/lib/client.js:144:14 
  at done (node_modules/kafka-node/node_modules/async/lib/async.js:132:19)
  ...
```

Any idea ? Is there a way to handle this exception ?

node: v0.10.40
kafka-node: 0.2.27
kafka: 0.8.2.1

**Comment by wanming** [comment]
+1

**Comment by mustafamamun** [comment]
same issue

**Comment by estliberitas** [comment]
@obazoud What do you use producer / consumer / both?

**Comment by pan1cz** [comment]
I get the same error occasionally using the kafka-node consumer to subscribe to a separate zookeeper service. It seems to be a traffic load related issue for me but the error is hard to debug.

node: 4.4.3
kafka-node: 0.3.3

**Comment by hyperlink** [comment]
Is your consumer still in a working state after this error? the client code has logic to reconnect the socket on errors.

**Comment by Maleandr** [comment]
Hi we have exactly some error in our production (not on test), so I guess it is somehow workload related. We use both producer/consumer and when this happen both are dead.
