### ISSUE TITLE
Error Could not find the leader

### ISSUE THREAD

**Issue by lucas-coelho** [SOHU-Co/kafka-node#245]
I have the following configuration:
- 3 kafka brokers
- 2 partition for topic A with 3 replicas

I have 2 HighLevelConsumer for the topic A, each one connect in one partition. When a  broker leader of one of the partitions is removed, both consumers emit the "rebalancing" and "rebalanced" events. The problem is that the consumer whose the leader was shutdown emitted  the "BrokerNotAvailableError: Could not find leader" error and stopped to fetch new messages. 

The consumer  shouldn't auto reconnect to a new leader?

**Comment by estliberitas** [comment]
@haio @lucas-coelho Any news about that issue? Seeing same picture on production cluster I use.

**Comment by estliberitas** [comment]
@lucas-coelho I guess #277 is about your issue.

**Comment by yangguoyk2015** [comment]
I think this fix is only for HighLevelConsumer,  now, we are using the ConsumerGroup, seems the same error occurs again. 

@estliberitas @hyperlink

**Comment by hyperlink** [comment]
For a period of time both Consumers could emit these types of errors while the broker elects a new leader and that information is propagated to the consumers. Eventually the consumers will get a `brokersChanged` event and recover.
