### ISSUE TITLE
JSON Parse can't keep up with Kafka

### ISSUE THREAD

**Issue by jfkoch** [SOHU-Co/kafka-node#251]
I"m using JSON Parse to deserialize the messages coming in from Kafka. I think it is overwhelming node as it eventually runs out of memory before being able to save it to Postgres. Anyone else have this issue? How did you solve the bottleneck?

**Comment by hyperlink** [comment]
on message you can use `pause()` the consumer and process the message then after that is competed call `resume()` to continue getting messages.
