### ISSUE TITLE
How to check if consumer is paused?

### ISSUE THREAD

**Issue by ersumitchh** [SOHU-Co/kafka-node#255]
In our application , we are pausing consumer and after a certain interval we are resuming it.
1): We want to check if consumer is paused or not at a gap of 10 minutes. How will we check?
2): Also if consumer is not paused and if we call consumer.resume() then what will happen?

Please help for the same.

**Comment by hyperlink** [comment]
1. Consumers have a `.paused` attribute you can check that
2. I would not call it unless `.paused` is true since it will call `fetch()` which starts the polling loop
