### ISSUE TITLE
Kafka 0.8.2 New Producer Implementation

### ISSUE THREAD

**Issue by lovato** [SOHU-Co/kafka-node#256]
Hi. After some tests, I discovered that all consumers receive the same message, if in the same partition. Which, under default settings, is expected.

I read also about ConsumerGroups, and how it should behave.

So I put all my consumers in the same consumer group, and all of them end receiving the same message, what is not supposed to be.

By reading, "they" changed this behavior in Kafka 0.8.2, and there is a "new producer" mode, which works perfectly, but only on their command line.

http://grokbase.com/t/kafka/users/1451nf236t/command-line-clients-and-request-balancing

$ ~/kafka/bin/kafka-console-producer.sh
--new-producer                          Use the new producer implementation.

If I have 3 consumers:
a) consumer group 1
b) consumer group 1
c) no consumer group

When I publish messages, it goes A-C, the other B-C, the other A-C and so on.

How can I enable this "new-producer" mode with kafka-node?

Best
Lovato

**Comment by lovato** [comment]
Here there is an implementation for "OldProducer" and "NewShinyProducer". 
https://apache.googlesource.com/kafka/+/466a83b78c2bfcb9ac3116748394e7845a99bf7a/core/src/main/scala/kafka/producer/ConsoleProducer.scala

**Comment by lovato** [comment]
To add more info, I am using KeyedMessage, and when I produce with Kafka bash script, works. When I use HighLevelProducer with KeyedMessage, nops. Same consumers.

**Comment by BadLambdaJamma** [comment]
"Hi. After some tests, I discovered that all consumers receive the same message, if in the same partition. Which, under default settings, is expected." - This is not true.  With unique group IDs all consumers read all messages from all partitions of a Topic.

Your Client ID should be unique.  Your groupID should be the same.  How are you setting your group ID?  How are you setting your client ID ?  Have you checked the Zookeeper Nodes to see how your consumers are balancing against  a set of partitions?  Also, what is your configuration? Number of kafka Brokers? How many partitions? How many Consumers? 

To check Zookeeper use this path:
/consumers/[groupId]/offsets/[topic]/[partitionId]

With three  consumers and three partitions  you would see this: (foo = consumer group, goo = topic the group is consuming from):

/consumers/foo/offsets/goo/0
/consumers/foo/offsets/goo/1
/consumers/foo/offsets/goo/2

The value of each node would be the current offset for the given partition number (0-2).  Note that "foo" is the consumer group.  Consumer groups can consumer from multiple topics and hence the noted ZK node structure.

**Comment by lovato** [comment]
Hi. I did all tests again, using a very simple configuration. And I also read more.

I have one Kafka instance, with a Zookeeper on the same machine.

I did a sample code using examples provided here, and I may be missing something. The code is here:

https://github.com/lovato/Kafka-NodeJS-Client-Test

I created a topic called KAFKAJSTests:
```
./kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 2 --topic KAFKAJSTests
```

# First, USING KAFKA .shs

consumer properties only defines a groupId

### Producer (NEW ALGORITHM):
```
~/kafka/bin/kafka-console-producer.sh --broker-list localhost:9092 --new-producer --topic KAFKAJSTests2
```
### Producer (OLD ALGORITHM):
```
~/kafka/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic KAFKAJSTests2
```
### Consumer:
```
~/kafka/config$ ~/kafka/bin/kafka-console-consumer.sh --topic KAFKAJSTests2 --consumer.config ~/kafka/config/consumer.properties  --zookeeper localhost:2181
```

### Facts:
- Both ways, producer know automatically how many partitions exists. I dont have to tell him.
- OLD way, puts only to partition 0, for 10 minutes (configurable), and then switch to partition 1
- NEW way, puts data in a round robin fashion, to both partitions 0 and 1.

# Second, using NodeJS lib

After cloning the repo and installing all dependencies, I ran 2 consumers, and one producer, all using default parameters. This way, ClientID gets different, and both GroupID and Topic gets the same.

Then, I ran:
- node consumer.js KAFKAJSTests (2x)
- node producer.js KAFKAJSTests

Both client got the same message, because both of them are bound to partition 0.

### Scenario A
So I have to manually put consumer A to Partition 0, and consumer B, to partition 1.

Then, IF I produce using NEW way, by Kafka shell commandline, it "works". 

### Scenario B
I then fired a producer. Somehow, when not told the partition to use, it used always "0".

So, if I keep alternating production to '0' and '1', it "works".

### Scenario C
I created another client.properties, to make different groupIds. Worked. But only for kafka.sh files.

# Questions
- How can I produce and consume without informing partition, just like kafka.sh files do? And expect the same behavior?


Does it make sense?

Best,
Marco

**Comment by lovato** [comment]
Hi. I did all tests again, using a very simple configuration (single node). And I also read little more. Mainly issue #139 and #260. 

One mistake I also did was to use a Consumer, instead of a HighLevelConsumer. My consumer now (using HighLevelConsumer) works just like Kafka native one.

This made things much more clear.

So one question remains: How can I produce content without informing partition? Currently, I send no partition to payload, but it always put it on 0.

If issue #260 is what I am looking for, this issue can be close.

Best
Lovato

**Comment by BadLambdaJamma** [comment]
Without specifying a partition, a round robin technique will be utilized.  This is not classical round robin as the leader will pick a partition and stick with it for a certain duration of time (10 minutes)  before switching to the next.  This approaches favors lower file handle use over true round robin.  It also means that you don't reach max parallelism until  N*Z Where N is the number of partitions and Z is the number of minutes the leader sticks with a partition.   If you want your processing stack to reach max parallelism sooner (as soon as all consumers start), create your own message partitioner and do "true" round robin at the expense of higher file handle usage.

**Comment by lovato** [comment]
Totally understand. I had created a message partitioner. Worked.
My question is about the new partitioner algorithm available in 0.8.2, if it will be supported... I dont want my app to handle how many partitions a topic has. I want my app to use as many partitions as are available.

And seems that #260 address exactly this. Am I correct?

**Comment by BadLambdaJamma** [comment]
I see the pull request #260,  it has not been accepted.  This has nothing to do with the kafka version being .8.2 however.  This is a pull request against the kafka-node client so that it contains a collection of partitioners "out of the box".  I would assume that this will give you the production pattern you are looking for but have not looked at the details of the PR.  I personally don't feel that the PR should be accepted nor should it be part of the core client.  I think partitioning logic, and client/production logic are separate concerns.  This is a highly stylistic and editorial comment thats others (including the PR author may take exception with)

**Comment by BadLambdaJamma** [comment]
If anything I think the high level producer "CTOR" (If writing prototype based javascript) should support "constructor injection" of the partitioning concern.

**Comment by ismriv** [comment]
As @BadLambdaJamma suggest, this has nothing to do with 0.8.2. 

But I have to disagree with this feature not being part of the driver itself. The high level producer has already a cyclic partitioner built-in (which can only be overridden by passing the partition with the payload). The Java/Scala driver has always provided a default partitioner, and an interface to let you use your custom partitioner: http://kafka.apache.org/081/documentation.html#producerconfigs

The pull request #260 has not been accepted *yet*, but @haio hasn't provided any feedback or rejected it either. I would be ok with rewriting it to allow constructor injection and pass the partitioner function to it.

**Comment by BadLambdaJamma** [comment]
Ok, maybe my separations of concerns argument is a bit weak.  I just see partitioning and keyed message production as being a point of modularity that will vastly differ based on the message type, lifetime and intention for each implementation. It would also allow a generic approach so that if you did need a custom partitioner, you would not modify core kafka-node client sources........

**Comment by ismriv** [comment]
Agreed. I'll change the implementation to make using custom partitioners possible if @haio thinks to merge #260.

**Comment by lovato** [comment]
Hi @ismriv, do you have any update on this to share?

**Comment by ismriv** [comment]
Hi @lovato, @haio hasn't given any feedback yet. We are using the changes of the PR #260 in production since then, no issues so far.

**Comment by haio** [comment]
Hi @ismriv , this feature is helpful, but I need some time to review changes, thanks!

**Comment by lovato** [comment]
Hi @haio and @ismriv  ... I just noticed that 10 days ago v0.3.1 was pushed to master and deployed to NPM. I am positive that the feature is included, and if so, this issue can be closed. This issue is about having the partitioner algorithm, and v0.3.1 has it. Does it make sense?
