### ISSUE TITLE
Close consumer after final message is consumed

### ISSUE THREAD

**Issue by daveroberts** [SOHU-Co/kafka-node#259]
**Edit**: It appears what I'm asking for is the ability to set consumer-timeout-ms on the consumer, and have a callback when it's hit.  Is this possible?

Is it possible to close the consumer after the last message is consumed?

```javascript
consumer.on('message', function(message){
  console.log(message.value);
});
```

I don't want that to hang forever waiting for the next message.

I would prefer the following:

```javascript
consumer.on('message', function(message){
  console.log(message.value);
});
consumer.on('end', function(){
  consumer.close(function(){
    console.log("Timeout reached waiting for message, closing connection.");
  });
});
```

**Comment by SomeKittens** [comment]
Kafka topics should be treated as an infinite stream - they don't have an "end" per-se.

**Comment by daveroberts** [comment]
I want to end listening to the stream and have the process stop.  The only way to do this now is to kill the node process.  I know that the stream is infinite.

**Comment by hyperlink** [comment]
You should be able to stop it by calling `.commit` followed by a `.close`. And then later on create a new consumer and continue. Consuming in batches is a supported use case for kafka.
