### ISSUE TITLE
not closing client

### ISSUE THREAD

**Issue by mattslocum** [SOHU-Co/kafka-node#267]
```
process.on('SIGINT', function() {
    consumer && consumer.close();
    client && client.close();
});
```
My node process won't close when using ctrl+c
This unit test is also failing:
./node_modules/.bin/mocha test/manual.gracefulexit.js
  1) Client #close should close gracefully:
     Error: timeout of 4000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by hyperlink** [comment]
Closing the consumer will close the client.

**Comment by hyperlink** [comment]
You should have a handler in your `consumer.close` call that calls `process.exit();`
