### ISSUE TITLE
Working on supporting compression

### ISSUE THREAD

**Issue by haio** [SOHU-Co/kafka-node#27]

**Comment by jkrems** [comment]
Hey - I have a mostly working version of compression hacked into a fork right now. If there's interest, I would clean it up and open a PR.

**Comment by jplock** [comment]
@jkrems we'd love to use it if you contribute it!

**Comment by jkrems** [comment]
Created #141 for this.

**Comment by haio** [comment]
The compression feature is available in ^0.2.16, thanks for @jkrems 's contribution.
