### ISSUE TITLE
Request: don't require snappy

### ISSUE THREAD

**Issue by macobo** [SOHU-Co/kafka-node#273]
Historically `kafka-node` requiring snappy has broken quite a few environments and caused many a headache [1].

Most users don't require or use compression for these messages, so I would propose not including snappy inside the main module but rather as an optional extension?

[1] See all these issues: https://github.com/SOHU-Co/kafka-node/issues/253 https://github.com/SOHU-Co/kafka-node/issues/248 https://github.com/SOHU-Co/kafka-node/issues/241 https://github.com/SOHU-Co/kafka-node/issues/221 https://github.com/SOHU-Co/kafka-node/issues/217 https://github.com/SOHU-Co/kafka-node/issues/204 https://github.com/SOHU-Co/kafka-node/issues/202 https://github.com/SOHU-Co/kafka-node/issues/153

**Comment by kaustavha** [comment]
+1
I had a similiar idea since I'm doing some research on Kafka and couldnt get this to compile. Monkey patched this together with my furry paws
https://github.com/kaustavha/kafka-node--light
Still has zlib compression. I really just made it to play around, dont know if I'd recommend using it since I dont know if I'll maintain it.

**Comment by Sneagan** [comment]
Yes please. This is a huge blocker for my deployment process, as there seems to be no reliable workaround to the referenced issues.

**Comment by DrMegavolt** [comment]
+1, snappy requires gyp rebuild, and it will not work on docker node:slim image. 
This dependency forces to use huge full image node:latest

**Comment by milashenko** [comment]
+1

**Comment by hyperlink** [comment]
So I found [codependency](https://www.npmjs.com/package/codependency) module that will let you do optional modules but I don't have any experience with it and don't how well it works in practice.

Is there another way to do this and how do other projects include optional modules?

**Comment by hyperlink** [comment]
I have a solution for this. Hope to get a PR for review soon.
