### ISSUE TITLE
client.send([{payload1},{payload2}],...) seems that it could not possibly work

### ISSUE THREAD

**Issue by memelet** [SOHU-Co/kafka-node#276]
I dont understand at all what Client.send is doing by checking 

```
    //client.js#377
    if (payloads[0].length && !payloads[1].length) {
    ...
    if (payloads[1].length) {
    ...
```

If payloads is an array of a "ProduceRequest is a JSON object" what does it mean to check the length of its elements? And what would be special about the first and second payload in this array? This code does not really make any sense at all.

I also see that there is no test for invoking send with an array of payloads. I wonder if this code had some plan that got forgotten about and with no tests it was noticed.

The actual behavior I see is that if you invoke send with an array of payloads only the last gets sent to kafka. (Because only the second if statement is true.)

**Comment by memelet** [comment]
Ok, I see. checkMetadatas() returns an array. But I still am only getting the last payload sent to kafka. Will continue digging.

**Comment by memelet** [comment]
Seems that protocol#groupByTopic eats payloads of the same topic:

```
function groupByTopic(payloads) {
    var r = payloads.reduce(function (out, p) {
        out[p.topic] = out[p.topic] || {};
        out[p.topic][p.partition] = p;
        return out;
    }, {});
    console.log("++++ ++++ protocol#groupByTopic: payloads=", payloads)
    console.log("++++ ++++ protocol#groupByTopic: r=", r)
    return r;
}
```

```
++++ ++++ protocol#groupByTopic: payloads= [ { topic: 'mtcagent-probes',
    partition: 0,
    messages: [ [Object] ],
    attributes: 0 },
  { topic: 'mtcagent-probes',
    partition: 0,
    messages: [ [Object] ],
    attributes: 0 } ]
++++ ++++ protocol#groupByTopic: r= { 'mtcagent-probes': 
   { '0': 
      { topic: 'mtcagent-probes',
        partition: 0,
        messages: [Object],
        attributes: 0 } } }
```

**Comment by memelet** [comment]
```
    var r = payloads.reduce(function (out, p) {
        out[p.topic] = out[p.topic] || {};
        out[p.topic][p.partition] = p;           // OVERWRITE
```

If there multiple payloads for the same topic and the same partition (like in my example) there will be data loss, no?

**Comment by askhogan** [comment]
Guys this is a confirmed bug.  Can you label it as such.  This one just got us pretty bad.  Your documentation makes no distinction between when array you can include in payloads.

**Comment by hyperlink** [comment]
Looks like this is the same issue as #288. I will update the docs for the next release.
