### ISSUE TITLE
Kafka auto create topic - does not work with kafka-node

### ISSUE THREAD

**Issue by karthikus** [SOHU-Co/kafka-node#283]
I am using kafka-node for my kafka client and I have Kafka servers with auto.create.topics.enable set to true. So without any topic creation logic, if I try to consume messages from a topic which do not exists, the topic should be created right ? It does not happen and still I get the topic not found error.

**Comment by hyperlink** [comment]
It's likely a consumer doesn't work but I do know that producing a message to a topic that doesn't exist will work since kafka will just create that topic. Just be aware you will get an error response on the first send to that topic.
