### ISSUE TITLE
HighLevelProducer does not publish all messages in a batch to Kafka

### ISSUE THREAD

**Issue by ducas** [SOHU-Co/kafka-node#288]
Sorry if this is a repeat or documented, but I couldn't find anything related and it's late...

I have found that publishing a payload that consists of multiple items for the same topic and partition does not actually publish them to kafka. E.g.

[{
   topic: 'topic-1',
   messages: 'foo',
   partition: 0
}, {
   topic: 'topic-1',
   messages: 'bar',
   partition: 0
}]

In this case, only 'bar' will actually be published onto the topic/partition. No error is returned, but the data in the callback only has 1 result.

**Comment by gogorush** [comment]
change the way of doing this to : 
```js
{
  topic: 'topic-1',
  messages: ['foo', 'bar']
  partition: 0
}
```

**Comment by ducas** [comment]
@gogorush yep - that's what i did. i just don't think this behaviour is expected. and if it is, there should probably be more information about it...

**Comment by gogorush** [comment]
True, can't find it in doc @ducas

**Comment by estliberitas** [comment]
Dunno, if it's a bug. But I found a reason and gonna submit PR which groups messages by topic in case you provided.

**Comment by aikar** [comment]
@hyperlink I just encountered this issue. Can we reopen this. 

Documentation is NOT the solution to this bug, as this is VERY illogical and unintuitive.

There was a PR https://github.com/SOHU-Co/kafka-node/pull/305 to fix this too.

This format absolutely should be supported.

**Comment by aikar** [comment]
ignore previous reply, just saw on another issue a PR linked that this was fixed....
