### ISSUE TITLE
Producer send request timeout

### ISSUE THREAD

**Issue by hyperlink** [SOHU-Co/kafka-node#289]
What do you think about adding a timeout capability to the `producer.send`? This is different than the `ackTimeoutMs` since that is dealing with a processing timeout on the broker side.

The use case is if there is network issue to the kafka server and the message is never sent through the socket (or ack is not received) the callback will never get called. Eventually the client will raise errors but that is not helpful because the caller of `send` is oblivious to the status of that request.

A similar feature is available in the Kafka's console producer as `--request-timeout-ms`. If there's network issue and the messages are not sent with in the timeout an error is thrown. In node-kafka's case after the timeout has passed the callback should be invoked with a timeout error.

I will look into coding this up in my branch. Thanks!

**Comment by devnetf** [comment]
Hello! I would need this feature for a project. Are you already done with this?

**Comment by hyperlink** [comment]
@devnetf I have a partial solution in a local branch. I don't know when I'll be able to get to it.

**Comment by sgajavada** [comment]
+1
We ran into this issue where there was a network issue to the kafka server and message is never sent thru the socket and the callback never got called. The requests started queued up so badly that node process and memory went 100%,

**Comment by eastlondoner** [comment]
Ahhhh running into this problem as well. any ideas?

**Comment by hyperlink** [comment]
@sgajavada what should the behavior be for those messages were in the queue, that timed out, but it eventually to the broker and an Acked should the callback be called again or should it be ignored?

**Comment by darshanp** [comment]
setting "max.block.ms = 3000" fixed it for me.

**Comment by hyperlink** [comment]
This was implemented in #691 for the new `KafkaClient`. Published as `2.0.0`
