### ISSUE TITLE
pauseTopics in HighLevelConsumer

### ISSUE THREAD

**Issue by kibs** [SOHU-Co/kafka-node#290]
I was wondering why pauseTopics is not available in HighLevelConsumer. Is this not possible?

**Comment by s1479** [comment]
HighLevelConsumer.prototype.pause = function () {
    this.paused = true;
};

**Comment by estliberitas** [comment]
@kibs I guess it's just not implemented. :wink: But let's see what @haio will say.

**Comment by jbarreto** [comment]
paused is used 

https://github.com/SOHU-Co/kafka-node/blob/master/lib/highLevelConsumer.js#L502

**Comment by hyperlink** [comment]
`pause()` just sets a flag to deactivate the fetch loop.
