### ISSUE TITLE
Wrong message order

### ISSUE THREAD

**Issue by OndroNR** [SOHU-Co/kafka-node#298]
I have problem with message order when consuming topic with 250k messages (which where loaded into Kafka in batches of 2000 messages) with fresh start (no offsets in zookeeper). Consumer often does not process messages from offset 0, rather it starts at 4000 or 8000, or so. Also it continuosly processes block of 1000 messages and jumps at later or sooner N*1000 offset. I have tried changed maxTickMessages to 800 and it process block od 800 messages, but it still jumped to N*1000 offset. I could not find missing 200 offsets in debug log. Chaning maxTickMessages or maxNumSegments to very large number did not help.

I was printing current message offset directly in Kafka binary protocol decoder, which should eliminate some of potential async effects. I am attaching [Offset log](https://github.com/SOHU-Co/kafka-node/files/81878/offsets2.tmp.txt) and used code [kafka-order-test.js](https://github.com/SOHU-Co/kafka-node/files/81875/kafka-order-test.js.txt). I think there is problem in Kafka binary protocol parsing, but I was not able to find problem in it.

Kafka itself should not be a problem as I dumped topic with kafkacat, which mantained correct offset and messages order. I also monitored node.js-Kafka network traffic with Wireshark, and messages were shown in correct order.

**Comment by OndroNR** [comment]
I have working solution using synchronous gzip/snappy decompression of messageset in protocol.js. PR on the way.

**Comment by janantala** [comment]
🎉 👍
