### ISSUE TITLE
Consumer stops consuming

### ISSUE THREAD

**Issue by OndroNR** [SOHU-Co/kafka-node#300]
I have problem with consuming messages after PR #262. Consumer consumes 24000 messages (single FetchResponse) and does not consume any more messages. It works with 9405c86.

**Comment by JohnyDays** [comment]
I've also experienced this, any fix? Maybe rollback the change? Using 0.2 for now, it's working.

**Comment by jachandler** [comment]
Up to  9168 messages, then my code stops. Did some analysis installing older versions and found that 0.2.30 works, but 0.3.0 and beyond exhibit this behavior.

**Comment by OndroNR** [comment]
I tried 0.3.0 and it worked for me.

**Comment by paddy3883** [comment]
Experiencing the same issue as described. Mine stopped consuming after 547 mgs which were 2k in size. Going to have to revert back to 0.2.29 in mean time

**Comment by codyhazelwood** [comment]
I tried 500k+ messages on v0.3.0 and it worked fine for me as well.

**Comment by carlessistare** [comment]
Hi @OndroNR  this PR #314  should normally fix your problem, could you confirm?
