### ISSUE TITLE
Consumer stops consuming after initial messages

### ISSUE THREAD

**Issue by codyhazelwood** [SOHU-Co/kafka-node#311]
I can only get kafka-node to read events that were created while the consumer was offline.

I have 3 terminal windows open:
1: A small application using kafka-node's Producer to send messages every 1 second to a topic with 1 partition.
2: Running `kafka-console-consumer.sh --zookeeper localhost --topic testTopic`
3: Running `node kafka-node/examples/consumer.js --topic=testTopic`.  Removed line 12.

The kafka-console-consumer receives every message.  The kafka-node consumer.js does not receive any messages.  When I close and re-open it, then it will receive all of the messages since the last restart, but no more until I close and re-open it again.

Using Node v4.2.4 on OS X 10.11.2.  Installed kafka with homebrew.

**Comment by mattkirwan** [comment]
We've just had this same issue over the last few days and managed to resolve it by bumping the version from 0.3.1 down to 0.2.27. 
We also had an issue with 0.3.1 where creating a new consumer group offsetOutOfRange was throwing errors.
At this stage we have no idea what's causing this, just thankful to be seeing our messages!

Hope this helps in the interim.

**Comment by codyhazelwood** [comment]
Version 0.2.27 won't build for me (an issue with snappy), but I tried version 0.3.0, and it seems to have solved the problem for me temporarily.  Thanks @mattkirwan!

This is definitely a bug in 0.3.1, though.

**Comment by jaxonpickett** [comment]
We've seen the same behavior with 0.3.1. Rolling back to 0.2.27 fixed.

**Comment by carlessistare** [comment]
Hi @codyhazelwood  this PR #314  should normally fix your problem, could you confirm?

**Comment by codyhazelwood** [comment]
Yes, this solves the problem.  Thanks!

**Comment by nandanrao** [comment]
Thanks @carlessistare, that branch works for me as well! Saved!

**Comment by tjmcclure0501** [comment]
Any idea when this fix will be applied to the latest version.  If did not work in 0.3.1 but does in 0.2.3 - it would seem to me that 0.3.1 is useless without this fix
