### ISSUE TITLE
HighLevelConsumer.resume() not works

### ISSUE THREAD

**Issue by barenko** [SOHU-Co/kafka-node#318]
I created a HighLevelConsumer with a flow control to not consume a lot of RAM on my performance tests. After I call pause() and process the messages, I call resume() that the api doesn't do anything. 

When I debug the api, I see that into resume() method, the encoder.name is encodeFetchRequest and the Client.prototype.sendToBroker method stay indefinitely on longpolling if clause because broker.waitting is always true.

On version 0.2.30 it works, but not on 0.3.1.

Snippet:
```
		let flowControl = async.queue( (task, done) => {
			this.emit(task.topic, task.message, () => {
				this.log.debug({topic: task.topic, offset: task.offset, action: 'done'})
				done()
			})
		} , this.config.throughput)
		flowControl.drain = ()=> {
			this.log.debug({sid:sid.value, action: 'resume'})
			this.kafka.consumer.resume()
		}
		flowControl.saturated = ()=> {
			this.log.debug({sid:sid.value, action: 'pause'})
			this.kafka.consumer.pause()
		}
```

```
		this.kafka.consumer.on('message', message => {
			this.kafka.flowControl.push({topic: message.topic, sid:currSid, offset:message.offset, message:message})
		})

```

**Comment by rphillips** [comment]
Might want to try this PR: https://github.com/SOHU-Co/kafka-node/pull/314

It's working for me with #314

**Comment by hyperlink** [comment]
PR #314 has been merged. Closing.
