### ISSUE TITLE
Does this module guarantee that a "message" event won't be fired during construction of HighLevelConsumer?

### ISSUE THREAD

**Issue by ultrafez** [SOHU-Co/kafka-node#322]
When creating a HighLevelConsumer object, there is a period of time before attaching the "message" event handler when a "message" event emitted by the HighLevelConsumer wouldn't be handled. This would only be possible if the "message" event was emitted during construction of the HighLevelConsumer (if it occurs on the next tick then the handler will be attached).

My assumption is that since retrieving any messages involves IO, the network requests will happen async and therefore the event handler will be attached by the time that the "message" event is emitted.

Can you confirm whether it's possible for "message" events to be emitted by the HighLevelConsumer during construction?

**Comment by hyperlink** [comment]
Shouldn't be a problem if you attach directly after instantiating the highLevelConsumer. There are several async operations that happen before the first message fetch is called.

**Comment by ultrafez** [comment]
That's great, thanks for confirming that for me.
