### ISSUE TITLE
Consumer is not realtime ! 

### ISSUE THREAD

**Issue by kinghadi** [SOHU-Co/kafka-node#325]
I installed kafka stable version (`kafka_2.11-0.8.2.2`) from its official website. I have no problem with  its command line interface and it works well i.e I ran a producer in one terminal and a consumer in another terminal. While I am producing the consumer consume it in real time! No problem with it.

**My scenario**
Steps I took:
1. I installed kafka-node with `npm`.
2. I ran `zookeeper` and `kafka` server on my local host.
3. I ran `bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic topic1 --from-beginning` 
4. I ran `node producer.js`
5. Every time I run the setp 4 I can see the result in the consumer terminal in real time. 

But when I ran the `node consumer.js` instead of step 3. I just get the list of previous messages. Every time I ran the producer I will not get any changes in the consumer terminal. But when I re-ran it I will. So it is offline instead of online. I read some other issues but they were not usefull. Any help will be useful. Thank you.

**Comment by pragya-mishra** [comment]
I am too facing the same issue. While the consumer is running and producer is run, unlike the console consumer which shows the message produced by producer in realtime, the node-consumer doesn't show the message in realtime, it needs to be re-run again to show the messages.

**Comment by kinghadi** [comment]
I've fixed it with [this](https://github.com/SOHU-Co/kafka-node/pull/314/files) changes .
