### ISSUE TITLE
Producer emits ready when not connected to broker

### ISSUE THREAD

**Issue by saurako** [SOHU-Co/kafka-node#326]
I have a producer instance created that listens to the 'error' event being emitted by lib/producer.js and then try to reconnect (on a timeout) using the strategy outlined in an answer to a different issue (on error, create new instance of producer) https://github.com/SOHU-Co/kafka-node/issues/209

The problem though, is that lib/producer (the new instance that is created) emits a ready event, when it is not actually connected to a broker. 

Steps to reproduce the issue:
1. Have Zookeeper and Kafka instances running
2. Start a producer instance, to connect to Kafka. This producer must implement the reconnection logic mentioned above.
3. a. Kill Kafka, and let the reconnection logic in the producer trigger.
3. b. DO NOT RESTART KAFKA at this point.
4. After the timeout / interval set in the reconnection logic, when reconnection is tried, lib/producer emits ready - when it is not really connected to any broker.

P.S - I think that the problem is actually in lib/client - it emits the 'ready' event outside of the callback to connect  to a broker - (https://github.com/SOHU-Co/kafka-node/blob/master/lib/client.js#L78). I think that this emit needs to be on line 75, just before the return.

**Comment by saurako** [comment]
Has anyone else seen this problem? Is there a recommended method to correctly reconnect to a broker in case of lost connections?

**Comment by hyperlink** [comment]
Have you tried running the test without any reconnect logic? The reason I mention this is b/c the sockets to the broker automatically reconnects every second when it's closed or encounters an error. I also have submitted some PRs which was merged dealing with recovering from both zookeeper and kafka. There should be limited cases where you need to reconnect manually.

**Comment by saurako** [comment]
@hyperlink: I have tried that, but it didn't work as expected. Which is why I had to write this reconnection logic.

**Comment by hyperlink** [comment]
Just to be clear you are using v0.2? There's still outstanding issues (at least ones that haven't been merged yet) with v0.3.

The only case I've come up against is when I receive a `NO_NODE` error I had to close and recreate the client/producer combo.
