### ISSUE TITLE
Always Connects to localhost

### ISSUE THREAD

**Issue by tjmcclure0501** [SOHU-Co/kafka-node#329]
Below is my code.  I get a connection failure when I try to connect to the remote zookeeper/kafka server.  Strangely when I bring zookeeper and kafka up on my development machine the code works.  I seems like that code is always looking to connect to localhost even though I am passing in the URL.  Any help will be appreciated.

Tim

var kafka = require('kafka-node');
var client = new kafka.Client("msg.strax.co:2181","media_server",{ retries : 2 });
var producer = new kafka.Producer(client);

producer.on('ready', function () {

    producer.createTopics(['test'], false, function (err, data) {
        if (err) {
            console.log(err);
        }
        else {
            console.log(data);
        }
    });
});

producer.on('error', function (err) {
    console.log(err);
});

**Comment by hyperlink** [comment]
Does the kafka console producer work against this server? Kafka is very particular about how it's configured in that it needs to be able to connect back to itself. Check what kafka ` advertised.host.name` is set to.

**Comment by tjmcclure0501** [comment]
That was the issue - I needed to set the advertised host name for kafka running in my docker container.
