### ISSUE TITLE
Consume Messages Starting At The Time Of Connection

### ISSUE THREAD

**Issue by tjmcclure0501** [SOHU-Co/kafka-node#330]
I only want to consume message that have been committed to the kafka queue after I have connected with the consumer - I want to ignore messages received earlier than this timestamp.  I will be sending many messages so I would have to have to keep track of the most current offset or have to read all messages and drop those in the past.  What is the best way to accomplish this task?

Thanks,
Tim

**Comment by hyperlink** [comment]
You can use the [offset](https://github.com/SOHU-Co/kafka-node#fetchpayloads-cb) client to get the latest offset.
