### ISSUE TITLE
Should Offset Client have a close function?

### ISSUE THREAD

**Issue by timtutt** [SOHU-Co/kafka-node#332]
It appears that the offset client allows you to connect to the kafka instance, but once operations are done there is no way to close it meaning there would be a persistent connection until there is some shutdown event or error. Should you be able to close an offset client as you would a consumer or producer or am I missing something?

Happy to add the code and submit a PR if I'm not missing some additional details here.

**Comment by hyperlink** [comment]
Calling close on your consumer or producer will call close on the client.
