### ISSUE TITLE
TLS/SSL support

### ISSUE THREAD

**Issue by atkinsnashville** [SOHU-Co/kafka-node#334]
Please add support for implementing 0.9 SSL functionality in broker connections.

**Comment by jadedfire** [comment]
+1

**Comment by shpros** [comment]
Is there a target release or date (month, quarter, year) for this issue?

**Comment by kumar-b** [comment]
+1

**Comment by arunpmathew** [comment]
+1

**Comment by austinkelleher** [comment]
+1

**Comment by hyperlink** [comment]
@atkinsnashville @jadedfire @shpros @kumar-b @arunpmathew @austinkelleher would you be willing to test @CharlesWall's PR and see if it works for you?

**Comment by shpros** [comment]
@hyperlink : Thanks for the notification. I'll have my colleague @jmacias try it out.

**Comment by kumar-b** [comment]
we are facing some issues in TLS enabled cluster. #427 
Anyone else tested with TLS enabled cluster?
