### ISSUE TITLE
High level consumer re-receives messages

### ISSUE THREAD

**Issue by ychen11** [SOHU-Co/kafka-node#335]
We've got this problem for a really long time, no clue if it is found or fixed.
When we restart our consumer each time, it will re-receive some of previous received message again from server side.
And this only happened on high level consumer, simple consumer works fine here.

**Comment by jbarreto** [comment]
@ychen11 Before restarting the consumer are you closing the connection ?
try doing something like this 
var callback = function(){};
consumer.close(true, callback);
the first parameter is for force and it will commit before closing the connection 
https://github.com/SOHU-Co/kafka-node/blob/master/lib/highLevelConsumer.js#L583

**Comment by tizzo** [comment]
Also worth noting here - kafka pretty much has an [at least once](https://kafka.apache.org/08/design.html) consumer delivery guarantee so you should be able to handle the case gracefully.  That said… it shouldn't happen much - that should be a rare corner-case.

**Comment by ychen11** [comment]
Looks like it is fixed in version 3.2, after we upgraded our client, it ain't happened again.
I will keep looking, close this for now
