### ISSUE TITLE
How consumers works?

### ISSUE THREAD

**Issue by gabrielgiussi** [SOHU-Co/kafka-node#338]
Kafka consumers are pull-based so  at first it seems to be a mismatch between this and the  event-based approach like the one that Node.js takes.
From Kafka [documentation](http://kafka.apache.org/documentation.html#theconsumer):

> The Kafka consumer works by issuing "fetch" requests to the brokers leading the partitions it wants to consume.

[You ](https://github.com/SOHU-Co/kafka-node/#onmessage-onmessage) have taken an event-based approach for this, like if messages were events. 

> By default, we will consume messages from the last committed offset of the current group
> 
>     onMessage: Function, callback when new message comes
> 
> Example:
> 
>     consumer.on('message', function (message) {
>        console.log(message);
>     });

My question is how you been able to translate the kafka fetch style to the node event style. Something like an libuv event thread polling to kafka topics?

**Comment by hyperlink** [comment]
There's a [setImmediate](https://github.com/SOHU-Co/kafka-node/blob/master/lib/highLevelConsumer.js#L256) call made after the fetch that kicks off the next fetch.
