### ISSUE TITLE
Can i consumer message one by one ? 

### ISSUE THREAD

**Issue by sunkuo** [SOHU-Co/kafka-node#349]
Now , i found that kafka-node will receive message on "message" event . But i want to handle a message ,then to fetch the next message ,not auto fetch . How to make it ?

**Comment by hyperlink** [comment]
Each fetch can grab more than one message so the only way to process one message at a time is to `pause()` after the first message and then use something like `async.queue` to process one at a time and `resume()` after finished processing all the messages.

**Comment by sunkuo** [comment]
Thank you for your Suggestion. I found that when i call pause() as soon as i receive the first message , But i still receive some other message on event "message" .  Can i just receive one message with the help of pause and resume ?

**Comment by hyperlink** [comment]
pause and resume controls the fetch loop. it doesn't provide fine grained control with message events. If you are sure of the size of your messages you can tweak the fetch size to limit the number of messages per fetch but it could be a tricky thing to get right.
