### ISSUE TITLE
Is there a way to get the logSize of a partition?

### ISSUE THREAD

**Issue by jakebarnett** [SOHU-Co/kafka-node#353]
Is there a way to fetch the logSize of a partition, or is there a way to start consuming from the newest message on the partition?

**Comment by hyperlink** [comment]
We recently merged #372 which gave you the capability to get the latest offset. You can feed this offset into your consumer.  Eventually we will implement `fromOffset` latest.

```json
{
 "fromOffset": "latest"
}
```
