### ISSUE TITLE
kafka-node installation error - Windows

### ISSUE THREAD

**Issue by vikramgoyal2012** [SOHU-Co/kafka-node#355]
Hi,
When I am trying to install kafka-node module on my windows machine, it is giving me the following error:

> snappy@4.1.2 install C:\Softwares\NodeJs\NodeJsGit\JsonAds\node_modules\kafka-
node\node_modules\snappy
> ./node_modules/.bin/node-gyp rebuild

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! weird error 1
npm ERR! not ok code 0

Any idea how this can be fixed?

**Comment by hyperlink** [comment]
There's a compile step for snappy using [node-gyp](https://github.com/nodejs/node-gyp). Make sure it's installed since this is possibly the failure. The next update of the module should make snappy optional (it hasn't been published to npm yet).

**Comment by estliberitas** [comment]
@vikramgoyal2012 Node version? I'm wondering, maybe this should be addressed to snappy developers. Because if this is error in snappy build process, we only can create PR which fixes the issue.

**Comment by vikramgoyal2012** [comment]
@estliberitas : Node version is v0.10.23
@hyperlink : I tried installing snappy as well. That too, is giving an error on windows.

**Comment by mattmiddlesworth** [comment]
@hyperlink Any timeline on the next release to npm?

**Comment by hyperlink** [comment]
@mattmiddlesworth I will work on getting a 0.3.3 release out soon.

**Comment by hyperlink** [comment]
@mattmiddlesworth v0.3.3 is published.
