### ISSUE TITLE
Support for Kafka 0.9.0.1

### ISSUE THREAD

**Issue by saurako** [SOHU-Co/kafka-node#358]
Does this module support or has been tested to work well with the latest version of Kafka: http://kafka.apache.org/documentation.html

The documentation only mentions versions 0.8.1 and later.

**Comment by janantala** [comment]
@saurako some features work
Kafka 0.9 however should still support kafka 0.8 consumers and producers.

**Comment by saurako** [comment]
Thank you @janantala
