### ISSUE TITLE
enum keyed message

### ISSUE THREAD

**Issue by itayB** [SOHU-Co/kafka-node#361]
Can I send keyed message which is not string (but enum)?

https://github.com/edenhill/librdkafka/issues/640

for more info: http://stackoverflow.com/questions/36979586/kafka-node-send-enum-key-message-instead-of-string-key

**Comment by hyperlink** [comment]
The code as it's written now only accepts string which eventually gets converted to bytes and sent over to the broker.

You would have to make several changes to kafka-node code to supports this use case and honestly I don't think it's a great idea. You would get better interoperability using a plaintext string. Is there a string representation of your enum that could be used instead?

**Comment by estliberitas** [comment]
@hyperlink keyed messages are OK for quite a long time already, I think we must support them.

**Comment by itayB** [comment]
Great! It for efficient purpose. It would be much faster for me after consuming message to search for it as number rather than string..

**Comment by hyperlink** [comment]
Resolved in #704
