### ISSUE TITLE
Consumer not registered

### ISSUE THREAD

**Issue by giaule** [SOHU-Co/kafka-node#362]
When i running my application then this alert error message 

`FailedToRebalanceConsumerError: Exception: NODE_EXISTS[-110]`

I had debug lib, i look error here 

`callback("Consumer not registered " + consumerId);`

Please help me

**Comment by hyperlink** [comment]
I would try using the `kafka/bin` tools to troubleshoot your connection to the kafka server. Verify you can consume messages using those tools first. Good luck.

**Comment by giaule** [comment]
Thanks for support.

 i had tried run agains, every when has error 👍
