### ISSUE TITLE
Consumer option 'autoCommitMsgCount' not documented?

### ISSUE THREAD

**Issue by rtorrero** [SOHU-Co/kafka-node#363]
I've been trying to find out what this option does but i've failed to find any documentation.

Could anyone give more information on this? Thanks!

**Comment by haio** [comment]
It's actually missing in document, but you can set `autoCommitMsgCount` in options

**Comment by hyperlink** [comment]
Looks like it's just defined in the default options? I don't see other [references](https://github.com/SOHU-Co/kafka-node/search?q=autoCommitMsgCount&type=Code&utf8=%E2%9C%93) to that attribute anywhere else.

**Comment by rtorrero** [comment]
Any idea how or why it got there in the first place?

**Comment by hyperlink** [comment]
No idea @rtorrero. I haven't been in the code base that long. Maybe it was a feature that was planned but never implemented. We should remove it to prevent confusion. PR's welcome! :)
