### ISSUE TITLE
Zookeeper path prefix

### ISSUE THREAD

**Issue by SirCameron** [SOHU-Co/kafka-node#364]
Hi,

My client's sysops has changed the key path for kafka data in zookeeper. 
So instead of using:
`/consumers`etc
They use:
`/kafka/consumers`

I have forked the repo and added a `pathPrefix` to the zkOptions object and to all places where a zk path is defined.

In keeping with your contribution guidelines, I'm creating an issue before I create the pull request.
May I go ahead with the pull?

**Comment by carlessistare** [comment]
LGTM

**Comment by SirCameron** [comment]
Cool! Here she is: https://github.com/SOHU-Co/kafka-node/pull/365

**Comment by hyperlink** [comment]
@SirCameron Thanks for the PR. I made some comments on it. Also could you update the `README` to document this new feature?

**Comment by hyperlink** [comment]
@carlessistare pointed out in the PR the solution is to add a `chroot` suffix to the `connectionString`.
