### ISSUE TITLE
Write low level kafka producer in node js

### ISSUE THREAD

**Issue by monish777** [SOHU-Co/kafka-node#366]
Below is my simple code used to produce messages to a kafka topic in node js, using the kafka-node module

````
var kafka = require('kafka-node')
   client = new kafka.Client('172.172.12.21:2181,172.172.12.22:2181'),
   producer = new kafka.Producer(client);

producer.on('error', function(err) {
   console.log(producer);
   console.log(err);

function produceMessages(topic, message) {
   var payloads = [];
   payloads[0] = {
     topic: topic,
     messages: message
   };
   producer.send(payloads, function(err, data) {
     if (err) {
        console.log('Error: While writing message to Kafka', err); 
        return;
     }
     console.log(data);
   });
}
module.exports = produceMessages;
````

Now the kafka-node module automatically detects the brokerList that the producer should try to connect to from the zookeeper, as per the docs.

But the broker list that it gets is wrong(Could be a bug at the kafka cluster end, where zookeeper isn't configured properly). Is there any way where I can specify the list of brokers to connect to from my node code itself? I guess this is what libraries in other languages allow .

----
I guess this is an issue with the kafka-node library. In kafka-node library: connectionString: Zookeeper connection string, default localhost:2181/

Where as in the no-kafka library: connectionString - comma delimited list of initial brokers list, defaults to '127.0.0.1:9092'

Is there a way in the kafka-node library to specify the connection string as comma delimited list of initial brokers list

**Comment by hyperlink** [comment]
Make sure you define a kafka advertised host and that host is reachable from where your code runs.

**Comment by StackDaddy** [comment]
Just to clarify, would defining advertised hosts on his various (potentially remote) brokers fix what may appear to be a configuration issue, preventing zookeeper from collecting the correct info, or would defining the advertised hosts allow the kafka-node library to 'specify the connection string as comma delimited list of initial brokers list'?

**Comment by hyperlink** [comment]
Clients and brokers both pull data from zookeeper to coordinate with the cluster so I would imagine a wrong configuration would affect your brokers as well (though it may not be immediately obvious).

`kafka-node` pulls the list of brokers from zookeeper. After received a `connect` event from your client do a `console.log(client.brokerMetadata)` to see what the module thinks your broker's are located.

Generally it's good idea to use the `kafka/bin/console-*` tools as a sanity check to make sure your kafka setup is configured correctly.
