### ISSUE TITLE
kafka-please for integration testing

### ISSUE THREAD

**Issue by eirslett** [SOHU-Co/kafka-node#367]
I made a little npm module called [kafka-please](https://www.npmjs.com/package/kafka-please) which sets up a local kafka/zookeeper broker, meant for integration tests. Is this npm module something you could be interested in using for integration testing of kafka-node?

**Comment by estliberitas** [comment]
I'll check it.

**Comment by estliberitas** [comment]
@eirslett as far as I get it, you just don't support current LTS. Which makes it a bit difficult to use for many people. I mean, at least me, I use LTS even on my machine, not only on production.

**Comment by eirslett** [comment]
You mean the node.js version? Yup, it uses the latest syntax. But that could easily be fixed, if needed!

**Comment by hyperlink** [comment]
We're using kafka in docker container for testing. Thank you for your suggestion.
