### ISSUE TITLE
Client and HighLevelConsumer - when they are ready?

### ISSUE THREAD

**Issue by tlenex** [SOHU-Co/kafka-node#380]
Is there any event that emits when the connection by `Client` and/or `HighLevelConsumer` is established? 

Currently my `Client` triggers `connect` event at least 2 times, sometimes even more and I just need to know when is it safe to set up my `message` listeners on `HLC`.

Are there any undocumented events that I'm missing? Like `connected`, `ready` or something?

**Comment by hyperlink** [comment]
You shouldn't have to worry about this just attach the listener in the same event loop after instantiating the highLevelConsumer. There are several async operations that happen before the first message fetch is called.

**Comment by tlenex** [comment]
So right after registration of `HLC` I can be allways sure that connection will be established succesfully?

**Comment by hyperlink** [comment]
If the purpose is to kick off another async service you can reject when you receive an `error` event and resolve when you receive a `connect` event .  Please keep in mind you can always receive `error` events sometime after a `ready`/`connect` So this won't map to promises 1 to 1. And even after receiving an `error` event it doesn't mean the end b/c the module will retry if there were connection issues.

`ready` = connected to zk
`connect` = connected to broker
`error` = socket error, or some other issue. can be interpreted as pending or rejected

Hope that helps.
