### ISSUE TITLE
Consumer init offset end

### ISSUE THREAD

**Issue by itayB** [SOHU-Co/kafka-node#388]
I'm using kafka-node to consume messages from a specific Kafka topic. When I restart my node server, it init my consumer as expected, but it's default behavior is to start consume from offset 0 while my goal is to receive only new messages (aka start consume from current offset). I didn't find a way to achieve that from the API documentation. Anyone knows if its supported?

Thanks!

http://stackoverflow.com/questions/37949759/kafka-node-start-consume-from-last-offset

**Comment by hyperlink** [comment]
Take a look at #342. We recently merged code that can get you the latest offset. It should be in the next release.

**Comment by itayB** [comment]
When the next release should be?

**Comment by hyperlink** [comment]
@itayB I hope to publish it by the end of this week.

**Comment by itayB** [comment]
@hyperlink perfect! Can't wait to get it ;-)

Thanks

**Comment by hyperlink** [comment]
v0.4.0 has been published with the method to get latest offset.
