### ISSUE TITLE
How to read message json

### ISSUE THREAD

**Issue by mkj-git** [SOHU-Co/kafka-node#389]
I have this JSON created in java:

            HashMap message = new HashMap();
            message.put("x", "xxxxx");
            message.put("y", "yyyyy");
            message.put("z", 100);
            ByteArrayOutputStream byteOut = new ByteArrayOutputStream();
            ObjectOutputStream out = new ObjectOutputStream(byteOut);
            out.writeObject(message);

I am using https://github.com/SOHU-Co/kafka-node/ pluginI am new to NodeJS. In nodejs when i do JSON.stringify i am getting 

    consumer.on('message', function (message) {
        console.log(JSON.stringify(message));
    });
It prints:

    {"topic":"newComment","value":"��\u0000\u0005sr\u0000\u0011java.util.HashMap\u0005\u0007���\u0016`�\u0003\u0000\u0002F\u0000\nloadFactorI\u0000\tthresholdxp?@\u0000\u0000\u0000\u0000\u0000\fw\b\u0000\u0000\u0000\u0010\u0000\u0000\u0000\u0003t\u0000\u0001xt\u0000\u0005xxxxxt\u0000\u0001yt\u0000\u0005yyyyyt\u0000\u0001zsr\u0000\u0011java.lang.Integer\u0012⠤���8\u0002\u0000\u0001I\u0000\u0005valuexr\u0000\u0010java.lang.Number���\u001d\u000b���\u0002\u0000\u0000xp\u0000\u0000\u0000dx","offset":8,"partition":0,"key":{"type":"Buffer","data":[107,49]}}

So how can get back JSON from this .I was going through https://nodejs.org/api/buffer.html#buffer_new_buffer_buffer but found nothing.

**Comment by hyperlink** [comment]
Looks like Java code needs to write the JSON string out instead of the buffer.

**Comment by mkj-git** [comment]
In java kafka, you can't send anything without:

        ByteArrayOutputStream byteOut = new ByteArrayOutputStream();
        ObjectOutputStream out = new ObjectOutputStream(byteOut);
        out.writeObject(YOUR MESSAGE);
So this part is mandatory

**Comment by hyperlink** [comment]
You don't use [this API](http://kafka.apache.org/090/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html) to produce messages?

**Comment by mkj-git** [comment]
Here is full code

            HashMap message = new HashMap();
            message.put("x", "xxxxx");
            message.put("y", "yyyyy");
            message.put("z", 100);
            ByteArrayOutputStream byteOut = new ByteArrayOutputStream();
            ObjectOutputStream out = new ObjectOutputStream(byteOut);
            out.writeObject(message);

            ProducerRecord producerRecord = new ProducerRecord(topic,  "k1", byteOut.toByteArray());
            producer.send(producerRecord);

**Comment by hyperlink** [comment]
What would happen if you warp your message into `JSONObject`?

**Comment by mkj-git** [comment]
Ok i will give it a try
