### ISSUE TITLE
Add examples of asynchronous message handlers

### ISSUE THREAD

**Issue by pcothenet** [SOHU-Co/kafka-node#391]
Hello!

The only example of consumer in the doc does a `console.log(message)`. Given that this is node, it seems very likely that a message handler can be asynchronous (that's my case).

What happens if the handler is asynchronous (callback or promise) and fails? What is the recommended way to handle errors in a message handler. Write to a 'dead' topic?

**Comment by hyperlink** [comment]
Pretty open question. That depends on your use case. You can `emit` an error in your handler class and let that class decide what to do-- maybe try to process that message again? Or you can just log the error and crash. Good luck!

**Comment by pcothenet** [comment]
What about commit behavior. If I crash (or simply SIGINT my consumer) while a message is processing, does the offset gets committed?

**Comment by hyperlink** [comment]
Module doesn't handle this case. You will need to handle SIGINT and commit and close your consumer.
