### ISSUE TITLE
minimatch security vulnerability

### ISSUE THREAD

**Issue by sgajavada** [SOHU-Co/kafka-node#395]
Security checks are flagging  **Regular Expression Denial of Service** vulnerability with  minimatch module in the following path.  Can you take a look at this?

kafka-node@0.3.3 > snappy@4.1.2 > node-gyp@3.2.1 > glob@4.5.3 > minimatch@2.0.10        
kafka-node@0.3.3 > snappy@4.1.2 > node-gyp@3.2.1 > minimatch@1.0.0 

More Info: https://nodesecurity.io/advisories/118

npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by hyperlink** [comment]
I'm experiencing the same issue with the latest snappy release (`5.0.4`) which uses latest `node-gyp` (`3.3.1`). Looks like this needs to be addressed in the `node-gyp` project that snappy uses.

`node-gyp` is only used during `npm install` to build snappy so maybe this isn't as serious to our module.

**Comment by sgajavada** [comment]
Thanks.  Did you happen to file an issue with node-gyp?

**Comment by hyperlink** [comment]
no I haven't @sgajavada.
