### ISSUE TITLE
Frequent FailedToRegisterConsumerError: Exception and CONNECTION_LOSS: Exception

### ISSUE THREAD

**Issue by snatesan** [SOHU-Co/kafka-node#396]
I am seeing high number of 
 FailedToRegisterConsumerError: Exception: CONNECTION_LOSS[-4]
followed by
CONNECTION_LOSS: Exception: CONNECTION_LOSS[-4]
errors while using high level consumer.

It automatically recovers from this state and start receiving messages.
But the this error occurs very frequently.

Occasionally consumer gets old messages redelivered and that is creating problem in application. 
I am wondering whether redelivery of messages has got anything with frequent connection loss errors.

Any idea why it is happening?

Appreciate your help.

**Comment by hyperlink** [comment]
Sounds like the client lost it's network connection Zookeeper and/or Kafka.

**Comment by snatesan** [comment]
@hyperlink looks like the connection loss is happening only in one of the vms where application is running. So I will troubleshoot into that why it is happening only one vm.
But it revealed an issue in rebalance logic. Due to network interruptions there is frequent rebalance occurs in short time and that leads to eventually fetch all messages from zookeeper not from the committed offset.
I have submitted a PR to resolve that issue, https://github.com/SOHU-Co/kafka-node/pull/402.
Please take a look.

**Comment by hyperlink** [comment]
Closing since #402 is merged.
