### ISSUE TITLE
Unable to connect to remote box

### ISSUE THREAD

**Issue by Tombert** [SOHU-Co/kafka-node#407]
Hello!  When I try and connect to a remote kafka instance, I get this error: 

```
Error: connect ECONNREFUSED 127.0.0.1:9092
```

Is there a place I need to specify the URL for a node?  

Here is the code I'm using: 

```
var Producer = kafka.Producer
var client = new kafka.Client("<remote_url>:2181"),
```

**Comment by hyperlink** [comment]
You may want to check your kafka/zookeeper is setup correctly. Try connecting with the kafka bin tools first.
