### ISSUE TITLE
Kafka consumer message event is firing more than once

### ISSUE THREAD

**Issue by vjmani** [SOHU-Co/kafka-node#426]
I have a scenario where I need to use two producers and two consumers. Producer1 is producing something in Topic1 which is being consumed by Consumer1, which is handled by Java app. Same time this java app after consuming, producing another message on Topic 2, which is being handled by my Consumer 2 in my node app. This all happening in one REST call. The Problem is that Consumer 2 is firing 'message' event more than once, so while listening on message event i am calling a callback, which is being called more than once and giving undesired behavior.
I have debug the library in client.js i have found this 'message' event emitter.

**Comment by hyperlink** [comment]
Sorry, I'm having trouble understanding the issue and why it would be undesirable to receive a callback for every message received.

**Comment by vjmani** [comment]
As its all happening in one http call..that callback is responsible for responding to http call. So when on message is listening more than once that callback is being called multiple time and causing issue. Here is the sceneri

**Comment by vjmani** [comment]
Sorry..it was typing mistake above.. so the scenario is..
Http request--> Producer1 (node app) ---> Consumer 1 (java app) ---> Producer 2 (java app) ---> Consumer 2 (node app) ---> http response.

I hope now it is understable.

**Comment by hyperlink** [comment]
I wouldn't not try to design this to fit in a single http request. There are multiple points of failure that is out of your control and your app may suffer from latency issues.

You should consider about making the request return after Producer1 successfully sends it's  request and then create a server side push event to get the results of the request back to your web client. Good luck.
