### ISSUE TITLE
Consumer does not work if the partition in topic config is a string

### ISSUE THREAD

**Issue by kumar-b** [SOHU-Co/kafka-node#441]
The consumer is not working if topic config looks like this - (where partition is a string)
```javascript
var topics = [{
    topic: 'test',
    partition: '7'
}];
```

Is this the expected behavior?  If yes, can we have this documented?

**Comment by hyperlink** [comment]
Looks like our examples and the examples in the docs all use integer as the partition. Do you think this should be explicitly called out?

**Comment by kumar-b** [comment]
It can be called out or we can throw error in case of string partition number provided. Right now it gives no error and finding the cause takes good amount of time.
By looking at java api of topic partition - error can be thrown on string partition config.
https://kafka.apache.org/090/javadoc/org/apache/kafka/common/TopicPartition.html
