### ISSUE TITLE
TypeError: Object PLAINTEXT://[IP]:9092 has no method 'find'

### ISSUE THREAD

**Issue by nagarashish** [SOHU-Co/kafka-node#446]
Hi,

I am trying to setup Apache Kafka server and kafka-node as a Consumer.  Apache Kafka server is running & I have verified with command line scripts.

Getting "no method 'find' error when trying to use kafka-node as consumer:

TypeError: Object PLAINTEXT://[IP]:9092 has no method 'find'
    at /root/kafka/nodeconsumer/node_modules/kafka-node/lib/client.js:134:46
    at Array.forEach (native)
    at Client.setupBrokerProfiles (/root/kafka/nodeconsumer/node_modules/kafka-node/lib/client.js:129:24)
    at null.<anonymous> (/root/kafka/nodeconsumer/node_modules/kafka-node/lib/client.js:84:12)
    at g (events.js:180:16)
    at emit (events.js:95:17)
    at /root/kafka/nodeconsumer/node_modules/kafka-node/lib/zookeeper.js:269:18
    at /root/kafka/nodeconsumer/node_modules/kafka-node/node_modules/async/lib/async.js:52:16
    at done (/root/kafka/nodeconsumer/node_modules/kafka-node/node_modules/async/lib/async.js:246:17)
    at /root/kafka/nodeconsumer/node_modules/kafka-node/node_modules/async/lib/async.js:44:16

Sample Consumer Code:
==================

var kafka = require('kafka-node');
var Consumer = kafka.Consumer;
var client = new kafka.Client('localhost:2181');
var offset = new kafka.Offset(client);

offset.fetch([
    {
      topic: 'test'
    }
    ], function (err, data) {
      console.log(err);
      console.log(data);

});

var consumer = new Consumer(
        client,
        [
            { topic: 'test', partition: 0, time: -1}
        ],

        {
           autoCommit: false, autoCommitIntervalMs: 5000,  fetchMaxWaitMs: 100, fromOffset: true, fetchMinBytes: 1, fetchMaxBytes: 1024 * 10
        }
    );

consumer.on('message', function (message) {
     console.log(message);
});

consumer.on('error', function (err) {
    console.log('error', err);
});

consumer.on('offsetOutOfRange', function (topic) {
    console.log("------------- offsetOutOfRange ------------");
    topic.maxNum = 2;
    offset.fetch([topic], function (err, offsets) {
        var min = Math.min.apply(null, offsets[topic.topic][topic.partition]);
        consumer.setOffset(topic.topic, topic.partition, min);
    });
});

Pls suggest how to resolve this issue.

Thanks

**Comment by hyperlink** [comment]
What version of node are you running?

**Comment by jackfengji** [comment]
I'm facing the same issue. The node version is v0.12.14

**Comment by nagarashish** [comment]
Node v0.10.42

**Comment by hyperlink** [comment]
I will push out `0.5.6` soon to fix this.
