### ISSUE TITLE
node.js-error ECONNREFUSED when killing a broker

### ISSUE THREAD

**Issue by sculeb** [SOHU-Co/kafka-node#450]
I have the same or at least very similar issue as in #116 . I opened a new one because 116 is closed. I have 2 kafka broker (0.10.0.1) and 1 zookeeper instance, all on the same vm and two client applications (producer and consumer) with kafka-node (0.5.6) on my local machine.

I was expecting the clients to automatically reconnect to a running broker when I kill the one, that is used. I do catch the 'error'-event in both the producer and consumer and the thrown error isn't a kafka-node error but a node.js one, I guess.

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED <ip_of_vm>:9092
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1057:14)
```
The broker I killed used port 9092, zookeeper uses default port 2181. Code of producer-client below:

```
var kafka = require('kafka-node'),
    client = new kafka.Client('<ip_of_vm>:2181/', 'producer-client'),
    producer = new kafka.Producer(client),
    payload = [{
      topic: 'replicated-topic',
      messages: ['it works!!']
    }];

producer.on('ready', () => {
  producer.send(payload, (err, data) => {
    console.log(data);
  });
});

producer.on('error', err => {
  console.log(err);
});
```
Any help is appreciated!
Thanks.

**Comment by hyperlink** [comment]
have you let it run and see if it recovers? Connection errors will throw errors but there's logic that will attempt to reconnect while the zk watch will refresh the brokers once it realized that killed broker is offline.

**Comment by sculeb** [comment]
The node-application crashes, the process stops.

**Comment by sculeb** [comment]
oh my....you're right! It does recover. Thank you for that hint. Kind of embarrassing lol
Thanks for the quick support.

**Comment by karocksjoelee** [comment]
@hyperlink  No , it doesnt recovered , I have listened to both consumer & producer's 'error' event .
Anything I missed ? 

Here is my code . PS: <cm> just my custom logging function . 
`const kafka = require('kafka-node');
const client = new kafka.Client('59.127.187.54:2181');
const Producer = new kafka.Producer(client);
const Offset = kafka.Offset;
const offset = new Offset(client);

let RcnoConsumer = new kafka.Consumer(client, [ { topic: 'streamingUpdateOrders', partition: 0 }], { autoCommit: false });

client.once('connect', () => {
  cm.logSuc('[KAFKA] Client Connected')
});


RcnoConsumer.on('message', (data) => {
  cm.logSuc('[KAFKA] Topic: RCNO');
  console.log(data);
});

RcnoConsumer.on('error', (err) => {
  cm.logErr('[KAFKA] Topic: RCNO Error');
  console.log('error', err);
});

RcnoConsumer.on('offsetOutOfRange', (topic) => {
  topic.maxNum = 2;
  offset.fetch([topic], function (err, offsets) {
    if (err) {
      return console.error(err);
    }
    var min = Math.min(offsets[topic.topic][topic.partition]);
    RcnoConsumer.setOffset(topic.topic, topic.partition, min);
  });
});


// Testing Producer :

let payloads = [
  { topic: 'streamingUpdateOrders', messages: 'Hello Joe 0012543~', partition: 0 }
];

Producer.on('ready', () => {
  cm.logSuc('[KAFKA] Producer is Ready');
});

Producer.on('error', err => {
  cm.logErr('[KAFKA] Producer Error')
  console.log(err);
});`

**Comment by hyperlink** [comment]
Hi, I am hoping PR #758 will resolve your issue.

**Comment by karocksjoelee** [comment]
@hyperlink  New error ...  from Consumer.on('error); 

`BrokerNotAvailableError: Could not find the leader
    at new BrokerNotAvailableError (/Users/joelee/studies/kafka-test/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at Client.sendToBroker (/Users/joelee/studies/kafka-test/node_modules/kafka-node/lib/client.js:565:17)
    at Client.send (/Users/joelee/studies/kafka-test/node_modules/kafka-node/lib/client.js:520:10)
    at Client.sendFetchRequest (/Users/joelee/studies/kafka-test/node_modules/kafka-node/lib/client.js:208:8)
    at Consumer.fetch (/Users/joelee/studies/kafka-test/node_modules/kafka-node/lib/consumer.js:181:15)
    at Consumer.resumeTopics (/Users/joelee/studies/kafka-test/node_modules/kafka-node/lib/consumer.js:297:21)
    at Timeout._onTimeout (/Users/joelee/studies/kafka-test/bin/www:216:22)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) message: 'Could not find the leader' }`

Here is my use-case : 
I am connection Kafka server (zookeeper) by IP (remotely), the problem is : if the remote Kafka server shutdown / re-open or connection lost --- 
(1) **It will crash my node by not handling client.on('close') event .**  
_events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 59.127.187.54:9092_

**(2) After I handle the client.on('close') event , I must call Producer.close()  . It still will show 
BrokerNotAvailableError: Could not find the leader**

I need my client / Consumer / Producer recover after Kafka server re-open . 
**Can you show me the example code using in production ?? Just consumer ,  maybe there's something I did wrong .**
I've followed READ.me & example/consumer.js . 
I've go over every issue in this repository . **謝謝您**

**Comment by hyperlink** [comment]
Node  will crash when you don't listen to the error event coming from your `Producer` or `Consumer` or other classes that use `Client`.

Direct usage of the `Client` should listen to the `error` on the client instance. Other classes will proxy error from the client so listening to the client error won't be necessary in those cases.

Hope that helps.
