### ISSUE TITLE
Consumers causing uncaughtException

### ISSUE THREAD

**Issue by kumar-b** [SOHU-Co/kafka-node#452]
uncaughtException occurs in two scenarios -
1. When kafka server gets disconnected. (To reproduce : just start a consumer and then stop the kafka).
The consumer should be fault tolerant and should not cause the process to exit abruptly. The following error is seen in the above scenario
```javascript
connect ECONNREFUSED <KAFKA_HOST>:<KAFKA_PORT> { pid: 12636 }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED <KAFKA_HOST>:<KAFKA_PORT>
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

Process finished with exit code 1
```
This also happens in cluster mode and one kafka server goes down but replicated servers are available.

2. When creating node-zookeeper-client https://github.com/SOHU-Co/kafka-node/blob/master/lib/zookeeper.js#L18, the expired event is not handled. This causes uncaughtException and exits the process. This happens specifically in cluster.

**Comment by hyperlink** [comment]
You shouldn't be getting any uncaught exceptions if have an error handler on your consumer.

Could you give more detail on the error you're getting from zookeeper?

**Comment by kumar-b** [comment]
I have an error handler which printed the first line
```javascript
consumer.on('error', function (err) {
        console.error(err.message, {pid: process.pid});
 });
```

It captures the error. Still it causes the uncaughtException.

**Comment by kumar-b** [comment]
This is error I am getting for consumer
```javascript
Tue Aug 23 2016 11:59:33 GMT+0530 (IST) - error: Kafka consumer error :Exception: CONNECTION_LOSS[-4] pid=23400
Tue Aug 23 2016 11:59:33 GMT+0530 (IST) - error: uncaughtException: Exception: CONNECTION_LOSS[-4] date=Tue Aug 23 2016 11:59:33 GMT+0530 (IST), pid=23400, uid=502, gid=504, cwd=/opt/node-server, execPath=/opt/node-server/node, version=v4.5.0, argv=[/opt/node-server/node, /opt/node-server/index.js, PEListener], rss=74702848, heapTotal=60071776, heapUsed=34473360, loadavg=[0.1240234375, 3.501953125, 6.1005859375], uptime=58361
CONNECTION_LOSS: Exception: CONNECTION_LOSS[-4]
    at ConnectionManager.cleanupPendingQueue (/opt/node-server/node_modules/node-zookeeper-client/lib/ConnectionManager.js:189:46)
    at ConnectionManager.onSocketClosed (/opt/node-server/node_modules/node-zookeeper-client/lib/ConnectionManager.js:274:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:486:12)
```

**Comment by kumar-b** [comment]
This is code snippet used
```javascript
var kafka = require('kafka-node');
var Client = kafka.Client;

var consumer;
var client;

var topics = [{
    topic: 'test',
    partition: 0
}];

var zkString = '<ZK_HOST>:<ZK_PORT>';

var startKafkaConsumer = function (kafkaClient, dataHandler) {
    client = kafkaClient;
    var Consumer = kafka.Consumer;
    var Offset = kafka.Offset;
    consumer = new Consumer(kafkaClient, topics, {
        groupId: 'kafka-node-group20'
    });
    var offset = new Offset(kafkaClient);

    consumer.on('message', function (message) {
        dataHandler(message.value);
    });
    consumer.on('error', function (err) {
        console.error(err.message, {pid: process.pid});
    });
    consumer.on('offsetOutOfRange', function (topic) {
        topic.maxNum = 2;
        offset.fetch([topic], function (err, offsets) {
            var min = Math.min.apply(null, offsets[topic.topic][topic.partition]);
            consumer.setOffset(topic.topic, topic.partition, min);
        });
    });
};

var kafkaClient = new Client(zkString);
startKafkaConsumer(kafkaClient, console.log);
```

Steps to reproduce : 
- Start zookeeper and kafka server
- Start above consumer
- Stop kafka server

The consumer throws uncaughtException.

Even I added an error listener for kafkaClient, still it throws exception.
```javascript
kafkaClient.on('error', function(err) {
    console.log(err);
});
```

**Comment by kumar-b** [comment]
I debugged the issue a bit. Found out that it's happening because of no error handler for offset. When added error listener for offset, it got captured.

Is it because of some recent changes? Earlier we were not having any error handler for offset and it used to work smoothly. Is 'ECONNREFUSED' error valid for offset?

**Comment by hyperlink** [comment]
kafka node will emit systems errors even though it will try it's best to recover from them by reconnecting. Since the Offset uses client broker like producer/consumer you will also need to listen to the error.

**Comment by karocksjoelee** [comment]
So ... how can I listen to the "Offset Error" you mentioned

**Comment by hyperlink** [comment]
The example had instantiated an Offset object. So you would just need to add a handler for the `error` event of the offset object.
