### ISSUE TITLE
Kafka Producer not sending messages, compatable with Python Kafka, Docker?

### ISSUE THREAD

**Issue by Lukeout** [SOHU-Co/kafka-node#453]
I have a EXP web service that POSTs to a model service that then populates the DB, the model service then responds with the new data (just json) back to the EXP web service. On the EXP service I am trying to then push this new data to Kafka via a producer but it's failing, after console logging the producer I see that ready: 'false' so I think I'm never actually sending messages. 

My consumer is using python-kafka because its a python script that automatically reads from Kafka and sends it to an ES. I am using docker-compose for my containers. I confirmed my set-up works because I am able to manually send things to my Kafka container via python, I am just having implementing it in node using kafka-node :l 

I declare Kafka at the top of my listing.js 
var kafka = require('kafka-node'),
    Producer = kafka.Producer,
    KeyedMessage = kafka.KeyedMessage,
    client = new kafka.Client('kafka:9092'),
    producer = new Producer(client);
    km = new KeyedMessage('key', 'message');

then in my Post request I have this: 

request(options)
  .then(function(parsedBody) {
    //payloads = [];
    //var msg = { topic: 'new-listings-topic', messages: parsedBody, partition: 0 };
    //payloads.push(msg)
    payloads = [
        { topic: 'new-listings-topic', messages: parsedBody, partition: 0 },
    ];
    console.log(producer);
    console.log(payloads);
    producer.on('ready', function () {
      producer.send(payloads, function (err, data) {
        console.log(payloads)
        console.log(data);
      });
   });

   producer.on('error', function (err) {
     console.log(err);
   });
    res.send(parsedBody);
    //res.send('Pokemon added through the exp api');
  })
  .catch(function (err) {
    res.send(err)
  })
});

**Comment by Lukeout** [comment]
After checking to see if my client or producer are ready it seems neither are ready. Is this a problem with how I'm connecting to the client? Does kafka-node support docker? I am using spotify/kafka which has built in zookeeper support. My docker-compose has this, so shouldn't the connection string be kafka:9092? 

i.e client = new kafka.Client('kafka:9092'),

and the web service has a links: - kafka already

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka



 if (client.ready) {
      console.log('client is ready');
    }
    else {
      console.log('client is not ready');
    }

    if (producer.ready) {
      console.log('producer is ready');
    }
    else {
      console.log('producer is not ready');
    }

**Comment by Lukeout** [comment]
[31mexp       |[0m EventEmitter {
[31mexp       |[0m   ready: false,
[31mexp       |[0m   client:
[31mexp       |[0m    EventEmitter {
[31mexp       |[0m      sslOptions: undefined,
[31mexp       |[0m      ssl: false,
[31mexp       |[0m      connectionString: 'kafka:9092',
[31mexp       |[0m      clientId: 'kafka-node-client',
[31mexp       |[0m      zkOptions: undefined,
[31mexp       |[0m      noAckBatchOptions: undefined,
[31mexp       |[0m      brokers: {},
[31mexp       |[0m      longpollingBrokers: {},
[31mexp       |[0m      topicMetadata: {},
[31mexp       |[0m      topicPartitions: {},
[31mexp       |[0m      correlationId: 0,
[31mexp       |[0m      _socketId: 0,
[31mexp       |[0m      cbqueue: {},
[31mexp       |[0m      brokerMetadata: {},
[31mexp       |[0m      ready: false,
[31mexp       |[0m      zk: EventEmitter { client: [Object], _events: [Object], _eventsCount: 4 },
[31mexp       |[0m      _events:
[31mexp       |[0m       { ready: [Function],
[31mexp       |[0m         brokersChanged: [Function],
[31mexp       |[0m         error: [Function],
[31mexp       |[0m         close: [Function] },
[31mexp       |[0m      _eventsCount: 4 },
[31mexp       |[0m   requireAcks: 1,
[31mexp       |[0m   ackTimeoutMs: 100,
[31mexp       |[0m   partitioner: {} }
[31mexp       |[0m EventEmitter {
[31mexp       |[0m   sslOptions: undefined,
[31mexp       |[0m   ssl: false,
[31mexp       |[0m   connectionString: 'kafka:9092',
[31mexp       |[0m   clientId: 'kafka-node-client',
[31mexp       |[0m   zkOptions: undefined,
[31mexp       |[0m   noAckBatchOptions: undefined,
[31mexp       |[0m   brokers: {},
[31mexp       |[0m   longpollingBrokers: {},
[31mexp       |[0m   topicMetadata: {},
[31mexp       |[0m   topicPartitions: {},
[31mexp       |[0m   correlationId: 0,
[31mexp       |[0m   _socketId: 0,
[31mexp       |[0m   cbqueue: {},
[31mexp       |[0m   brokerMetadata: {},
[31mexp       |[0m   ready: false,
[31mexp       |[0m   zk:
[31mexp       |[0m    EventEmitter {
[31mexp       |[0m      client:
[31mexp       |[0m       Client {
[31mexp       |[0m         domain: null,
[31mexp       |[0m         _events: [Object],
[31mexp       |[0m         _eventsCount: 3,
[31mexp       |[0m         _maxListeners: undefined,
[31mexp       |[0m         connectionManager: [Object],
[31mexp       |[0m         options: [Object],
[31mexp       |[0m         state: [Object] },
[31mexp       |[0m      _events:
[31mexp       |[0m       { init: [Object],
[31mexp       |[0m         brokersChanged: [Function],
[31mexp       |[0m         disconnected: [Object],
[31mexp       |[0m         error: [Function] },
[31mexp       |[0m      _eventsCount: 4 },
[31mexp       |[0m   _events:
[31mexp       |[0m    { ready: [Function],
[31mexp       |[0m      brokersChanged: [Function],
[31mexp       |[0m      error: [Function],
[31mexp       |[0m      close: [Function] },
[31mexp       |[0m   _eventsCount: 4 }

**Comment by hyperlink** [comment]
- The `ready` event is only emitted once. So with the way the code is written you would only send a single message. It would be better to wrap the ready to around your code so it doesn't send a  request until the producer is ready.
- You may want to format your sample code with  markdown. It would make it much more readable
- We use docker to run our tests check out our [docker-compose file](https://github.com/SOHU-Co/kafka-node/blob/master/docker-compose.yml).

**Comment by Lukeout** [comment]
I don't get what you mean. I only want to send messages as they are created with a POST request is made. I am triggering the send on the request.then method. 

I think my problem is with connecting to my kafka container? Or should I move the declaration of kafka into my POST method?

the full code here: 
https://jsfiddle.net/0uak2nwd/

**Comment by hyperlink** [comment]
Since kafka is a dependency you need to ensure that's `ready` before you sending any messages. So you can either put that on top of your code and in your ready handler initialize your route or since you're using promises you can use a Promise wrapper similar to below.

```javascript
'use strict';

var kafka = require('kafka-node');
var Producer = kafka.Producer;
var Client = kafka.Client;

module.exports = function () {
  var args = arguments;
  return new Promise(function (resolve, reject) {
    var client = Client.apply(null, args);
    var producer = new Producer(client, { requireAcks: 1 });

    producer.on('ready', function () {
      resolve(promisedSend);
    });

    producer.on('error', function (err) {
      reject(err);
    });

    function promisedSend(payloads) {
      return new Promise(function (resolve, reject) {
        producer.send(payloads, function (error) {
          if (error) {
            return reject(error);
          }
          resolve();
        })
      });
    }
  });
};
```

Outside your route you can define:

```javascript
var producerPromise = require('./example/producer.init');
var producerReady = producerPromise('127.0.0.1:2181'); // NOTE: this is ZK address!

// inside your request post handler you can call:

producerReady.then (function (producerSend) { return  producerSend([{topic: 'test', partition: 0, messages: 'my message'}]);  });
```
Make sure you update your code to use the zookeeper address and not kafka broker.

**Comment by Lukeout** [comment]
Gonna be honest do not think I follow, 

So I made a producer.js and I put the first chunk of your code in it ver batum (don't know what I would change) keep in mind I am using spotify/kafka (which has Zookeeper and Kafka together so I'm not sure of the settings to alter)

On the top of my route file for the post request I define 

```
var producerPromise = require('../producer.js'); //I used a .js file not a .init file correct?
var producerReady = producerPromise('kafka:9092'); // I changed this to ADVERTISED_HOST:ADVERTISED_PORT
```

Then in my POST METHOD on the request-promise after getting a response I call

```
request(options)
  .then(function(parsedBody) {
producerReady.then (function (producerSend) { return  producerSend([{topic: 'new-listings-topic', partition: 0, messages: parsedBody}]);  });
```

Is this correct? Sorry I'm not trying to bother you I am just confused. This is my first time working with kafka at all. 

I did the above and it doesn't seem to be working :l

**Comment by hyperlink** [comment]
The default kafka port is `9092`. The zookeeper port should be `2181`. Connecting to the kafka  broker won't emit a ready you should provide the zookeeper host to the client instead.

**Comment by Lukeout** [comment]
Would I need to change anything in my docker-compose then? I think the thing tripping me up is using a docker image with zookeeper and kafka bundled together?

I changed: var producerReady = producerPromise('kafka:2181'); But I do not think it's sending to my python consumer as it prints out anything that is being sent to my new-listings-topic. 

I know my python script is connected to my kafka container, but I don't think my node producer is being connected.  

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

**Comment by hyperlink** [comment]
I would recommend you start with a very simple test file that just initializes a producer (see [examples](https://github.com/SOHU-Co/kafka-node/tree/master/example) folder) and see if you can produce to the kafka/zk container. You can use the kafka bin tools to verify messages are being received.
