### ISSUE TITLE
Duplicate messages in HightLevelConsumer

### ISSUE THREAD

**Issue by Satyricon** [SOHU-Co/kafka-node#454]
Here is a simple HighLevelConsumer code for reproducing the problem

```js
'use strict';

const kafka = require('kafka-node');
const client = new kafka.Client('localhost:2181', `idsConsumerClient-${process.pid}`);
const consumer = new kafka.HighLevelConsumer(client, [{topic: 'ids' }], {fetchMaxWaitMs: 10, fetchMaxBytes: 1024});

let messagesCounter = 0;

consumer.on('message', (message) => {
  messagesCounter++;
  console.log(messagesCounter);
});

process.on('SIGINT', function () {
  consumer.close(true, function () {
    console.log("Caught SIGINT, will close Kafka Consumer and exit.");
    process.exit();
  });
});
```

In case when there are at least 8000 messages in kafka topic output for messagesCounter goes up to 16 more items. For example for 10000 messages under the topic I am getting console output from 1 up to 10016. Duplicate messages are appearing around between 7000th and 10000th item and are always random but sequential.

Everything is fine in kafka-node up to version 0.4.0 and this problem starts from version 0.5.0 up to the latest one.

**Comment by Satyricon** [comment]
Another example which prints messages and counter on duplicates

```js
'use strict';

const kafka = require('kafka-node');
const client = new kafka.Client('localhost:2181', `idsConsumerClient-${process.pid}`);
const consumer = new kafka.HighLevelConsumer(client, [{topic: 'ids' }], {fetchMaxWaitMs: 10, fetchMaxBytes: 1024});

let messagesCounter = 0;
let itemsMap = {};

consumer.on('message', (message) => {
  messagesCounter++;
  if (itemsMap[message.value]) {
    console.log(`DUPLICATE ON message: ${message.value} and counter: ${messagesCounter}`);
  } else {
    itemsMap[message.value] = 1;
  }
});

process.on('SIGINT', function () {
  consumer.close(true, function () {
    console.log("Caught SIGINT, will close Kafka Consumer and exit.");
    process.exit();
  });
});
```

And output example I am getting is

```
DUPLICATE ON message: 35457fe8-6daf-11e6-a6ac-935a4853472d and counter: 9329
DUPLICATE ON message: 3544227d-6daf-11e6-a6ac-935a4853472d and counter: 9330
DUPLICATE ON message: 35450ce4-6daf-11e6-a6ac-935a4853472d and counter: 9331
DUPLICATE ON message: 35433660-6daf-11e6-a6ac-935a4853472d and counter: 9332
DUPLICATE ON message: 3545316d-6daf-11e6-a6ac-935a4853472d and counter: 9333
DUPLICATE ON message: 3544e611-6daf-11e6-a6ac-935a4853472d and counter: 9334
DUPLICATE ON message: 354420a3-6daf-11e6-a6ac-935a4853472d and counter: 9335
DUPLICATE ON message: 354559b7-6daf-11e6-a6ac-935a4853472d and counter: 9336
DUPLICATE ON message: 35435ebb-6daf-11e6-a6ac-935a4853472d and counter: 9337
DUPLICATE ON message: 35455978-6daf-11e6-a6ac-935a4853472d and counter: 9338
DUPLICATE ON message: 3543fab3-6daf-11e6-a6ac-935a4853472d and counter: 9339
DUPLICATE ON message: 35455b40-6daf-11e6-a6ac-935a4853472d and counter: 9340
DUPLICATE ON message: 35442224-6daf-11e6-a6ac-935a4853472d and counter: 9341
DUPLICATE ON message: 35438568-6daf-11e6-a6ac-935a4853472d and counter: 9342
DUPLICATE ON message: 3544bfa0-6daf-11e6-a6ac-935a4853472d and counter: 9343
DUPLICATE ON message: 3544e5d3-6daf-11e6-a6ac-935a4853472d and counter: 9344
```

**Comment by hyperlink** [comment]
Do you have the code the produces this? It would help to create a test case with.

Does this issue happen if your `fetchMaxBytes` was larger? The default we have in the examples is `1024*1024`.

**Comment by Satyricon** [comment]
Producer is Scala application, but it just adds uuid's to kafka topic (as you can see from my previous comment message value is just a uuid string). I tried with smaller `fetchMaxBytes` values, but not bigger ones as my message is just a uuid and it was still giving some duplicates even though less of them. I can try it tomorrow with bigger values.

**Comment by hyperlink** [comment]
I'll see if I can reproduce this. Thanks!

**Comment by Satyricon** [comment]
I made couple of tests with 20.000 messages in kafka topic and different fetchMaxBytes values. Here are some observations:

fetchMaxBytes:   1*1024 - 20016 messages received
fetchMaxBytes: 10*1024 - 20165 messages received
fetchMaxBytes: 11*1024 - 20181 messages received
fetchMaxBytes: 12*1024 - 20198 messages received
fetchMaxBytes: 12300 - 20198 messages received
fetchMaxBytes: 12350 - 20199 messages received
fetchMaxBytes: 12370 - 20199 messages received
fetchMaxBytes: 12371 - 20199/20000 messages received
fetchMaxBytes: 12372 - 20000 messages received
fetchMaxBytes: 12373 - 20000 messages received
fetchMaxBytes: 12375 - 20000 messages received
fetchMaxBytes: 12385 - 20000 messages received
fetchMaxBytes: 12400 - 20000 messages received
fetchMaxBytes: 12500 - 20000 messages received
fetchMaxBytes: 12.5*1024 - 20000 messages received
fetchMaxBytes: 13*1024 - 20000 messages received
fetchMaxBytes: 15*1024 - 20000 messages received
fetchMaxBytes: 20*1024 - 20000 messages received
fetchMaxBytes: 50*1024 - 20000 messages received
fetchMaxBytes: 100*1024 - 20000 messages received
fetchMaxBytes: 1024*1024 - 20000 messages received

Tests were done with kafka-node version 0.5.0.

So in case of 20000 messages in kafka topic there is a "magic" number 12371 when duplicate keys appear/disappear.

**Comment by Satyricon** [comment]
any update on this one?

**Comment by hyperlink** [comment]
I found one case that's caused by queued rebalance after registering itself to the consumer group. The fix is not straightforward as I expected since it also causes intermittent failures with a rebalance test. This was added in `0.5.4` so I am not sure it's the same cause. I will try to fix this case first and circle back to see if it still happens.

**Comment by hyperlink** [comment]
@Satyricon can you point your `kafka-node` module to `SOHU-Co/kafka-node#fix-unscheduled-rebalance` and see if you're still running into this issue?
