### ISSUE TITLE
It just doesn't work

### ISSUE THREAD

**Issue by groyee** [SOHU-Co/kafka-node#468]
I wanted to make a list of the things that are not working but the list is really too long. 

Worst thing is that  I wrote a consumer and it worked great. I stopped for several minutes and without modifying anything else it just stopped working. Not retrieving any messages. And then one day it suddenly works again. So sometimes it works and sometimes it doesn't.

Just out of curiosity I wrote another consumer in Python to see if works when the node doesn't. And well, it does... I am not a big fan of Python but I guess I have no choice

Even when it consumed messages I ran Kafka command to see if it actually consumed it:

bin/kafka-run-class.sh kafka.tools.ConsumerOffsetChecker --zookeeper kafka-prod-1:2181  --topic fenout-test-prod --group kafka-node-group

And it showed me like it didn't produce it at all.

Pid Offset          logSize         Lag             Owner
kafka-node-group fenout-test-prod               0   140             917             777             none
kafka-node-group fenout-test-prod               1   141             918             777             none
kafka-node-group fenout-test-prod               2   141             918             777             none
kafka-node-group fenout-test-prod               3   140             918             778             none
kafka-node-group fenout-test-prod               4   140             918             778             none
kafka-node-group fenout-test-prod               5   140             918             778             none
kafka-node-group fenout-test-prod               6   140             918             778             none
kafka-node-group fenout-test-prod               7   140             918             778             none
kafka-node-group fenout-test-prod               8   140             917             777             none
kafka-node-group fenout-test-prod               9   140             917             777             none

I ran the producer again to read thousands messages and got the same result.

Pid Offset          logSize         Lag             Owner
kafka-node-group fenout-test-prod               0   140             917             777             none
kafka-node-group fenout-test-prod               1   141             918             777             none
kafka-node-group fenout-test-prod               2   141             918             777             none
kafka-node-group fenout-test-prod               3   140             918             778             none
kafka-node-group fenout-test-prod               4   140             918             778             none
kafka-node-group fenout-test-prod               5   140             918             778             none
kafka-node-group fenout-test-prod               6   140             918             778             none
kafka-node-group fenout-test-prod               7   140             918             778             none
kafka-node-group fenout-test-prod               8   140             917             777             none
kafka-node-group fenout-test-prod               9   140             917             777             none

And my autocommit is true. 

Is this a production tested driver?

**Comment by sanear** [comment]
We have been using this in production for about 18 months at my company. If it has been "production tested," it certainly shouldn't have passed. We have had nothing but problems - some similar to those you describe, and some of our own (the latest is seemingly unprompted offset resets, causing our processors to requeue tens of thousands of messages - just like we wanted).

I'd go with the Python of Java drivers if I were you. Unfortunately for me, I'm shackled to the thing right now, but we are trying to get off of it as soon as possible.

**Comment by TomDmitriev** [comment]
I was just about to create a similar issue when I encountered this one. Moreover, it looks like there is no robust and complete nodejs kafka client implementation at the moment. I ended up using https://github.com/LivePersonInc/kafka-java-bridge for a `HighLevelConsumer` and this library for a `Producer`.
