### ISSUE TITLE
Leader is not elected when one of the three brokers are down

### ISSUE THREAD

**Issue by rakesh190** [SOHU-Co/kafka-node#469]
Hi,
I'm using three brokers with 5 partitions for my topic to push messages to kafka queue, but when of the leader is going down, the leadership to another broker is not mitigated, is there any approach to tackle this situations, I've been working on this from very long time but couldn't crack it.

**Comment by hyperlink** [comment]
Do you get an error emitted from the module when this happens?

**Comment by rakesh190** [comment]
Yes, it says leader is not available error even though other broker is up. It is still trying to connect the one which is down, out of five partitions one broker is allocated to one partition and rest four partitions allocated to other brokers. 
![broker error](https://cloud.githubusercontent.com/assets/14300554/18795141/f7adfc36-8177-11e6-966d-460ce834c254.png)

**Comment by rakesh190** [comment]
I have manually brought down one of the brokers out of three and when I restarted I could see 'client is ready' and 'producer is ready' from 'client.on' and 'producer.on' functions but when I'm sending a message I'm getting leader not available error. I simulated this scenario to test my service, how it will behave when one of the brokers are down and I got this error.
![leadernot](https://cloud.githubusercontent.com/assets/14300554/18803182/9d480fea-81a2-11e6-8a30-964978094e5b.png)

**Comment by hyperlink** [comment]
Re reconnecting there should be a zookeeper `brokerChanged` event that fires to tell the client to refresh it's broker list and tells the producer to clear it's metadata.

How does kafka's console producer behave when you take down a broker?

**Comment by rakesh190** [comment]
Below are the producer objects when one of the broker is down and getting leader not available error and when all the brokers are up and messages are sending:

**When one of the broker is down:**
EventEmitter {
  ready: true,
  client:
   EventEmitter {
     sslOptions: undefined,
     ssl: false,
     connectionString: '173.36.80.223:2181,173.36.80.148:2181',
     clientId: 'kafka-node-client',
     zkOptions: undefined,
     noAckBatchOptions: undefined,
     brokers: { '173.36.80.148:9092': [Object] },
     longpollingBrokers: {},
     topicMetadata: {},
     topicPartitions: {},
     correlationId: 1,
     _socketId: 1,
     cbqueue: {},
     brokerMetadata: { '1': [Object] },
     ready: true,
     zk:
      EventEmitter {
        client: [Object],
        _events: [Object],
        _eventsCount: 3,
        inited: true },
     _events:
      { ready: [Object],
        error: [Object],
        brokersChanged: [Function],
        close: [Function] },
     _eventsCount: 4,
     brokerProfiles: { '173.36.80.148:9092': [Object] } },
  requireAcks: 1,
  ackTimeoutMs: 100,
  partitioner: { c: 0 },
  _events:
   { ready: [Function],
     brokersChanged: [Function],
     error: [Function] },
  _eventsCount: 3 }

**When all brokers are up and Messages are pushing**
EventEmitter {
  ready: true,
  client:
   EventEmitter {
     sslOptions: undefined,
     ssl: false,
     connectionString: '173.36.80.223:2181,173.36.80.148:2181',
     clientId: 'kafka-node-client',
     zkOptions: undefined,
     noAckBatchOptions: undefined,
     brokers:
      { '173.36.80.148:9092': [Object],
        '173.36.80.223:9092': [Object] },
     longpollingBrokers: {},
     topicMetadata: { 'decision-service-logs': [Object] },
     topicPartitions: { 'decision-service-logs': [Object] },
     correlationId: 2,
     _socketId: 2,
     cbqueue: {},
     brokerMetadata: { '1': [Object], '2': [Object] },
     ready: true,
     zk:
      EventEmitter {
        client: [Object],
        _events: [Object],
        _eventsCount: 3,
        inited: true },
     _events:
      { ready: [Object],
        error: [Object],
        brokersChanged: [Function],
        close: [Function] },
     _eventsCount: 4,
     brokerProfiles:
      { '173.36.80.148:9092': [Object],
        '173.36.80.223:9092': [Object] } },
  requireAcks: 1,
  ackTimeoutMs: 100,
  partitioner: { c: 0 },
  _events:
   { ready: [Function],
     brokersChanged: [Function],
     error: [Function] },
  _eventsCount: 3 }

**Comment by Black-Star** [comment]
+1

**Comment by rakesh190** [comment]
@hyperlink @Black-Star  is there a potential solution or approach to tackle with this particular scenario?

**Comment by hyperlink** [comment]
The producer should eventually recover after it loads the topic metadata. It's up to the send messages resend any failed messages through the producer.

Are you seeing behavior where it's not recovering eventually?

**Comment by rakesh190** [comment]
Nope, it is behaving the same way, it is still trying to reconnect with the broker that has been brought down even though other brokers are up, if you can observe  topicMetadata: {}, topicPartitions: {} are not getting refreshed.  When I'm doing clientProducers.brokerMetadata broker metadata is getting refreshed  but not topicMetadata and topicPartitions.

**Comment by hyperlink** [comment]
Hmm then it's possible this scenario wasn't tested. I've focused a lot of effort on making the highLevelConsumer recoverable I haven't tested producer myself.

So when this happens you should halt sending messages and manually fire of a request to `client.loadMetadataForTopics`.

**Comment by rakesh190** [comment]
Hey @hyperlink , thanks for your help and time. 
Would you mind sharing a sample arguments for the below function i.e. topics and cb ?

client.loadMetadataForTopics(topics, cb)

**Comment by hyperlink** [comment]
Actually now that I think about it's better if you called `client.refreshMetadata(topics, cb)` instead. And the `topics` argument is just an array of topics.

**Comment by rakesh190** [comment]
I have used the above function in following way but it is throwing me an error:

clientProducers.refreshMetadata(['decision-service-logs'],function(err, rs){
            if(err){
                console.log(err);
            }else{
                console.log(rs);
            }
        });

![kafkabrokererror](https://cloud.githubusercontent.com/assets/14300554/18900527/da361c92-84f6-11e6-9d2a-266a3dd60e03.png)

**Comment by hyperlink** [comment]
@rakesh190 could you try calling `refreshMetadata` after you receive a `brokersChanged` event from the `client`?  This will ensure that the module has access to the latest list of brokers from zookeeper before you attempt to load the metadata.

**Comment by rakesh190** [comment]
@hyperlink, thanks a lot for the suggestions and I really appreciate you help in resolving this particular issue.
I have used the brokersChanged event in the following way:
var clientProducers = new kafka.Client("<kafka broker values>");
clientProducers.on('brokersChanged', function(err){
            console.log('hii')
            if(err){
                console.log(err);
            }else{
                console.log('Brokers changed');
            }
        })
Even though I simulate a situation on bringing down the one of the brokers, this particular event is not triggering.

**Comment by rakesh190** [comment]
Any update on this bug?

**Comment by hyperlink** [comment]
Sorry @rakesh190 I haven't had a chance to look at it yet. Was busy putting out 1.0.0 with the new Consumer Group. I'm hoping to look at this and other producer related issues for the next release.

**Comment by gogorush** [comment]
I m having the same issue here. Is there any update on this issue?

**Comment by hyperlink** [comment]
I'm hoping to take a look at this in a week or two.

**Comment by hyperlink** [comment]
Possibly be fixed with #580
