### ISSUE TITLE
Consumer groups

### ISSUE THREAD

**Issue by gangleri** [SOHU-Co/kafka-node#47]
Hi, I'm trying to run the following code:

``` js
'use strict';

var kafka = require('kafka-node');
var client = new kafka.Client('127.0.0.1:2181/');

var consumer = new kafka.Consumer(client, [{topic: 'test-topic'}], {groupId:'test-group'});

consumer.on('message', function(message){
  console.log('*********** On Message ********************');
  console.dir(message);
});
```

When I run two instances of this code I see the message being picked up by both consumers, even though I specify a consumer group. My understanding is that messages will just go to one consumer in the group.

Do you see what I'm doing wrong?

**Comment by Ankur-Jat** [comment]
This is still happening. How do we solve this ?
