### ISSUE TITLE
Support Binary Data

### ISSUE THREAD

**Issue by vanthome** [SOHU-Co/kafka-node#470]
While Kafka supports binary data, this module only seems to support text based data.
It would be great if you could support binary data based on streams and buffer.

**Comment by hyperlink** [comment]
Have you tried setting the `encoding` option to `buffer` ?

**Comment by vanthome** [comment]
will try and let you know

**Comment by pcothenet** [comment]
I've been using this module with Avro for a couple months, works great.

**Comment by hyperlink** [comment]
@vanthome did setting the encoding option to buffer work for you?

**Comment by MedGhassen** [comment]
@hyperlink @vanthome  I have tried setting the Encoding Option in the Consumer to 'buffer' and it is working fine . Thank you very much.
It could be very nice to  enhance the documentation by saying that it is possible to transfer binary data through buffers by setting the encoding option of the Consumer and that NO prior setting for the producer are required . 
In other word that it does not depend on the producer's encoding but it depends on the consumer's encoding . 
Thank you very much :D

**Comment by kevinswarner** [comment]
Is the encoding option available for the ConsumerGroup?
