### ISSUE TITLE
consumer / (high level consumer) doesn't work over SSL

### ISSUE THREAD

**Issue by deldim1** [SOHU-Co/kafka-node#478]
Kafka 0.9 supports SSL in NewConsumer API only.
looks like current consumer implementation in kafka-node is based on old API. 
:(

**Comment by hyperlink** [comment]
What makes you say it doesn't support it? We've been using SSL and highLevelConsumer for awhile now.

In any case I have a PR up for the new consumer hope to have it released soon.

**Comment by deldim1** [comment]
Hi,
I disabled plain text mode on kafka server and  configured SSL.
I have number of java clients connecting to this server and one node js
uses kafka-node.
All my java clients use newConsumer API and connect to kafka machine
~kafkahost:9092


But kafka-node clients connect  to the zookeeper:2181.
All kafka-node produsers work well,
But kafka-node consumers can't receive messages.

Before switching to SSL everything worked fine.


Thank you.
Daniel.

**Comment by hyperlink** [comment]
Could you show some example code on how you connect the consumer?

There's really no change in kafka API to use SSL-- it's just connecting to a different port with a TLS socket.

**Comment by deldim1** [comment]
Hi,
something like that:
.....

    function initConsumer(topic, f) {
        logger.info("initConsumer", topic);
        var Consumer = kafka.Consumer,
            client = new
kafka.Client(connectionUrl,"something",undefined,undefined,{
rejectUnauthorized: false } ),
            consumer = new Consumer(
                client,
                [{topic: topic, partition: 0}],
                {
                    autoCommit: false
                }
            );
        consumer.on('message', function (message) {
            logger.debug('onMessage', message);
            f('message', message);

        });
        consumer.on('error', function (err) {
            logger.error('onError', err);
            handleKafkaError(err);
        });

        kafkaStatus = "Connected";
        logger.info("Consumer for topic ", topic, "] was created");
    }

............

**Comment by deldim1** [comment]
full code example:

config.js:
kafkaConnectionUrl = 'xxx.xxx.xxx.xxx:2181';


kafkaManager.js:

var kafkaManager = (function () {
    require('../config.js')
    var log4js = require('./logger.js');
    var logger = log4js.getModuleLogger();
    var kafka = require('kafka-node');
    var socket;
    var setSockeIO = function (o) {
        socket = o;
    }
    function handleKafkaError(error) {
        var code = error.code;
        var message = error.message;
        if (error.code == "ETIMEDOUT" ||
            error.code == "ECONNREFUSED" ||
            error.code == "ECONNRESET" ||
            message == "Could not find a broker") {
            if (kafkaStatus != "Disconnected") {
                kafkaStatus = "Disconnected";
                socket.broadcast();
            }
        }
        logger.error("ERROR: " + error.message);
    };


    function initConsumer(topic, f) {
        logger.info("initConsumer", topic);
        var Consumer = kafka.Consumer,
            client = new kafka.Client(kafkaConnectionUrl,
                undefined,
                undefined,
                undefined,
                {
                    rejectUnauthorized: false
                }),
            consumer = new Consumer(
                client,
                [{topic: topic, partition: 0}],
                {
                    autoCommit: false
                }
            );
        consumer.on('message', function (message) {
            logger.debug('onMessage', message);
            kafkaStatus = "Connected";
            f('message', message);

        });
        consumer.on('error', function (err) {
            logger.error('onError', err);
            handleKafkaError(err);
        });

        logger.info("Consumer for topic ", topic, "] was created");
    }

    var sendMessage = function (topic, message) {
        logger.debug("sendMessage", topic, message);
        var argv = require('optimist').argv;
        var p = argv.p || 0;
        var a = argv.a || 0;

        var client = new kafka.Client(kafkaConnectionUrl,
            undefined,
            undefined,
            undefined,
            {
                rejectUnauthorized: false
            });
        var Producer = kafka.Producer;
        var producer = new Producer(client, {requireAcks: 1});

        producer.on('ready', function () {
            try {
                producer.send([
                    {topic: topic, partition: p, messages: [message], attributes: a}
                ], function (err, result) {
                    if (err) {
                        logger.error(err);
                    } else {
                        logger.debug(result);
                    }
                });
            } catch (err) {
                logger.error("Error on producer 'ready' ", err);
            }
            logger.debug("Producer sending: " + message);
        });

        producer.on('error', function (err) {
                logger.error('Producer ready - error', err);
            }
        );

    }

    return {
        initConsumer: initConsumer,
        sendMessage: sendMessage,
        setSocketIO: setSockeIO,
    };
}());

module.exports = kafkaManager;

**Comment by hyperlink** [comment]
After the client is ready could you `console.log` the contents of `client.brokerProfiles` and `client.ssl` ?

Also what version of kafka are you using?

**Comment by deldim1** [comment]
client.ssl =true
I use Kafka server 0.9.
And the broker . list I will check. 



Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Xiaoxin Lu <notifications@github.com> Date: 10/6/16  20:58  (GMT+02:00) To: SOHU-Co/kafka-node <kafka-node@noreply.github.com> Cc: deldim1 <daniel.delion@gmail.com>, Author <author@noreply.github.com> Subject: Re: [SOHU-Co/kafka-node] consumer / (high level consumer) doesn't work over SSL (#478) 
After the client is ready could you console.log the contents of client.brokerProfiles and client.ssl ?

Also what version of kafka are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SOHU-Co/kafka-node","title":"SOHU-Co/kafka-node","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SOHU-Co/kafka-node"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hyperlink in #478: After the client is ready could you `console.log` the contents of `client.brokerProfiles` and `client.ssl` ?\r\n\r\nAlso what version of kafka are you using?"}],"action":{"name":"View Issue","url":"https://github.com/SOHU-Co/kafka-node/issues/478#issuecomment-252040407"}}}

**Comment by deldim1** [comment]
Finally i got it work.
The client.brokerProfiles was undefined.

**Comment by rajashekhargundeti** [comment]
Here is my consumer code, but not working... can u help in correcting this
```
var kafka = require('kafka-node');
var Consumer = kafka.Consumer;
var Offset = kafka.Offset;
var Client = kafka.Client;

const environment = process.env.APP_ENV || 'development';
const action = "consume";
const connectorType = "direct";
const configs = require("./config/" + environment);

const config = configs[action][connectorType];

var topic = config.topic;

var client = new Client(config.brokers,null,null,null,{  
  
    certFile: config.cert,
    keyFile: config.key
  
});
var topics = [
    {topic: topic}
];
var options = { autoCommit: false, fetchMaxWaitMs: 1000, fetchMaxBytes: 1024 * 1024 };

var consumer = new Consumer(client, topics, options);
var offset = new Offset(client);

consumer.on('message', function (message) {
  console.log(message);
});

consumer.on('error', function (err) {
  console.log('error', err);
});

/*
* If consumer get `offsetOutOfRange` event, fetch data from the smallest(oldest) offset
*/
consumer.on('offsetOutOfRange', function (topic) {
  topic.maxNum = 2;
  offset.fetch([topic], function (err, offsets) {
    if (err) {
      return console.error(err);
    }
    var min = Math.min(offsets[topic.topic][topic.partition]);
    consumer.setOffset(topic.topic, topic.partition, min);
  });
});
```

**Comment by hyperlink** [comment]
If you are passing in kafka broker hosts you should use `KafkaClient` instead of `Client`.

**Comment by b1swa** [comment]
@deldim1 Could you please explain how you resolved  client.brokerProfiles when it was undefined
