### ISSUE TITLE
FailedToRebalanceConsumerError: Exception: NODE_EXISTS[-110]

### ISSUE THREAD

**Issue by yatendernitk** [SOHU-Co/kafka-node#487]
kafka-node:zookeeper Node: /consumers/my-group/ids/my-consumer-id-3 was created. +0ms
  kafka-node:HighLevelConsumer rebalance() my-consumer-id-3 is rebalancing: false ready: false +2ms
  kafka-node:HighLevelConsumer Deregistered listeners my-consumer-id-3 +2ms
  kafka-node:HighLevelConsumer Registered listeners my-consumer-id-3 +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 is attempting to rebalance +2ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 stopping data read during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 assembling data for rebalance +6ms
  kafka-node:zookeeper Children are: ["my-consumer-id-3"]. +2ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 releasing current partitions during rebalance +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 determining the partitions to own during rebalance +1ms
  kafka-node:HighLevelConsumer consumerPerTopicMap.consumerTopicMap {"my-consumer-id-3":["test"]} +0ms
  kafka-node:HighLevelConsumer newTopicPayloads [{"topic":"test","partition":"0","offset":0,"maxBytes":1048576,"metadata":"m"}] +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 gaining ownership of partitions during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 rebalance attempt failed +7ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 is attempting to rebalance +141ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 stopping data read during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 assembling data for rebalance +5ms
  kafka-node:zookeeper Children are: ["my-consumer-id-3"]. +2ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 releasing current partitions during rebalance +3ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 determining the partitions to own during rebalance +0ms
  kafka-node:HighLevelConsumer consumerPerTopicMap.consumerTopicMap {"my-consumer-id-3":["test"]} +0ms
  kafka-node:HighLevelConsumer newTopicPayloads [{"topic":"test","partition":"0","offset":0,"maxBytes":1048576,"metadata":"m"}] +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 gaining ownership of partitions during rebalance +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 rebalance attempt failed +21ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 is attempting to rebalance +282ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 stopping data read during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 assembling data for rebalance +2ms
  kafka-node:zookeeper Children are: ["my-consumer-id-3"]. +2ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 releasing current partitions during rebalance +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 determining the partitions to own during rebalance +0ms
  kafka-node:HighLevelConsumer consumerPerTopicMap.consumerTopicMap {"my-consumer-id-3":["test"]} +0ms
  kafka-node:HighLevelConsumer newTopicPayloads [{"topic":"test","partition":"0","offset":0,"maxBytes":1048576,"metadata":"m"}] +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 gaining ownership of partitions during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 rebalance attempt failed +7ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 is attempting to rebalance +410ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 stopping data read during rebalance +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 assembling data for rebalance +2ms
  kafka-node:zookeeper Children are: ["my-consumer-id-3"]. +2ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 releasing current partitions during rebalance +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 determining the partitions to own during rebalance +0ms
  kafka-node:HighLevelConsumer consumerPerTopicMap.consumerTopicMap {"my-consumer-id-3":["test"]} +0ms
  kafka-node:HighLevelConsumer newTopicPayloads [{"topic":"test","partition":"0","offset":0,"maxBytes":1048576,"metadata":"m"}] +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 gaining ownership of partitions during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 rebalance attempt failed +7ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 is attempting to rebalance +1s
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 stopping data read during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 assembling data for rebalance +3ms
  kafka-node:zookeeper Children are: ["my-consumer-id-3"]. +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 releasing current partitions during rebalance +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 determining the partitions to own during rebalance +1ms
  kafka-node:HighLevelConsumer consumerPerTopicMap.consumerTopicMap {"my-consumer-id-3":["test"]} +0ms
  kafka-node:HighLevelConsumer newTopicPayloads [{"topic":"test","partition":"0","offset":0,"maxBytes":1048576,"metadata":"m"}] +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 gaining ownership of partitions during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 rebalance attempt failed +7ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 is attempting to rebalance +1s
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 stopping data read during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 assembling data for rebalance +4ms
  kafka-node:zookeeper Children are: ["my-consumer-id-3"]. +5ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 releasing current partitions during rebalance +2ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 determining the partitions to own during rebalance +0ms
  kafka-node:HighLevelConsumer consumerPerTopicMap.consumerTopicMap {"my-consumer-id-3":["test"]} +0ms
  kafka-node:HighLevelConsumer newTopicPayloads [{"topic":"test","partition":"0","offset":0,"maxBytes":1048576,"metadata":"m"}] +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 gaining ownership of partitions during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 rebalance attempt failed +5ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 is attempting to rebalance +1s
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 stopping data read during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 assembling data for rebalance +4ms
  kafka-node:zookeeper Children are: ["my-consumer-id-3"]. +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 releasing current partitions during rebalance +2ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 determining the partitions to own during rebalance +0ms
  kafka-node:HighLevelConsumer consumerPerTopicMap.consumerTopicMap {"my-consumer-id-3":["test"]} +0ms
  kafka-node:HighLevelConsumer newTopicPayloads [{"topic":"test","partition":"0","offset":0,"maxBytes":1048576,"metadata":"m"}] +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 gaining ownership of partitions during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 rebalance attempt failed +10ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 is attempting to rebalance +1s
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 stopping data read during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 assembling data for rebalance +3ms
  kafka-node:zookeeper Children are: ["my-consumer-id-3"]. +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 releasing current partitions during rebalance +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 determining the partitions to own during rebalance +0ms
  kafka-node:HighLevelConsumer consumerPerTopicMap.consumerTopicMap {"my-consumer-id-3":["test"]} +0ms
  kafka-node:HighLevelConsumer newTopicPayloads [{"topic":"test","partition":"0","offset":0,"maxBytes":1048576,"metadata":"m"}] +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 gaining ownership of partitions during rebalance +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 rebalance attempt failed +7ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 is attempting to rebalance +1s
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 stopping data read during rebalance +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 assembling data for rebalance +2ms
  kafka-node:zookeeper Children are: ["my-consumer-id-3"]. +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 releasing current partitions during rebalance +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 determining the partitions to own during rebalance +0ms
  kafka-node:HighLevelConsumer consumerPerTopicMap.consumerTopicMap {"my-consumer-id-3":["test"]} +0ms
  kafka-node:HighLevelConsumer newTopicPayloads [{"topic":"test","partition":"0","offset":0,"maxBytes":1048576,"metadata":"m"}] +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 gaining ownership of partitions during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 rebalance attempt failed +5ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 is attempting to rebalance +1s
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 stopping data read during rebalance +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 assembling data for rebalance +2ms
  kafka-node:zookeeper Children are: ["my-consumer-id-3"]. +2ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 releasing current partitions during rebalance +2ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 determining the partitions to own during rebalance +0ms
  kafka-node:HighLevelConsumer consumerPerTopicMap.consumerTopicMap {"my-consumer-id-3":["test"]} +0ms
  kafka-node:HighLevelConsumer newTopicPayloads [{"topic":"test","partition":"0","offset":0,"maxBytes":1048576,"metadata":"m"}] +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 gaining ownership of partitions during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 rebalance attempt failed +27ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 is attempting to rebalance +1s
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 stopping data read during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 assembling data for rebalance +3ms
  kafka-node:zookeeper Children are: ["my-consumer-id-3"]. +1ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 releasing current partitions during rebalance +2ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 determining the partitions to own during rebalance +0ms
  kafka-node:HighLevelConsumer consumerPerTopicMap.consumerTopicMap {"my-consumer-id-3":["test"]} +1ms
  kafka-node:HighLevelConsumer newTopicPayloads [{"topic":"test","partition":"0","offset":0,"maxBytes":1048576,"metadata":"m"}] +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 gaining ownership of partitions during rebalance +0ms
  kafka-node:HighLevelConsumer HighLevelConsumer my-consumer-id-3 rebalance attempt failed +4ms

---

my consumer code

---

var kafka = require('kafka-node'),
    HighLevelConsumer = kafka.HighLevelConsumer,
    client = new kafka.Client(),
consumer = new HighLevelConsumer(
    client,
    [
        { topic: topic[0] }
    ],
    {
        groupId: 'my-group',
        id: 'my-consumer-id-' + parseInt(Math.random() \* 10),
    }
);

**Comment by yatendernitk** [comment]
I have attached the debug logs .. while restarting sometimes it comes please help me is there something I am doing it wrong or this is known issue.

**Comment by yatendernitk** [comment]
process.on('SIGINT', function () {
    highLevelConsumer.close(true, function () {
        process.exit();
    });
});

this also I have added in my code

**Comment by hyperlink** [comment]
Could you try the new [ConsumerGroup](https://github.com/SOHU-Co/kafka-node#consumergroup)? It works very similarly to HighLevelConsumer but doesn't suffer from issues dealing with Zookeeper.

**Comment by SimenB** [comment]
Seeing the same issue (I think) after going from 0.5.7 to 1.0.5. We are using kafka 0.8, so using ConsumerGroup isn't an option

**Comment by gogorush** [comment]
@hyperlink I run into the same issue with this high level consumer rebalance issue. So I changed into ConsumerGroup with kafka 0.9. But when I run my application on several machines, only the first one can consumer data from kafka. Is that a bug or did I do anything wrong ?

**Comment by hyperlink** [comment]
If you have a good stacktrace you can find out which zookeeper node exists. It usually happens during registration or rebalance.

**Comment by SimenB** [comment]
@hyperlink The stack trace is async, not alot of help

```
FailedToRebalanceConsumerError: Exception: NODE_EXISTS[-110]
    at new FailedToRebalanceConsumerError (/Users/simbekkh/repos/finnlet-server/node_modules/@finn-no/kafka-events/node_modules/kafka-node/lib/errors/FailedToRebalanceConsumerError.js:11:9)
    at /Users/simbekkh/repos/finnlet-server/node_modules/@finn-no/kafka-events/node_modules/kafka-node/lib/highLevelConsumer.js:180:39
    at /Users/simbekkh/repos/finnlet-server/node_modules/@finn-no/kafka-events/node_modules/kafka-node/lib/highLevelConsumer.js:474:9
    at /Users/simbekkh/repos/finnlet-server/node_modules/async/lib/async.js:726:13
    at /Users/simbekkh/repos/finnlet-server/node_modules/async/lib/async.js:52:16
    at /Users/simbekkh/repos/finnlet-server/node_modules/async/lib/async.js:264:21
    at /Users/simbekkh/repos/finnlet-server/node_modules/async/lib/async.js:44:16
    at /Users/simbekkh/repos/finnlet-server/node_modules/async/lib/async.js:723:17
    at /Users/simbekkh/repos/finnlet-server/node_modules/async/lib/async.js:167:37
    at /Users/simbekkh/repos/finnlet-server/node_modules/@finn-no/kafka-events/node_modules/kafka-node/lib/highLevelConsumer.js:455:13
    at /Users/simbekkh/repos/finnlet-server/node_modules/async/lib/async.js:52:16
    at /Users/simbekkh/repos/finnlet-server/node_modules/async/lib/async.js:264:21
    at /Users/simbekkh/repos/finnlet-server/node_modules/async/lib/async.js:44:16
    at /Users/simbekkh/repos/finnlet-server/node_modules/@finn-no/kafka-events/node_modules/kafka-node/lib/highLevelConsumer.js:447:19
    at /Users/simbekkh/repos/finnlet-server/node_modules/async/lib/async.js:726:13
    at /Users/simbekkh/repos/finnlet-server/node_modules/async/lib/async.js:52:16
```

**Comment by SimenB** [comment]
Is it possible to get better traces?

**Comment by hyperlink** [comment]
Looks like it failed at `addPartitionOwnership` where it checks the partition wasn't owned and then  tries to add ownership in zookeeper but as it does zookeeper is saying it's already there.

I would check that zookeeper path it's trying to create and see if it's possible to track which session/instance owned that node.

I don't know of a way to get better stack traces but you can get longer stack traces if you increase your `Error.stackTraceLimit`.

**Comment by SimenB** [comment]
We never had this problem using 0.5.7. Is this `node-kafka` surfacing an error it swallowed before, or is it an actual regression?

**Comment by hyperlink** [comment]
Are you seeing the issue in 0.5.8 or 0.5.9?

We're still using the highLevelConsumer in production and haven't seen these issues though I can double check our logs.

**Comment by SimenB** [comment]
It's a bit hard to say, it doesn't happen all the time.

The last time it happened, 2 out of 4 replicas failed (but after deleting the pods, the new ones were fine). After a deploy just now, all 4 were fine.

**Comment by UnsignedInt8** [comment]
I have the same issue. No any ideas? @hyperlink

**Comment by hyperlink** [comment]
No idea though I encourage everyone to use `ConsumerGroup`. And once Kafka client is released to use that along with the `ConsumerGroup` so these zookeeper errors could be avoided.
