### ISSUE TITLE
Wrong commit order when using autoCommit=false in HighlevelConsumer

### ISSUE THREAD

**Issue by postmann** [SOHU-Co/kafka-node#488]
I'm using a HighlevelProducer and HighlevelConsumer to send and receive Messages. The HighlevelConsumer is configured with autoCommit=false as I want to commit Messages only when it was produced successfully. The problem is, that the first message never really gets commited.

Example:
* Send Messages 1-10.
* Receive Message 1
* Receive Message 2
* Commit Message 2
* ...
* Receive Message 10
* Commit Message 10
* Commit Message 1

If I restart my Consumer, all messages from 1 to 10 are processed again. Only if I send new messages to the consumer, the old messages get committed. This happens for any number of messages.

My Code reads as follows:
```
var kafka = require('kafka-node'),
    HighLevelConsumer = kafka.HighLevelConsumer,
    client = new kafka.Client("localhost:2181/");
consumer = new HighLevelConsumer(
    client,
    [
        { topic: 'mytopic' }
    ],
    {
        groupId: 'my-group',
        id: "my-consumer-1",
        autoCommit: false
    }
);

consumer.on('message', function (message) {
    console.log("consume: " + message.offset);
    consumer.commit(function (err, data) {
        console.log("commited:" + message.offset);
    });
    console.log("consumed:" + message.offset);
});

process.on('SIGINT', function () {
    consumer.close(true, function () {
        process.exit();
    });
});

process.on('exit', function () {
    consumer.close(true, function () {
        process.exit();
    });
});
```
```
var messages = 10;

var kafka = require('kafka-node'),
    HighLevelProducer = kafka.HighLevelProducer,
    client = new kafka.Client("localhost:2181/");
var producer = new HighLevelProducer(client, { partitionerType: 2, requireAcks: 1 });

producer.on('error', function (err) { console.log(err) });

producer.on('ready', function () {
    for (i = 0; i < messages; i++) {
        payloads = [
            { topic: 'mytopic', messages: "" }
        ];
        producer.send(payloads, function (err, data) {
            err ? console.log(i + "err", err) : console.log(i + "data", data);
        });
    }
});
```

Am I doing something wrong or is this a bug in kafka-node?

Kind regards,
Peter

**Comment by hyperlink** [comment]
Hi Peter.

Each fetch retrieves a batch of messages which are synchronously emitted as a `'message'` event. After that is `'done'` [the internal offsets are updated](https://github.com/SOHU-Co/kafka-node/blob/master/lib/highLevelConsumer.js#L309).

When you call `commit` it commits the offsets stored in the internal offset. So when you commit while inside the message handler you are committing the offsets from the last fetch.

Hope that clears it up.

**Comment by postmann** [comment]
Hm, ok, thanks. Seems like solving my problems using nodesjs and kafka is not the ideal solution :)
