### ISSUE TITLE
Consume using broker list 

### ISSUE THREAD

**Issue by ezarya** [SOHU-Co/kafka-node#489]
Hi,
If I'm not mistaken right now `kafka-node` can consume through zookeeper only.
Are there any plans to support broker list?

**Comment by hyperlink** [comment]
The new `ConsumerGroup` will be the only consumer type that could support broker list and we will need to disable high level consumer migration feature since that depends on zookeeper.

I don't have plans to work on it at the moment but if anyone wants to submit a PR I will be glad to review.

**Comment by hyperlink** [comment]
This is implemented in #691 and published as 2.0.0.
