### ISSUE TITLE
how do i can commit messages by offset with consumerGroup

### ISSUE THREAD

**Issue by manor21** [SOHU-Co/kafka-node#502]
Hi ,
when I used the regular consumer , I did :
offset.commit(groupId,topics,function(){})
for committing specific offsets.
topics is array of:
{topic: test, offset: 5} for example. 
now I want to do the same with consumerGroup , but i need the client object for initial the Offset object and the consumerGroup hides the client object.

how can I handle this?

thanks

**Comment by hyperlink** [comment]
Just curious what's your use case for manually committing the offsets? You should be able to access the Client by the `client` attribute off the consumer. for example: `consumerGroup.client`

**Comment by manor21** [comment]
My consumer needs to deliver the messages to third party, and I will commit the message only if it succeeded. 
I hope i do it wright.

**Comment by manor21** [comment]
Hi,
I have extra question, 
I do not find how to consume from specific partition , where I can configure that?

thanks

**Comment by hyperlink** [comment]
Both `HighLevelConsumer` and `ConsumerGroup` will consume on all partitions. If you want to consume from a specific partition you should use a `Consumer` where you can define a `partition` attribute into the payload.

I have not manually committed before but I would imagine it would work something like this:

- Turn autoCommit off
- Create an buffer of messages
- `pause()` after receiving the first message
- Most likely you will more messages (since fetch will fetch a batch) save these messages to your buffer
- Process the buffer and then manually commit the offset
- call `resume()` on the consumer
- Repeat

**Comment by manor21** [comment]
thanks, 
As what I read , the kafka himself manage the offsets now and not the zookeeper, 
if will work with the simple consumer, it will let the zookeeper manage the offsets no? and as I understood the consumerGroup is for the kafka 0.9+
my kafka is 0.10.

I notice that the consumerGroup host is the zookeeper , and I wonder why not the kafka against the kafka consumer example :
./bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test3 --from-beginning
they configured the kafka address...

thanks!

**Comment by hyperlink** [comment]
Good questions @manor21.

You are right the `Consumer` uses version 0 of the [offsetCommitRequest](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetCommitRequest) which is kept in zookeeper.

The consumerGroup was written with the goal of making it easy to migrate from highLevelConsumer (with minimal changes). With that in mind the zookeeper host is required to use the migration feature which persists the previously saved offsets in zookeeper to kafka broker. Also the old client code uses zookeeper to discover the other brokers (which can be done with a metadata request directly to a broker). So there's no technical reason to continue to use zookeeper other than to help migration. And issue #489 seems to be a feature request for this.

From my interpretation of the kafka protocol I am not sure if it is possible to manually define a partition to consume on and still use the new consumer group mechanism. Is this possible with the java client?

**Comment by vidhill** [comment]
I have been trying to do the same thing, 

I have a consumerGroup, 
I have configured it with `autoCommit: false`

To manually commit the offset I had to use `consumer.client.sendOffsetCommitV2Request(...)`

I couldn't get it to work using any other methods, 
did I miss something?
