### ISSUE TITLE
ConsumerGroup : commit specific offsets

### ISSUE THREAD

**Issue by manor21** [SOHU-Co/kafka-node#509]
Hi,
I work with kafka 0.10 , I produce messages with:
./bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test3

and I use the consumerGroup. 
my options:
     {
        host: 'localhost:2181',
        groupId: groupId,
        sessionTimeout: 15000,
        protocol: ['roundrobin'],
        fromOffset: 'earliest',  
        autoCommit: false,
        encoding: 'utf8'
    }
I tried to commit specific message by doing this:
var consumer = new kafka.ConsumerGroup(options,'test3'),
offset = new kafka.Offset(consumer.client);
//topics: [{"topic":"test3","partition":0,"offset":225}]
    offset.commit(groupId, topics, function (err, data) {
        if (err) {
            log('err from commit:' + JSON.stringify(err));
            return;
        }
        log('data from commit: ' + JSON.stringify(data));
    });

and I didnt get any error(I got data :{"test3":{"partition":0,"errorCode":0}}),
but when I kill the consumer and run it again I still get the same messages that I committed them(for sure, i got response from the commits).

what I do wrong?

thanks.

**Comment by hyperlink** [comment]
oh, don't do that. I wasn't even aware of the Offset had a commit method. It looks like it uses version 0 as we have discussed in the other thread.

**Comment by manor21** [comment]
Hi thanks for the response!

Is there another way to work with the ConsumerGroup without using auto commit (commit manually specific offsets)?

Just to clarify, I'm writing my consumer from scratch with Kafka 0.10, there is no need for migration from an old deprecated consumer. But I do need to control the commits and not auto commit. What to you suggest is the best use of the kafka-node for my needs? 

We implemented a consumer using the regular Consumer with Kafka 0.8, but we understand that consuming directly through ZooKeeper might be deprecated in Kafka 0.10 and its better to do it through Kafka?

**Comment by hyperlink** [comment]
You can turn autoCommit off in the `ConsumerGroup` by setting `autoCommit` to `false`. Majority of the settings in the HighLevelConsumer should still apply to `ConsumerGroup`.

**Comment by ashishnetworks** [comment]
autoCommit: doesn't make any change in Kafka consumer group. is it a bug?

**Comment by sumitjainn** [comment]
Can we use consumer.setOffset('topic', 0, 0); to commit specific offset??

**Comment by hyperlink** [comment]
@sumitjainn no don't do that. It was used to set the initial internal offsets uses for fetches.
