### ISSUE TITLE
kafka highlevel consumer consume all datas in the topic for the first when app starts

### ISSUE THREAD

**Issue by mlanandnair** [SOHU-Co/kafka-node#510]
For my application I am sending 4 json data to kafka topic and that data is inserted to postgres database as realtime. When i start the app for the first time, consumer consumes all data in the queue,say if there is 100 offsets all data will be consumed, whether i inject the data into kafka or not. After that when i insert 4 objects they are transacted correctly to database. What can be the reason for that sir?

**Comment by hyperlink** [comment]
By default the HighLevelConsumer will start consuming from the earliest offset available. If you want to consume from earliest you'll need to do it [manually](https://github.com/SOHU-Co/kafka-node#for-a-new-consumer-how-do-i-start-consuming-from-the-latest-message-in-a-partition). If you use the new ConsumerGroup you can define an attribute `fromOffset` in the options to control this which can take either `earliest` or `latest` offsets. Hope that helps.

**Comment by mlanandnair** [comment]
Thank you sir , I have done it manually. Is there are upgrade like setting the offset flag to "latest" for HighLevelConsumer.

**Comment by hyperlink** [comment]
`fromOffset` "latest" and "earliest" is not available in the HighLevelConsumer only in the ConsumerGroup.
