### ISSUE TITLE
Asynchronous processing of messages

### ISSUE THREAD

**Issue by BryceCicada** [SOHU-Co/kafka-node#524]
Firstly, thank you for this library.

I'm processing messages asynchronously with promises like:
```javascript    
require('promise.prototype.finally').shim();
let consumer = new kafka.ConsumerGroup(options, topics);
consumer.on('message', message => {
    consumer.pause();
    doSomethingAsync(message)
        .catch(err => console.log(err))
        .finally(() => consumer.resume());
});
```

I was hoping that the _message_ event would not be emitted between pause and resume of the consumer.  This way, my application should not fill its memory with pending promises.  However, this is not the case.

I imply that that _pause()_ and _resume()_ work on the kafka fetch-loop, rather than per message.  I think I can see that code in _protocol.js_ and _client.js_.  Is that so?  If so, that explains why the _message_ event continues to be emitted for all messages in the fetch response, regardless of consumer paused state.

To work around this, I need to synchronise the asynchronous emission of messages with my asynchronous processing of those messages.  It seems like I could either:

1. Wrap my asynchronous processing up into code that blocks the javascript event-loop, thereby ensuring that the consumer cannot emit a message. Or,
2. Cache the messages in my own message queue from which I pause/resume emitting of messages.  Resume the kakfa fetch-loop only when my queue is empty.  Manage the committed offsets manually as my messages are emitted from this queue.

1 is unsatisfactory for me.  2 looks like a pain. Is there a better way?

**Comment by BryceCicada** [comment]
Oh, perhaps I see a third option to mitigate the issue:
  3. Pause consumer on _done_ event and resume when all promises are fulfilled.  This assumes that I receive the _done_ event synchronously along with the consumer, so that I can pause before the next _consumer.fetch()_ is executed asynchronously.

**Comment by hyperlink** [comment]
Yes the `pause` and `resume` are for the fetch loop. So pausing doesn't stop the emitting of message event if that batch of messages had not finished being emitted. We use a queuing layer on top of kafka it's very similar to the example in #497.

**Comment by BryceCicada** [comment]
Thank you.  I've solved this as at option 3.

**Comment by Tin-Nguyen** [comment]
hi @BryceCicada , have you resolved the case we have 3 messages in queue? I did the same way as yours, but it seems like we just make synchronous process for 1st message, 2 other messages still come into the consumer at the same time, instead of one by one.

**Comment by murdercdh** [comment]
I have the same problem when using this sdk. if the concurrent can not solve by hook consumer's on-message event.It is useless.

**Comment by nancycg** [comment]
My kafka node and kafka stream are blocking node single event thread... how did you solve the issue @brycecicada
