### ISSUE TITLE
I can not get messages from kafka  by consumer

### ISSUE THREAD

**Issue by phpengineer** [SOHU-Co/kafka-node#525]
This is my code 

var kafka = require("kafka-node");
var Consumer = kafka.Consumer,
consumerClient = new kafka.Client('10.x.x.x:2181'),
consumer = new Consumer(consumerClient, [{ topic: 'filter_output4'}], {autoCommit: true});

consumerClient.on('ready', function () { 
	console.log('client ready!')
})

consumer.on('error', function (err) {
  console.log("Kafka Error: Consumer - " + err);
});

consumer.on('offsetOutOfRange', function (err) {
	console.log(err);
})

consumer.on('message', function (message) {
  console.log(message.data.content);
});

It does not work, no error, no messages, something wrong with my code ?

**Comment by hyperlink** [comment]
if you want to retrieve the data of the message you should access it with `message.value`. I would also try to use `kafka/bin` tools to verify kafka is working ok.

**Comment by phpengineer** [comment]
@hyperlink  thanks  for your answer !

kafka/bin  tool works well, but i add "console.log('test')" in 'message' callback like this   consumer.on('message', function (message) {
console.log('test');
});

If "message" is called , the word 'test' must be printed, unfortunately, there isn't anything!

**Comment by phpengineer** [comment]
@hyperlink I just find the answer,   kafka server has 3 partitions ,but I set the partition to 0 .so  I can not get the messages sometimes !

**Comment by lammh** [comment]
Hello,
I have the same problem
I can not solve it
you can help me please

**Comment by hyperlink** [comment]
@lammh try using a `ConsumerGroup`. It should automatically consume from all partitions.
