### ISSUE TITLE
Online-status of the HighLevelConsumer

### ISSUE THREAD

**Issue by sfrehse** [SOHU-Co/kafka-node#526]
Is it possible to check the connection status of the HighLevelConsumer? I would like to test whether the connection is still alive.

**Comment by hyperlink** [comment]
Connection to the kafka broker or zookeeper? And what if the instance in the group doesn't own any partitions what should the status be?

**Comment by sfrehse** [comment]
The status to the kafka broker. The status may encode any group status.

Is there any heartbeat message to the broker from the node client running?

**Comment by hyperlink** [comment]
The [ConsumerGroup](https://github.com/SOHU-Co/kafka-node#consumergroup) will periodically send a heartbeat to the kafka broker (and retry if it encounters failures). The HighLevelConsumer doesn't have this exact mechanism built in.

To monitor the health of your group it's best to use a service like [burrow](https://github.com/linkedin/Burrow). I don't think it has good support for HighLevelConsumer. It's recommended you migrate to the new ConsumerGroup if possible.

**Comment by sfrehse** [comment]
Thanks. I'll shift to ConsumerGroups soon... :-).
