### ISSUE TITLE
Expected result on Kafka/ZK/network failure?

### ISSUE THREAD

**Issue by ty10r** [SOHU-Co/kafka-node#528]
I'm trying to ensure the fact that one of my services which use
- kafka-node `Client`
- kafka-node `HighLevelProducer`
- kafka-node `HighLevelConsumer`
is resilient to kafka/zk/network failure. In this case, all I need to know is that it will continually retry to connect to the kafka/zk services and log every time it tries/fails to reconnect.

I thought I could achieve this by setting `.on('error' ...)` handlers on my `Client`, `HighLevelProducer`, and `HighLevelConsumer`. Unfortunately this does not seem to be showing me any information about disconnections.

For info, I am simulating a failure by:
- docker-compose up (on ZK and kafka together)
- start my `Client`, `HighLevelProducer`, and `HighLevelConsumer`
- register error listeners on each
- docker-compose down (on ZK and kafka together)

This case is not emitting any error events I would expect.

How should I best enforce that my objects reconnect and that they log all disconnects and all reconnect retries?

**Comment by hyperlink** [comment]
There's code in `kafka-node` to recover from network issues. Though there's an open issue (#469) about this not working properly for producer (very possible the recovery was mainly focused from the consumer perspective).

If you are interested to know about connection changes you could listen for `reconnect` and `connect` events on the client. Unfortunately there is not an event for disconnects but you will likely get a socket level `error` emitted on your consumer/producer. In your case you should  expect to receive lots of `ECONNREFUSED` errors. If you aren't seeing these I would verify the consume/producers are connected before the containers were taken down.

And I would encourage a migration to [ConsumerGroup](https://github.com/SOHU-Co/kafka-node#consumergroup) if possible. HighLevelConsumers will be likely deprecated by kafka in the future.

**Comment by ty10r** [comment]
@hyperlink Thank you for the information. It's a huge help.
I've already ensured that the consumer/producer are connected before causing disconnection.

I will start listening on the `reconnect` event.

As for the `ECONNREFUSED` errors, I will probably have to check all of my catch clauses to be sure we're not accidentally swallowing those errors.
