### ISSUE TITLE
Unhandled 'error' event terminates node.js process

### ISSUE THREAD

**Issue by snmgian** [SOHU-Co/kafka-node#531]
After stopping a kafka instance (I have 2 running instances under normal conditions), node prints the following output and then terminates the process:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:9093
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```

I attached 'error' event handlers on all the Client, Offset and Consumer objects that I've manually instantiated. 

If I setup a global error handler, then the process doesn't terminate and the consumer happily continues receiving messages from the remaining broker.

```javascript
process.on('uncaughtException', (err) => {
  console.log('whoops! there was an error', err.stack);
});
```

In Client#fetchLatestOffsets (the app is invoking this method) there are the following lines:
https://github.com/SOHU-Co/kafka-node/blob/master/lib/offset.js#L91
```javascript
      var offset = new Offset(client);
      offset.fetch(payloads, callback);
```

So, it creates an internal new `Offset` object, that newly offset has not attached an 'error' event handler, so when Client emits an error it aborts the process because the offset re-emits the event but no one is listening to it.

https://github.com/SOHU-Co/kafka-node/blob/master/lib/offset.js#L18
``` javascript
var Offset = function (client) {
  var self = this;
  // ... 
  this.client.on('error', function (err) {
    self.emit('error', err);
  });
};
```

The solution seems to be to not create a new `Offset` and just invoke `self.fetch(...)`, or don't re-emit Client error events forcing the user to handle those events with `Client#on`.

This problem does not occur if I don't invoke `Offset#fetchLatestOffsets`. I'm using v1.0.7

Any thoughts?

**Comment by hyperlink** [comment]
I would lean towards using the `self.fetch` but I'm not sure why a one time instance of Offset is created. Maybe @CharlesWall recalls?
