### ISSUE TITLE
Support for 0.9

### ISSUE THREAD

**Issue by bryanburgers** [SOHU-Co/kafka-node#535]
The title for this project is "Node.js client for Apache Kafka 0.8", but some of the documentation, changelog, and features suggest that it is compatible with Kafka 0.9. Is it? If so, can the project title be changed?

**Comment by hyperlink** [comment]
Yes, it's compatible with 0.9 and 0.10 as well. Unfortunately I am not an admin for this repo so either @haio or @crzidea will need to update it.

**Comment by crzidea** [comment]
I will update the README.
