### ISSUE TITLE
Snappy codec is not installed

### ISSUE THREAD

**Issue by ighack** [SOHU-Co/kafka-node#549]
> E:\node-kafka\Kafka-Node>node client.js
> Server running at http://127.0.0.1:9999/
> E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kafka-node\lib\codec\snappy.js:9
>     throw new Error('Snappy codec is not installed');
>     ^
> 
> Error: Snappy codec is not installed
>     at Object.unavailableCodec (E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kaf
> ka-node\lib\codec\snappy.js:9:11)
>     at Object.<anonymous> (E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kafka-no
> de\lib\protocol\protocol.js:183:17)
>     at Object.self.tap (E:\node-kafka\Kafka-Node\node_modules\.0.3.0@binary\inde
> x.js:248:12)
>     at decodeMessageSet (E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kafka-node
> \lib\protocol\protocol.js:161:8)
>     at Object.<anonymous> (E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kafka-no
> de\lib\protocol\protocol.js:128:26)
>     at Object.self.tap (E:\node-kafka\Kafka-Node\node_modules\.0.3.0@binary\inde
> x.js:248:12)
>     at Object.decodePartitions (E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kaf
> ka-node\lib\protocol\protocol.js:123:8)
>     at Object.self.loop (E:\node-kafka\Kafka-Node\node_modules\.0.3.0@binary\ind
> ex.js:267:16)
>     at Object.<anonymous> (E:\node-kafka\Kafka-Node\node_modules\.1.1.0@kafka-no
> de\lib\protocol\protocol.js:57:8)
>     at Object.self.loop (E:\node-kafka\Kafka-Node\node_modules\.0.3.0@binary\ind
> ex.js:267:16)

I have "E:\node-kafka\Kafka-Node\node_modules\snappy"
so what should I do on windows?

**Comment by hyperlink** [comment]
Did you see errors during the `npm install`? You need to resolve any node-gyp issues before you can use snappy. If you didn't intend to use snappy codec make sure you don't have the  compression option selected.

**Comment by ighack** [comment]
> E:\node-kafka\Kafka-Node>cnpm install snappy
> 
> E:\node-kafka\Kafka-Node\node_modules\.5.0.5@snappy>node "C:\Users\Administrator
> \AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\nod
> e-gyp.js" rebuild
> 在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
> CL : fatal error C1510: Cannot load language resource clui.dll. [E:\node-kafka\
> Kafka-Node\node_modules\.5.0.5@snappy\build\deps\snappy\snappy.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
> ` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roamin
> g\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
> s.js:215:12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "D:\\Application\\Node.js\\node.exe" "C:\\Users\\Administrator\
> \AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-b
> in\\node-gyp.js" "rebuild"
> gyp ERR! cwd E:\node-kafka\Kafka-Node\node_modules\.5.0.5@snappy
> gyp ERR! node -v v6.9.3
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> Error: post install error, please remove node_modules before retry!
> Run "C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
>     at ChildProcess.proc.on.code (C:\Users\Administrator\AppData\Roaming\npm\nod
> e_modules\cnpm\node_modules\runscript\index.js:67:21)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> npminstall version: 2.16.0
> npminstall args: D:\Application\Node.js\node.exe C:\Users\Administrator\AppData\
> Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --u
> serconfig=C:\Users\Administrator\.cnpmrc --disturl=https://npm.taobao.org/mirror
> s/node --registry=https://registry.npm.taobao.org snappy
> 
> E:\node-kafka\Kafka-Node>

this is my client.js
```
var http = require('http');

http.createServer(function (request, response) {

	// 发送 HTTP 头部 
	// HTTP 状态值: 200 : OK
	// 内容类型: text/plain
	response.writeHead(200, {'Content-Type': 'text/plain'});
	
	var kafka = require('kafka-node'),
    Consumer = kafka.Consumer,
	//HighLevelConsumer = kafka.HighLevelConsumer,
    client = new kafka.Client(),
    consumer = new Consumer(
        client,
        payloads = [
            { topic:'fltest',partition:0},
			{ topic:'fltest',partition:1},
			{ topic:'fltest',partition:2}
        ],
        options = {
			groupId: 'kafka-node-group',
            autoCommit: false,
			fetchMaxWaitMs: 100,
			fetchMinBytes: 1,
			fetchMaxBytes: 1024 * 1024,
			fromOffset: false,
			encoding: 'utf8'
       }
    );
	//consumer = new HighLevelConsumer(
		//client,
		//[
			//{topic:'fltest'}
		//],
		//{
			//groupId: 'kafka-node-group',
            //autoCommit: false,
			//fetchMaxWaitMs: 100,
			//fetchMinBytes: 1,
			//fetchMaxBytes: 1024 * 1024,
			//fromOffset: false,
			//encoding: 'utf8'
		//}
	//);
	consumer.on('message', function (message) {
			console.log(message);
		});
	consumer.on('error', function (err) {
			console.log(err);
		});
	//consumer.on('offsetOutOfRange', function (err) {
			//console.log(err);
		//});
	//consumer.close(function(){});
	
	// 发送响应数据 "Hello World"
	response.end('Hello World\n');
}).listen(9999);

// 终端打印如下信息
console.log('Server running at http://127.0.0.1:9999/');
```
How do I disable compression option.
I just know Producer has compression option "attributes" that is default 0
What is compression option of  Consumer?

**Comment by ighack** [comment]
Now,that error is 

> E:\node-kafka\Kafka-Node>cnpm install snappy
> 
> E:\node-kafka\Kafka-Node\node_modules\.5.0.5@snappy>node "C:\Users\Administrator
> \AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\nod
> e-gyp.js" rebuild
> 在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
> E:\node-kafka\Kafka-Node\node_modules\.5.0.5@snappy\build\deps\snappy\snappy.vc
> xproj(20,3): error MSB4019: 未找到导入的项目“E:\Microsoft.Cpp.Default.props”。
> 请确认 <Impor
> t> 声明中的路径正确，且磁盘上存在该文件。
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
> ` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roamin
> g\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
> s.js:215:12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "D:\\Application\\Node.js\\node.exe" "C:\\Users\\Administrator\
> \AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-b
> in\\node-gyp.js" "rebuild"
> gyp ERR! cwd E:\node-kafka\Kafka-Node\node_modules\.5.0.5@snappy
> gyp ERR! node -v v6.9.3
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> Error: post install error, please remove node_modules before retry!
> Run "C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
>     at ChildProcess.proc.on.code (C:\Users\Administrator\AppData\Roaming\npm\nod
> e_modules\cnpm\node_modules\runscript\index.js:67:21)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> npminstall version: 2.16.0
> npminstall args: D:\Application\Node.js\node.exe C:\Users\Administrator\AppData\
> Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --u
> serconfig=C:\Users\Administrator\.cnpmrc --disturl=https://npm.taobao.org/mirror
> s/node --registry=https://registry.npm.taobao.org snappy
> 
> E:\node-kafka\Kafka-Node>
>

**Comment by ighack** [comment]
I give up windows,it works on linux.
snappy can't bulid on windows,I don't know

**Comment by ighack** [comment]
I give up windows,it works on linux.
snappy can't bulid on windows,I don't know

**Comment by ighack** [comment]
I give up windows,it works on linux.
snappy can't bulid on windows,I don't know

**Comment by bstitt79** [comment]
I'm also having this problem. My node app isn't producing any messages to kafka, only consuming and I can't figure out how to turn compression off for the HighLevelConsumer. I've tried passing an attributes attribute to various options maps and nothing has yet worked. Advice?

const kafka = require('kafka-node');

var HighLevelConsumer = kafka.HighLevelConsumer,
    // The client specifies the ip of the Kafka producer and uses
    // the zookeeper port 2181
    client = new kafka.Client("my-ip:2181"),
    // The consumer object specifies the client and topic(s) it subscribes to
    consumer = new HighLevelConsumer(
        client,
        [
            {
                topic: 'zipkin-topic'
            }
        ],
        {
            groupId: 'brad-node-consumer-test'
        },
        {
            attributes: 0,
            autoCommit: false,
            encoding: 'utf8',
            compressionType: 'uncompressed'
        }
    );

console.log('initing kafka stuff');

consumer.on('message', function (message) {
    // grab the main content from the Kafka message
    var data = JSON.parse(message.value);
    console.log(data);
});

**Comment by hyperlink** [comment]
You can produce messages to kafka using a `Producer` or `highLevelProducer`. A consumer is used for reading messages. Compression is turned off by default.

If you're having snappy errors installing the module you can use the `--no-optional` flag.

```
npm install kafka-node --no-optional --save
```

Also I would recommend using `ConsumerGroup` instead. HLC will become deprecated soon.

**Comment by bstitt79** [comment]
I already have a kafka topic populated by other systems that aren't using compression. This app will only consume messages. Are you saying that decompression in the highlevelconsumer is turned off by default? 

And our current system is Kafka .8 so I'm not sure I have an option to use the consumer group.

**Comment by hyperlink** [comment]
Are you getting back a buffer? You can try calling `.toString('utf8')` on it.

https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html#buffer_buf_tostring_encoding_start_end

**Comment by bstitt79** [comment]
It never gets to the message handler. It always fails with this: Error: Snappy codec is not installed. I can't seem to change that behavior regardless of what I do.

**Comment by hyperlink** [comment]
Chances are the messages you are trying to consume was originally encoded with snappy codec. The module detects this through the message set's `attribute`.

https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Messagesets

You will need to resolve this codec installation issue before you can read the message. This maybe helpful:

https://github.com/nodejs/node-gyp/wiki/Visual-Studio-2010-Setup

I would poke around the node-gyp docs for steps to get it running in your environment.

**Comment by ZephD** [comment]
So... What if you can see snappy **build and install correctly** when installing kafka-node, yet the consumer spurts out this error?
This is currently happening to me. I can see snappy get built and is installed, yet the consumer errors saying it's not installed.

**Comment by hyperlink** [comment]
I am not seeing consumer error. That looks like yarn output @ZephD ?

**Comment by ZephD** [comment]
Correct.
The consumer error is the same as above: "Snappy codec not installed".
The yarn output shows snappy is installed (it doesn't show the build success, but it doesn't show the build errors either which means a success)

**Comment by hyperlink** [comment]
Could this a yarn issue? Does the same thing happen with npm?

**Comment by cuvillier** [comment]
Here is how I solved this issue on Windows:

BEFORE: Install VisualStudio C++ to get the msbuild to compile the snappy C++ code.
The "VS Express" version is fine.

Then, run (You may need to be granted as Administrator):
  npm install --global --production windows-build-tools
  setx PYTHON "%USERPROFILE%\.windows-build-tools\python27\python.exe"
  npm install --global node-gyp
  npm install snappy

Good luck.

**Comment by NishiJain91** [comment]
I am also facing the same issue. I am on a mac system. 

My ConsumerGroup code looks like below:

const KafkaConsumerGroupService = function (groupName, topicName, msgRecieveCb, errorCb) {
    var options = {
      // connect directly to kafka broker (instantiates a KafkaClient)
      kafkaHost: kafkaConstants.CLIENT_BROKER_ADDRESS,
      groupId: groupName,
      autoCommit: true,
      autoCommitIntervalMs: 5000,
      sessionTimeout: 15000,
      fetchMaxBytes: 10 * 1024 * 1024, // 10 MB
      // An array of partition assignment protocols ordered by preference. 'roundrobin' or 'range' string for
      // built ins (see below to pass in custom assignment protocol)
      protocol: ['roundrobin'],
      // Offsets to use for new groups other options could be 'earliest' or 'none'
      // (none will emit an error if no offsets were saved) equivalent to Java client's auto.offset.reset
      fromOffset: 'latest',
      // how to recover from OutOfRangeOffset error (where save offset is past server retention)
      // accepts same value as fromOffset
      outOfRangeOffset: 'earliest',
    };
  
    const consumerGroup = new kafka.ConsumerGroup(options,topicName);
  
    consumerGroup.on('message', function (message) {
        console.log('Message recieved in consumer:', JSON.parse(message.value))
        //console.log('Message: ', typeof message.value == 'object' ? JSON.parse(message.value) : message.value);
        msgRecieveCb(message);
    });
  
    consumerGroup.on('error', function onError(error) {
      console.error(error);
      errorCb(error)
    });

    process.once('SIGINT', function(){
      async.each([consumerGroup], function (consumer, callback = () => {}) {
          console.error("Closing the kafka build consumer process");
          consumer.close(true, callback);
      });
    })

    return consumerGroup;
};


There is no option in ConsumerGroup configuration to specify the compressionType. Did anyone faced and resolved the similar issue ?

**Comment by hyperlink** [comment]
@NishiJain91 

> There is no option in ConsumerGroup configuration to specify the compressionType. Did anyone faced and resolved the similar issue ?

@NishiJain91 this is not something you need to specify since the consumer should automatically picks up the correct compression type based on the message response.

**Comment by jafri** [comment]
Same error, snappy builds fine but error still shows

**Comment by HuihuangZhang** [comment]
I am facing the same problem. Here is some information:
```
macos: 10.14.3
nodejs: v10.7.0
npm: 6.1.0
yarn: 1.9.4
```

when I use command `yarn install`, program crashes with  "Snappy codec not installed". but I fix it using command `npm install`. I think it maybe a yarn issue.

**Comment by ZephD** [comment]
Hi @HuihuangZhang , that's probably a caching/lock issue with Yarn. If you deleted your node modules and `yarn install`ed, it'll probably do the same as the `npm install` did.
