### ISSUE TITLE
How can I be sure that the client is connected?

### ISSUE THREAD

**Issue by nkurothe** [SOHU-Co/kafka-node#550]
I was not able to find any assertive way to check if the client is connected to ZK or not.

`var kafka = require('kafka-node');
var Producer = kafka.Producer;
var KeyedMessage = kafka.KeyedMessage;
var Client = kafka.Client;
var client = new Client(validZKUrl);
`

```
var kafka = require('kafka-node');
var Producer = kafka.Producer;
var KeyedMessage = kafka.KeyedMessage;
var Client = kafka.Client;
var client = new Client(invalidZKUrl);
```

how can I check if the client is connected to the ZK?

**Comment by hyperlink** [comment]
the client will emit a `ready`.

**Comment by nkurothe** [comment]
Thanks for the quick reply. I was assuming in case the ZK url is invalid, the client will emit an error, but it doesn't. Is there any state that will help me catch this exception that the client is not connected, so that I can take necessary action based on it.

**Comment by hyperlink** [comment]
You may have to handle this in your application and throw an error of the client does not become a ready after a period of time.
