### ISSUE TITLE
Autocommit on HighLevelConsumer fires even if offsets haven't changed

### ISSUE THREAD

**Issue by brunowonka** [SOHU-Co/kafka-node#567]
This doesn't happen very often, but I identified that if a HighLevelConsumer is "idling" (no messages are coming in), autocommit keeps getting called periodically (via the `done` event on the consumer). 

I forked the repos with the proposed changes (very simple), I can create a PR upon request:

https://github.com/brunowonka/kafka-node/tree/autocommit_fix

**Comment by hyperlink** [comment]
Look forward to the PR @brunowonka. Thanks!

**Comment by hyperlink** [comment]
Merged into master.
