### ISSUE TITLE
Error "Could not find the leader" when Kafka server restarts

### ISSUE THREAD

**Issue by mdnorman** [SOHU-Co/kafka-node#569]
Whenever a Kafka server in a cluster restarts, the kafka-node library loses connection to the kafka server and fails to reconnect properly.

When trying to publish a message, we get the following error:
kafka-node@1.3.1:
```
2017-01-19 11:42:43.866 ERROR Error executing participate: Could not find the leader BrokerNotAvailableError: Could not find the leader

    at new BrokerNotAvailableError (/Projects/libraries/kafka-utils/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at .<anonymous> (/Projects/libraries/kafka-utils/node_modules/kafka-node/lib/client.js:529:19)
    at Client.handleReceivedData (/Projects/libraries/kafka-utils/node_modules/kafka-node/lib/client.js:740:12)
    at Socket.<anonymous> (/Projects/libraries/kafka-utils/node_modules/kafka-node/lib/client.js:700:10)
```

kafka-node@1.0.7
```
2017-01-19 11:38:48.629 ERROR Error executing participate: Could not find the leader BrokerNotAvailableError: Could not find the leader
    at new BrokerNotAvailableError (/Projects/libraries/kafka-utils/node_modules/kafka-node/lib/errors/BrokerNotAvailableError.js:11:9)
    at .<anonymous> (/Projects/libraries/kafka-utils/node_modules/kafka-node/lib/client.js:519:19)
    at Client.handleReceivedData (/Projects/libraries/kafka-utils/node_modules/kafka-node/lib/client.js:725:12)
    at Socket.<anonymous> (/Projects/libraries/kafka-utils/node_modules/kafka-node/lib/client.js:685:10)
```

**Comment by hyperlink** [comment]
This could be the same as #469. I will look into it.

**Comment by hyperlink** [comment]
I'm having issues reproducing this. Do you have a easy way to reproduce? Do you need to have a cluster for servers for it to work? How long was that broker offline for?

**Comment by mdnorman** [comment]
I'll work on a simple reproduction scenario that removes the complexity of our code. In the meantime, you don't need multiple brokers. I was able to reproduce with running kafka and zookeeper in separate docker containers, stopping (but not destroying) only the kafka docker container, waiting a few seconds, and then starting it back up again. When I attempted to publish a message to the topic, it fails with the error above.

**Comment by mdnorman** [comment]
The following seems to spew errors when disconnected, and even after `connect` (we never receive a `reconnect`), it is still spewing errors. Eventually after a few times it comes back. This could be due to the KeyedMessage. I'm still working on a ConsumerGroup repro scenario.

```
'use strict';

const kafkaNode = require('kafka-node');

/* eslint-disable no-console */

const zkConnection = 'zookeeper:2181';
const consumerGroupName = 'reconnect-test';

const partitionerTypes = kafkaNode.HighLevelProducer.PARTITIONER_TYPES;
const partitionerType = partitionerTypes.keyed;
const topic = 'local.reconnect';
const key = 'the-data-12345';
const message = { param1: 'value1', param2: 2 };

const compressionTypes = {
  none: 0,
  gzip: 1,
  snappy: 2,
};
const compression = compressionTypes.gzip;

process.on('uncaughtException', err => {
  console.error(`Uncaught exception: ${err && err.stack || err}`, err);
});

process.on('unhandledRejected', err => {
  console.error(`Unhandled rejected: ${err && err.stack || err}`, err);
});

process.on('warning', warning => {
  console.log(`Process warning: ${warning && warning.stack || warning}`, warning);
});

const kafkaClient = new kafkaNode.Client(zkConnection, consumerGroupName);

const clientConnectionListenerError = err => {
  console.error(`Error connecting to kafka client: ${err.stack || err.message}`, err);
};

kafkaClient.on('connect', data => {
  console.log('Connect:', data);
});

kafkaClient.once('error', clientConnectionListenerError);

kafkaClient.once('ready', () => {
  console.log('Kafka client ready.');
  kafkaClient.removeListener('error', clientConnectionListenerError);

  kafkaClient.on('reconnect', data => {
    console.log('Reconnect:', data);
  });

  const kafkaProducer = new kafkaNode.HighLevelProducer(kafkaClient, { partitionerType });
  console.log('Kafka producer ready.');

  setInterval(() => {
    kafkaProducer.send([{
      topic,
      key,
      messages: [new kafkaNode.KeyedMessage(key, JSON.stringify(message))],
      attributes: compression,
    }], (err, result) => {
      if (err) {
        console.error(`Error sending message: ${err.stack || err.message}`, err);
        return;
      }

      console.log('Result:', result);
    });
  }, 1000);
});

/* eslint-enable no-console */
```

**Comment by hyperlink** [comment]
I noticed waiting just a few seconds for the container yields some strange behavior. The kafka container gets into a weird state with zookeeper and service spews a lot of zookeeper related errors. In this case I can't produce even if the client is restarted.

In other cases the container will terminate with an exception.

```
kafka_1      | java.lang.RuntimeException: A broker is already registered on the path /brokers/ids/1001. This probably indicates that you either have configured a brokerid that is already in use, or else you have shutdown this broker and restarted it faster than the zookeeper timeout so it appears to be re-registering.
kafka_1      | 	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:295)
kafka_1      | 	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:281)
kafka_1      | 	at kafka.server.KafkaHealthcheck.register(KafkaHealthcheck.scala:64)
kafka_1      | 	at kafka.server.KafkaHealthcheck.startup(KafkaHealthcheck.scala:45)
kafka_1      | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:231)
kafka_1      | 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:37)
kafka_1      | 	at kafka.Kafka$.main(Kafka.scala:67)
kafka_1      | 	at kafka.Kafka.main(Kafka.scala)
```

In my test if I wait about 35 or more seconds to start the container the container seems to be ok and producer recovers successfully.

**Comment by mdnorman** [comment]
It does appear that the later kafka-node version (1.3.1) recovers better than the previous (1.0.7) version. I'm going to install that into some of my services and see if we notice better behavior.

**Comment by mdnorman** [comment]
I was able to reconnect properly without errors if I call code to update the topic metadata for all of the topics the code publishes to:

```
client.loadMetadataForTopics(topics, (error, metadata) => {
  const err = error || metadata[1] && metadata[1].error;
  if (err) {
    logger.warn(`Error getting metadata for ${topics}: ${err.stack || err.message}`, err);
    throw err;
  }
  updateMetadatas(metadata);
});
```

This is required before publishing to topics with the keyed partitioner, and apparently it's required every time the brokers change (even if only due to a network hiccup).

**Comment by hyperlink** [comment]
Looks like the metadata gets [cleared](https://github.com/SOHU-Co/kafka-node/blob/74d3d2a387f77bc803aa5d9278a71de476c563a8/lib/baseProducer.js#L86) when the broker changes.  Maybe the expectation is it will get refreshed later [here](https://github.com/SOHU-Co/kafka-node/blob/74d3d2a387f77bc803aa5d9278a71de476c563a8/lib/client.js#L515).  Unfortunately it's needed [here](https://github.com/SOHU-Co/kafka-node/blob/74d3d2a387f77bc803aa5d9278a71de476c563a8/lib/baseProducer.js#L111).

**Comment by hyperlink** [comment]
Hi @mdnorman could you point to this branch `SOHU-Co/kafka-node#producer-broker-recovery` and see if it fixes the issue for you?

**Comment by mdnorman** [comment]
This branch appears to have fixed the issue we were seeing. It seems to be automatically updating the metadata for any topics we've seen before, which is very helpful.
