### ISSUE TITLE
kafka zookeeper returns java error "too many open files"

### ISSUE THREAD

**Issue by qbadx** [SOHU-Co/kafka-node#571]
Hello,

Even after having set correct ulimit values, I'm hitting this error and I can't figure out why ..

I'm monitoring the number of openfiles of nodejs with `lsof -i -n -P | grep nodejs`

and it always crashes when it reaches around 8000 openfiles.

I can't say wether it is caused by the module or by the js code ..

**Comment by hyperlink** [comment]
`kafka-node` does not open any files so this issue shouldn't be caused by the module. Good luck!

**Comment by qbadx** [comment]
Thx, I'll continue my investigations.. I have been looking for days so f you have any pointers please do not hesitate

**Comment by hyperlink** [comment]
@qbadx you should call `close` on either one of the producer or consumer types which will implicitly close the client. And do not share client instances.

**Comment by nkumarclm** [comment]
I think we should flush before we close the connection 
```
producer.flush();
producer.close();
```

**Comment by hyperlink** [comment]
`flush` is not a method on the producer.
