### ISSUE TITLE
kafka connect refused

### ISSUE THREAD

**Issue by macurial** [SOHU-Co/kafka-node#584]
在初始化连接的时候报错
error { Error: connect ECONNREFUSED 65.74.177.129:9092
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '65.74.177.129',
  port: 9092 }

用的是例子中的代码，
let kafka = require('kafka-node');
// kafkaport :9092
var HighLevelProducer = kafka.HighLevelProducer;
var Client = kafka.Client;
var client = new Client('192.168.0.31:2181/');
var argv = [];
var topic = argv.topic || 'topic1';
var count = 10;
var rets = 0;
var producer = new HighLevelProducer(client);

**Comment by hyperlink** [comment]
network issue?
