### ISSUE TITLE
Consume latest Kafka messages

### ISSUE THREAD

**Issue by phagunbaya** [SOHU-Co/kafka-node#587]
Right now, there is no way to consume latest messages irrespective of committed offset. Even setting fromOffset to true and passing topic offset does not help. I always ends up getting all the old messages.

**Comment by hyperlink** [comment]
Which consumer are you using?

Consuming using the `ConsumerGroup` by default will start from the latest but you can also define the `fromOffset` setting to `latest`. With the other consumers you will need to manually set it by querying the `Offset.fetchLatestOffsets` and setting it on the payload.

**Comment by phagunbaya** [comment]
I'm using `HighLevelConsumer`

**Comment by hyperlink** [comment]
Unless you're on kafka 0.8 I would recommend `ConsumerGroup` which lets you start consuming from the latest. Otherwise you'll need to get the latest offsets yourself.

**Comment by phagunbaya** [comment]
@hyperlink Thanks that worked !
