### ISSUE TITLE
cannot get all list of topics

### ISSUE THREAD

**Issue by macurial** [SOHU-Co/kafka-node#588]
When I use this method to get topicList
client.loadMetadataForTopics([], function (error, results) {
  console.log('%j', _.get(results, '1.metadata'));
});
It return me a undefined,why is this happened? 
 
and I am sure my Kafka indeed has topics

**Comment by hyperlink** [comment]
What does the value of the `error` parameter ?

**Comment by macurial** [comment]
{ [BrokerNotAvailableError: Broker not available] message: 'Broker not available' } @hyperlink

**Comment by macurial** [comment]
{ [BrokerNotAvailableError: Broker not available] message: 'Broker not available' } @hyperlink 

kafka是按照官网的教程启动的，只有一个broker，broker.id = 0

**Comment by hyperlink** [comment]
Most of the time this means the client has no socket connection to the kafka broker.

Did you receive a `ready` event from the client? 

What is the value of `client.ready` ?

**Comment by macurial** [comment]
![image](https://cloud.githubusercontent.com/assets/10878381/22732267/8a0b9a30-ee28-11e6-8009-28d87d2f7731.png)

client.ready is false,but I still can get the message

**Comment by hyperlink** [comment]
Try calling `loadMetadataForTopics` after the `connect` event has been emitted.

**Comment by macurial** [comment]
that worked! thank you
