### ISSUE TITLE
Problem getting list of all topics when using ConsumerGroup and Kafka 0.10

### ISSUE THREAD

**Issue by TomCoates8161** [SOHU-Co/kafka-node#593]
The method for getting a list of all topics suggested in the FAQ (https://www.npmjs.com/package/kafka-node#how-do-i-get-a-list-of-all-topics) is not working for me. Doing this:

```
var kafka = require('kafka-node');
var options = {
  host: zooKeeperServer+':'+zooKeeperPort,
  groupId: 'MyConsumerGroup'
};
 
var consumerGroup = new kafka.ConsumerGroup(options, []);
consumerGroup.client.loadMetadataForTopics([], function (error, results) {
    console.log('error = %j', error);
    console.log('results = %j', results);
});
```
where `zooKeeperServer` and `zooKeeperPort` are set to point to my ZooKeeper results in:
```
error = {"message":"Broker not available"}
results = undefined
```
Note that I am running Kafka 0.10, which I think means that Kafka co-ordinates everything itself rather than relying on ZooKeeper.  Also, running in debugging mode with
```
export DEBUG=kafka-node:*
```
produces output that suggests kafka-node:ConsumerGroup has successfully found all the topics and partitions.  But I don't understand how to access a list of all the topics.  Any help would be greatly appreciated!

**Comment by hyperlink** [comment]
Take a look at #588 @TomCoates8161

**Comment by TomCoates8161** [comment]
Many thanks!  👍
