### ISSUE TITLE
Support custom log implementations

### ISSUE THREAD

**Issue by bripkens** [SOHU-Co/kafka-node#595]
It would be great if this library could be instructed to use user-configurable logging mechanisms. Specifically, this would make integration into larger applications (and their log handling) easier. On top of this, some logging implementations can be turned on/off during the runtime of an application for improved debugging.

Thinking of this goal, the following would be great to have in `kafka-node`:

 1. Set custom logging implementations, e.g.

```javascript
var kafka = require('kafka-node');
kafka.setLoggerProvider(myLoggerProvider);
```

Where `myLoggerProvider` can be called with a name (`string`) to create a new logger. A logger is any object with a `.warn`, `.info` and `.error` function, e.g. console, bunyan, winston or pino loggers.

Example provider for debug logger:

```javascript
var debug = require('debug');

function debugLoggerProvider(name) {
  var logger = debug(name);
  logger = logger.bind(logger);

  return {
    info: logger,
    warn: logger,
    error: logger
  };
}
```

 2. Continue to use `debug` as the default logging implementation for full backward compatibility.
 3. Adapt the `kafka-node` code to use the user configured logger with reasonable log levels.

The change would be backward compatible and I am willing to contribute it. So if you agree, I'll get right to it.

**Comment by hyperlink** [comment]
That sounds great. Go for it!
