### ISSUE TITLE
出现取不走消息的情况

### ISSUE THREAD

**Issue by nbwgl** [SOHU-Co/kafka-node#596]
kafka0.9.0.0版本，使用kafka-node1.0.4，出现过两次取不走消息的情况了，使用的是consumer
            KeyedMessage = kafka.KeyedMessage,
            client = new kafka.Client(setting.kafka),
            producer = new Producer(client),
            consumer = new Consumer(
                    client,
                    [
                        { topic: setting.topic, partition: setting.partition }//, { topic: 'uu', partition: 1 }
                    ],
                    {
                        groupId: 'kafka-node-group',//consumer group id, default `kafka-node-group`
                        // Auto commit config
                        autoCommit: true,
                        autoCommitIntervalMs: 5000,
                        // The max wait time is the maximum amount of time in milliseconds to block waiting if insufficient data is available at the time the request is issued, default 100ms
                        fetchMaxWaitMs: 100,
                        // This is the minimum number of bytes of messages that must be available to give a response, default 1 byte
                        fetchMinBytes: 1,
                        // The maximum bytes to include in the message set for this partition. This helps bound the size of the response.
                        fetchMaxBytes: 1024 * 10,
                        // If set true, consumer will fetch message from the given offset in the payloads
                        fromOffset: false,
                        // If set to 'buffer', values will be returned as raw buffer objects.
                        encoding: 'buffer'
                    }
            );
现象是运行一段时间后，程序还运行着，但是消息就取不走了。重启程序之后也取不走，单独用kafka_node写了小程序也一样，取不走消息。
[uns@uu23 kafka_2.11-0.9.0.0]$ bin/kafka-run-class.sh kafka.tools.ConsumerOffsetChecker --zookeeper 192.168.0.11:2181 --group uu-node-group --topic uu
[2017-02-12 15:19:09,450] WARN WARNING: ConsumerOffsetChecker is deprecated and will be dropped in releases following 0.9.0. Use ConsumerGroupCommand instead. (kafka.tools.ConsumerOffsetCheck
er$)Group           Topic                          Pid Offset          logSize         Lag             Owner
uu-node-group   uu                             0   66309           66966           657             none
uu-node-group   uu                             1   64839           65917           1078            none
uu-node-group   uu                             2   61237           61913           676             none
uu-node-group   uu                             3   15263           15475           212             none
用java写的客户端都能够取走消息。
如果我换一个新的topic又能运行一段时间。
请帮忙支持一下，是因为什么原因？

**Comment by nbwgl** [comment]
这个问题非常困扰我，因为现在已经是正式运营的系统，如果还解决不了这个问题，只能重新考虑用其他语言重构系统了。

**Comment by hyperlink** [comment]
I noticed the group Id you used in your example `kafka-node-group` doesn't match the group id used in the ConsumerOffsetChecker which is `uu-node-group`.

**Comment by nbwgl** [comment]
感谢回复，你指出的那个问题是因为我写测试程序的时候修改的，实际上我用uu-node-group也试过。也是一样。目前我暂时使用no-kafka代替，但是这个库没有kafka-node活跃，而且nodejs官方也没有推荐。
