### ISSUE TITLE
possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by macurial** [SOHU-Co/kafka-node#602]
在项目中是按照如下使用的
let kafka = require('kafka-node');
// kafkaport :9092
let config = sails.config.kafkaInfo;
let topic = sails.config.code;
let client = new kafka.Client(config.clientString);
let HighLevelProducer = new kafka.HighLevelProducer(client);
let obj = {};
client.on('connect', function () {
    client.loadMetadataForTopics([], function (error, results) {
        let metadata = _.get(results, '1.metadata');

        HighLevelProducer.on('ready', function () {
            console.log('kafka ready');
        });
        HighLevelProducer.on('error', function (err) {
            console.log('error', err);
        });
        if (!metadata.hasOwnProperty(topic)) {
            HighLevelProducer.createTopics([topic], true, function (err, data) {
                if (err) console.log(err);
                console.log(data);
            });
        }

        obj.producer = function (msg) {
            let message = new kafka.KeyedMessage('key', JSON.stringify(msg));
            HighLevelProducer.send([
                {topic: topic, messages: [message]}
            ], function (err, data) {
                if (err) console.log(err);
                else console.log(data);
            });
        }
    });
});

在用了一段时间之后会报这个内存泄漏
(node) warning: possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at HighLevelProducer.addListener (events.js:239:17)
    at null.<anonymous> (/Users/wenlei/WebstormProjects/WYMCloud/api/services/kafka.js:14:27)
    at Client.createTopics.Client.handleReceivedData (/Users/wenlei/WebstormProjects/WYMCloud/node_modules/kafka-node/lib/client.js:740:12)
    at Socket.<anonymous> (/Users/wenlei/WebstormProjects/WYMCloud/node_modules/kafka-node/lib/client.js:700:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:537:20)

**Comment by hyperlink** [comment]
Create a new client instance (instead of sharing one with Producer) to get all the topics. As specified in the example use `once` a one time listener for the `connect` event.

**Comment by macurial** [comment]
I just use `once` for the `connect` event ,and it seemed not happen yet
