### ISSUE TITLE
Can't connect to Kafka, kafkacat works

### ISSUE THREAD

**Issue by Industrial** [SOHU-Co/kafka-node#608]
Hi.

Using the code

```js
const kafka = require('kafka-node')
const Consumer = kafka.Consumer

const client = new kafka.Client('127.0.1.1:9092')

const consumer = new Consumer(
  client,
  [
    { topic: 'test', partition: 0 },
  ]
)

consumer.on('message', (message) => {
  console.log(`MESSAGE: ${message}`)
})
```

I can't seem to connect to the running Kafka service.

When I run `kafkacat -b 127.0.1.1:9092 -t test -C` on the commandline it works. I get 5 test messages (that I put in using -P)

**Comment by hyperlink** [comment]
You need to pass in the zookeeper host instead.

**Comment by Industrial** [comment]
Okay

I've tried 0.0.0.0:2181, 127.0.0.1:2181, 127.0.1.1:2181 (hostname -i)

All with the same results.
