### ISSUE TITLE
Get the list of Brokers

### ISSUE THREAD

**Issue by nkurothe** [SOHU-Co/kafka-node#609]
I am trying to get the list of brokers after connecting to the client but when I do 
client.getBrokers() it always returns {}. 

I have set up zookeeper and broker on separate servers.
What am I doing wrong?

**Comment by nkurothe** [comment]
Need to call client.getBrokers() inside client.on('connect');!

**Comment by hyperlink** [comment]
Hmm, that method returns the client's current connected brokers if any and it's more of a private method. You can take a look at `client.brokerProfiles` object after `ready` has been emitted there are also other ways to get a list of brokers.
