### ISSUE TITLE
ability to have custom partitioner?

### ISSUE THREAD

**Issue by bkim54** [SOHU-Co/kafka-node#619]
can we inject our own partitioner into the HLP?

**Comment by hyperlink** [comment]
I don't think this is possible without code change. Want to submit a PR?

**Comment by bkim54** [comment]
i was able to do it by overwriting the KeyedPartitioner prototype

`KeyedPartitioner.prototype["getPartition"] = getPartition;`

@hyperlink do you think you could approve this PR in DT? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14911 I needed to declare the KeyedPartitioner in TS

**Comment by hyperlink** [comment]
That seems dangerous. That would affect the implementation for all keyedPartitioner wouldn't it?  It should be easy to update the baseProducer's 'defaultPartitionerType' to accept a constructor function or just the `getPartition` implementation as a regular function.

**Comment by bkim54** [comment]
it would affect all keyedPartitioners yes, but in one application that seems okay? 

anyways above PR creates a new CustomPartitioner type

**Comment by phreed** [comment]
@bkim54 
Is there are reason you made the update in `master` rather than `@types`?
Unless things have changed, that is what is needed in order to get `npm install @types/kafka-node` to work correctly.
