### ISSUE TITLE
How to send msg  to remote kafka?

### ISSUE THREAD

**Issue by wc188996** [SOHU-Co/kafka-node#621]
I have two kafka servers ,local and remote .
It was successful when send msg to local kafka, but error to the remote。
The error is “ Error: connect ECONNREFUSED 127.0.0.1:9092”
It seems that the param "conf" is invalid, 

```
var kafka = require('kafka-node');
var Producer = kafka.Producer;
//var KeyedMessage = kafka.KeyedMessage;
var conf = '192.168.1.33:2181';//'127.0.0.1:2181'=successful  but '192.168.1.33:2181'=error
var client = new kafka.Client(conf);
var producer = new Producer(client);
var msg = [
    { topic: 'test', messages: 'test msg', partition: 0 }
];
producer.on('ready', function () {
    producer.send(msg, function (err) {
        if (err) { 
                console.log(err);
           } );
});
```

Thanks!

**Comment by hyperlink** [comment]
Looks like the remote one is connecting to localhost? double check you can connect to the remote broker using one of the kafka ./bin tools. Good luck!

**Comment by wc188996** [comment]
您好：
      感谢您的回答，我测试了我本地的kafka 可以和远端的kafka通信，但是通过Nodejs却不行，我仅仅想知道如何和远端的kafka进行连接，明明设置了连接远程的IP，代码启动后却连接本地的Kafka。
