### ISSUE TITLE
Connect to kafka instead of zookeeper

### ISSUE THREAD

**Issue by codeofsumit** [SOHU-Co/kafka-node#624]
afaik the latest version of kafka requires a connection to kafka, not zookeeper. Is this supported by this library?

**Comment by hyperlink** [comment]
We use this module with kafka 0.10.1.1 without any issues.

**Comment by uschen** [comment]
how to directly connect to Kafka instead of zookeeper?

**Comment by hyperlink** [comment]
@uschen checkout issue #666
