### ISSUE TITLE
sslOptions

### ISSUE THREAD

**Issue by zrwdopod** [SOHU-Co/kafka-node#628]
Could you show me a demo of options to be passed to the tls broker sockets.I have to use ssl,but i can not find any demo of this.
你是中国人哇，我用你这个库访问kafka，可是我们的kafka配置了ssl，但是在网上找不到ssl如何在kafak-node下的配置。不会用sslOptions。请指教

**Comment by hyperlink** [comment]
See Nodejs [tls.connect](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback) options.
