### ISSUE TITLE
Unable to read from the earliest available offset in ConsumerGroup

### ISSUE THREAD

**Issue by divgwd** [SOHU-Co/kafka-node#629]
Hi,
I have kafka holding system metrics data , then using consumer group to consume this data then insert it into influxdb,while doing this influxdb went down but the consumerGroup continued to consume data from kafka .Now, I want to start reading from an earlier offset than that is commited to zookeeper.I tried changing the option of fromOffset to 'earliest' but it started consuming from the latest committed offset not the earlier offset.Below is the consumer options ::
var consumerOptions = {
  host: '172.16.23.15:8086',
  groupId: 'ExampleTestGroup',
  sessionTimeout: 15000,
  protocol: ['roundrobin'],
  autoCommit: true,
  fromOffset: 'earliest', // equivalent of auto.offset.reset valid values are 'none', 'latest', 'earliest'
  //fromOffset: 'latest', // equivalent of auto.offset.reset valid values are 'none', 'latest', 'earliest'
  fetchMaxWaitMs: 1000,
  fetchMaxBytes: 1024 * 1024
};

Console Output for consumerGroup:
-----------------
12:31:45 PM - info: consumer groups options
12:31:45 PM - info:  host=172.16.23.15:8086, groupId=ExampleTestGroup, sessionTimeout=15000, protocol=[roundrobin], autoCommit=true, fromOffset=earliest, fetchMaxWaitMs=1000, fetchMaxBytes=1048576
12:31:45 PM - info: Topics 0=Aircel_Chennai
12:31:48 PM - info: consumed:357166
12:31:48 PM - info: consumed:357167
12:31:48 PM - info: consumed:357168
12:31:49 PM - info: consumed:357170
12:31:49 PM - info: consumed:357171

----------------------------------
2:48:51 PM - info: consumer groups options
2:48:51 PM - info:  host=172.16.23.15:8086, groupId=ExampleTestGroup, sessionTimeout=15000, protocol=[roundrobin], autoCommit=true, fromOffset=earliest, fetchMaxWaitMs=1000, fetchMaxBytes=1048576
2:48:51 PM - info: Topics 0=Aircel_Chennai
2:48:54 PM - info: consumed:357416
2:48:55 PM - info: consumed:357417
2:48:55 PM - info: consumed:357418
2:48:55 PM - info: consumed:357420
2:48:55 PM - info: consumed:357421
2:48:55 PM - info: consumed:357422

is there something I am doing wrong? any help is appreciated! 
thanks in advance!

**Comment by hyperlink** [comment]
the setting `fromOffset` only applies when there's no initial offset in Kafka (ConsumerGroup stores this in Kafka while HighLevelConsumer stores offsets in zookeeper). This works the same way as kafka's `auto.offset.reset`.

You will need to set a new unique groupId if you want to `fromOffset` to apply again.
