### ISSUE TITLE
kafka client fails to connect when the host name can't be resolved

### ISSUE THREAD

**Issue by kobik** [SOHU-Co/kafka-node#640]
Hi,
I have an issue connecting to kafka, when running the server locally on my mac.
I know that there is some kind of an issue in resolving host names in my networ.
So I'm passing to the client zookeeper's ip address and not the host name, still for some reason the client tries to connect to the kafka server using the host name.

```
kafka-node:ConsumerGroup Error from kafka-node-client { Error: getaddrinfo ENOTFOUND kobis-mbp kobis-mbp:9092
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'kobis-mbp',
  host: 'kobis-mbp',
  port: '9092' } +269ms
Kafka error { Error: getaddrinfo ENOTFOUND kobis-mbp kobis-mbp:9092
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'kobis-mbp',
  host: 'kobis-mbp',
  port: '9092' }```

**Comment by hyperlink** [comment]
I would check the broker config. The (advertised) hostname is probably still a hostname and not an ip address.

**Comment by qodirovshohijahon** [comment]
> I would check the broker config. The (advertised) hostname is probably still a hostname and not an ip address.

Hi bro 
how can I solve this problem
should I write smth into my docker-compose file
