### ISSUE TITLE
just one node instance consume data when node cluster use the consumerGroup

### ISSUE THREAD

**Issue by arainyu** [SOHU-Co/kafka-node#642]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

## Bug Report
Does the module support node cluster?

1. start two node instance for consumer, node cluster.
2. one instance begin consume, another one is stop.

### Environment

* Node version: v7.2.0
* Kafka-node version: lastest
* Kafka version: 0.10

### For specific cases also provide
* Number of Brokers: 2
* Number partitions for topic: 4

### Include Sample Code to reproduce behavior

```js
var client = new kafka.Client(kafkaConfig.connectString, kafkaConfig.clientId)

var consumer = new kafka.ConsumerGroup({
  host: kafkaConfig.connectString,
  zk: kafkaConfig.zkOptions,
  groupId: 'cuckoo-kafka-consumer'
}, 'yzx_test')

consumer.on('message', function (message) {
  console.log('消费消息：' + JSON.stringify(message));
})

consumer.on('error', function (err) {
  console.log('消费error：' + err);
})
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by honorcode** [comment]
With Kafka consumer group: if you want both nodes to consume all msgs from the same topic then the two nodes need to have different groupId's e.g. groupId: 'cuckoo-kafka-consumer-node-1'

**Comment by hyperlink** [comment]
Make sure the `connectString` you provided is the zookeeper host. For now the module discovers kafka brokers using zookeeper.

**Comment by arainyu** [comment]
@honorcode @hyperlink 
问题可能没描述到位，重新描述一下，让两位帮忙分析一下。
1. 现在用的是consumerGroup
2. 如果只运行一个nodejs服务，现在是可以正常消费的
3. 如果同时运行两个nodejs服务（集群方式），只有一个服务能消费数据

我想要的是：
两个nodejs服务负载均衡。比如现在有两个nodejs服务分别是node1,node2, 同时消费kafka中topic 1中的1，2，3条消息。其中node1消费1，3， node2消费2，

**Comment by arainyu** [comment]
@honorcode  @hyperlink 
we confuse how to start two efficient consumer in a consumer group. These consumer deploy on the different server for consume the same broker source.

**Comment by hyperlink** [comment]
I'm not sure what you mean by "_efficient_" consumer. Each instance of the ConsumerGroup (in the same group id) will coordinate with the broker and each other to divide up the ownership of the partition. The specific algorithm for this is called an assignment protocol and there's some  built in ones you can use as well as customize your own. Look at the [ConsumerGroup doc](https://github.com/SOHU-Co/kafka-node#consumergroup) for more details

**Comment by raeesaa** [comment]
Even I am facing similar issue with ConsumerGroup. My scenario is, we are running node process as a cluster of 2 instances and we want both the instances to consume message published to the topic. With our current setup only one consumer gets the message, is there any way to achieve this?

**Comment by hyperlink** [comment]
@raeesaa you want both instances to receive the same messages? or do you want them to distribute the message processing (each instance gets a unique message) ?

**Comment by raeesaa** [comment]
We want them to distribute message for processing.

**Comment by hyperlink** [comment]
@raeesaa make sure you have the same `groupId` for all your `ConsumerGroup` instances and it should automatically distribute the partitions among each.
