### ISSUE TITLE
Receiving same messages upon restart of consumer

### ISSUE THREAD

**Issue by bhatti** [SOHU-Co/kafka-node#643]
I am testing 0.10.2.0 version of Kafka with 3.4.9 version of zookeeper and 1.6.0 version of kafka-node. I setup a simple consumer and producer using your examples, however I am receiving same messages that were previously sent despite using latest offset. 

Here is my consumer.js:
var kafka = require('kafka-node');
var Consumer = kafka.Consumer;
var Offset = kafka.Offset;
var Client = kafka.Client;
var argv = require('optimist').argv;
var topic = argv.topic || 'sample_topic';

var client = new Client('localhost:2181');
var topics = [ 
    {topic: topic, partitions: 1}, 
    {topic: topic, partitions: 0}
];

var options = { 
  autoCommit: false,
  host: 'localhost:2181',
  ssl: false, // optional (defaults to false) or tls options hash 
  groupId: 'test_channel',
  fromOffset: 'latest', // default 
  outOfRangeOffset: 'latest' // default 
};

var consumer = new Consumer(client, topics, options);
var offset = new Offset(client);

consumer.on('message', function (message) {
  console.log(message);
    offset.commit('groupId', [
        { topic: message.topic, partition: message.partition, offset: message.offset}
        ], (err, data) => {
        });
});

I am committing offsets after receiving them.

And here is my producer.js

var kafka = require('kafka-node');
var Producer = kafka.Producer;
var KeyedMessage = kafka.KeyedMessage;
var Client = kafka.Client;
var client = new Client('localhost:2181');
var argv = require('optimist').argv;
var topic = argv.topic || 'sample_topic';
var p = argv.p || 0;                                                                                                               
var a = argv.a || 0;
var producer = new Producer(client, { requireAcks: 1 }); 

producer.on('ready', function () {
  var message = 'from kafka message ' + Date();
  var keyedMessage = new KeyedMessage('keyed', 'a keyed message ' + Date());

  producer.send([
    { topic: topic, partition: p, messages: [message, keyedMessage], attributes: a } 
  ], function (err, result) {
    console.log(err || result);
    process.exit();
  }); 
});

When I run consumer and producer, everything works but when I restart consumer, it receives messages that were previously received and committed using offset.commit API. Ideally, I would like to specify groupId and receive messages that have not received since latest offset for that groupId.

Thanks.

**Comment by hyperlink** [comment]
Can you try using the `ConsumerGroup` and see if that works better for you?

**Comment by respond-sw** [comment]
I have the similar issue using almost the same setup - after restarting, the consumer is always reading all the messages. Is the use of ConsumerGroup is the only solution?

**Comment by hyperlink** [comment]
I would recommend using the consumerGroup if you don't want to receive the same messages that group has already seen.
