### ISSUE TITLE
Fatal error C1083: Cannot open include file: librdkafka/rdkafka.h: No such file or directory

### ISSUE THREAD

**Issue by berylwilson** [SOHU-Co/kafka-node#644]
When I try use "npm install node-kafka", i get below error.

Fatal error C1083: Cannot open include file: librdkafka/rdkafka.h: No such file or directory...librdkafkabinding.vcxproj

**Comment by hyperlink** [comment]
This project is `kafka-node`.

**Comment by berylwilson** [comment]
sorry did I miss something? I got this error while trying to install node-kafka.

**Comment by berylwilson** [comment]
Thanks. It works now.
