### ISSUE TITLE
why I use ConsumerGroup, but has no message response...

### ISSUE THREAD

**Issue by jyunhan** [SOHU-Co/kafka-node#645]
Hi, I'm new in Kafka / nodejs. so, here might be a simple question...  =[

I'd like to connect to a kafka broken as a consumer.
the follow is the kafka & develop environment info:
- **host:** 192.168.2.137:9092
- **groupid:** '1'
- **version**: 0.10.1
- **nodejs:** 6.9.4
- **kafka-node:** 1.6.0
- **OS:** windows7 64bit
- **Java and Scala consumer implementations have no problems consuming these topics**

In node.js, when I try to fetch a **topic [ named: topic1 ]**,
there are no response display, neither success msg nor error msg.
could anyone tell me how to get the message correctly?? ...

here is my current code below:

	var kafka = require('kafka-node'),
		ConsumerGroup = kafka.ConsumerGroup,
		topics = ['topic1'];

	var createConsumer = function(topics) {
    		var consumerGroup = new ConsumerGroup(
	  	  	{
				ssl: false,
	   	 		groupId: '1',
		    		host: '192.168.2.137:9092',
	    			sessionTimeout: 30000,
	    			fromOffset: 'earliest',
		    		migrateHLC: false,
				migrateRolling: false,
				fetchMaxBytes: 1024 * 100,
				fetchMinBytes: 1,
				fetchMaxWaitMs: 100,
				autoCommit: true,
				autoCommitIntervalMs: 5000
		    	},
		    	topics
	    	);

		consumerGroup.on('error', onError);
		consumerGroup.on('message', onMessage);

    		function onError (error) {
			console.error(error);
			console.error(error.stack);
		}

		function onMessage (message) {
			console.log(message);
		}
	}
	createConsumer(topics);

**Comment by serialLinker** [comment]
Did you try to enable logs ?
DEBUG=kafka-node:* node <app>.js

**Comment by hyperlink** [comment]
The `host` should point to zookeeper address. In future release we will have a client that will connect to kafka brokers only.

**Comment by jyunhan** [comment]
Thanks for your answer..., 
Then I change the host to zookeeper address, and it's working!!!
It's look forward to new features  :-D
