### ISSUE TITLE
consumer group restart cause CPU load high

### ISSUE THREAD

**Issue by gogorush** [SOHU-Co/kafka-node#647]
## Questions?
I am using ConsumerGroup in my production environment, but running into an error whenever I restart my servers, the CPU load on those machines running to 100%, and traffic load is dramatically increased. 

### Environment
* Node version: v6.6.0
* Kafka-node version: v1.6.0
* Kafka version: 0.9 

### For specific cases also provide
* Number of Brokers: 60
* Number partitions for topic:200

My consumer group settings
```js
let zookeeperOptions = {
  sessionTimeout: 10000
};
var consumerOptions = {
  host: config.KAFKA_SERVER_ADDRESS,
  groupId: 'node-lbs',
  zk: zookeeperOptions,
  sessionTimeout: 10000,
  protocol: ['roundrobin'],
  fromOffset: 'latest' // equivalent of auto.offset.reset valid values are 'none', 'latest', 'earliest'
};

```

not sure if this caused by the fromOffset : 'latest' not working, the following is the offset info : 
Group           Topic                          Pid Offset          logSize         Lag             Owner
node-lbs        lbs.location                   0   695964697       698907607       2942910         none
node-lbs        lbs.location                   1   694153813       698862961       4709148         none
node-lbs        lbs.location                   2   663943771       667228968       3285197         none
node-lbs        lbs.location                   3   694526170       697932859       3406689         none
node-lbs        lbs.location                   4   694675111       698220206       3545095         none
node-lbs        lbs.location                   5   698911737       701724524       2812787         none
node-lbs        lbs.location                   6   697583757       702544010       4960253         none
node-lbs        lbs.location                   7   668768667       672790927       4022260         none
node-lbs        lbs.location                   8   699908573       703072280       3163707         none
node-lbs        lbs.location                   9   697646129       700713093       3066964         none
node-lbs        lbs.location                   10  698312675       703074576       4761901         none
node-lbs        lbs.location                   11  653779932       657330985       3551053         none
node-lbs        lbs.location                   12  698082480       702622731       4540251         none
node-lbs        lbs.location                   13  696370536       699910817       3540281         none
node-lbs        lbs.location                   14  694158425       698007356       3848931         none
node-lbs        lbs.location                   15  696016954       699888606       3871652         none
node-lbs        lbs.location                   16  696374318       700841866       4467548         none
node-lbs        lbs.location                   17  679258579       683123651       3865072         none
node-lbs        lbs.location                   18  697441274       701774379       4333105         none
node-lbs        lbs.location                   19  695993121       699446130       3453009         none
node-lbs        lbs.location                   20  670628821       673905235       3276414         none
node-lbs        lbs.location                   21  694908197       698728894       3820697         none
node-lbs        lbs.location                   22  695235561       699460207       4224646         none
node-lbs        lbs.location                   23  694407632       698756585       4348953         none
node-lbs        lbs.location                   24  696426561       700143222       3716661         none
node-lbs        lbs.location                   25  695927357       698343093       2415736         none
node-lbs        lbs.location                   26  695867823       698831066       2963243         none
node-lbs        lbs.location                   27  662540950       665244978       2704028         none
node-lbs        lbs.location                   28  695824398       698849605       3025207         none
node-lbs        lbs.location                   29  661174809       664806060       3631251         none
node-lbs        lbs.location                   30  696859869       700250515       3390646         none
node-lbs        lbs.location                   31  663223396       666154227       2930831         none
node-lbs        lbs.location                   32  693522451       696822164       3299713         none
node-lbs        lbs.location                   33  695478010       698669571       3191561         none
node-lbs        lbs.location                   34  696424083       699348395       2924312         none
node-lbs        lbs.location                   35  696796421       699777068       2980647         none
node-lbs        lbs.location                   36  697121569       699434895       2313326         none
node-lbs        lbs.location                   37  696218774       699232541       3013767         none
node-lbs        lbs.location                   38  698154709       701345590       3190881         none
node-lbs        lbs.location                   39  698658026       701901485       3243459         none
node-lbs        lbs.location                   40  700539061       702761472       2222411         none
node-lbs        lbs.location                   41  695326738       698024215       2697477         none
node-lbs        lbs.location                   42  696728816       699666245       2937429         none
node-lbs        lbs.location                   43  698735156       701861783       3126627         none
node-lbs        lbs.location                   44  694707544       698711130       4003586         none
node-lbs        lbs.location                   45  699544378       702586702       3042324         none
node-lbs        lbs.location                   46  698924046       701154662       2230616         none
node-lbs        lbs.location                   47  696328784       699550634       3221850         none
node-lbs        lbs.location                   48  699776262       701992835       2216573         none
node-lbs        lbs.location                   49  694448177       697836953       3388776         none
node-lbs        lbs.location                   50  696211983       698758111       2546128         none
node-lbs        lbs.location                   51  697316344       699369764       2053420         none
node-lbs        lbs.location                   52  695561961       698409816       2847855         none
node-lbs        lbs.location                   53  698915616       701766682       2851066         none
node-lbs        lbs.location                   54  695755526       699183285       3427759         none
node-lbs        lbs.location                   55  695909860       699067309       3157449         none
node-lbs        lbs.location                   56  661382168       664457320       3075152         none
node-lbs        lbs.location                   57  696296512       699107350       2810838         none
node-lbs        lbs.location                   58  665957163       669318340       3361177         none
node-lbs        lbs.location                   59  694287807       698011755       3723948         none
node-lbs        lbs.location                   60  665500104       669103075       3602971         none
node-lbs        lbs.location                   61  694753966       698574940       3820974         none
node-lbs        lbs.location                   62  695657315       699127602       3470287         none
node-lbs        lbs.location                   63  695066112       698510297       3444185         none
node-lbs        lbs.location                   64  663402793       665979645       2576852         none
node-lbs        lbs.location                   65  699749494       702891067       3141573         none
node-lbs        lbs.location                   66  698026301       700875150       2848849         none
node-lbs        lbs.location                   67  697631510       700154964       2523454         none
node-lbs        lbs.location                   68  699737476       701582777       1845301         none
node-lbs        lbs.location                   69  701017085       703631807       2614722         none
node-lbs        lbs.location                   70  696191402       699760967       3569565         none
node-lbs        lbs.location                   71  697197606       700635989       3438383         none
node-lbs        lbs.location                   72  696950552       699259783       2309231         none
node-lbs        lbs.location                   73  691913667       695509761       3596094         none
node-lbs        lbs.location                   74  695979893       698708296       2728403         none
node-lbs        lbs.location                   75  697335927       700524017       3188090         none
node-lbs        lbs.location                   76  693723850       696688916       2965066         none
node-lbs        lbs.location                   77  696804115       699870521       3066406         none
node-lbs        lbs.location                   78  697907337       701196266       3288929         none
node-lbs        lbs.location                   79  696721140       699243125       2521985         none
node-lbs        lbs.location                   80  698171737       700515616       2343879         none
node-lbs        lbs.location                   81  697133722       699674784       2541062         none
node-lbs        lbs.location                   82  697944693       700970755       3026062         none
node-lbs        lbs.location                   83  698226320       700284871       2058551         none
node-lbs        lbs.location                   84  698314782       700680185       2365403         none
node-lbs        lbs.location                   85  662535952       664759996       2224044         none
node-lbs        lbs.location                   86  695997802       698488520       2490718         none
node-lbs        lbs.location                   87  663709349       666043406       2334057         none
node-lbs        lbs.location                   88  697025472       699071430       2045958         none
node-lbs        lbs.location                   89  693033329       695830013       2796684         none
node-lbs        lbs.location                   90  696214663       698964991       2750328         none
node-lbs        lbs.location                   91  695390849       698585859       3195010         none
node-lbs        lbs.location                   92  696408738       699498231       3089493         none
node-lbs        lbs.location                   93  659404136       662143535       2739399         none
node-lbs        lbs.location                   94  695397897       697790718       2392821         none
node-lbs        lbs.location                   95  696627391       699515047       2887656         none
node-lbs        lbs.location                   96  696988992       700311192       3322200         none
node-lbs        lbs.location                   97  694706870       698103512       3396642         none
node-lbs        lbs.location                   98  698218266       700553751       2335485         none
node-lbs        lbs.location                   99  695621620       698068996       2447376         none
node-lbs        lbs.location                   100 544883128       547889495       3006367         none
node-lbs        lbs.location                   101 545438725       548801805       3363080         none
node-lbs        lbs.location                   102 544518784       548032126       3513342         none
node-lbs        lbs.location                   103 544552871       547260712       2707841         none
node-lbs        lbs.location                   104 546113949       548353149       2239200         none
node-lbs        lbs.location                   105 546804027       549755550       2951523         none
node-lbs        lbs.location                   106 545588023       548127222       2539199         none
node-lbs        lbs.location                   107 545072183       547862973       2790790         none
node-lbs        lbs.location                   108 545526163       548415448       2889285         none
node-lbs        lbs.location                   109 547548153       549375437       1827284         none
node-lbs        lbs.location                   110 543645082       546778833       3133751         none
node-lbs        lbs.location                   111 544300826       547409095       3108269         none
node-lbs        lbs.location                   112 546213177       548448876       2235699         none
node-lbs        lbs.location                   113 545423853       547268569       1844716         none
node-lbs        lbs.location                   114 544811327       547519620       2708293         none
node-lbs        lbs.location                   115 546161825       549005304       2843479         none
node-lbs        lbs.location                   116 546114173       549050869       2936696         none
node-lbs        lbs.location                   117 546458518       548480049       2021531         none
node-lbs        lbs.location                   118 546951950       549431840       2479890         none
node-lbs        lbs.location                   119 546570161       548480578       1910417         none
node-lbs        lbs.location                   120 548052618       550192629       2140011         none
node-lbs        lbs.location                   121 545817045       548803234       2986189         none
node-lbs        lbs.location                   122 543289527       545479729       2190202         none
node-lbs        lbs.location                   123 545628756       548271967       2643211         none
node-lbs        lbs.location                   124 545666340       548086490       2420150         none
node-lbs        lbs.location                   125 544449074       548214306       3765232         none
node-lbs        lbs.location                   126 547177169       549515924       2338755         none
node-lbs        lbs.location                   127 546641439       549776941       3135502         none
node-lbs        lbs.location                   128 545344023       548874201       3530178         none
node-lbs        lbs.location                   129 546344015       549225103       2881088         none
node-lbs        lbs.location                   130 546649043       549533355       2884312         none
node-lbs        lbs.location                   131 502514510       504726063       2211553         none
node-lbs        lbs.location                   132 544276239       546946027       2669788         none
node-lbs        lbs.location                   133 544994846       547526121       2531275         none
node-lbs        lbs.location                   134 545408634       547550873       2142239         none
node-lbs        lbs.location                   135 545233894       548175606       2941712         none
node-lbs        lbs.location                   136 545728568       548697843       2969275         none
node-lbs        lbs.location                   137 528397621       530271723       1874102         none
node-lbs        lbs.location                   138 546667327       549290889       2623562         none
node-lbs        lbs.location                   139 543205026       546672821       3467795         none
node-lbs        lbs.location                   140 544764868       546998021       2233153         none
node-lbs        lbs.location                   141 543166828       545997899       2831071         none
node-lbs        lbs.location                   142 546368300       549043316       2675016         none
node-lbs        lbs.location                   143 543939486       546875163       2935677         none
node-lbs        lbs.location                   144 546378066       548839167       2461101         none
node-lbs        lbs.location                   145 545740107       548520700       2780593         none
node-lbs        lbs.location                   146 545799889       548977033       3177144         none
node-lbs        lbs.location                   147 545323903       547846764       2522861         none
node-lbs        lbs.location                   148 547918903       551149042       3230139         none
node-lbs        lbs.location                   149 545097438       547559041       2461603         none
node-lbs        lbs.location                   150 546204128       548342408       2138280         none
node-lbs        lbs.location                   151 544539176       547068558       2529382         none
node-lbs        lbs.location                   152 546099420       548296247       2196827         none
node-lbs        lbs.location                   153 544007026       546207304       2200278         none
node-lbs        lbs.location                   154 546604011       548916306       2312295         none
node-lbs        lbs.location                   155 543879753       546105252       2225499         none
node-lbs        lbs.location                   156 546463774       549544169       3080395         none
node-lbs        lbs.location                   157 546398591       548641024       2242433         none
node-lbs        lbs.location                   158 543153708       546192185       3038477         none
node-lbs        lbs.location                   159 545717201       547714979       1997778         none
node-lbs        lbs.location                   160 547890189       550378525       2488336         none
node-lbs        lbs.location                   161 545589932       548546798       2956866         none
node-lbs        lbs.location                   162 544929063       547566681       2637618         none
node-lbs        lbs.location                   163 545627239       547942133       2314894         none
node-lbs        lbs.location                   164 547896004       551226138       3330134         none
node-lbs        lbs.location                   165 546747064       549723198       2976134         none
node-lbs        lbs.location                   166 547018039       549901752       2883713         none
node-lbs        lbs.location                   167 544310563       547811494       3500931         none
node-lbs        lbs.location                   168 546512604       549811935       3299331         none
node-lbs        lbs.location                   169 543016309       546541204       3524895         none
node-lbs        lbs.location                   170 545826977       548226132       2399155         none
node-lbs        lbs.location                   171 544327768       547425524       3097756         none
node-lbs        lbs.location                   172 545524109       548144918       2620809         none
node-lbs        lbs.location                   173 543294365       546407522       3113157         none
node-lbs        lbs.location                   174 544732366       547946350       3213984         none
node-lbs        lbs.location                   175 543716380       546152266       2435886         none
node-lbs        lbs.location                   176 544889161       548788541       3899380         none
node-lbs        lbs.location                   177 544278897       546965465       2686568         none
node-lbs        lbs.location                   178 545284935       549101868       3816933         none
node-lbs        lbs.location                   179 544172185       548206964       4034779         none
node-lbs        lbs.location                   180 545658038       548839096       3181058         none
node-lbs        lbs.location                   181 542896848       545927310       3030462         none
node-lbs        lbs.location                   182 545645116       548101448       2456332         none
node-lbs        lbs.location                   183 545687887       548631918       2944031         none
node-lbs        lbs.location                   184 544755466       548649509       3894043         none
node-lbs        lbs.location                   185 547368902       550214717       2845815         none
node-lbs        lbs.location                   186 545515814       548840270       3324456         none
node-lbs        lbs.location                   187 501917510       503933275       2015765         none
node-lbs        lbs.location                   188 545040940       548510741       3469801         none
node-lbs        lbs.location                   189 541666041       545849283       4183242         none
node-lbs        lbs.location                   190 544752531       548645950       3893419         none
node-lbs        lbs.location                   191 543437868       546628933       3191065         none
node-lbs        lbs.location                   192 543791560       547395049       3603489         none
node-lbs        lbs.location                   193 543362625       547189523       3826898         none
node-lbs        lbs.location                   194 542907806       546258099       3350293         none
node-lbs        lbs.location                   195 545079884       548546884       3467000         none
node-lbs        lbs.location                   196 500601317       502784083       2182766         none
node-lbs        lbs.location                   197 526450226       529876599       3426373         none
node-lbs        lbs.location                   198 544501744       548852011       4350267         none
node-lbs        lbs.location                   199 542639153       547488343       4849190         none

Nothing changed when I restart my servers.

Any help @hyperlink

**Comment by hyperlink** [comment]
`fromOffset` only applies to a newly created group. If the group already existed before it will use the offsets recently committed.

Do you have one instance of `ConsumerGroup` ? If there's a lot of lag (looks like it) and a lot of partitions that single consumer owns then it's reasonable the consumer is doing a lot of work to "catch up" to the current offsets (the lag is fairly high in your example).

I would recommend creating more instances of your `node-lbs` consumer group in different servers if you could but at the very least separate processes. Good luck!

**Comment by gogorush** [comment]
There are 200 ConsumerGroup in my production environment. I digged into the problem later, seems the problem caused because producers produce too fast that consumers can not consume them in time. Thx for the quick response @hyperlink
