### ISSUE TITLE
when i deployed 2 nodejs servers to consume the same topic, one message is processed by both servers, but these 2 consumers' groupId are the same

### ISSUE THREAD

**Issue by Uoliver** [SOHU-Co/kafka-node#651]
## Questions?
when i deployed 2 nodejs servers to consume the same topic(for an example, the consumers are consumer 1, consumer 2), one message is processed by consumer 1, consumer 2 at the same time, but these 2 consumers' groupId are the same(ExampleTestGroup). 
i think only one consumer will consume the incoming message at the same time if i specify the groupId.
Please help to see if i missing some config. 
Thanks in advance!

### Environment

* Node version: v6.10.0
* Kafka-node version: kafka-node@1.6.0
* Kafka version: kafka_2.12-0.10.2.0
*zookeeper version: zookeeper-3.4.9

### below is the script to create the test topic
kafka-topics.bat --create --zookeeper localhost:2180 --replication-factor 1 --partitions 1 --topic TEST2

### Include Sample Code to reproduce behavior

```js
let client=new kafka.Client("localhost:2180");
  let consumer = new Consumer(
    client,
    [
      { topic: 'TEST2'}
    ],
    {
      autoCommit: true,
      groupId: 'ExampleTestGroup'
    }
  );
  client.on('ready', function(){
    console.log('Consumer is Ready,consumer groupid:'+consumer.options.groupId);
  });
  consumer.on('message', function (message) {
    console.log("Received an message at:"+new Date());
    try{
      console.log(message.value);
    }catch(e){
      console.log(chalk.bold.red("error occured, during process email message: "+e.message));
    }
  });
  consumer.on('error', function (err) {
  console.log("error:  " + err);
});
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by hyperlink** [comment]
Try using `ConsumerGroup` instead. It takes different options but it should be what you need.

**Comment by Uoliver** [comment]
@hyperlink . Thanks for your suggestion.
I used below code to do the testing(my testing environment is a stand-alone server, one zookeeper server and one kafka broker), but failed with this error:
Error in consumer: **NotCoordinatorForGroup: Kafka Error Code: 16**

may you help to share any ideas about this?

  var options = {
    host: "192.168.18.1:2181",
    groupId: "test-consumer-group",
    sessionTimeout: 20000,
    id: "consumer1",
    autoCommit: true
  };
  var topics = ['TEST2'];
  var consumerGroup = new ConsumerGroup(options, ['TEST2']);
  consumerGroup.on('connect', function () {
    console.log("Consuming Kafka %s, topic=%s", JSON.stringify(options), topics);
  });
  consumerGroup.on('message', function (message) {
    console.log('%s read msg Topic="%s" Partition=%s Offset=%d', this.client.clientId, message.topic, message.partition, message.offset);
    console.log(message.value);
  });
  consumerGroup.on('error', function (err) {
    console.log("Error in consumer: " + err);
  });

**Comment by michallevin** [comment]
@hyperlink @Uoliver 
Running 2 process that each have a **consumerGroup with the same group-id** read from the same topic and commit each message manually using sendOffsetCommitRequest results in **both consumers reading all messages. Is this a bug or expected behavior?** Is the "locking" of partitions controlled by the client or by Kafka?

**Comment by hyperlink** [comment]
For `ConsumerGroup` the "locking" is done by restricting committing offsets to clients who are members of the group. HLC offsets are tracked through zookeeper and anybody who can connect to zookeeper will be able modify that.

More details are in the [kafka protocol guide](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol).

**Comment by michallevin** [comment]
@hyperlink Do you have any guesses why two clients of the same group id will ready messages from the same partition at the same time?

**Comment by hyperlink** [comment]
@michallevin I don't think that should happen the `ConsumerGroup` or `HighLevelConsumer`. Are you currently seeing that issue?

**Comment by michallevin** [comment]
@hyperlink Yep. If I run the following code at the same time from two different terminal windows, I am seeing the same messages being read from the same partition:

```
const kafka = require('kafka-node');
const sleep = require('sleep');

const options = {
  groupId: 'testing',
  autoCommit: true,
  host: '127.0.0.1:2181',
  sessionTimeout: 15000,
  protocol: ['roundrobin'],
  fromOffset: 'earliest'
};

const client = new kafka.Client();
const offset = new kafka.Offset(client);

const ConsumerGroup = kafka.ConsumerGroup;
const consumerGroup1 = new ConsumerGroup(options, ['Test']);

consumerGroup1.on('message', (message) => {
  console.log(`topic ${message.topic} partition ${message.partition} offset ${message.offset}`);

  consumerGroup1.sendOffsetCommitRequest([{
                                        topic: message.topic,
                                        partition: message.partition, //default 0
                                        offset: message.offset,
                                        metadata: 'm', //default 'm'
                                     }], (err, data) => {
                                     console.log("successfully committed");
                                     console.log("err:" + err);
                                     console.log("data: " + data);
                                     });
  sleep.sleep(120
  );
});

consumerGroup1.on('error', (error) => {
  console.log(error);
});
```

**Comment by michallevin** [comment]
By the way, we are using Kafka version 0.10 :)

**Comment by hyperlink** [comment]
The sleep can cause some problems if it does halts the eventloop.

What happens if you remove it?

Also turn on debugging by adding `DEBUG=kafka-node:*` before `node` and see what it says.

**Comment by michallevin** [comment]
@hyperlink I removed it and it looks like it's working! Thank you very much for the help.

**Comment by hyperlink** [comment]
@Uoliver are you still having issues?

**Comment by Uoliver** [comment]
@hyperlink I am just planning to tell you about this thing. I found out quite by accident that my ConsumerGroup can connect another stand-alone kafka server. Seems this issue only happens in its my local kafka server.
But when i migrated my consumer from HLC to ConsumerGroup, i found the offset is not changed after consumed one message. I find these words "**Offsets, group members, and ownership details are not stored in Zookeeper**", but when i created a new ConsumerGroup, the offset is changed accordingly after one message has been consumed.
Below code for your reference. And attached a screenshot to show the difference between end and offset.
`
function startKafkaConsumerGroup(consumerGroup, topics, callback) {
  var consumerGroupT = new ConsumerGroup(Object.assign({ id: 'keywordConsumer' }, {
    host: config.kafkaConnectURI,
    groupId: consumerGroup,
    sessionTimeout: 15000,
    protocol: ['roundrobin'],
    fromOffset: 'earliest', // equivalent of auto.offset.reset valid values are 'none', 'latest', 'earliest'
    migrateHLC: true, // default is false
    migrateRolling: false // default is true
  }), topics);
  consumerGroupT.on('error', function (err) {
    console.log(chalk.bold.red("Consumer group: " + consumerGroup + " failed, error:", err));
  });
  consumerGroupT.on('message', function (message) {
    let messageValue = message.value;
    winston.info("Partition:" + message.partition + ",message value:" + messageValue + ", time: " + new Date().toLocaleString());
    try {
      callback(messageValue);
    }
    catch (e) {
      winston.error("Consumer group: " + consumerGroup + " processed failed at " + new Date().toLocaleString()
        + ", message content: " + messageValue + ", error:" + e);
    }
  });
  consumerGroupT.on('connect', function () {
    winston.warn(chalk.bold.red("Consumer group: " + consumerGroup + " is connected."));
  });


}
`
![customer mapper](https://cloud.githubusercontent.com/assets/10161949/26294511/e61a5f18-3ef6-11e7-9ca9-cc2df9c88e6a.png)

**Comment by hyperlink** [comment]
@Uoliver could you add the output with `DEBUG=kafka-node:*` activated? That may give a better picture.

**Comment by Uoliver** [comment]
@hyperlink seems it is the util's issue. i have used the command line to see it is correct.
