### ISSUE TITLE
HighLevelConsumer - SSL Connection Issue

### ISSUE THREAD

**Issue by Madan-Gopal-Devadoss** [SOHU-Co/kafka-node#652]
**Questions?**

Im trying to use HighLevelConsumer to make an SSL connection to Kafka Server (by basically passing the sslOption to the Client creation API)

It tried with both pem file and pfx file. I haven't been able to solve the issue.

I did see a similar issue reported @ https://github.com/SOHU-Co/kafka-node/issues/478. The recommendation here was to check for client.ssl & client.brokerProfiles. What are these and where are these located? (i am sorry if the question is too naive)

**Bug Report**
 
Environment

Node version: v0.10.48
Kafka-node version: kafka-node@0.3.2
Kafka version: 0.10.0.0 
*zookeeper version: zookeeper-3.4.6

**Include Sample Code to reproduce behavior**

var kafka = require('..');
var fs = require('fs'),
    path = require('path');
var HighLevelConsumer = kafka.HighLevelConsumer;
var Client = kafka.Client;
var argv = require('optimist').argv;
var topic = argv.topic || '<topic name>';

var sslOption = {
    rejectUnauthorized: false,
    key: fs.readFileSync(Path to cert key pem file),
    cert: fs.readFileSync(Path to cert pem file),
    ca: fs.readFileSync(CA cert file pem file)
};

// I also tried with Pfx file
//var sslOption = {
//     rejectUnauthorized: false,
//     pfx: fs.readFileSync(Pfx File Path),
//     passphrase: 'Pass Phrase',
//     requestCert: true
//};

var client = new Client(<Zookeeper Service Name>+':2181',
                        'kafka-node-client',
                         {},
                         {},
                         sslOption
                       );
var topics = [ { topic: topic }];
var options = { autoCommit: true, fetchMaxWaitMs: 1000, fetchMaxBytes: 1024*1024 };
var consumer = new HighLevelConsumer(client, topics, options);
consumer.on('message', function (message) {}
consumer.on('error', function (err) {}

**Comment by hyperlink** [comment]
Why would you using such an old version of `kafka-node`? There's been fixes in area dealing with SSL since 0.3.2.

**Comment by Madan-Gopal-Devadoss** [comment]
Thank you for the response. I am constrained to use Cent OS 6.8. Latest version of kafka-node needs node engine 4.7.7 or later. Unfortunately this also means I need access to gcc 4.8.2 or more (a C++ 11 compatible compiler). I can't find an easy way to get gcc 4.8.2 or greater on CentOS 6.8. What do you recommend? I truly appreciate your response. I would like to move to the latest version of kafka-node if possible on CentOS 6.8

**Comment by hyperlink** [comment]
I am not familiar with Cent OS. Do you need to use snappy compression? Otherwise you can install `kafka-node` with --no-optional as documented [here](https://github.com/SOHU-Co/kafka-node#what-are-these-node-gyp-and-snappy-errors).

**Comment by hyperlink** [comment]
@Madan-Gopal-Devadoss did this work for you?
