### ISSUE TITLE
fetchOffsets is never calling callback when requesting offset for a non-existent topic

### ISSUE THREAD

**Issue by Kingles** [SOHU-Co/kafka-node#661]
### Environment

* Node version: v6.10.2
* Kafka-node version: v1.6.0
* Kafka version: v0.10.1.0

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: 1

### Include Sample Code to reproduce behavior

```js
const options = { zookeeper: 'localhost:2181', name: 'my-cool-thing' };
const client = new Kafka.Client(options.zookeeper, options.name);
const offset = new Kafka.Offset(client);
offset.fetchLatestOffsets(['nonexistent-topic'], (err, offsets) => {
  // this callback is never fired
});
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on
No output - logging isn't done in `offset.js`

**Comment by hyperlink** [comment]
Published as 1.6.1
