### ISSUE TITLE
How work with few zookeepers and few brokers ?

### ISSUE THREAD

**Issue by Koval-Sergey** [SOHU-Co/kafka-node#664]
Hi guys. 
I have problem in work with few brokers and zookeepers. 
For example I have 2 brokers: 
-kafka1.broker:9092;
-kafka2.broker:9092;
and 2 zookeepers: 
-kafka1.zookeper:2181;
-kafka2.zookeper:2181.
I tried wrote zookeepers in connectinString separated by a comma, but i got errors: 
`info: [Warnings] error Error
    at ConnectionManager.onSocketData (C:\VIP Box\node_modules\node-zookeeper-client\lib\ConnectionManager.js:570:35)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:559:20)`
Can you explain what I should set up for making good integration with few zookeepers and brokers ?

P.S. 
With one zookeeper and broker, which have next name: 'kafka.example.connection:9092' and 'kafka.example.connection:2181' all works well. And I don't get any errors. 

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

### Environment

* Node version: 7.8.0
* Kafka-node version: 1.6.0
* Kafka version:

### For specific cases also provide
* Number of Brokers: 2
* Number partitions for topic: default

### Include Sample Code to reproduce behavior
```js
//Consumer: 
let kafka = require('..');
            let Consumer = kafka.HighLevelConsumer;
            let Client = kafka.Client;
            let topic = 'kafka_topic_name';
            let client = new Client('kafka1.zookeper:2181,kafka2.zookeper:2181');
            let topics = [
                {topic: topic, partition: 1}
            ];

            let options = {autoCommit: true, groupId: 'snow_consumer', fetchMaxWaitMs: 1000, fetchMaxBytes: 1024 * 1024, fromOffset: 'latest'};
            let consumer = new Consumer(client, topics, options);

//Producer: 
let kafka = require('..');
            let Producer = kafka.Producer;
            let Client = kafka.Client;
            let client =new Client('kafka1.zookeper:2181,kafka2.zookeper:2181');
            let argv = require('optimist').argv;
            let topic = 'kafka_topic_name';
            let p = argv.p || 0;
            let a = argv.a || 0;
            let producer = new Producer(client, {requireAcks: 1});
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

 kafka-node:zookeeper Failed to list children of node: /brokers/ids due to: Exception: NO_NODE[-101]. +0ms
info: [Warnings] error Error
    at ConnectionManager.onSocketData (C:\VIP Box\node_modules\node-zookeeper-client\lib\ConnectionManager.js:570:35)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:559:20)
info: [Warnings] error Error
    at ConnectionManager.onSocketData (C:\VIP Box\node_modules\node-zookeeper-client\lib\ConnectionManager.js:570:35)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:559:20)

Thank you a lot guys ! Hope for your help !

**Comment by hyperlink** [comment]
Looks like the brokers are not available according to zookeeper.  Are you're brokers setup to use the zookeeper instances?

**Comment by KovalSerhii** [comment]
Hi @hyperlink . I'm not sure. Before I used the same broker and zookeeper, also connection string had only one connect-point.
Can you explain how I can set up brokers to use zookeeper instances ?

**Comment by hyperlink** [comment]
There are docs to configure kafka can be found on their website https://kafka.apache.org.

If you're just interested in just testing the module it maybe easier to use dockerized version. These containers has kafka and zookeeper already configured. There are a couple out there but you can use the one this project uses.  Check out the code and look at https://github.com/SOHU-Co/kafka-node#running-tests
