### ISSUE TITLE
How to connect to Kafka with SSL endpoint enabled?

### ISSUE THREAD

**Issue by lucaslago** [SOHU-Co/kafka-node#675]
We are struggling with SSL configuration to connect to a SSL enabled endpoint.

It would be awesome to have an example on how to achieve that in the project README.md. Maybe an SSL connection section?

**Comment by Juraci** [comment]
+1 on that, the Readme only mentions that it's necessary to pass a sslOptions object to the Client constructor but there are no documentation about what those options are.

**Comment by hyperlink** [comment]
We pass [those options](https://github.com/SOHU-Co/kafka-node/blob/master/lib/client.js#L661) directly to `tls.connect` call. See node's [TLS module](https://nodejs.org/dist/latest-v6.x/docs/api/tls.html)

We also test SSL in our [code](https://github.com/SOHU-Co/kafka-node/blob/master/test/test.highlevelProducer.js#L20). Hope that helps.
