### ISSUE TITLE
kafka partitioner not working as expected

### ISSUE THREAD

**Issue by vincentvc** [SOHU-Co/kafka-node#676]
Hi all, 

In my case, I would like to produce the message with partition type 2, which is cyclic. And then I check my kafka message with kafka-manager with it seems that all the message are directed to partition 0 only. My code:

```
let option = {
    requireAcks: 1,
    ackTimeoutMs: 100,
    partitionerType: 2
  }

 let client = new kafka.Client('connection string','name'),
 let producer = new Producer(client,option);
 var payloads = [
        { topic: 'Topic', messages: 'hi'}
   ];
  producer.send(payloads, function (err, data) {
          console.log(data);
  });
```

And then, what the only data I got is:

In console:

`{ 'TOPIC': { '0': offset} }`

In kafka-manager only partition 0 has changes in its latest offset.

Also, I tried the HighLevelProducer, but it results the same. Did I misunderstand something about the partition type?  Will producer help me to decide the partition if I don't classify the partition in payload like in my code? Thanks in advance.

* Node version: 4.2.4
* Kafka-node version: 4.0.2
* Kafka version: 2.0

* Number of Brokers:  6
* Number partitions for topic: 3

**Comment by hyperlink** [comment]
did you call `client.refreshMetadata` before sending the first message?

**Comment by vincentvc** [comment]
@hyperlink 

I did try calling `client.refreshMetadata` before sending first message. But It gave me error in Client.js:481

```
if (!topicNames.length) return cb();
                 ^
TypeError: Cannot read property 'length' of undefined****
```
So now my work around is to call loadMetadataForTopics(['TOPIC']) and updateMetadatas before sending and it works.
