### ISSUE TITLE
Have roundrobin with HighLevelProducer?

### ISSUE THREAD

**Issue by hieuit7** [SOHU-Co/kafka-node#678]
### Environment

* Node version: 6.9.5
* Kafka-node version: 1.6.2
* Kafka version: 2.11

### For specific cases also provide
* Number of Brokers: 5
* Number partitions for topic: 8

### Include Sample Code to reproduce behavior

```js

var kafka = require('kafka-node'),
  HighLevelProducer = kafka.HighLevelProducer,
  client = new kafka.Client('myhost', 'client02'),
  producer = new HighLevelProducer(client);
// client.refreshMetadata()
var debug = require('debug')('producer');
var payloads = [
  { topic: 'test2', messages: ["The message tesst", "have message"] }
];


producer.on('ready', function () {
  // client.refreshMetadata()
  setInterval(() => {
    producer.send(payloads, function (err, data) {
      debug('Send messagge: ', data);
    });
  }, 1000);
});
producer.on('error', (e) => {
  debug(e);
})
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on
```shell
producer Send messagge:  { test2: { '0': 1577 } } +1s
  producer Send messagge:  { test2: { '0': 1581 } } +1s
  producer Send messagge:  { test2: { '0': 1585 } } +1s
  producer Send messagge:  { test2: { '0': 1589 } } +1s
  producer Send messagge:  { test2: { '0': 1593 } } +1s
  producer Send messagge:  { test2: { '0': 1597 } } +1s
  producer Send messagge:  { test2: { '0': 1601 } } +1s
  producer Send messagge:  { test2: { '0': 1605 } } +1s
  producer Send messagge:  { test2: { '0': 1609 } } +1s
  producer Send messagge:  { test2: { '0': 1613 } } +1s
  producer Send messagge:  { test2: { '0': 1617 } } +1s
  producer Send messagge:  { test2: { '0': 1621 } } +995ms
  producer Send messagge:  { test2: { '0': 1625 } } +1s
  producer Send messagge:  { test2: { '0': 1629 } } +1s
  producer Send messagge:  { test2: { '0': 1633 } } +1s
  producer Send messagge:  { test2: { '0': 1637 } } +1s
  producer Send messagge:  { test2: { '0': 1641 } } +1s
  producer Send messagge:  { test2: { '0': 1645 } } +1s
  producer Send messagge:  { test2: { '0': 1649 } } +1s
  producer Send messagge:  { test2: { '0': 1653 } } +1s
  producer Send messagge:  { test2: { '0': 1657 } } +1s
  producer Send messagge:  { test2: { '0': 1661 } } +1s
  producer Send messagge:  { test2: { '0': 1665 } } +1s
```

Only partition 0 on topic have message!! what is problem?
Please help me debug this!
 Thank you !

**Comment by hyperlink** [comment]
Before sending your messages you need to call `client.refreshMetadata([your_topics], callback);` after the producer is ready.

**Comment by jaejo-cm** [comment]
I had the same issue as this, and calling `client.refreshMetadata([your_topics], callback)` seems to work.  On kafka console producer, I didn't have this issue.

All settings related to partition including partitionerType is in producer, so I think it would be more intuitive if updating metadata happens automatically or it exists in producer.  Thanks.

**Comment by hyperlink** [comment]
@jaejo-cm fetching the metadata will be performed during the `connect` in the Kafka only client. I'm hoping to release it soon.

**Comment by harshitgupta30** [comment]
client.refreshMetadata([your_topics], callback) is not working as expected for me when partitioner type = 2.
@hyperlink Can you please help me to fix the issue.

I have three partition of the topic and using HighLevelProducer to produce the message. I want to do round-robin the messages to all the partitions. But by using paritioner_type = 2 (cyclic), all the messages are going to partition 0 only even after using client.refreshMetadata([your_topics], callback) . But when I am using partition_type = 1 (random), then messages are going to partition 1 and 2 also but not in the equal proportion. 


Sample Code: 

var kafka = require('kafka-node');
var HighLevelProducer = kafka.HighLevelProducer;
client = kafka.Client(config.zookeeper.host);

var options  = {requireAcks:1, ackTimeoutMs:100, partitionerType:2};

producer = new HighLevelProducer(client, options);
producer.on("ready", function(err, response) {
     client.refreshMetadata([req.message.queue], function(err3, response1) {
               producer.send(payload, function(err2, result) {
               }
     }
}


Whar partitioner_type should I use to round_robin all the messages. OR Am I doing any mistake?
