### ISSUE TITLE
support kerberos?

### ISSUE THREAD

**Issue by yuu2lee4** [SOHU-Co/kafka-node#680]
whether supported kerberos or not?

**Comment by hyperlink** [comment]
Been asked in #511. There's no support at the moment.  PRs are welcome!

**Comment by subhasisbanik** [comment]
Are you supporting kerberos?
If not could you please point me to one module that does, cause I did not find any satisfactory module for it except
 https://github.com/Blizzard/node-rdkafka
which has node-gyp issues.

**Comment by Vidz51** [comment]
Are you supporting kerberos?
