### ISSUE TITLE
ConsumerGroup: Specify which partitions to consume from

### ISSUE THREAD

**Issue by prettyboyswag** [SOHU-Co/kafka-node#687]
I am looking at the docs for ConsumerGroup and I see that you can specify topic partitions with `Custom Partition Assignment Protocol` but the docs are confusing. There isn't any code examples on how to accomplish this. I also see in the standard configuration, there is this comment `roundrobin' or 'range' string for built ins `. Will this be a simpler way to consume from multiple partitions?

**Comment by prettyboyswag** [comment]
or will ConsumerGroup read from all partitions no matter what? The older `Consumer` made you specify the partition

**Comment by hyperlink** [comment]
Right. Both `ConsumerGroup` and `HighLevelConsumer` will automatically read from all partitions of the topic and load balance them among themselves. `range` and `roundrobin` assignment algorithms (they are confusingly called assignment protocols by kafka) are supported with the ConsumerGroup.

With the plain `Consumer` you will need to define specific partitions.
