### ISSUE TITLE
ConsumerGroup not reading all the messages

### ISSUE THREAD

**Issue by nithjino** [SOHU-Co/kafka-node#689]
From my understanding, ConsumerGroup reads from all partitions. This specific kafka server I'm reading from has over 70k messages, but I am only able to read about 6400. This is my configuration

```javascript
ConsumerGroup = kafka.ConsumerGroup

var consumerOptions = {
  host: config.kafka_url,
  zk : undefined,
  batch: undefined,
  ssl: false, 
  groupId: config.kafka_consumer_id,
  sessionTimeout: 15000,
  protocol: ['roundrobin'],
  fromOffset: 'earliest', 
  outOfRangeOffset: 'latest',
  migrateHLC: false,
  migrateRolling: true
};

var consumer = new ConsumerGroup(consumerOptions, config.kafka_topic);
```

Any idea on what I'm doing wrong?

**Comment by hyperlink** [comment]
Are you sure the consumer hasn't committed the offsets under that `groupId` previously? How many messages are read if you randomize the `groupId`? You can also try turn on [debugging](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) to see how the initial offsets are determined.

**Comment by bunuble** [comment]
It seems that you are right. Debug shows that I am reading from all the partitions and the offsets shows that they have been committed I think. A member of my team is adamant that everything is right with the servers and says that something is acting up with kafka-node. Is there a way to read from the beginning no matter what or is that impossible? 

`
kafka-node:ConsumerGroup kafka-node-client fetchOffset Response: {"[topic name]":{"0":5,"1":56,"2":3,"3":3,"4":27,"5":3100,"6":1,"7":2,"8":1,"9":1,"10":1,"11":1,"12":3,"13":0,"14":3987,"15":0,"16":0,"17":8,"18":1,"19":0,"20":3,"21":2,"22":4184,"23":0,"24":1592,"25":0,"26":0,"27":35,"28":0,"29":0,"30":476,"31":11,"32":0,"33":1,"34":0,"35":0,"36":0,"37":0,"38":0,"39":0,"40":0,"41":0,"42":210,"43":29,"44":7,"45":96,"46":30,"47":0,"48":0,"49":0,"50":0,"51":0,"52":0,"53":2,"54":0,"55":43712,"56":1,"57":0,"58":0,"59":22,"60":16,"61":0,"62":174,"63":0}} +34ms
`

**Comment by hyperlink** [comment]
if you don't care about reprocessing messages you could just use a plain Consumer and read from all partitions  You can use the Offset class and get the earliest offsets for those partitions before reading.
