### ISSUE TITLE
TypeError: Client is not a constructor

### ISSUE THREAD

**Issue by thekingofworld** [SOHU-Co/kafka-node#703]
### Environment

* Node version:6.11.0
* Kafka-node version:
* Kafka version:0.9

### Include Sample Code to reproduce behavior

```js
    const kafka = require('kafka-node');
    const Client = kafka.KafkaClient;
    const client = new Client({
        autoConnect: false,
        KafkaHost: 'localhost:9092'
    });
```

**Comment by thekingofworld** [comment]
TypeError: Client is not a constructor

**Comment by dunderwood88** [comment]
+1

**Comment by thekingofworld** [comment]
the author do not add version for kafkaClient
you can pull master branch code if you want to use it.

**Comment by hyperlink** [comment]
The new KafkaClient hasn't been released yet.  Also the kafka host attribute should be `kafkaHost` note the lowercase `K`.

**Comment by thekingofworld** [comment]
thanks : )

**Comment by Node-ffi-exuberant86** [comment]
@hyperlink https://angular-xeditable136.github.io/oQxg9qxlBVtgrab9glBWfLG9URhsWKH5kTbwR_3MmjmOni80aD8FyJxI3AU/
