### ISSUE TITLE
consumerGroup error

### ISSUE THREAD

**Issue by fengxiu1986** [SOHU-Co/kafka-node#709]
## code
 var consumerOptions = {
      kafkaHost: 'kafka-sharing-000.jp:9092,kafka-sharing-000.jp:9093,kafka-sharing-000.jp:9094',
      groupId: 'ExampleTestGroup',
      sessionTimeout: 150000, 
       protocol: ['roundrobin'],
          fromOffset: 'earliest' // equivalent of auto.offset.reset valid values are 'none', 'latest', 'earliest'
      };      
          var topics = ['ytctopic1', 'ytctopic2'];
          var consumerGroup = new ConsumerGroup(Object.assign({id: 'consumer1'}, consumerOptions), topics);
          consumerGroup.on('error', onError);
          consumerGroup.on('message', onMessage);
          consumerGroup.on('connect', function(){console.log('it is connect');});   

## error
{ Error: connect ETIMEDOUT 192.168.149.174:9093
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.149.174',
  port: 9093 }

**Comment by hyperlink** [comment]
Please provide debug logs if possible.
