### ISSUE TITLE
Missing the messages from Kafka consumer on process restart.

### ISSUE THREAD

**Issue by vnsrahul1304** [SOHU-Co/kafka-node#711]
## Question?
When we are restarting the Kafka consumer, after an exit, the offsets received are very much larger than the last committed offset. We seem to miss a lot of messages in between.
How can this happen? 
Any help would be greatly appreciable!

### Environment
* Node version: 7.10.0
* Kafka-node version: "2.0.0"

### Configurations
* Number of Brokers: 1
* autoCommit: false
* fromOffset: false

We are committing the offset manually by setOffset after processing the messages.

**Comment by hyperlink** [comment]
Unfortunately `setOffset` does not commit the messages. It's can be used to set the initial offset before fetching of messages starts.

Which type of Consumer are you try to use?

**Comment by vnsrahul1304** [comment]
@hyperlink  We am using HighLevelConsumer. We are committing the message after setOffset.
Actually there was some bug on our end in consumer creation, we needed to make autoCommit: false, which was by default true. 
Now it works fine. Thanks!
 You can close this bug.
