### ISSUE TITLE
Producer Is Never Connecting or Timing Out

### ISSUE THREAD

**Issue by ecastill** [SOHU-Co/kafka-node#719]
## Questions?
So I'm trying to get a timeout message or some sort of response when my kafka is down, but I don't get any sort of message or response back. I also have producer.on('error'), client.on('error') and I'm not getting anything with those either. Has anyone had this issue?
### Include Sample Code to reproduce behavior

```js
var kafka = require('kafka-node');
var Producer = kafka.Producer;
var kafkaConnFlag = false

function kafkaProducer(fileName, config, callback) {
    var client = new kafka.Client(config.kafka.host);
    var producer = new Producer(client, {connectTimeout:3000});
    var msg = fileName;
    var payloads = [
        { topic: config.kafkaTopic, messages: msg }

    ];
producer.on('ready', function () {
        kafkaConnFlag = true;
        producer.send(payloads, function (err, data, resp) {
            kafkaConnFlag = true;
            if (err) {
                callback(err, null);
            }
            callback(null, kafkaConnFlag);
        })
    });
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by hyperlink** [comment]
Are you passing the zookeeper host to kafka.Client?
