### ISSUE TITLE
新加的offsetOutOfRange问题

### ISSUE THREAD

**Issue by justjv** [SOHU-Co/kafka-node#72]
测试了一下，手动调大了zookeeper的offsets，再启动客户端，
consumer.on('offsetOutOfRange', function(err) {}打印出来的err是：
{ topic: 'mytp',
partition: 0,
message: 'OffsetOutOfRange',
maxNum: 1000,
metadata: 'm',
time: 1404702859069 }
partition: 0中的所有消息重新消费了一遍。有没有办法避免消息重新消费？或者是我的测试方法错误？

**Comment by pirlck** [comment]
嗯，准备用zk客户端试试
