### ISSUE TITLE
sudo node index.js Host Error

### ISSUE THREAD

**Issue by Chucktheduck404** [SOHU-Co/kafka-node#724]
Im working on a self watering plant system. Link here https://www.hackster.io/demirhanaydin/waterpi-houseplant-remote-watering-and-monitoring-system-340400. I followed all the steps and have modifed the code slightly for my lcd to work. I keep running into this error and I'm not sure how to fix it. Any help would be appreciated.

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND a2paxuwr910.iot.us-west-2.amazonaws.com a2paxuwr910oz.iot.us-west-2.amazonaws.com:883
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

**Comment by hyperlink** [comment]
You're using kafka for your plant watering system?

**Comment by Chucktheduck404** [comment]
I realized this is probably not the best forum because no i'm not using kafka but someone who was using kafka had the same issue has me so I thought Id post mine. The code i'm using is for waterpi-node and waterpi-web. Which can be seen in the link by scrolling down to the bottom. If you could check it out id appreciate it.

**Comment by hyperlink** [comment]
I see... I would try stackoverflow. Good luck @Chucktheduck404
