### ISSUE TITLE
Round-Robin not working with HighlevelProducer for partitionerType = 2

### ISSUE THREAD

**Issue by harshitgupta30** [SOHU-Co/kafka-node#725]
client.refreshMetadata([your_topics], callback) is not working as expected for me when partitioner type = 2.

I have three partition of the topic and using HighLevelProducer to produce the message. I want to do round-robin the messages to all the partitions. But by using paritioner_type = 2 (cyclic), all the messages are going to partition 0 only even after using client.refreshMetadata([your_topics], callback) . But when I am using partition_type = 1 (random), then messages are going to partition 1 and 2 also but not in the equal proportion.

Sample Code:

var kafka = require('kafka-node');
var HighLevelProducer = kafka.HighLevelProducer;
client = kafka.Client(config.zookeeper.host);

var options = {requireAcks:1, ackTimeoutMs:100, partitionerType:2};

producer = new HighLevelProducer(client, options);
producer.on("ready", function(err, response) {
client.refreshMetadata([req.message.queue], function(err3, response1) {
producer.send(payload, function(err2, result) {
}
}
}

Whar partitioner_type should I use to round_robin all the messages. OR Am I doing any mistake?

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 3

**Comment by frankjrangel** [comment]
I'm having exactly the same issue

**Comment by hyperlink** [comment]
This seems to be working for me.

I would double check the topic actually has three partitions. If it's a new topic that doesn't exist the broker will create a topic for you automatically when you call refreshMetadata on that topic. And I believe by default it is 1 partition.
