### ISSUE TITLE
Consumer Group Receive Message from abnormal Offset 

### ISSUE THREAD

**Issue by apphace** [SOHU-Co/kafka-node#727]
Hi all,

Thanks for contribute such good library and it helps us much in our project. 
Recently we found one strange problem when we use ConsumerGroup to consume the messages from Kafka. 

Below is the message log captured by application in on('message', callback) of consumer group.
{ 
    "messageTime" : ISODate("2017-07-24T02:51:55.096+0000"), 
    "instance" : "52", 
    "messageID" : "dc4dc2ff-321d-4c9b-a1fe-a46fb723842a", 
    "topic" : "TEST.KAFKA.CONSUMERGROUP.TOPIC", 
    "partition" : "2", 
    "offset" : "9238562", 
    "key" : "-1", 
    "highWaterOffset" : "9240848"
}
{ 
    "messageTime" : ISODate("2017-07-24T03:13:01.858+0000"), 
    "instance" : "52", 
    "messageID" : "dc4dc2ff-321d-4c9b-a1fe-a46fb723842a", 
    "topic" : "TEST.KAFKA.CONSUMERGROUP.TOPIC", 
    "partition" : "2", 
    "offset" : "9238562", 
    "key" : "-1", 
    "highWaterOffset" : "9240840"
}

Below is the shelljs + kafka in-built ConsumerOffsetChecker command capture offset snapshot for the consumer group(GMT+8 timezone) per 2 minutes.
7/24/2017, 10:49:59 AM - info: Start offset checker
7/24/2017, 10:50:10 AM - info: 
Group           Topic                          Pid Offset          logSize         Lag             Owner
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 0   7520233         7523891         3658            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 1   2116271         2117342         1071            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 2   9238494         9240524         2030            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 3   3036583         3037999         1416            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 4   2999436         3001632         2196            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 5   4864395         4866565         2170            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 6   2503708         2508396         4688            none

7/24/2017, 10:52:00 AM - info: Start offset checker
7/24/2017, 10:52:05 AM - info: 
Group           Topic                          Pid Offset          logSize         Lag             Owner
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 0   7521234         7524235         3001            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 1   2116271         2117556         1285            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 2   9239495         9240860         1365            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 3   3037584         3038256         672             none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 4   3001438         3001966         528             none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 5   4864395         4866897         2502            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 6   2504709         2508728         4019            none

7/24/2017, 10:54:00 AM - info: Start offset checker
7/24/2017, 10:54:05 AM - info: 
Group           Topic                          Pid Offset          logSize         Lag             Owner
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 0   7521234         7524529         3295            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 1   2116271         2117741         1470            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 2   9239495         9241158         1663            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 3   3037584         3038486         902             none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 4   3001438         3002262         824             none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 5   4864395         4867193         2798            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 6   2504709         2509022         4313            none

7/24/2017, 10:56:00 AM - info: Start offset checker
7/24/2017, 10:56:03 AM - info: 
Group           Topic                          Pid Offset          logSize         Lag             Owner
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 0   7521234         7525407         4173            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 1   2116271         2118395         2124            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 2   9239495         9241930         2435            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 3   3037584         3039171         1587            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 4   3001438         3003040         1602            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 5   4864395         4867974         3579            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 6   2504709         2509802         5093            none

7/24/2017, 10:58:00 AM - info: Start offset checker
7/24/2017, 10:58:10 AM - info: 
Group           Topic                          Pid Offset          logSize         Lag             Owner
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 0   7521234         7525809         4575            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 1   2116271         2118679         2408            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 2   9239495         9242309         2814            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 3   3037584         3039503         1919            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 4   3001438         3003419         1981            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 5   4864395         4868352         3957            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 6   2504709         2510186         5477            none

7/24/2017, 11:00:00 AM - info: Start offset checker
7/24/2017, 11:00:06 AM - info: 
Group           Topic                          Pid Offset          logSize         Lag             Owner
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 0   7521234         7526155         4921            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 1   2116271         2118909         2638            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 2   9239495         9242655         3160            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 3   3037584         3039773         2189            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 4   3001438         3003764         2326            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 5   4864395         4868694         4299            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 6   2504709         2510523         5814            none

7/24/2017, 11:01:59 AM - info: Start offset checker
7/24/2017, 11:02:11 AM - info: 
Group           Topic                          Pid Offset          logSize         Lag             Owner
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 0   7521234         7526481         5247            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 1   2116271         2119102         2831            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 2   9240496         9242986         2490            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 3   3037584         3040025         2441            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 4   3002439         3004096         1657            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 5   4865396         4869025         3629            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 6   2504709         2510855         6146            none

7/24/2017, 11:03:59 AM - info: Start offset checker
7/24/2017, 11:04:15 AM - info: 
Group           Topic                          Pid Offset          logSize         Lag             Owner
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 0   7521234         7526945         5711            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 1   2116271         2119469         3198            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 2   9240496         9243460         2964            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 3   3038585         3040431         1846            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 4   3002439         3004570         2131            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 5   4865396         4869502         4106            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 6   2504709         2511329         6620            none

7/24/2017, 11:05:59 AM - info: Start offset checker
7/24/2017, 11:06:05 AM - info: 
Group           Topic                          Pid Offset          logSize         Lag             Owner
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 0   7521234         7527284         6050            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 1   2116271         2119646         3375            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 2   9240496         9243785         3289            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 3   3038585         3040651         2066            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 4   3002439         3004889         2450            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 5   4865396         4869819         4423            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 6   2504709         2511652         6943            none

7/24/2017, 11:08:00 AM - info: Start offset checker
7/24/2017, 11:08:04 AM - info: 
Group           Topic                          Pid Offset          logSize         Lag             Owner
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 0   7521234         7527752         6518            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 1   2116271         2119963         3692            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 2   9240496         9244256         3760            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 3   3038585         3041021         2436            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 4   3002439         3005366         2927            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 5   4865396         4870294         4898            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 6   2504709         2512128         7419            none

7/24/2017, 11:09:59 AM - info: Start offset checker
7/24/2017, 11:10:03 AM - info: 
Group           Topic                          Pid Offset          logSize         Lag             Owner
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 0   7521234         7528116         6882            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 1   2116271         2120167         3896            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 2   9240496         9244622         4126            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 3   3038585         3041262         2677            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 4   3002439         3005734         3295            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 5   4865396         4870665         5269            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 6   2504709         2512497         7788            none

7/24/2017, 11:12:00 AM - info: Start offset checker
7/24/2017, 11:12:03 AM - info: 
Group           Topic                          Pid Offset          logSize         Lag             Owner
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 0   7521234         7528600         7366            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 1   2116271         2120522         4251            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 2   9241497         9245106         3609            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 3   3038585         3041659         3074            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 4   3003440         3006213         2773            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 5   4866397         4871144         4747            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 6   2504709         2512975         8266            none

7/24/2017, 11:14:00 AM - info: Start offset checker
7/24/2017, 11:14:03 AM - info: 
Group           Topic                          Pid Offset          logSize         Lag             Owner
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 0   7521234         7528920         7686            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 1   2116271         2120729         4458            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 2   9241497         9245424         3927            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 3   3038585         3041907         3322            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 4   3003440         3006527         3087            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 5   4866397         4871462         5065            none
Test_ConsumerGp TEST.KAFKA.CONSUMERGROUP.TOPIC 6   2504709         2513289         8580            none

From the captured result, the kafka server offset have change to > 9239495 after 10:52AM in GMT+8 but the message in offset 9238562 still be received at 11:13AM in GMT+8. The problem happened sometime in our production environment and it caused thousands of messages are reprocessed again during that period. Could you help to give some tips of the problem and how to fix that? Thanks and looking forward your kindly response!

### Environment

* Node version: 7.5.0
* Kafka-node version: 1.6.0
* Kafka version: 0.9.0
* Kafka partition number: 7
* Node server number: 6

### Code
  new ConsumerGroup(Object.assign({ id: 'testConsumer' }, {
    host: config.kafkaConnectURI,
    groupId: 'Test_ConsumerGp',
    sessionTimeout: 15000,
    autoCommit: true,
    protocol: ['roundrobin'],
    fromOffset: 'latest',
  }), ['TEST.KAFKA.CONSUMERGROUP.TOPIC']);

**Comment by hyperlink** [comment]
Did any of your kafka brokers have issues during this time? We have only seen this rewind behavior  once when one of our brokers had several corrupted indexes.

Also It would make it much easier to debug if you could provide logs from the module. See [configuring log output](https://github.com/SOHU-Co/kafka-node#how-do-i-configure-the-log-output).

**Comment by apphace** [comment]
Thanks for your kindly reply, @hyperlink. We added more log yesterday and found the reported case yesterday may relate to duplicate message delivery during the application restart and rebalance the kafka consumers. And because async.queue is using in our consumer to throttle the messages, it may cause minutes delay before the application handle that. It may not the real rewind case.
For the rewind offset behavior, may I ask your experience that brokers had corrupted index? Before we added detail app message, we encountered twice, one time is that one topic offset changed to -1 and another time is that one partition offset rollback from 2M+ to 1M+ which is handled days ago. And in kafka-node, do we have some cache maintain for offset value or totally depends on the value returned from zookeeper/kafka?

**Comment by hyperlink** [comment]
@apphace we use the committed offset when the consumer joins the group. Then we cache and updates the value for future fetches. If the group is rejoined it will fetch a new value and use that since they may not own the same partitions it owned previously.

A offset of -1 means it's topic/partition without any previous offsets we have guard against this in the [consumerGroup](https://github.com/SOHU-Co/kafka-node/blob/master/lib/consumerGroup.js#L375).

**Comment by apphace** [comment]
@hyperlink , Got it and many thanks.
