### ISSUE TITLE
HighLevelProducer.send callback not called on failure

### ISSUE THREAD

**Issue by hugebdu** [SOHU-Co/kafka-node#750]
Happens when I try sending some messages and my kafka & zookeeper goes down 
(I use [dockerized](https://github.com/spotify/docker-kafka) for my tests).

Also what is the best practice to get notification that kafka is not available?
I use `KafkaClient` and `HighLevelProducer`. What I see it that `producer.send` callback is never called.

**Comment by hugebdu** [comment]
*UPD*: my bad. It is mocha.js who kills the process upon `AssertionError`.
However the second part of my Q is still stands: 
> Also what is the best practice to get notification that kafka is not available?
I use KafkaClient and HighLevelProducer. What I see it that producer.send callback is never called.

**Comment by hugebdu** [comment]
Might be related https://github.com/SOHU-Co/kafka-node/issues/428
To simulate kafka & zookeeper failure I don't use `tcpkill` but simply stop and restart docker container.

**Comment by hyperlink** [comment]
Are you using the `KafkaClient` or `Client`?  I have noticed this can happen with the `KafkaClient`.

**Comment by hugebdu** [comment]
@hyperlink, thanks for quick response.
KafkaClient indeed. See above.

**Comment by hyperlink** [comment]
Published as v2.2.2
