### ISSUE TITLE
ListGroups and DescribeGroups

### ISSUE THREAD

**Issue by wooyeong** [SOHU-Co/kafka-node#769]
Hi.
 
After upgrading kafka from 0.8 to 0.10, our kafka admin tools didn't show useful numbers, so I am migrating from zookeeper to kafka and trying to implement `fetchCommits`, `listGroups`, and `describeGroups` features to display information on the admin tool properly.
 
I made `ListGroups` and `DescribeGroups`, It seems work well, and I hope kafka-node to have these protocols then our service can utilize the features. I followed instructions on #764, and (manually) tested against 0.9, 0.10, and 0.11.
 
In my opinion, APIs could be located on `kafkaClient` since both protocols are for 0.9+ brokers.
 
For `ListGroups`, I could fetch groupIds from all available brokers by using `client.brokerMetadata` and `client.brokerForLeader`.
 
And for `DescribeGroups`, I think it should accept list of groups as param, but we need to find groups' coordinators to send requests. So I had to use `sendGroupCoordinatorRequest` before asking.
 
What could be done to proceed to pr? Any suggestions?

**Comment by hyperlink** [comment]
Create a PR and I will be glad to review it.

**Comment by wooyeong** [comment]
I'm glad to finish this. Thank you. 😄
