### ISSUE TITLE
autoCommiting is not working in consumer group?

### ISSUE THREAD

**Issue by ashishnetworks** [SOHU-Co/kafka-node#773]
My consumerGroup configuration is as follow
`var consumerOptions = {
    host: '127.0.0.1:2181',
    autoCommit:false,
    groupId: 'ExampleTestGroup',
    sessionTimeout: 15000,
    protocol: ['roundrobin'],
    fromOffset: 'earliest
};`
after declaring autoCommit to false, I was expecting I would receive repeated messages but I'm not receiving them. That means messages are still getting autocommited but why? disabling autCommit in single consumer object works fine then why not in consumerObject, is it a bug or my configuration seems incorrect?

**Comment by ivands** [comment]
Ye this is really annoying if you want to guarantee only once semantics.
Please make sure the autoCommit:false flag works.

**Comment by hyperlink** [comment]
See #648 and there's also [a test](https://github.com/SOHU-Co/kafka-node/blob/master/test/test.consumerGroup.js#L999) in place to verify this feature works.
