### ISSUE TITLE
The consumer receiving nothing when there are data in the topic

### ISSUE THREAD

**Issue by yunnysunny** [SOHU-Co/kafka-node#779]
## Bug Report
When I ran command in shell `bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic topic.1 --from-beginning`， it would print the data to the console, but when I ran the code as follows, it got nothing.

### Environment

* Node version:6.9.2
* Kafka-node version:2.2.3
* Kafka version:0.11.0

### For specific cases also provide
* Number of Brokers:1
* Number partitions for topic:1

### Include Sample Code to reproduce behavior

```js
var kafka = require('kafka-node');
var Consumer = kafka.Consumer;
var Offset = kafka.Offset;
var Client = kafka.Client;
var topic = 'topic.1';

var client = new Client(process.env.ZOOKEEPER_PEERS);
client.on('ready',function() {
  console.log('client is ready');
});
var topics = [
    {topic: topic, partition: 0,offset:0},
];
var options = { autoCommit: false, fetchMaxWaitMs: 1000,fetchMinBytes: 1, fetchMaxBytes: 1024 * 1024 , fromOffset:true};

var consumer = new Consumer(client, topics, options);
var offset = new Offset(client);

consumer.on('message', function (message) {
  console.log(message);
});

consumer.on('error', function (err) {
  console.log('error', err);
});

/*
* If consumer get `offsetOutOfRange` event, fetch data from the smallest(oldest) offset
*/
consumer.on('offsetOutOfRange', function (topic) {
  topic.maxNum = 2;
  offset.fetch([topic], function (err, offsets) {
    if (err) {
      return console.error(err);
    }
    var min = Math.min(offsets[topic.topic][topic.partition]);
    consumer.setOffset(topic.topic, topic.partition, min);
  });
});
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) 
```{"topic.1":{"0":{"topic":"topic.1","partition":0,"leader":0,"replicas":[0],"isr":[0]}}}```

**Comment by hyperlink** [comment]
This works for me.

**Comment by yunnysunny** [comment]
![kafka](https://user-images.githubusercontent.com/734818/31545128-b27e54b8-b050-11e7-8ea7-5b4623ed4589.png)
I wonder why the sockets of the consumers are in the status of `CLOSE_WAIT`. Is it not reconnect when the connection is disconnected?

**Comment by hyperlink** [comment]
How long do these sockets stay in that state?

Sockets will get disconnected by kafka broker if left idle. We allow this to happen if we haven't written anything to the socket in awhile. This is controlled through the `idleConnection` setting.

**Comment by yunnysunny** [comment]
When I found the close_wait status, I restarted my consumer application, but it still in the status of close_wait after restart.

**Comment by yunnysunny** [comment]
![zk](https://user-images.githubusercontent.com/734818/31600137-e2dfe25a-b287-11e7-8402-05933f76b712.png)
We created the client with the class of [client](https://github.com/SOHU-Co/kafka-node#client), which will create a connection with zookeeper. You have said that kafka broker will disconnect the idle connectioin. But is it also suitable for connecting by zookeeper?
As given the TCP status above, the process of logical is our producer application, while the app.js is our consumer application. Even if the kafka broker will kill the idle connection, but how  the consumer get new messages on a broken connection?

**Comment by hyperlink** [comment]
I didn't notice those connections were zookeeper connections. The idle disconnect only works with the `KafkaClient` with kafka brokers not the old `Client` which connects to zookeeper for discovery. I would recommend using `KafkaClient` to avoid zookeeper.

**Comment by yunnysunny** [comment]
Can I replace the `Client` with `KafkaClient` in the code of the sample I have given?

**Comment by hyperlink** [comment]
Yes It *should* work. We tried to make it compatible with Client. Let me know if you run into issues.

**Comment by yunnysunny** [comment]
I think this issue may be caused by dirty data of zookeeper or kafka. I reinstalled kafka and zookeeper, and it worked OK now.

**Comment by yunnysunny** [comment]
@hyperlink There dates ,our team tried to use KafkaClient instead  of Client (the client using zookeeper), and we found KafkaClient was more stable than Client.
The Client made me irritable when the connection of the server of kafka re-connected, it seem that the either the producer or the consumer could recovery from error status.
So I suggest everyone use KafkaClient.

**Comment by samarthsikotara** [comment]
@yunnysunny yes, I am using KafkaClient as well but faced the similar problems. I resolved by just changing the topic name. I guess It might be because of the dirty data. I noticed the offset was null after certain amount of data produced.

**Comment by yunnysunny** [comment]
> @yunnysunny yes, I am using KafkaClient as well but faced the similar problems. I resolved by just changing the topic name. I guess It might be because of the dirty data. I noticed the offset was null after certain amount of data produced.

If offset is null , you may not write to kafka successfully.
