### ISSUE TITLE
Document creating ConsumerGroup with multiple consumers

### ISSUE THREAD

**Issue by mlazzarini** [SOHU-Co/kafka-node#783]
I haven't found a simple way to init a `ConsumerGroup` with multiple consumers.
- Is it necessary to define and pass a whole `CustomPartitionAssignmentProtocol` through the `protocol` param?
- Is it any sample code for that?

### Environment

* Node version: 7.10.1
* Kafka-node version: 2.2.3

Thanks in advance.

**Comment by hyperlink** [comment]
Just start another instances of the `ConsumerGroup` with the same group ID. The kafka broker will automatically coordinate between the multiple instances and balance partition ownership among your instances.

It's not required to define a custom assignment protocol. We use the built ins `roundrobin` protocol.
