### ISSUE TITLE
ConsumerGroup: whenever new consumer is added to group, first few messages consumed twice.

### ISSUE THREAD

**Issue by SharanKaur14** [SOHU-Co/kafka-node#787]
## Questions?
testConsumer.js using  ConsumerGroup to create consumer (auto commit = true, round robin protocol).

Test: - 
 one Topic(testtopic) having 2 partiions. Let prodcuer produce messages over this topic.

Issue:- 
Step 1:- start one testConsumer.js process (lets say Consumer1). Consumer1 will start consuming from both partitions(0 and 1) of the topic (testtopic).
Step 2:- Now start another testConsumer.js process(lets say Consumer2). One of the partitions will be assigned to this topic (lets say 0).
Now observer, consumer1 is still consuming from partitions (0 and 1) for certain time. (heartbeatInterval). on sendHeartbeat() consumer1 will know rebalancing is happening. Post that all rebalancing will happen and it will get one partition (1) and things will run smoothly now.**  

Because of this certain messages (starting messages fetched by  consumer2) are consumed twice. Once by consumer1 and other by consumer2.
Whenever new consumer joins the group the first few messages consumed by new consumer are duplicated(as these messages are already consumed by some other consumer). Is there any way to solve this issue.. ?

My observation:- 
Consumer2 should wait for certain time before fetching messages till consumer1 should register that new consumer has joined and rebalance.
Consumer1 should commit offset forcefully as soon as it knows new consumer has joined.

### Environment

* Node version: 6.10.3
* Kafka-node version: 2.2.3
* Kafka version: 0.11.0.1

### For specific cases also provide
* Number of Brokers: 2
* Number partitions for topic: 2

### Include Sample Code to reproduce behavior

```js
**Currently how consumer1 knows consumer2 has joined. 
ConsumerGroupRecovery.prototype.tryToRecoverFrom = function (error, source) {
// source = heartbeat
  // error.errorCode == 27 is returned when new consumer join
  //reconnect happens
}
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by hyperlink** [comment]
I don't know if it's possible to entirely avoid this issue. The commit for the topic/partition is not in sync with what was consumed. The consumer is only allowed to commit offsets when it's still part of the group and during a rebalance the consumer is no longer part of the group and so I believe any commits made by the consumer at that point will be rejected.

You can try to reduce the number of duplicate messages by tuning both the commit interval and heartbeat interval but the GroupConsumer only have information allowed by the protocol: 

https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol

**Comment by aikar** [comment]
@hyperlink I asked in Kafka IRC and someone said the protocol should handle it:
https://cwiki.apache.org/confluence/display/KAFKA/Kafka+0.9+Consumer+Rewrite+Design#Kafka0.9ConsumerRewriteDesign-Offsetcommitsduringrebalance

So looks like there may be something missing in the library to handle this

**Comment by aikar** [comment]
@hyperlink looking over the docs, it looks like as soon as the rebalance is triggered, this consumer must commit its current offsets BEFORE it sends the JoinGroupRequest.

Which should be trivial for auto commit work flows, but auto commit false will require a way for users to hook in and perform commits before the join group request fires.
