### ISSUE TITLE
kafkaClient.refreshMetadata callback never called 

### ISSUE THREAD

**Issue by iamsahil1989** [SOHU-Co/kafka-node#789]
We are using KafkaClient refreshMetadata/send like below . But some times the callback is not getting called., due to which our consumer remains paused [we are calling async queue callback within] forever. 

```
producerClient.refreshMetadata([producerTopic], function (error, response) {
        producer.send(payloads, function (err, data) {
             // Code here           
           }
       );
    });
```

I can see that there is a return statement inside KafkaClient.refreshMetadata which might have caused this. 
`if (operation.retry(err)) {
          return;
  }`

Can you please suggest what could be done in this situation

**Comment by hyperlink** [comment]
We're using the [retry](https://www.npmjs.com/package/retry) module and `operation.retry` is a way to check the operation will be retried so a return is necessary there. Have you turned on debugging to see if there's any helpful logs there?

**Comment by iamsahil1989** [comment]
This is happening once in a while .. i will enable debug logs today, but with the application logs it is verified that the callback is never called .. it is either refreshMetadata callback or send callback.

**Comment by iamsahil1989** [comment]
@hyperlink : I am getting below logs in debug mode in loop . Any idea ?


`Mon, 30 Oct 2017 23:37:27 GMT kafka-node:KafkaClient clearing test.com:9092 callback queue without error
Mon, 30 Oct 2017 23:37:28 GMT kafka-node:KafkaClient kafka-node-client reconnecting to test.com:9092
Mon, 30 Oct 2017 23:37:28 GMT kafka-node:KafkaClient Sending versions request to test.com:9092
Mon, 30 Oct 2017 23:37:28 GMT kafka-node:KafkaClient Received versions response from test.com:9092
--
Mon, 30 Oct 2017 23:39:17 GMT kafka-node:KafkaClient clearing test.com:9092 callback queue without error
Mon, 30 Oct 2017 23:39:18 GMT kafka-node:KafkaClient kafka-node-client reconnecting to test.com:9092
Mon, 30 Oct 2017 23:39:18 GMT kafka-node:KafkaClient Sending versions request to test.com:9092
Mon, 30 Oct 2017 23:39:18 GMT kafka-node:KafkaClient Received versions response from test.com:9092
--
Mon, 30 Oct 2017 23:39:28 GMT kafka-node:KafkaClient clearing test.com:9092 callback queue without error
Mon, 30 Oct 2017 23:39:29 GMT kafka-node:KafkaClient kafka-node-client reconnecting to test.com:9092
Mon, 30 Oct 2017 23:39:29 GMT kafka-node:KafkaClient Sending versions request to test.com:9092
Mon, 30 Oct 2017 23:39:29 GMT kafka-node:KafkaClient Received versions response from test.com:9092
--
Mon, 30 Oct 2017 23:41:18 GMT kafka-node:KafkaClient clearing test.com:9092 callback queue without error
Mon, 30 Oct 2017 23:41:19 GMT kafka-node:KafkaClient kafka-node-client reconnecting to test.com:9092
Mon, 30 Oct 2017 23:41:19 GMT kafka-node:KafkaClient Sending versions request to test.com:9092
Mon, 30 Oct 2017 23:41:19 GMT kafka-node:KafkaClient Received versions response from test.com:9092
--
Mon, 30 Oct 2017 23:41:29 GMT kafka-node:KafkaClient clearing test.com:9092 callback queue without error
Mon, 30 Oct 2017 23:41:30 GMT kafka-node:KafkaClient kafka-node-client reconnecting to test.com:9092
Mon, 30 Oct 2017 23:41:30 GMT kafka-node:KafkaClient Sending versions request to test.com:9092
Mon, 30 Oct 2017 23:41:30 GMT kafka-node:KafkaClient Received versions response from test.com:9092
`

**Comment by hyperlink** [comment]
What version of Kafka are you using?

**Comment by iamsahil1989** [comment]
We are using  kafka **0.10.2.1**. And the version of kafka-node we are using is **2.2.3**

**Comment by hyperlink** [comment]
Could you checkout the code, setup docker (description in the README) and create sample code that replicates this issue?

**Comment by iamsahil1989** [comment]
@hyperlink : Thanks. I will try to do so. Can you please confirm, with the kafka-node 2.2.3 is it a good idea to call refresh metadata before producer.send ?

**Comment by hyperlink** [comment]
the callback queues are [cleared](https://github.com/SOHU-Co/kafka-node/blob/master/lib/client.js#L711) when the socket is closed. There maybe a period of time before node notices that the socket is closed (TCP/IP sockets seems forgiving).

**Comment by iamsahil1989** [comment]
@hyperlink  : So i believe i need to figure out a work around to fix this.  Thanks for the response. 

I can understand the need to refresh metadata (broker down, rebalancing, etc) , do i need to explicitly call refresh metadata before every send request ? I can see that in case of 'brokerNotAvailable' refresh metadata is called, but are other cases catered as well (like increase in the number of partitions ?)

**Comment by hyperlink** [comment]
@iamsahil1989 refreshing periodically seems reasonable and would catch the case when the number of partitions has been increased. Calling refresh before every send request seems overkill.

**Comment by iamsahil1989** [comment]
@hyperlink  : Thanks a lot :)
