### ISSUE TITLE
how to set message.max.bytes?

### ISSUE THREAD

**Issue by zwb-ict** [SOHU-Co/kafka-node#793]
// The maximum permitted size of a message (defaults to 1000000). Should be
// set equal to or smaller than the broker's `message.max.bytes`.

**Comment by Ding9257** [comment]
How to set

**Comment by hyperlink** [comment]
There's a `fetchMaxBytes` option for consumers. Is this what you are looking for?

**Comment by Ding9257** [comment]
不起作用，通过修改kafka的配置可以解决
