### ISSUE TITLE
How to consume old messages from kafka topic on timestamp basis

### ISSUE THREAD

**Issue by SreedharaHJ** [SOHU-Co/kafka-node#796]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

### Environment

* Node version: 6.9.4
* Kafka-node version: 1.6.0
* Kafka version:0.10.1

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 10

I need to reprocess old messages on node restart from pase 3 hours. Please help me how to read messages with respect to time stamp. Currently I saw offset based reading but didn't get option to fetc based on time.

**Comment by hyperlink** [comment]
We can only use APIs that are exposed by Kafka. I don't see a way to [fetch](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-FetchRequest) with using a timestamp.
