### ISSUE TITLE
how could I keep long connection to kafka on producer?

### ISSUE THREAD

**Issue by xiaogang12** [SOHU-Co/kafka-node#802]
hi,
   I want keep long connection to kafka on producer, not every time I send a message to establish a connection，so I create a global client at first, then I create a producer when I send a message, 
but ready event not emit, why? there is some wrong?  

#### JS代码　

```javascript
var kafka = require('kafka-node');

KafkaAccessor = function RedisAccessor(){
	this.client = null;
	this.clientId = "kafka-node-client-"+process.pid;
};

KafkaAccessor.prototype.initialize = function () {
	this.client = new kafka.Client("192.168.2.56:2181, 192.168.2.57:2181", this.clientId);
}

KafkaAccessor.prototype.sendMsgToKafka = function (key, msg, cb) {
	var Producer = kafka.Producer;
	var producer = new Producer(this.client);
	var payloads = [ { topic: this.topic, messages: strSql, key:key, partition: 0 } ];
	
	producer.on('ready', function () {         /////////////////////  event not emit
		producer.send(payloads, function (err, data) {
                        if (err) {
				// client.close();
				cb(err);  return;
			} else {
				// client.close();
				cb(null, data); return;
			}
		});
	});
	
	producer.on('error', function (err) { cb(err); return; });
};
```

usage:
1、
	var kafkaAccessor = new KafkaAccessor();
	kafkaAccessor.initialize();
2、 
       kafkaAccessor.sendMsgToKafka(12, "test", function(err, data) { ......... });
#  I have two question:
 1、Should I choose a long connection on producer, when sending messages more frequetly?
 2、if choose a long connection, is there a better way ?

**Comment by hyperlink** [comment]
Depending on how often you send a message it's probably best to just hold a reference to the producer and call send anytime you need it.

**Comment by nareshtank001** [comment]
Hi @hyperlink, I am doing the same way holding a reference to the producer and calling send every second, but the problem that I am facing is when a new partition is added to the topic, producer is unaware about the new partition and it doesn't send messages to the newly added partition. 

I am using kafka 1.1.0
 Can you suggest me what I am doing wrong? I expect messages to be sent to the new partition without any intervention. Please advice. Thanks

**Comment by hyperlink** [comment]
@nareshtank001 the producer's client does not refresh it's metadata unless there's an error producing  so you will need to implement a mechanism to refresh the metadata when you add a new partition. This can be a manual call you make directly or it can be a timer that refreshes it periodically. up to you.
