### ISSUE TITLE
Consumer group - unknown error

### ISSUE THREAD

**Issue by plcstpierre** [SOHU-Co/kafka-node#803]
I am trying to make a consumer group working on aiven.

I always get this error.

{ topic: 'my.topic', partition: 6, message: 'Unknown' }

Any clue?

**Comment by hyperlink** [comment]
Can you provide some logs or sample code that replicates this issue?

**Comment by plcstpierre** [comment]
I am using aiven as a kafka provider.

Here is my code.

`function consoleLoggerProvider (name) {
    return {
        debug: console.debug.bind(console),
        info: console.info.bind(console),
        warn: console.warn.bind(console),
        error: console.error.bind(console)
    };
}

const kafkaLogging = require('kafka-node/logging');
kafkaLogging.setLoggerProvider(consoleLoggerProvider);

const kafka = require('kafka-node');
const ConsumerGroup = kafka.ConsumerGroup;

const fs = require('fs');

let sslOptions = {
    key: fs.readFileSync('service.key'),
    cert: fs.readFileSync('service.cert'),
    ca: [ fs.readFileSync('ca.pem') ]
};

let options = {
    autoCommit: true,
    kafkaHost: 'my-thingy.aivencloud.com:15957',
    groupId: 'my-testing-group',
    protocol: ['roundrobin'],
    fromOffset: 'earliest',
    ssl: true,
    sslOptions: sslOptions,
    id: "my-id",
    debug: "all"
};

let consumerGroup = new ConsumerGroup(options, ['my.topic']);

consumerGroup.on('message', (msg) => {
    console.log(msg);
});

consumerGroup.on('error', (error) => {
    console.error(error);
});

consumerGroup.on('connect', (connect) => {
    console.log("connect");
});

consumerGroup.on('offsetOutOfRange', (connect) => {
    console.log("offsetOutOfRange");
});

`

**Comment by plcstpierre** [comment]
It does not produce any low levle log even with

DEBUG=kafka-node:*`

**Comment by plcstpierre** [comment]
Maybe it's related ot aiven running on kafka 0.11.0.1?

**Comment by hyperlink** [comment]
perhaps it would depend on what `log.message.format.version` they are using. We only support 0.10.2 currently.

**Comment by AmazingTurtle** [comment]
I'm having the same issue. Why did you close it, @hyperlink ?
I'd like to help investigate this issue. What can I do?
