### ISSUE TITLE
can you provide me the examples without zookeper and docker

### ISSUE THREAD

**Issue by praveen4554** [SOHU-Co/kafka-node#805]
Hi 

  I would like to use node-kafka without zookeeper and docker can you provide me any example. cloned your application but i am unable to figured out to run the application without docker and zookeeper 

Thanks
Praveen

**Comment by hyperlink** [comment]
I would go to the apache kafka page and read the instructions on how to set up kafka locally but imo the easiest way to play around with kafka is to use docker.
