### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by kylezhang** [SOHU-Co/kafka-node#829]
What time to support async / await?
Thanks！

**Comment by hyperlink** [comment]
This library doesn't use promises and we need to support latest LTS so I would say at the earliest after node 6 leaves LTS.

**Comment by DanielWLam** [comment]
@hyperlink Hi, if I want to use async/await, what can i do? Can I use blurbird `promisify` to promise this library?

**Comment by hyperlink** [comment]
@DanielWLam shouldn't be an issue to bluebird or utils.promisify to promisify callback style methods.

**Comment by RobertHerhold** [comment]
Promises are [definitely supported natively in Node 6](https://node.green/). I understand not using async/await yet but it would be nice to at least have the option for users to use async/await on promises returned by this library.

**Comment by cuvillier** [comment]
It works fine with blurbird .

Here is an example:
`  var Promise = require("bluebird");
  ...
  const kafkaProducer = new kafka.Producer(kafkaClient, producerOptions);
  const kafkaProducerSend = Promise.promisify(kafkaProducer .send, {context: kafkaProducer });

async function yop() {
  ...
  await kafkaProducerSend ([kafkaMessage]);
  // Send is complete when you reach this point and there is no exception
}
`

Enjoy.

**Comment by LunaPg** [comment]
Does a async/await version is planed ?

**Comment by hyperlink** [comment]
Nope, but you can create a PR @LunaPg
