### ISSUE TITLE
ConsumerGroupStream with autoCommit=false commits offsets on close

### ISSUE THREAD

**Issue by kpala** [SOHU-Co/kafka-node#830]
In my use case, offsets should be committed only if the messages are handled successfully. In case of error (such as, no connection to database), the application should restart and retry handling the same message which caused the error. Eventually, no messages should be lost.

I tried the following:
1. Create HighLevelProducer and produce one message
2. Create ConsumerGroupStream with `autoCommit = false` and `fromOffset = 'none'`
3. When the message is consumed, commit offset manually and close ConsumerGroupStream by `close` method
4. Produce second message
5. Create new ConsumerGroupStream with the same parameters
6. The first message is skipped as expected. Now, when the second message is consumed, *do not commit* offset manually and close ConsumerGroupStream by `close` method
7. Create new ConsumerGroupStream with the same parameters
8. *Expected behavior*: ConsumerGroupStream should re-consume the second message, but instead, it continues from the latest offset

Sorry for not providing code for reproducing the issue (I have plenty of other business logic mixed in the code). Just wanted first to check if the described expected behavior is valid?

kafka-node 2.3.0

**Comment by sanditha** [comment]
without closing the consumergroup while using consumergroupstream. last offset does not get committed

**Comment by sanditha** [comment]
Thanks @hyperlink

**Comment by kpala** [comment]
Sorry I didn't have time to verify the fix earlier, but seems to be working now indeed. Thanks a lot!
