### ISSUE TITLE
Include option to use client in producerStream 

### ISSUE THREAD

**Issue by plingampally** [SOHU-Co/kafka-node#833]
Hi, it looks like constructor forn`ProducerStream` only supports `kafkaClient` right now: 

producerStream.js:
```
constructor (options) {
    if (options == null) {
      options = {};
    }

    super({ objectMode: true, decodeStrings: false, highWaterMark: options.highWaterMark || DEFAULT_HIGH_WATER_MARK });

    _.defaultsDeep(options, DEFAULTS);

    this.client = new KafkaClient(options.kafkaClient);
    this.producer = new HighLevelProducer(this.client, options.producer, options.producer.customPartitioner);
    this.producer.on('error', error => this.emit('error', error));
  }
```

When I changed this on my own to accept the standard client, I was receiving "Could not find the leader" errors.  I'd like to use the standard client so I don't have to list out all my brokers. Has anyone successfully used the standard client with the ProducerStream?

**Comment by hyperlink** [comment]
You actually don't need to list out all your brokers with the `KafkaClient`. It just need to reach one and it will do a metadata request to obtain the other brokers in the cluster. Hope that helps.
