### ISSUE TITLE
test.rebalance.js sometimes fails

### ISSUE THREAD

**Issue by LeiSun-1101** [SOHU-Co/kafka-node#839]
I have made some changes on KafkaClient.js. When I run all the tests, some tests of test.rebalance.js fails. But it seems that some tests randomly fails. I check the automated test of this project, it disables this test file when the travis CI runs. Does someone can explain it?

**Comment by hyperlink** [comment]
Unfortunately it's not a stable test so it's disabled in the CI. But could be good sanity check to make sure the rebalancing code works.

**Comment by LeiSun-1101** [comment]
Thanks for the reply. I would first close this ticket and If I have time I would try to investigate it.
