### ISSUE TITLE
How to assign consumer to listen to all partitions?

### ISSUE THREAD

**Issue by loudywen** [SOHU-Co/kafka-node#840]
Hi,
From the example, I see that we only assign partition 0 to the consumer. if i have 10 partitions, do i need to i assign it like this:

var topics = [
            {
                topic: topic,
                partition: 0
            },
            {
                topic: topic,
                partition: 1
            },
            {
                topic: topic,
                partition: 2
            },
            {
                topic: topic,
                partition: 3
            },
            {
                topic: topic,
                partition: 4
            },{
                topic: topic,
                partition: 5
            },{
                topic: topic,
                partition: 6
            },{
                topic: topic,
                partition: 7
            },{
                topic: topic,
                partition: 8
            },{
                topic: topic,
                partition: 9
            }
        ];

**Comment by loudywen** [comment]
I got it,, I use consumergroup instead. thx

**Comment by syahiaoui** [comment]
Hello,

Can you share your solution ??

Thank's
