### ISSUE TITLE
kafkaBrokers producer is not stable

### ISSUE THREAD

**Issue by tian-yuan** [SOHU-Co/kafka-node#845]
## Bug Report
use kafkaBrokers producer, the connection to kafka brokers is lost and can not refresh broker metadata after a period of time.

### Environment

* Node version: node-v6.10.3-linux-x64
* Kafka-node version: 2.3.0
* Kafka version: kafka_2.11-0.11.0.0

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 3

### Include Sample Code to reproduce behavior

```js
// include code here
'use strict';
const kafka = require('kafka-node');
const Producer = kafka.Producer;
const client = new kafka.KafkaClient({kafkaHost: config.kafkaBrokers});
const producer = new Producer(this.client, {requireAcks: 0});

producer.on('ready', function() {
  logger.error('kafka producer is ready!');
});

producer.on('error', function(err) {
  logger.error('kafka producer is error : ', err);
});

// the following function is invoked many times
producer.send(payloads, function(err, data) {});
```

### error information
send message to kafka error : "Broker not available (sendRequest)"

[2018-01-07 13:42:03.948] [ERROR] server-log - kafka producer is error :  { NestedError: refreshBrokerMetadata failed

Caused By: Error: Unable to find available brokers to try

### broker config
localhost:9092,localhost9093,localhost9094

### kafka cluster
kafka cluster install
https://kafka.apache.org/quickstart
  
### other information
use kafka console produer and consumer is work when the problem is occur:
./bin/kafka-console-producer.sh --broker-list localhost:9092 --topic mytopic
./bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic mytopic

**Comment by tian-yuan** [comment]
sorry, this is idleConnection config options problem, it will reconnect any more after the idle connection is closed.

**Comment by JavoByte** [comment]
Hi @tian-yuan . Can you share how you solved it? 
We are having the same issue

**Comment by tian-yuan** [comment]
I just add "idleConnection" option and set to 24 hours:

```
this.client = new kafka.KafkaClient({idleConnection: 24 * 60 * 60 * 1000, kafkaHost: config.kafkaBrokers});

// Partitioner type (default = 0, random = 1, cyclic = 2, keyed = 3, custom = 4), default 0

this.producer = new Producer(this.client, {requireAcks: 0, partitionerType: 2});
```

**Comment by tian-yuan** [comment]
I just add "idleConnection" option and set to 24 hours:

```
this.client = new kafka.KafkaClient({idleConnection: 24 * 60 * 60 * 1000, kafkaHost: config.kafkaBrokers});

// Partitioner type (default = 0, random = 1, cyclic = 2, keyed = 3, custom = 4), default 0

this.producer = new Producer(this.client, {requireAcks: 0, partitionerType: 2});
```

**Comment by JavoByte** [comment]
Thank you @tian-yuan !

**Comment by sagitsofan** [comment]
> I just add "idleConnection" option and set to 24 hours:
> 
> ```
> this.client = new kafka.KafkaClient({idleConnection: 24 * 60 * 60 * 1000, kafkaHost: config.kafkaBrokers});
> 
> // Partitioner type (default = 0, random = 1, cyclic = 2, keyed = 3, custom = 4), default 0
> 
> this.producer = new Producer(this.client, {requireAcks: 0, partitionerType: 2});
> ```

@tian-yuan  But there is a `reconnectOnIdle` ( true by default ) property which will be reconnect automatically if the connection is closed.
Are you sure it is the `idleConnection` issue?
