### ISSUE TITLE
The ConsumerGroup's autoCommit does not work.

### ISSUE THREAD

**Issue by yunnysunny** [SOHU-Co/kafka-node#856]
## Bug Report
We use ConsumerGroup to consumer our topic, and use kafka manager to monitor the status of consumer.
And we find that the `Consumer Offset` always stay the number of `33541`, even though we find the latest message was consumed by our consumer. I paste a message from our conumser's log:
```javascript
{ topic: 'zylive-logical-chat',
   value: '{"user_type":1,"ip":1879728129}',
   offset: 182728590,
   partition: 0,
   highWaterOffset: 182728591,
   key: null }
```
![manager](https://user-images.githubusercontent.com/734818/35470121-a7d0628c-037e-11e8-95ff-4676135e31a4.png)

### Environment

* Node version: 6.11.2
* Kafka-node version:2.3.1
* Kafka version:0.10.1.0

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 1

**Comment by hyperlink** [comment]
this should be working we have tests that cover this area. Are you getting similar results using the kafka/bin tools? specifically using the `kafka-consumer-groups.sh` command.

**Comment by yunnysunny** [comment]
The issue could not recurrent when there is few data in the queue of kafka. We found this problem after we wrote a large number of data in kafka.

**Comment by yunnysunny** [comment]
I have not try run consumer on console, because it's an online project. And I have met the problem in my development environment. The common prerequisite to trigger the issue is producing data at high concurrency. 
We use pm2 to manage our node processes, and reloaded our consumer process after this problem came up, but found it did not work. At the end we ran `pm2 kill` to shutdown pm2 , then run `pm2 start my-consumer-process`, and found the consumed offset recoveried from error state.  I don't know whether the deal of restarting the process of pm2 take effect.

**Comment by yunnysunny** [comment]
I think it may be a bug of kafka manager. 
Since I run `kafka-consumer-groups.sh  --describe --group my-group-id --bootstrap-server my-broker-server-list-string`, and find it output the information of the process of  consume correctly.
