### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by varunrayen** [SOHU-Co/kafka-node#865]
I am running Apache Kafka in AWS EC2 using a docker container. When i tried to create a producer and send messages to the broker. I get an error 

```
{ Error: connect ETIMEDOUT <my VPC private IP>:9092
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1096:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '<my VPC private IP>',
  port: 9092 }
```

### Environment

* Node version: 7.8.0
* Kafka-node version: 2.4.1
* Kafka version: 0.11.0.1

When I connect to my Zookeeper, I connect using a public provided by AWS.

**Comment by hyperlink** [comment]
I would double check you can reach the broker from your EC2 instance.

**Comment by varunrayen** [comment]
Yeah I can reach the broker and I could also send messages using the CLI. But this happens only through kafka-node

**Comment by hyperlink** [comment]
There's not much information to go on.

**Comment by varunrayen** [comment]
What more information would be needed?

**Comment by hyperlink** [comment]
to start you could provide example code on how you connect using kafka-node and how you verify the connection using the cli.  Just pasting a generic error message isn't sufficient.

**Comment by varunrayen** [comment]
var kafka = require("kafka-node");  
    var Producer = kafka.Producer;
    var client = new kafka.Client("<PRIVATE VPC IP>:2181", "kafka-node-client");
    var producer = new Producer(client);
    var payloads = [
            { topic: "first_topic", messages: "Welcome from Producer!", attributes: 1, timestamp: Date.now() },
            { topic: "first_topic", messages: "Thanks", attributes: 1, timestamp: Date.now() }
    ];
    producer.on("ready", function(err, data) {
        console.log("Producer Connected!" + data);
        console.log(err);
        producer.send(payloads, function (err, data) {
                  console.log(data);
                  console.log(err);
            });
    });
    producer.on("error", function(error) {
      console.error(error);
    });


This is the code I used to connect using kafka-node.

**Comment by ayZagen** [comment]
Have you found any solution about this issue ? I am getting the same error.

**Comment by varunrayen** [comment]
@ayZagen Not yet!

**Comment by secreter** [comment]
the same

**Comment by gavimg** [comment]
This issue is closed without giving reason.

**Comment by alliancegh** [comment]
the same
