### ISSUE TITLE
Is Zookeeper Clustering Environment supported in kafka-node npm module

### ISSUE THREAD

**Issue by kameshwari-suresh** [SOHU-Co/kafka-node#866]
## Questions?

* Is Zookeeper Clustering Environment supported in kafka-node npm module?
* If possible , then where to specify the multiple zookeeper connection string

### Environment

* Node version: 6.7.0
* Kafka-node version:2.4.1
* Kafka version:1.0.0

### For specific cases also provide
* Number of Brokers:2
* Number partitions for topic:5

### Include Sample Code to reproduce behavior

```js
// include code here
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by hyperlink** [comment]
The first argument to `Client` can be a comma separated host:port pairs.

**Comment by kameshwari-suresh** [comment]
Thank you for the reply @hyperlink 👍

**Comment by maulikbiztechconsultancy** [comment]
How can we use multiple zookeeper instances in KafkaClient? Seems like right now it does not have the Client api?
This is not working 
```js
client = new kafka.KafkaClient('192.168.1.11:22181,192.168.1.11:32181,192.168.1.11:42181');
//Nor this
client = new kafka.KafkaClient({kafkaHost: '192.168.1.11:22181,192.168.1.11:32181,192.168.1.11:42181'});
```
Thanks
