### ISSUE TITLE
how to start ConsumerGroup from last committed offset?

### ISSUE THREAD

**Issue by Royvaknin29** [SOHU-Co/kafka-node#867]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

### Environment

* Node version:
* Kafka-node version:
* Kafka version:

### For specific cases also provide
* Number of Brokers:
* Number partitions for topic:

### Include Sample Code to reproduce behavior

```js
// include code here
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by hyperlink** [comment]
`ConsumerGroup` will automatically fetch from the last committed offset for the `groupId`. If there has been no commits made it will uses the `fromOffset` option which by default is the latest offset.

**Comment by Royvaknin29** [comment]
Hi.. sorry but I didn't ask my question properly.
I have an issue with setting up ConsumerGroup with last committed offset.
I am running:
```
let kafka = require('kafka-node')
let options = {
            kafkaHost: configuration.KafkaUrl,
            autoCommit: false,
            groupId: 'group-id',
            sessionTimeout: 10000,
            protocol: ['roundrobin'],
            encoding: 'utf8'
        };
consumer = new kafka.ConsumerGroup(options, configuration.Topics);

consumer.on('connect', function () {
            logger.info('topicPayloads', consumer.topicPayloads);
        });
```
and I'm getting:
```
 "topicPayloads [ { topic: 'E-T-1',\n    partition: 0,\n    offset: 20,\n    maxBytes: 1048576,\n    metadata: 'm' },\n  { topic: 'E-T-1',\n    partition: 1,\n    offset: 20,\n    maxBytes: 1048576,\n    metadata: 'm' },\n  { topic: 'E-T-1',\n    partition: 2,\n    offset: 20,\n    maxBytes: 1048576,\n    metadata: 'm' },\n  { topic: 'E-T-1',\n    partition: 3,\n    offset: 20,\n    maxBytes: 1048576,\n    metadata: 'm' }
```
even though the actual offset is 11:
```
./kafka-run-class.sh kafka.tools.ConsumerOffsetChecker --topic E-T-1 --zookeeper localhost:2181 --group group-id
```
is returning:
```
Group           Topic                          Pid Offset          logSize         Lag             Owner
group-id        E-T-1                          0   11              20              9               none
group-id        E-T-1                          1   11              20              9               none
group-id        E-T-1                          2   11              20              9               none
group-id        E-T-1                          3   11              20              9               none
group-id        E-T-1                          4   11              20              9               none
```

**Comment by hyperlink** [comment]
Have you previously committed? Because setting your `autoCommit` option to false means it will not be committing your offsets.

**Comment by hyperlink** [comment]
Also you should check offsets using `kafka-consumer-groups.sh` instead since that will look at groups data from kafka and not zookeeper (`ConsumerGroup` stores offsets in kafka).

**Comment by Royvaknin29** [comment]
Hi again,
first of all thanks for the replies.
The case I showed you before indeed happened after several replies with the latest version of kafka-node (2.4.1)

I'm trying to use the autoCommit=false feature so I can manual commit the message after the consumer 
async action will finish.
when I'm processing messages from the start of the partition (offset 0) and with the same ConsumerGroup in my application (without killing it) I manage to read all the messages. the thing is if I stop my application while there are still messages in the topic that weren't committed yet and start it over the offset is set to the end of the queue (probably because the default fromOffset policy is 'latest' and the new consumer can't find/fetch the correct offset for the consumer group). 
for the example I've sent 100 messages to the a topic with 3 partitions and killed it after 50 was committed.
When I run:
```
./kafka-consumer-groups.sh --describe  --bootstrap-server localhost:9092 --new-consumer --group group-id
```
I get: 
```
GROUP                          TOPIC                          PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             OWNER
group-id                       ET2                            0          unknown         34              unknown         kafka-node-client_/172.17.0.1
group-id                       ET2                            1          unknown         33              unknown         kafka-node-client_/172.17.0.1
group-id                       ET2                            2          unknown         33              unknown         kafka-node-client_/172.17.0.1
```
the code I ran is:
```
let options = {
            kafkaHost: 'localhost:9092',
            autoCommit: false,
            groupId: 'group-id',
            sessionTimeout: 10000,
            protocol: ['roundrobin'],
            encoding: 'utf8'
        };

        consumer = new kafka.ConsumerGroup(options, configuration.Topics);
        offset = new kafka.Offset(consumer.client);

   consumer.on('message', (msg) => {
//some async code that calls 'commit' at the end              
 handleIncomingMessage(msg.partition, {
                    msg: msg.value,
                    offset: msg.offset,
                    partition: msg.partition
                });
            });

function commit(partition, offsetValue) {
    let offsetRequestObj = {
        topic: 'ET2',
        partition: partition,
        offset: offsetValue
    };
    offset.commit('group-id', [offsetRequestObj], function (err, data) {
        if (err) {
            logger.error('error committing manually to kafka', err.message);
            // doesen't happen
        }
        console.log(util.inspect(data, false, null));
         // logs { partition: <PARTITION_NUM>, errorCode: 0 } }
    });
};

```

* Why is the offset set to unknown? 
* how can I use the autoCommit=false feature correctly and manual manage the commits?

**Comment by hyperlink** [comment]
Unfortunately, the `Offset` commit is not compatible with `ConsumerGroup`. I should add some documentation about this. There's no easy way to manually commit with plain `ConsumerGroup` to commit manually I would suggest using the `ConsumerGroupStream` instead with  autoCommit set false and calling it's commit method manually.

Good luck!

**Comment by Royvaknin29** [comment]
I can't find in the documentation any reference to  ConsumerGroupStream's manual commit..
can you point me to it or send me some example?
thanks ahead.
@hyperlink

**Comment by hyperlink** [comment]
I just updated the readme.
