### ISSUE TITLE
Number of connections with zookeeper increases every time zookeeper gets restarted

### ISSUE THREAD

**Issue by mariosouto** [SOHU-Co/kafka-node#868]
Hi!

I'm using `kafka-node` to connect to Kafka and i'm experiencing some issues with the number of connections with Zookeeper, specifically getting the `too many connections error` after a while.

Doing some research i discovered that every time zookeeper gets restarted the number of connections increases, in other words, `kafka-node` is not closing the connections with Zookeeper.

This could be easily reproduced by just creating a consumer, connecting it to Kafka and restart Zookeeper while having Kafka up.

If you run the command

```
echo "stat" | nc localhost 2181
```

You'll see that the number of connections with Zookeeper increases every time it gets restarted.

This seems like this same issue that was opened last year in the `node-zookeeper-client` repo

https://github.com/alexguan/node-zookeeper-client/issues/60

According to the answer given by the repo owner, is not a bug from `node-zookeeper-client` but a misuse and when we do this

```js
zk.once('disconnected', function () {
    if (!zk.closed) {
      zk.close();
      self.connect();
      self.emit('zkReconnect');
    }
  });
```

we should wait to the connection to get closed before  doing `self.connect()`.

I was trying to check if `zk.close()` returned a promise or maybe emitted some event to check if the connection was closed but without success.

Could someone gave me some guidance on how to tackle this issue?

Thanks!

### Environment

* Node version: 6.11.5
* Kafka-node version: 1.6.2
* Kafka version: 0.11.0.0

**Comment by hyperlink** [comment]
You could avoid using zookeeper by using `KafkaClient` instead. This is probably the best route since kafka is deprecating using of zookeeper from kafka clients.

**Comment by mariosouto** [comment]
But the snippet that i pasted before

```js
zk.once('disconnected', function () {
    if (!zk.closed) {
      zk.close();
      self.connect();
      self.emit('zkReconnect');
    }
  });
```

is used inside the definition of Client (https://github.com/SOHU-Co/kafka-node/blob/master/lib/client.js), which is used for the ConsumerGroups :(

That's the reason of why i need Zookeeper.

Did i understand what you said correctly?

**Comment by hyperlink** [comment]
`ConsumerGroups` will create the appropriate client for you depending on what you pass into it. So passing a `kafkaHost` will use a `KafkaClient` instead of `Client`.

See the options here: https://github.com/SOHU-Co/kafka-node#consumergroup

**Comment by mariosouto** [comment]
Oh, ok. I'll try that and see what happens. I'll let you know. Thanks!

**Comment by mariosouto** [comment]
@hyperlink I'm pretty sure that i can replace `Client` with `KafkaClient` and give `ConsumerGroup` the `kafkaHost`... but i'm also using HighLevelProducer. HighLevelProducer also works with `KafkaClient` instead of `Client`?

**Comment by hyperlink** [comment]
Yes it should work.

**Comment by mariosouto** [comment]
@hyperlink Hi!

I was trying to see if the `KafkaClient` and `Client` interfaces were compatible.

I setted a infrastructure on my computer with 3 Kafka brokers running on `localhost:9092`, `localhost:9093` and `localhost:9094` respectively. 

Zookeeper is running on `localhost:2181`.

To see if this infrastructure was properly setted i started a producer and a consumer using the console, running the commands

```
bin/kafka-console-consumer.sh --bootstrap-server localhost:9092,localhost:9093,localhost:9094 --topic test --from-beginning
```

and

```
bin/kafka-console-producer.sh --broker-list localhost:9092,localhost:9093,localhost:9094 --topic test
```

And every time i killed one of the brokers, another broker was chosen as a leader and i was able to send messages from the producer to the consumer. So the infrastructure is fine. Important detail: Kafka brokers have a replication factor of 3 and the topic has also a replication factor of 3.

When i tested this , i mean the ability to change the leader based on the availability of the broker, with the `Client` interface, it worked fine also. I killed a broker, and another was chosen as a leader, and i still was able to exhange messages.

But when i changed to the `KafkaClient` interface this doesn't work. I kill a broker, another one is chosen, but the consumer gets stucked and unable to consume messages. The producer sometimes works, and sometimes it doesn't. Sometimes it just gets stucked and processes the same message forever.

I'm using `HighLevelProducer` and `ConsumerGroup` with the new `KafkaClient` interface. 

Are you already aware of this issue? I tried to check if there was already a similar issue open but i couldn't find one.

If you need help can you point me in the right direction of where in the code the problem could be?

Thanks!
