### ISSUE TITLE
(node:6591) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by mafeifan** [SOHU-Co/kafka-node#876]
## Questions?
I think it's not a bug,  please see the below code. when I frequently call the request, I always get the warn message. 

我认为这不是一个bug，也许是我对node或kafka-node的使用问题。由于刚刚接触kafka不知道如何优化。
我有一个这样的需求，有一个接口，我需要非常频繁的调用他将请求信息放到kafka中。但是经常出现警告`(node:6591) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit`
而我也找到了解决方案 https://stackoverflow.com/questions/9768444/possible-eventemitter-memory-leak-detected。
但是他们提示我最好从代码入手。而不是直接调大参数。
请问我改如何优化呢？代码在下面。非常感谢

### Environment

* Node version:  v9.4.0
* Kafka-node version:  v2.3.2
* Kafka version:  2.11

### Include Sample Code to reproduce behavior

express, 
```
var kafka = require('./toKafka.js');
app.post('/' , (req, res) => {
  // send to kafka
  kafka.produce(1, req.body, function (result) {
      res.send(result)
    });
} )
```

toKafKa.js
```
var kafka = require('kafka-node');
var KeyedMessage = kafka.KeyedMessage;
var Producer = kafka.Producer;

var client = new kafka.Client( '192.168.1.10:2181');
var options = {requireAcks:1, ackTimeoutMs:100, partitionerType:2 }
var producer = new Producer(client, options);

console.log('connecting kafka...');

class toKafka {

    static produce(key, message, cb) {

        let payloads = [
            { topic: 'test', messages: new KeyedMessage(key, message) }
        ];

        producer.on('ready', function () {
            console.log('connection successful')
        });

        producer.on('error', function(error) {
            console.log('error')
            console.log(error)
        })

        producer.send(payloads, function (err, data) {
            if (!!err){
                console.log(err)
            }
            cb(data);
        });
    }
}

module.exports = toKafka;

```

**Comment by hyperlink** [comment]
Looks like you are attaching a new `error` and `ready` handler with every request so you will get that warning after the 10th request. Either use `once` instead of `on` or don't implement it that way.

**Comment by mafeifan** [comment]
yes, you are right, I should put the event listener function out of the class.

**Comment by iitrsachin** [comment]
@mafeifan : I am getting the same error and once is not working in my case so you please post your modified sample code.

**Comment by iitrsachin** [comment]
**Sample code:**
**testKafka.js**
var producer = require('producer.js');
var publisher = new producer({
        "kafkaHost": "localhost:9092"
    });
publisher.initProducer('high', (err) => {
    if (err) {
        L.critical('controller', 'Getting error in publisher configuration: ', err);
    } else {
        L.log('controller','publisher configured');
    }
});

var payload = [{
                topic: "test",
                messages: "Hello"
            }];

publisher.publishData(payload);
module.exports = testKafka


**producer.js**
/* jshint multistr: true, node: true*/
'use strict';

import kafka    from "kafka-node";
import _        from "lodash";
import Q        from "q";
import L        from "lgr";
import CONFIG   from "./config";

/**
 * @class
 * Producer Class to create kafka producer and publish data in the topic
 */
class Producer {
    /**
     * Configure specifications
     * @param { object } configParams The connection configuration.
     * @param { string } configParams.kafkaHost Kafka broker/host combination delimited by comma.
     * @param { number } [configParams.connectTimeout] In ms it takes to wait for a successful connection before moving to the next host default.
     * @param { number } [configParams.requestTimeout] In ms for a kafka request to timeout.
     * @param { boolean } [configParams.autoConnect] Automatically connect when KafkaClient is instantiated otherwise you need to manually call connect.
     * @param { object } [configParams.retryOptions] Retry options in case of connection or request failure.
     * @param { number } [configParams.maxAsyncRequests] Maximum async operations at a time toward the kafka cluster.
     * @param { number } [configParams.idleConnection] Allows the broker to disconnect an idle connection from a client.
     * @param { string } [configParams.requireAcks] Configuration for when to consider a message as acknowledged values can be 0, 1 or all.
     * @param { integer } [configParams.ackTimeoutMs] The amount of time in milliseconds to wait for all acks before considered.
     */
    constructor(configParams) {
        this.kafkaConfig = configParams ? configParams : {};

        this.options = {};
        this.options.kafkaHost = _.get(this.kafkaConfig, 'kafkaHost', null);
        this.options.connectTimeout = _.get(this.kafkaConfig, 'connectTimeout', CONFIG.KAFKA_CONFIG.CONNECTION_TIMEOUT);
        this.options.requestTimeout = _.get(this.kafkaConfig, 'requestTimeout', CONFIG.KAFKA_CONFIG.REQUEST_TIMEOUT);
        this.options.autoConnect = _.get(this.kafkaConfig, 'autoConnect', CONFIG.KAFKA_CONFIG.AUTO_CONNECT);
        this.options.connectRetryOptions = _.get(this.kafkaConfig, 'retryOptions', CONFIG.RETRY_OPTIONS);
        this.options.maxAsyncRequests = _.get(this.kafkaConfig, 'maxAsyncRequests', CONFIG.KAFKA_CONFIG.MAX_ASYNC_REQUEST);
        this.options.idleConnection = _.get(this.kafkaConfig, 'idleConnection', CONFIG.KAFKA_CONFIG.IDLE_CONNECTION);

        this.producerOptions = {
            "requireAcks"   : _.get(this.kafkaConfig, 'requireAcks', CONFIG.PRODUCER_ACKS),
            "ackTimeoutMs"  : _.get(this.kafkaConfig, 'ackTimeoutMs', CONFIG.PRODUCER_ACK_TIMEOUT_MS)
        };

        if (this.options.kafkaHost === null) {
            L.error('Kafka Producer: ', CONFIG.MESSAGES.KAFKA_HOST_ERROR);
            throw new Error(CONFIG.MESSAGES.KAFKA_HOST_ERROR);
        }
    }

    _initClient() {
        this.client = this.client ? this.client: new kafka.KafkaClient(this.options);
    }

    _bindListeners(cb, deferred) {
        this.producer.on('ready', () => {
            L.log('Producer is ready! You can publish messages now.');
            return this._prepareResponse(cb, deferred, null, CONFIG.MESSAGES.PRODUCER_READY);
        });

        this.producer.on('error', (err) => {
            L.error('Error in producer: ', err);
            return this._prepareResponse(cb, deferred, err, null);
        });

        this.producer.on('SIGTERM', function() {
            L.log('Shutdown producer!');
            return this._prepareResponse(cb, deferred, null, CONFIG.MESSAGES.PRODUCER_STOPPED);
        });
    }

    _prepareResponse(cb, deferred, error, data) {
        error ? deferred.reject(error) : deferred.resolve(data);

        if(cb && cb !== 'undefined') {
            return error ? cb(error) : cb(null, data);
        }
    }

    /**
     * Create and Initialize new producer
     * @param { string } producerType Producer type it can be simple or high to create different type of producer
     * @param { function } [cb] Callback function
     */
    initProducer(producerType, cb) {
        let deferred = Q.defer();
        if (!(producerType === 'simple' || producerType === 'high')) {
            L.error('initProducer: ', CONFIG.MESSAGES.PRODUCER_TYPE);
            return this._prepareResponse(cb, deferred, CONFIG.MESSAGES.PRODUCER_TYPE, null);
        }
        this.producerType = producerType;

        try {
            this._initClient();

            this.producer = (this.producerType === 'simple') ?
                new kafka.Producer(this.client, this.producerOptions) :
                new kafka.HighLevelProducer(this.client, this.producerOptions);
            return this._prepareResponse(cb, deferred, null, this.producer);
        } catch (error) {
            L.error('initProducer: ', error);
            return this._prepareResponse(cb, deferred, error, null);
        }

        return deferred.promise;
    }

    /**
     * Function to publish data in the kafka topic
     * @param { object } payload Data to publish
     * @param { function } [cb] Callback function
     */
    publishData(payload, cb) {
        let deferred = Q.defer();
        if (this.producer === 'undefined' || !this.producer) {
            return this._prepareResponse(cb, deferred, CONFIG.MESSAGES.PRODUCER_NOT_EXIST, null);
        }

        if (payload) {
            try {
                this.producer.send(payload, (err, data) => {
                    return this._prepareResponse(cb, deferred, err, data);
                });
            } catch (err) {
                L.error('publishData: ', err);
                return this._prepareResponse(cb, deferred, err, null);
            }
        } else {
            L.error('publishData: ', CONFIG.MESSAGES.PAYLOAD_NOT_EXIST);
            return this._prepareResponse(cb, deferred, CONFIG.MESSAGES.PAYLOAD_NOT_EXIST, null);
        }
        return deferred.promise;
    }

}

module.exports = Producer;

**Comment by Billzaifei** [comment]
@iitrsachin have u fixed ur problem?

My sample code is as below, it seems works.(I'm a fresh nodejser from java)
/**
* Module for kafka functions and references
* @module api/utils/vvicKafka
*/
var vvicKafka = {},
    kafka = require('kafka-node'),
    KeyedMessage = kafka.KeyedMessage,
    Producer = kafka.Producer,
    logger = require('./log.js');



(function (vvicKafka) {
    var log = logger('vvicKafka'),
    client = new kafka.Client('192.168.64.236:2181,192.168.64.237:2181,192.168.64.238:2181'),
    producer = new Producer(client);
    console.log('kafka connecting...');
    producer.once('ready', function () {
        console.log('kafka connected.');
    });
    producer.once('error', function (err) {
        if (!!err){
            console.log(err)
        } 
    });

    /**
     * produce message
     * @param key
     * @param message
     * @returns {*}
     */
    vvicKafka.produce = (key, message) => {
        producer.send(message, function (err, data) {
            if (!!err){
                console.log(err)
            }
        });
    }

    /**
     * batch producing messages
     * @param messages
     * @returns {*}
     */
    vvicKafka.batchProduce = (messages) => {
        producer.send(messages, function (err, data) {
            if (!!err){
                console.log(err)
            }
        });
    }
}(vvicKafka));

module.exports = vvicKafka;
