### ISSUE TITLE
Fails to install from npm on docker images node:stretch and node:8-stretch

### ISSUE THREAD

**Issue by andreas-marschke** [SOHU-Co/kafka-node#884]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
Yes
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?
Yes
## Bug Report

Tried both node:stretch and node:8-stretch versions of the docker container and installing node-kafka
within that.

Kafka header dependencies in the form of `librdkafka-dev` were installed.   

Attached is the build log as returned when attempting to run `npm install node-kafka` in the shell.
[node-kafka.log](https://github.com/SOHU-Co/kafka-node/files/1778288/node-kafka.log)

Looking at the issue tracker it appears as this has not been done or reported before. Looking at the logs I'm not sure but it appears as if the versions of the headers are incompatible?

Is there a minimum version for dependency libraries the project would recommend in this situation?

Repro Dockerfile for the issue is also attached.
[Dockerfile.txt](https://github.com/SOHU-Co/kafka-node/files/1778292/Dockerfile.txt)

To reproduce you should rename `Dockerfile.txt` to `Dockerfile` and store in a fresh directory. Then run the `docker build` command as follows:

```sh
docker build -t docker-node-kafka-bug --force-rm --compress ./
``` 

### Environment

* Node version: both latest 8.x and 9.x at least
* Kafka-node version: most recent according to npm registry
* Kafka version: N/A
* librdkafka-dev version: 0.9.3-1

**Comment by hyperlink** [comment]
This is filed in the wrong project this is kafka-node and we do not use librdkafka.

**Comment by andreas-marschke** [comment]
@hyperlink Okay, may have installed the wrong libraries headers then, that's fine. 
But node-kafka still doesn't install using npm. 

Any chance you could look at the build log and tell me what's wrong then?

**Comment by hyperlink** [comment]
no problem.
