### ISSUE TITLE
ConsumerGroup not detecting new Partitions

### ISSUE THREAD

**Issue by mavencheong** [SOHU-Co/kafka-node#887]
## Questions?
Hi, 
Is there a way to make the ConsumerGroup to auto detect new partitions?

**Comment by hyperlink** [comment]
This is something the `ConsumerGroup` should handle. The `HighLevelConsumer` used to call rebalance whenever the partition changed through zookeeper. Perhaps we need to have a mechanism to monitor change by periodically polling the metadata.

**Comment by hyperlink** [comment]
Published as 3.0.0
