### ISSUE TITLE
Is it ok to access createTopics directly from Client.prototype.createTopics?

### ISSUE THREAD

**Issue by zignd** [SOHU-Co/kafka-node#892]
The documentation on the README.md only refers to the `Producer.prototype.createTopics`, I checked the source code and it seems to be possible to call it directly from `Client.prototype.createTopics`. Is there any reason for not to have this alternative through the Client documented? I have a specific use case in which I only need a Consumer instance, and therefore, I'd like to not to have to create a Producer instance for the sole purpose of creating a topic.

Here's an example to demonstrate the usage, it might not be necessary, but I'm adding for completion.

```javascript
const client = new KafkaClient({
  kafkaHost: 'localhost:9092',
});
client.on('error', (err) => {
  console.log('client error', err);
});
client.on('ready', () => {
  client.createTopics('test-1', false, function (err, data) {
    console.log('create error', err);
    console.log('create data', data);
  });
});
```

Thanks in advance.

**Comment by hyperlink** [comment]
Sure but it's not a reliable way to create topics since it's dependent on the broker's auto create topic setting. There's issue #639 to add admin APIs to create topics.

**Comment by zignd** [comment]
Got it, I performed a quick test and it behaves as you described, there is an `auto.create.topics.enable` property in the [broker config](https://kafka.apache.org/documentation/#brokerconfigs) which when set to `False` will not create the topic when `client.createTopics` (example above) is called, it's also worth noting that even though the function returns an error on the provided callback, it will be properly called but no error will be returned, which is a bit confusing for someone calling this function directly.

Thanks for the reply @hyperlink!
