### ISSUE TITLE
Remove node 7 from Travis

### ISSUE THREAD

**Issue by aikar** [SOHU-Co/kafka-node#893]
Node 7 is not LTS, nor latest bleeding. Suggesting removing it from Travis to help speed up travis runtime.

Note node 5 is not currently supported either, so 7 should be treated the same way.

**Comment by hyperlink** [comment]
Sounds good to me @aikar !

**Comment by aikar** [comment]
@hyperlink Node 4 ends support on April 30th. Thoughts on dropping it?

[Node v4 is missing quite a lot of language features](http://node.green/) and can improve the code base using latest syntax improvements if it is dropped.

**Comment by aikar** [comment]
A major bump could be a great thing.

I def have some good ideas for a major rev bump (refactoring ConsumerGroupStream)

I will open up some issue-per-idea for a major bump I'd like to see changed soon.
