### ISSUE TITLE
Is there a way of starting a ConsumerGroup/ConsumerGroupStream from a specific offset?

### ISSUE THREAD

**Issue by kelveden** [SOHU-Co/kafka-node#898]
I can see that a combination of `fromOffset: true` and a payload for a `Consumer` will have the desired effect but is there an equivalent for a `ConsumerGroup` (and, therefore, `ConsumerGroupStream`)?

**Comment by hyperlink** [comment]
For a fresh uncommitted group? There's not a easy way to start from a specific commit. Your choices currently are  either `earliest` or `latest`.

**Comment by kelveden** [comment]
Ah ok; that's a shame. Thanks for the info.
