### ISSUE TITLE
question about consumer group. 

### ISSUE THREAD

**Issue by xiaojun789** [SOHU-Co/kafka-node#9]
in the kakfa document said, only one conusmer can consume one partition in the same consumer group. but I test kafka-node, it seems allow doing this. 

doese the kafka-node support this feature? or I have some mistake? Thanks~!

**Comment by karthic891** [comment]
Hi haio,

As @geoffrey-young pointed out, in Kafka, message distribution is load balanced across all the consumers of the same consumer group and hence should not receive the same message.

Currently with kafka-node, all the consumers under a consumer group, listening to the same topic, receive the same set of messages. Would there be a fix for this in kafka-node?

I'm building a Node.js + Socket.io cluster for server-side push using Kafka as the event-driven messaging system. The kafka-node consumers in all the nodes in my cluster is listening to the same topic and gets duplicate messages, and hence I end up pushing the same message to the browser multiple times(the same number as the number of Kafka consumers).

Thanks & Regards,
Karthic

**Comment by dmtrs** [comment]
+1

**Comment by dmtrs** [comment]
@karthic891 Did you actually resolve this issue?

**Comment by karthic891** [comment]
@dmtrs No, the issue is still open as I couldn't find any alternative way(hack) to achieve the desired behaviour.

**Comment by dmtrs** [comment]
@haio Can we reopen this issue please. It seems that they have result issue in python client

**Comment by rajiff** [comment]
+1

Let's try to see how this can be fixed, if possible, I am willing to contribute with some help

**Comment by hyperlink** [comment]
Are you using the `ConsumerGroup`? This is not still an issue afaik.
