### ISSUE TITLE
"loadMetadataForTopics after connect failed" kills client?

### ISSUE THREAD

**Issue by thomaslee** [SOHU-Co/kafka-node#903]
## Bug Report

Maybe something of a design question: should this perhaps disconnect and retry after emitting an error? Or are errors assumed to be permanent & unrecoverable?

https://github.com/SOHU-Co/kafka-node/blob/e7b08646080fc0620a434ecea159e2823e4690c6/lib/kafkaClient.js#L144-L145

When we hit this code the consumer is effectively stopped in its tracks. I think we can work around it, but feels like something kafka-node might be able to take care of for us.

### Environment

* Node version: 8.x
* Kafka-node version: 2.4.1
* Kafka version: 1.0.0

### For specific cases also provide
* Number of Brokers: 1
* Number partitions for topic: N/A

### Include Sample Code to reproduce behavior

I effectively started a Kafka broker, then in a separate terminal ran the following loop to make it perform terribly:

```
while true; do kill -STOP $KAFKA_PID; sleep 0.2; kill -CONT $KAFKA_PID; done
```

(Blunt, but it works!)

Then I kicked off the repro program (may take a few tries to trigger the right error):

```js
const kafka = require('kafka-node')

const group = new kafka.ConsumerGroup({
  kafkaHost: 'localhost:9092',
  groupId: 'example-group',
  sessionTimeout: 6000,
}, 'repro-topic')
group.on('error', err => {
  console.log(err)
})
group.on('message', msg => {
  console.log(msg)
})

process.on('INT', () => {
  group.close(() => {
    process.exit(0)
  })
})
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

```
$ DEBUG=kafka-node:* npm run dev

> kafka-repro@0.0.1 dev /Users/tom/local-src/kafka-repro
> node index.js

  kafka-node:KafkaClient Connect attempt 1 +0ms
  kafka-node:KafkaClient Trying to connect to host: localhost port: 9092 +3ms
  kafka-node:KafkaClient Sending versions request to localhost:9092 +15ms
  kafka-node:KafkaClient broker socket connected {"host":"localhost","port":"9092"} +3ms
  kafka-node:KafkaClient getApiVersions request timedout probably less than 0.10 using base support +502ms
  kafka-node:KafkaClient setting api support to {"produce":{"min":0,"max":1,"usable":1},"fetch":{"min":0,"max":0,"usable":0},"offset":{"min":0,"max":0,"usable":0},"metadata":{"min":0,"max":0,"usable":0},"leader":null,"stopReplica":null,"updateMetadata":null,"controlledShutdown":null,"offsetCommit":{"min":0,"max":2,"usable":2},"offsetFetch":{"min":0,"max":1,"usable":1},"groupCoordinator":{"min":0,"max":0,"usable":0},"joinGroup":{"min":0,"max":0,"usable":0},"heartbeat":{"min":0,"max":0,"usable":0},"leaveGroup":{"min":0,"max":0,"usable":0},"syncGroup":{"min":0,"max":0,"usable":0},"describeGroups":{"min":0,"max":0,"usable":0},"listGroups":{"min":0,"max":0,"usable":0},"saslHandshake":null,"apiVersions":{"min":0,"max":0,"usable":0},"createTopics":null,"deleteTopics":null} +0ms
  kafka-node:KafkaClient loadMetadataForTopics after connect failed { TimeoutError: Request timed out after 30000ms
    at new TimeoutError (/Users/tom/local-src/kafka-repro/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout (/Users/tom/local-src/kafka-repro/node_modules/kafka-node/lib/kafkaClient.js:389:14)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Request timed out after 30000ms' } +30s
  kafka-node:ConsumerGroup Error from kafka-node-client { TimeoutError: Request timed out after 30000ms
    at new TimeoutError (/Users/tom/local-src/kafka-repro/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout (/Users/tom/local-src/kafka-repro/node_modules/kafka-node/lib/kafkaClient.js:389:14)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Request timed out after 30000ms' } +7ms
{ TimeoutError: Request timed out after 30000ms
    at new TimeoutError (/Users/tom/local-src/kafka-repro/node_modules/kafka-node/lib/errors/TimeoutError.js:6:9)
    at Timeout.setTimeout (/Users/tom/local-src/kafka-repro/node_modules/kafka-node/lib/kafkaClient.js:389:14)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) message: 'Request timed out after 30000ms' }
```

At this point we see no more output and the consumer/client is effectively "broken".

**Comment by aikar** [comment]
I'm working on some timeout stuff. I'll see if I can resolve this in my PR.

**Comment by thomaslee** [comment]
@aikar really glad to hear it. Was starting to try and put a patch together myself last night & woke up to your message this morning. There are a few ways this could be addressed, I think:

* (a) Do we just ignore the fact the initial metadata load failed & mark the consumer ready anyway? (the first send may fail, but will in turn attempt another metadata load iirc)
* (b) Do we retry until the initial load succeeds?
* (c) Do we disconnect entirely, consider it a "failed connect" & go through the whole `retry` "loop" again?

I think (b) makes the most sense, but it raises other questions about how we deal with timeouts during the connect process. If you can let me know the semantics you're shooting for, that'd be really helpful. 👍

**Comment by aikar** [comment]
@thomaslee ok looking at this, i think yeah it should be infinite retries.

That should be a separate PR than mine though

**Comment by thomaslee** [comment]
Okay, I'll see if I can pick it up if somebody doesn't beat me to it 👍

**Comment by hyperlink** [comment]
@thomaslee I prefer option C in this scenario.  To me `loadMetadataForTopics` timing out indicates a connection issue and we should give the client an opportunity to connect to a new broker in the cluster and try the initialization on that broker instead. We should be able to accomplish this by wrapping `connectToBrokers` and `loadMetadataForTopics` in a async series and in that handler call `connect.retry` for the failure case. What do you think?

**Comment by thomaslee** [comment]
> To me loadMetadataForTopics timing out indicates a connection issue and we should give the client an opportunity to connect to a new broker in the cluster and try the initialization on that broker instead. We should be able to accomplish this by wrapping connectToBrokers and loadMetadataForTopics in a async series and in that handler call connect.retry for the failure case.

Makes sense -- I'll see if I can hook that up. Thanks!

**Comment by aikar** [comment]
@thomaslee @hyperlink created his own PR to resolve this already, he tagged you on at https://github.com/SOHU-Co/kafka-node/pull/920

**Comment by thomaslee** [comment]
Oops, great -- thanks!
