### ISSUE TITLE
Why do I need to specify consumer's parition

### ISSUE THREAD

**Issue by DanielWLam** [SOHU-Co/kafka-node#904]
Why do I need to specify consumer's partition? If I don't specify consumer's partion, it will be the default value 0, which means when the partition is more than 1, like 4, the consumer can only get ONE message, and the other three message will miss.

**Comment by aikar** [comment]
If you are using a ConsumerGroup, you would not specify a partition. Assignment is handled automatically.

**Comment by aikar** [comment]
Consumer is a VERY low level implementation where you are expected to have extremely simple needs or really know what your doing

HighLevelConsumer was the next step up from that, but that has been deprecated in favor of ConsumerGroup/ConsumerGroupStream

**Comment by DanielWLam** [comment]
@aikar Hi, the ConsumerGroup's options confused me as I only know the kafka client host, topic. I don't know what the broker host is...

**Comment by aikar** [comment]
@DanielWLam kafkaHost is your kafka server (9092). 

```javascript
const consumer = new ConsumerGroupStream({
            kafkaHost: "localhost:9092",
            groupId: "your-group-id",
        }, topics);
```

Is the bas config for ConsumerGroup/Stream (Stream is optional)

**Comment by DanielWLam** [comment]
Thanks, I solved it now.
