### ISSUE TITLE
How to understand the setting of protocol in ConsumerGroup

### ISSUE THREAD

**Issue by fantasydong** [SOHU-Co/kafka-node#915]
I am using ConsumerGroup to consume my topic. But I do not quite understand how to use the setting of **protocol** according to the readme.

Does the setting of protocol is used for setting the consumer to consume message from the specific partition? And also can somebody provide me an example of how to use **Custom Partition Assignment Protocol**?

Thanks a lot.

Regards!

**Comment by hyperlink** [comment]
The assignment protocol is used to determine which consumer member instance "owns" the topcs/partitions in the group. One consumer member is elected as the leader to do the assignment. There are some built-ins that can be used `range` and `roundrobin`.

You can provide your own implementation by pushing a an object literal with `name`, `version`, `userData` and `assign` function.  The readme should have details of what structure of data to expect to be passed to your implementation's assign function.
