### ISSUE TITLE
No way to deregister handlers?

### ISSUE THREAD

**Issue by deathgaze** [SOHU-Co/kafka-node#924]
An event has occurred in my application that requires me to register a new 'message' event handler with Kafka-Node and remove the old one. But unless I'm mistaken, it doesn't appear as if this library includes a way to remove old handlers other than disposing of the object entirely. Am I off base here? 

A way to stop listening on a handler like in `EventEmitter` objects would be keen.

```js
  function handler(message) {
    // do something with message
  }
  consumerGroup.on(handler);
  consumerGroup.off(handler); // method does not exist
```

**Comment by hyperlink** [comment]
It's just an EventEmitter so you need to call [removeListener](https://nodejs.org/dist/latest-v6.x/docs/api/events.html#events_emitter_removelistener_eventname_listener).
