### ISSUE TITLE
ConsumerGroup is not creating multiple consumer for NodeJS Cluster

### ISSUE THREAD

**Issue by FoysalOsmany** [SOHU-Co/kafka-node#933]
## Bug Report
ConsumerGroup is not creating consumer for each worker in a NodeJS Cluster

### Environment
* Node version: v6.9.2
* Kafka-node version: ^2.3.2
* Kafka version: kafka_2.12-1.0.0

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 8

### Sample Code to reproduce behaviour:

```js
let consumerOptions = {
  groupId: 'gateway-consumer-group',
  host: "localhost:2181",
  kafkaHost: "localhost:9092,localhost:9093,localhost:9094",
  sessionTimeout: 15000,
  fromOffset: 'earliest',
  protocol: ['roundrobin'],
  autoCommit: false,
  versions: {
    disabled: true
  }
};
plugins.register("/worker", function (ob) {
  plugin = ((plugin) => {
    const consumer = new ConsumerGroup(consumerOptions, ['INCOMING_REQUESTS']);
consumer.on('message', (data) => {
      cargoQ.push(data);
      consumer.pause();
    });
  })(plugin);
```

### Output
Only first worker is getting all the messages of the topic. 
![image](https://user-images.githubusercontent.com/1332990/38775803-d88a2e60-40ac-11e8-8224-7aafee6ce110.png)

### Expected behaviour
All worker of the same consumer group should get unique messages from all partitions.

**Comment by FoysalOsmany** [comment]
@hyperlink please check

**Comment by aikar** [comment]
@FoysalOsmany this seems like something you need to investigate with what ever is providing this plugins.register API, or else the issue lies on your producer.

ensure your producer is not setting the key for every message to the same value.

**Comment by FoysalOsmany** [comment]
Thanks Guys, the issue was with my producer it was sending all messages to a single partition.

**Comment by mkscastillo** [comment]
@FoysalOsmany How were you able to resolve this?
