### ISSUE TITLE
Wrong type definition for `consumer.close()`

### ISSUE THREAD

**Issue by respinha-ribeiro** [SOHU-Co/kafka-node#936]
I get a typing error if I invoke `consumer.close` with an `error` parameter in the callback within my Typescript code. The `.d.ts` file from [`@types/kafka-node` ](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/kafka-node) only accepts a callback with no arguments, but it is pretty clear on the `Consumer` code that an error can be passed. 

Example:
```js
consumer.close((err) => { // "argument is not assignable..."
    if (err) {
      // .... handle err
    }
    // closed
  });
```

**Comment by aikar** [comment]
You need to open an issue with DT. Doesn't look like the maintainers of this project wrote the d.ts file.

**Comment by priithaamer** [comment]
Getting type definitions into better shape is currently a work in progress: https://github.com/SOHU-Co/kafka-node/pull/959

**Comment by respinha-ribeiro** [comment]
Awesome! Thank you!
