### ISSUE TITLE
ConsumerGroupStream with autocommit true

### ISSUE THREAD

**Issue by th3nu11** [SOHU-Co/kafka-node#944]
I'm trying to use consumer stream with autocommit setted to true but I have some problems: 

File consumerGroupStream.js

row 109: you set this.committing = true to avoid to starts multiple commits.

it is reseted to false only at row 114.

Are you sure this behaviours is correct? when "force" argument is true the rese will never called and so autocommit will never starts. I'm wrong? 

Thanks!
Regards

```
commitQueued (commits, force, callback) {
    ---> this.committing = true;
    --->if (!force) {
      this.autoCommitTimer = setTimeout(() => {
        logger.debug('setting committing to false');
        --->this.committing = false;**
        const queuedCommits = convertToCommitPayload(this.commitQueue);
        if (!_.isEmpty(queuedCommits)) this.commitQueued(queuedCommits);
      }, this.consumerGroup.options.autoCommitIntervalMs);
    }
    if (_.isEmpty(commits)) {
      logger.debug('commit ignored. no commits to make.');
      return callback && callback(null);
    }
    logger.debug('committing', commits);
    this.consumerGroup.sendOffsetCommitRequest(commits, error => {
      if (error) {
        logger.error('commit request failed', error);
        if (callback) {
          return callback(error);
        }
        this.emit('error', error);
        return;
      }
      for (let tp of commits) {
        if (_.get(this.commitQueue, [tp.topic, tp.partition]) === tp.offset) {
          this.commitQueue[tp.topic][tp.partition] = null;
        }
      }
      callback && callback(null);
    });
  }
```

**Comment by hyperlink** [comment]
`force` overrides committing flag so the request is always sent. This flag is used to throttle the commit requests we do to the broker. I can see you might run into issues if you've forced a commit and then later decided to use the auto commit.

**Comment by khushbookatta** [comment]
@hyperlink  Yes, facing the same, Please suggest a solution to it in this case.

**Comment by khushbookatta** [comment]
@hyperlink  Also, trying on a new topic and with new consumer in consumer group stream, and with auto commit true . Still getting all the previous messages on the restart of the consumer. 
But this should not be the case the processed messages which are auto committed should not be received again. 

Please clearify

**Comment by hyperlink** [comment]
The offsets are committed based on the groupId so make sure they are the same between restarts of your consumer.

**Comment by khushbookatta** [comment]
Yes, They are same. I am working with the only one consumer in the group and its group Id is same through out. 
Still facing

**Comment by hyperlink** [comment]
@khushbookatta include sample code?

You can run with [debugging](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on and see what messages are printed.

**Comment by khushbookatta** [comment]
const options = {
	messageWaitTimeout: 15000,
	clientReadyWaitTimeout: 60000,
	closeWaitTimeout: 60000,
	sessionTimeout: 15000,
	protocol: ['roundrobin'],
	asyncPush: false,
	groupId: 'test-1',
	fromOffset: 'earliest',
	highWaterMark: 10,
	fetchMaxBytes: 1024 * 100,
	attributes: 0,
	kafkaHost: '52.91.199.239:32400',
	retries: 2
};

let consumer = new kafka.ConsumerGroupStream(options, 'moci.test.1');
consumer.on('data', function (message) {
	console.log(message);
});
consumer.on('error', err => {
	console.log(err);
});



This is the basic code I am using. 
OK , I will do with debugging turned on.

**Comment by hyperlink** [comment]
`messageWaitTimeout` `clientReadyWaitTimeout` and `closeWaitTimeout` are not options we use where did they come from?

**Comment by khushbookatta** [comment]
It worked, The configurations were not right
