### ISSUE TITLE
我怎么知道 一个知道名字的cosumer里面的每个partition 的lag的数量

### ISSUE THREAD

**Issue by adolfheir** [SOHU-Co/kafka-node#952]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

### Environment

* Node version:
* Kafka-node version:
* Kafka version:

### For specific cases also provide
* Number of Brokers:
* Number partitions for topic:

### Include Sample Code to reproduce behavior

```js
// include code here
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on

Thanks for your contribution!

**Comment by adolfheir** [comment]
这是在shell里面看的 但是我是想在produce 发送的时候 有什么方法能看到某个consumer的partition 的lag堆积情况  然后动态的向空闲的partition里面发送

**Comment by hyperlink** [comment]
If you round robin produce to your your partitions they should be fairly balanced right?

Looks like this is similar question to #954 where you want to programmatically calculate the lag based on the committed offsets and the total offsets in topic/partition. And at this time it's not easy to do without pulling some parts of the code from `ConsumerGroup`.

**Comment by adolfheir** [comment]
burrow 是一个方案 不过我们现在已经变成consumer 端控制分配了 不用partition 对应一台机子来分配了
