### ISSUE TITLE
Warning without explanation: WARNING: Batch multiple messages of the same topic/partition together as an array on the messages attribute otherwise you may lose messages!

### ISSUE THREAD

**Issue by niahmiah** [SOHU-Co/kafka-node#961]
Can you please explain what this warning means:

WARNING: Batch multiple messages of the same topic/partition together as an array on the messages attribute otherwise you may lose messages!

What scenario leads to this causing lost messages?

**Comment by hyperlink** [comment]
Take a look at #786
