### ISSUE TITLE
highLevelConsumer的offset问题

### ISSUE THREAD

**Issue by justjv** [SOHU-Co/kafka-node#98]
zookeeper中记录的分区1的offset为500，但实际上kafka中此分区只有246条消息。然后启动HighLevelConsumer，这时候会触发this.on('offsetOutOfRange'事件，但是打印self.offsetRequest返回的offsets参数发现，offsets有两个值0和99，这两个值跟246差别好大啊，不管取哪个值，都会导致重复消费。是什么原因照成的？kafka配置错误？或者self.offsetRequest发送了错误的命令？我们使用的kafka版本是0.8.1.1

**Comment by baolinCloud** [comment]
@justjv 在rebalance的时候，取的offset也和server端的相差较大，同样会重复消费。这里你们是如何解决的?
https://github.com/SOHU-Co/kafka-node/blob/master/lib/highLevelConsumer.js#L115
