### ISSUE TITLE
ListGroups returns errors as successful call

### ISSUE THREAD

**Issue by ahmedlafta** [SOHU-Co/kafka-node#984]
## Questions?

* Check the [Troubleshooting / FAQ](https://github.com/SOHU-Co/kafka-node#troubleshooting--faq) ?
* Search the [issues](https://github.com/SOHU-Co/kafka-node/issues) ?

## Bug Report
When using the `listGroups` method of `KafkaAdmin`, errors are not getting returned properly to the `error` param within the callback. According to this line, any errors that are created will just get set to the `errors` property of `groups`.
https://github.com/SOHU-Co/kafka-node/blob/1c07d7d160b0d407296d7d7bac777f2f7ba6c69f/lib/protocol/protocol.js#L1211-L1230

In the KafkaClient, it doesn't appear that there are any checks for a populated error property. As a result, I get this error on certain clusters within the `res` callback param
https://github.com/SOHU-Co/kafka-node/blob/1c07d7d160b0d407296d7d7bac777f2f7ba6c69f/lib/kafkaClient.js#L463-L466
```
Object {error: Error: ClusterAuthorizationFailed
    at createGroupError
```
Am I incorrect in assuming that this error should be passed down through the `error` param, or is this expected behavior?

### Environment

* Node version: 8.9.3
* Kafka-node version: 2.6.1
* Kafka version: 0.10.2

### For specific cases also provide
* Number of Brokers: 3
* Number partitions for topic: 3

### Include Sample Code to reproduce behavior

```js
const client = new kafka.KafkaClient();
const admin = new kafka.Admin(client); // client must be KafkaClient
admin.listGroups((err, res) => {
  console.log('consumerGroups', res);
});
```

### Include output with [Debug](https://github.com/SOHU-Co/kafka-node#how-do-i-debug-an-issue) turned on
I cannot at this time, but if necessary I can work to include some.

I'm also glad to contribute a PR.

**Comment by hyperlink** [comment]
Thanks for the report and please feel free to submit a PR @ahmedlafta !
