### ISSUE TITLE
Commiting ConsumerGroups messages after processing

### ISSUE THREAD

**Issue by srolija** [SOHU-Co/kafka-node#996]
Hi,
First, thank you for maintaining and great work on this library. 

I have few questions related to using kafka-node, basically, it boils down to:
- how can we achieve concurrent batch processing of multiple messages (to avoid flooding workers with too many messages at once), committing work only once it is processed
- is it possible to manually update offsets on consumer groups

---

We have multiple workers, each consuming multiple partitions. They process the messages from kafka and pass them on further down the pipeline. 

We would like to:
- ensure that offset updates are committed only when work is really done, so if workers die or are redeployed for updating purposes we can resume the work
- it is not an issue if the message gets consumed multiple times, but given the number of messages it should not start from the beginning since it could take a very long time to process them all again
- given the number of messages that can be sent, we need to be able to "pause" `on('message')` handler so the worker can process data first (to avoid flooding workers with too many messages) 
- in some rare cases we need to explicitly set offset (backward) from which consumers start consuming

As far as we figured out from the documentation and other git issues there are two ways to do it.

### Using Consumer

Using Consumer we can explicitly select the partitions each worker consumes, also we can call `setOffset` to start working from last processed message (given we store offset for the last message that was processed), we can then use `consumer.pause()` and `consumer.resume()` to control the flow of messages, and call `consumer.commit()` before resuming to ensure that offset is properly committed.

So basically the flow is:
- create `Consumer` with selected partitions and `setOffset` for each partition
- start consuming and use `pause()` and `resume()` to avoid flooding on too many messages called on the message handler
- when need be, we can jump back to any offset by calling `setOffset`

The main **drawback** is that this way we **can not simply add new consumers to handle the peak load**. Which brings us to the ConsumerGroup.

### Using ConsumerGroup

As far as I understood from reading readme, taking a look at source code and issues #780, #683, #631, #509, #502 and #576. 

- We can manually commit messages by setting `autoCommit: false` and calling `consumer.commit(message)` after we have processed all the messages from that fetch loop.
- We can use `group.pause()` and `group.resume()` methods just like we would on normal Consumer to (manually) ensure that workers do not get overflooded with many messages.
- The advantage of using aforementioned approach compared to ConsumerGroupStream is that we can commit messages once they are processed rather than once they are fetched from kafka. However, we need to manually ensure that the order of calling commit for messages on each (topic, partition) is correct (so that we don't call commit for the message that was dispatched after message that is still being processed). Is that right?

So the flow would be:
- create `ConsumerGroup` with `autoCommit: false`
- start consuming messages and use `pause()` and `resume()` to avoid flooding on too many messages when finished with all of them before resuming call commit with latest messages for each partition

**However there seems to be no way to explicitly set offset to a specific value.** 

Is there maybe a way to work it around either by:
- Using `group.setOffset` (which isn't recommended for ConsumerGroups since it changes only internal offsets), along with calling `consumer.client.sendOffsetCommitV2Request` (to update state on kafka) which seems hacky.
- Or by calling `group.commit` with message that is tailored with topic, partition and offset which we want to jump to.

Finally is there a way to find out exactly which topics current ConsumerGroup is listening for and find out each time it rebalances. As far as I found out it should be available as `consumerGroup.topicPayloads` and I can subscribe to `on('rebalance')` event so I can figure out when they change?

Thank you in advance,
Hopefully, if it all works out we can create example showing how to do it, judging by issues there seemed to be multiple people looking at how to solve similar scenario (committing a message only after processing in paralel). :D

**Comment by phumberdroz** [comment]
Hey @srolija,

I am not sure If you are still working on this problem or have solved it. Anyway, here is our Solution:
We utilized this Package [Link](https://github.com/mafintosh/parallel-transform)
That way where are able to process async and commit in sync/order.

`
this.consumer = new kafka.ConsumerGroupStream({
        kafkaHost: this.kafkaBroker,
        groupId: this.consumerGroup,
        id: 'enrichment',
        autoCommit: false,
      }, this.KafkaTopics);

      const stream = transform(parallelProcessAmount, (data, cb) => this.handleMessage(data, cb));
      const commitWriter = new EnrichmentCommitWriter(this);
      this.consumer.pipe(stream);
      stream.pipe(commitWriter);
`

`class EnrichmentCommitWriter extends Writable {
  constructor(kafkaEnrichment) {
    super({
      objectMode: true,
      highWaterMark: 1,
    });
    this.kafkaEnrichment = kafkaEnrichment;
  }

  _write(msg, encoding, done) {
    this.kafkaEnrichment.consumer.commit(msg, true, (err) => {
      if (err) {
        // Failed to commit to Kafka. Just log and continue
        pino.warn(err);
      }
      // All done! Move to next message
      pino.info(`Updated ${msg.topic} state for ${msg.key} to offset ${msg.offset}`);
      done();
      return Promise.resolve();
    });
  }
}`

**Comment by aikar** [comment]
You can see: https://github.com/SOHU-Co/kafka-node/issues/975 for some code on how I do it using ConsumerGroupStream

**Comment by ninxxxxx** [comment]
i was look around in other languages that supported Kafka, i saw some of them they loop to check new message. if they got new message then pull it to process then commit after process done.

**Comment by b1swa** [comment]
Hi @srolija ,
Did you find any solution to the problem mentioned above. Could you please share how did you accomplish it.

Thanks in advance

**Comment by srolija** [comment]
Sure, we have solved the aforementioned issues in two different ways, depending on the use cases.

The first case deemed the first solution as a better choice since we couldn't get the ConsumerGroups working as expected and at the time there were some weird issues, we settled on using normal Consumer and explicitly assigning the partitions to them. Essentialy, we fetch the batch of messages (eg. 500) from Kafka, process them and commit them. If the process fails, we continue from the previous offset. We implemented a simple processing queue based around what I described as first approach above, that receives the messages either until it is full (eg. 500 msgs), or the time limit expires (0.5s). Then we process them and manually commit the offsets before moving on (meanwhile it can fetch the next 500 messages from kafka so next batch is ready). This, however, has the issue I mentioned above, we cannot simply scale the workers since we need to update the configurations of all workers and restart them. But for our use case, it works good enough.

For the second case, we used go language with librdkafka wrapper, so I am not sure whether the following will be useful to anybody. But the main difference is that in golang one app can run on multiple CPUs so there is the real benefit of parallelizing the work. In our case, we did something similar, we created the queue with the sliding window of messages that are processed, which tracks the processing and once the first message finishes processing, it marks it as ready for commit and then the other thread, regularly commits the messages to kafka (to avoid committing every message which would be slow). I feel like the only benefit to that approach which we could port to node is that in case the processing of the batch takes longer time, if the process fails, you could recover from further on than the start of the batch. But in my opinion, it isn't that big of an advantage since you could always change the queue size to something smaller.

Given that in meantime the https://github.com/nodefluent/node-sinek library got so much better, I personally wouldn't even consider using this library (`kafka-node`) manually, since `sinek` does exactly that I mentioned above. Further more it supports both the `kafka-node` and `node-rdkafka` (which does have the disadvantages of having native dependencies, but is faster and more refined since librdkafka is base for many kafka libraries in other languages instead of being Node specific).

So if you are just starting, I would recommend just go with it.
